### ISSUE TITLE
Global Search Bar

### ISSUE THREAD

**Issue by llermaly** [searchkit/searchkit#1002]
Hello! , 

What's the best practice for generating a global search bar with react-router? (i.e: Global Header)

In  other frameworks I just imported the hook in both components and worked, but here seems like are living in different scopes.

I guess I could pass the state down through a root component, wrap it with withSearchKit, then re-create the search bar to handle the api object .. but probably there is a more elegant way to do it?

Thanks

**Comment by llermaly** [comment]
I found my answer here: 

https://github.com/searchkit/searchkit/blob/next/examples/create-react-app/src/index.js

There is a provider that can wrap all the applications and that should do the trick :)

I will create a new issue with more specific questions if needed, thank you

**Comment by joemcelroy** [comment]
FYI the other alternative way is to have a search bar that sets the query param in the url, redirecting to the page. the search page (with router) will pick up the state from the url

**Comment by phinett** [comment]
Just expanding on this, i'm using a next app, i tried setting the query param as a querystring value, however this only works if you are not currently on the search results page, if you are already on this page it doesn't update the results even though the query param gets updated.

Think its a feature of the router to treat it as the same page, is there a workaround for this?
