### ISSUE TITLE
Question/Suggestion - entries.id alternative?

### ISSUE THREAD

**Issue by artgibson** [searchkit/searchkit#1010]
We have been using "entries.id" heavily in our own custom facets to keep track of options selected. Since it has been removed from gql queries (RC41), we are not able to key-off the selected ids.

* Is the guidance currently to switch to "entries.label"?
* Any plans to add a "key" field back to SKFacetSetEntry to support both a display field and an identifier field?

RE: https://searchkit.co/docs/guides/update-notes-rc41

**Comment by joemcelroy** [comment]
hey @artgibson - so before it was removed, the `id` field was a combination of `facet.identifier` and `facetEntry.id` [Example code](https://github.com/searchkit/searchkit/blob/v3.0.0-canary.40/packages/searchkit-schema/src/facets/RefinementSelectFacet.ts#L67). You can do the same within your code to get the same experience.

In terms of best practice, really depends what you are doing for selected ids. Are you using `@searchkit/client` as the API (via  [isFilterSelected](https://searchkit.co/docs/reference/searchkit-client#searchkitclient-methods) ) you can detect whether a facet option has been selected or not. Maybe you could share what you are doing to keep track of options selected within your components.

`key` is likely what it should of been named in the first place. Happy to add this, if you open an issue for this explicitly.

**Comment by artgibson** [comment]
Thanks @joemcelroy wrapping this up, we were able to switch over isFilterSelected and use summary.results.appliedFilters to maintain our facets.
