### ISSUE TITLE
Bug with nested properties (hit changes)

### ISSUE THREAD

**Issue by llermaly** [searchkit/searchkit#1017]
Hello, I have an object with this structure : 

```
{
"title": "Example",
"personEntities": [{"id":1, "name":"ex"}],
"chemicalEntities": [{"id":1, "name":"ex"}]
}
```

If I query the data the response in network tab is ok : 

chemicalEntities

```
{
    "name": "carbon",
    "id": 18,
    "__typename": "Entity"
  }
]
```

personEntities

```
[
  {
    "name": "anthony rullo",
    "id": 657,
    "__typename": "Entity"
  },
  {
    "name": "pat seppi",
    "id": 658,
    "__typename": "Entity"
  },
  {
    "name": "andrew s. hartten",
    "id": 659,
    "__typename": "Entity"
  },
  {
    "name": "linda range",
    "id": 53,
    "__typename": "Entity"
  }]
```

But then when I call the field in the UI (hit.fields.chemicalEntities) , then the object has changed, and mixes different values from chemicals and persons.

I will try using different types for each field but I think this way should work anyways.

Another thing is "id" field is not unique between chemicalEntities and personEntities but within each one.

Any advice?

Thanks

**Comment by joemcelroy** [comment]
yeh - with the same id and type, Apollo's client side cache wont be able to handle it. By using different typenames, it should be fine.
