### ISSUE TITLE
Code for custom react facet component doesn't work

### ISSUE THREAD

**Issue by weslleylc** [searchkit/searchkit#1051]
## Code for custom react facet component doesn't work

Hello everyone.

I'm trying to create a custom component for a facet display. I followed the tutorial, but for some reason, I'm getting an error that I seem to be associated with filters and not facets. Any suggestions on what it might be?

Obs: The only thing I changed in the code was mapping values from 0/1 to true/false.

## Environment

Searchkit version (or git revision) that exhibits the issue: 3.0.0-canary.46
Apollo version: ^3.3.11
Next.js version: ^12.0.3

## Details

If necessary, describe the problem you have been experiencing in more detail.

React component

```
## Code To Reproduce Issue

import React from 'react'
import { EuiTitle } from '@elastic/eui'
import {FilterLink, useSearchkit} from '@searchkit/client'

export const ColourPickerFacet = ({ facet, loading }) => {
  const api = useSearchkit()

  const entries = facet.entries.map((entry) => (
    <li
      style={{ backgroundColor: entry, border: api.isFilterSelected({ identifier: facet.identifier, value: entry.label ==1 ? "true":"false" }) ? '1px solid red' : "none" }}
    >
      <FilterLink filter={{ identifier: facet.identifier, value: entry.label ==1 ? "true":"false" }}>
        {entry.label ==1 ? "true":"false"}
      </FilterLink>
    </li>
  ))

  return (
    <>
      <EuiTitle size="xxs">
        <h3>{facet.label}</h3>
      </EuiTitle>
      <ul>{entries}</ul>
    </>
  )
}


ColourPickerFacet.DISPLAY = 'ColourPickerFacet'
```

Applying the facet.
`  const Facets = FacetsList([ColourPickerFacet])
`

I've got this error when applying the filter. 

```
Unhandled Runtime Error
Error: could not display selected filters for is_active_filter facet. Use customFilterComponents prop to pass a component to handle this filter for ColourPickerFacet display
```

**Comment by joemcelroy** [comment]
Hey! So that error originates from the SelectedFilters component (https://github.com/searchkit/searchkit/blob/next/packages/searchkit-elastic-ui/src/SelectedFilters/index.tsx#L70-L77). You need to implement the custom filter selection view. Example below:

```javascript

// example configuration of facet / filter

    new TermFilter({
      identifier: 'CustomFilter',
      field: 'practice_state',
      label: 'type',
      display: "ColourPickerFacet" <--- this can be changed to something more like PracticeStateFacet
    })

// example client code
const ValueFilter = ({ filter, loading }) => {
  const ref = useRef<FilterLinkClickRef>()

  // or whatever you want the presentation to be...
  return (
    <EuiFlexItem grow={false}>
      <EuiButton
        iconSide="right"
        iconType="cross"
        isLoading={loading}
        onClick={(e) => {
          ref.current.onClick(e)
        }}
      >
        <FilterLink ref={ref} filter={filter}>
          <>
            {filter.label}: {filter.value}
          </>
        </FilterLink>
      </EuiButton>
    </EuiFlexItem>
  )
}

const CustomFilterComponents = {
   ColourPickerFacet: ValueFilter
}

 <SelectedFilters data={data?.results} loading={loading} customFilterComponents={CustomFilterComponents} />
```

Hope this helps.

**Comment by weslleylc** [comment]
Thanks for replying so fast.

I'm trying to use a facet:
```
  new RefinementSelectFacet({
       field: 'is_active',
       identifier: 'is_active_filter',
       label: 'Active',
       display: 'ColourPickerFacet'
    // })
```

even though I'm using a facet and passing it via `const Facets = FacetsList ([ColourPickerFacet])`. I still need to pass `<SelectedFilters data={data?.results} loading={loading} customFilterComponents={CustomFilterComponents} />`?

I was confused because I thought this error would only happen with filters and not facets.

**Comment by joemcelroy** [comment]
hey @weslleylc its because when the facet option has been selected, a filter is applied to the search and that option is displayed to the user via SelectedFilters. Therefore you need to implement for the custom filter to display this filter. hope that makes sense.
