### ISSUE TITLE
Theming css with Grid / List Hit scaffold

### ISSUE THREAD

**Issue by joemcelroy** [searchkit/searchkit#106]
Able to easily make pretty "hit" results with out the box grid / list item styles

**Comment by GregoryPotdevin** [comment]
Do you mean having default list/grid components and dumping custom data in it ?

**Comment by joemcelroy** [comment]
Having default html / styles for common grid / list patterns. Bootstrap like. So others don't need to create their own css / html, less friction to get started.

**Comment by joemcelroy** [comment]
done
