### ISSUE TITLE
The use Facets, their customization could be better documented

### ISSUE THREAD

**Issue by DavisAre** [searchkit/searchkit#1107]
## The problem

The use of Facets directly instead of using <Facets /> parent component should be better documented
Currently https://searchkit.co/docs/reference/searchkit-elastic-ui contains only videos of components themselves, but doesn't go too extensive on implementing and possibly customizing them.

Some starting point: https://codesandbox.io/s/infallible-joana-fv658d?file=/src/App.js

This refferences a discussion I had with @joemcelroy @ Discord.

**Comment by joemcelroy** [comment]
Thanks DavisAre

Hoping in the next week I will get round to improving the client / elastic-ui components to make it easier to extend the view components + better documentation on how to build your own easily.

**Comment by joemcelroy** [comment]
hey @DavisAre so the reason was due to the position of the useRef. it should of been within the map iterator. https://codesandbox.io/s/damp-architecture-19hz58

**Comment by DavisAre** [comment]
@joemcelroy 
Follow up on this:
> it should of been within the map iterator.
I think it may work in some cases, but based on my experience (discussed @ Discord in more detail) and React documentation, this doesn't seem to be a reliable approach.

As defined @ https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level
> Don’t call Hooks inside loops, conditions, or nested functions.
 
Based on this, I think **[this part should be refactored within the module](https://github.com/searchkit/searchkit/blob/next/packages/searchkit-elastic-ui/src/Facets/ListFacet/index.tsx#L9)**.

I made some changes that seemed to work for me - https://codesandbox.io/s/serverless-field-93cfjw?file=/src/App.js:5270-5276
Based on suggestion from: https://stackoverflow.com/a/56063129/2312308
