### ISSUE TITLE
Docs dont scroll

### ISSUE THREAD

**Issue by bradennapier** [searchkit/searchkit#1119]
## The problem

Your documentation page doesnt scroll so i cant read anything
https://searchkit.co/docs/core/reference/searchkit-sdk/query-autocomplete

**Comment by joemcelroy** [comment]
Could you tell me more about your setup. what browser / device are you on?

**Comment by bradennapier** [comment]
Chrome latest, OS X / iMac

**Comment by joemcelroy** [comment]
Very strange! Your setup is exactly like mine and im sure with many others but I still can scroll / browse the site fine.
