### ISSUE TITLE
Extend an elastic query to include result collapsing  using the "collapse" parameter

### ISSUE THREAD

**Issue by gallbrook** [searchkit/searchkit#1123]
## The problem

Extend an elastic query to include result collapsing  using the "collapse" parameter as seen on https://www.elastic.co/guide/en/elasticsearch/reference/current/collapse-search-results.html

## Environment
"@searchkit/client": "3.0.0-canary.55",
"@searchkit/elastic-ui": "3.0.0-canary.55",
"@apollo/client": "^3.5.8",

## Details

I have updated the searchkit config  ( some parts removed for brevity) 

const searchkitConfig = {
  host: process.env.ES_HOST,
  index: process.env.ES_INDEX,
  hits: {
    fields: [
      'title',
      'content',
      'name',
      'create_time',
      'modify_time',
      'path',
      'uri',
      'case_number',
    ],
    highlightedFields: [
      'title',
      'name',
      'content',
    ],
  },
  query: new CustomQuery({
    queryFn: (query) => {
      return {
        bool: {
          minimum_should_match: 1,
          should: [
            {
              multi_match: {
                query: query,
                fields: ['title^2', 'content'],
                type: 'phrase_prefix',
              },
            },
            {
              term: {
                id: {
                  value: query,
                },
              },
            },
            {
              match: {
                name: {
                  query: query,
                  fuzziness: 'AUTO',
                  fuzzy_transpositions: 'true',
                },
              },
            },
          ],
        },
      }
    },
  }),
  facets: [ ..facets removed ],
  sortOptions: [  ... sort removed  ],
  postProcessRequest: (body) => {
    return {
      ...body,
      collapse: {
        field: 'case_number.keyword',
        inner_hits: {
          name: 'others',
          size: 5,
        },
      },
    }
  },
}

I've also updated the gql schema to accommodate the elasticsearch result format.
But the field "inner_hits" is always null.  So something isn't quite right.  Via kabana, the query 
"query":{ <custom query>},
 "collapse": {
    "field": "case_number.keyword",
    "inner_hits":{
      "name": "others",
      "size": 5
    }
  }
returns content:
        "inner_hits" : {
          "others" : {
            "hits" : {
              "total" : {
                "value" : 157,
                "relation" : "eq"
              },
              "max_score" : 21.39983,
              "hits" : [....]
etc

**Comment by joemcelroy** [comment]
Now released under latest version. See documentation for usage https://searchkit.co/docs/core/reference/searchkit-sdk/grouping

Let me know on discord if you have any issues, happy to help!
