### ISSUE TITLE
Continue support for ES 7

### ISSUE THREAD

**Issue by rockliffelewis** [searchkit/searchkit#1134]
## The problem

We use Elastic Search 7.12 with searchkit, and searchkit versions beyond canary-47 do not work with this ES version

## Environment

* Searchkit version (or git revision) that exhibits the issue: canary-48 or above
* Last Searchkit version that did not exhibit the issue (if applicable): canary-47
* ElasticSearch/OpenSearch version: 7.12.1

## Details

The issue seems to be around how source-fields were included: https://github.com/searchkit/searchkit/pull/1098

the error is somewhat cryptic as follows:
```
{
    "error": {
        "root_cause": [
            {
                "type": "parsing_exception",
                "reason": "Unknown key for a START_OBJECT in [includes].",
                "line": 6,
                "col": 13
            }
        ],
        "type": "parsing_exception",
        "reason": "Unknown key for a START_OBJECT in [includes].",
        "line": 6,
        "col": 13
    },
    "status": 400
}
```

But if I remove the `_source` block from the ES query it works as expected

**Comment by rockliffelewis** [comment]
Hang on, I understand what's going on now.

Searchkit changed its configuration structure at some point and I am still using the old style. If i update to the new configuration style it works as expected.

**Comment by joemcelroy** [comment]
Hey! Glad its sorted. Background to the issue: before that PR, source fields never worked. Your configuration was ignored prior to that release.
