### ISSUE TITLE
`FacetResponseEntry['count']` type should be `number`

### ISSUE THREAD

**Issue by awx-josh-fu** [searchkit/searchkit#1137]
https://github.com/searchkit/searchkit/blob/13425f03af68decbe4f2773962588f10fc0a40e8/packages/searchkit-sdk/src/facets/BaseFacet.ts#L18-L21

```ts
 export interface FacetResponseEntry { 
   label: string 
   count: number 
 } 
```

**Comment by joemcelroy** [comment]
thank you for the bug report. Will fix it.
