### ISSUE TITLE
`CompletionSuggestor`'s option `skip_duplicates` is reversed

### ISSUE THREAD

**Issue by awx-josh-fu** [searchkit/searchkit#1141]
https://github.com/searchkit/searchkit/blob/af346f5a07233e4329b62c2bd4b49b6f04abe74b/packages/searchkit-sdk/src/suggestors/CompletionSuggestor.ts#L24-L46

Hi, I found this weird issue, that if I explicitly pass `skip_duplicates` as `true`, it would not skip the duplicated ones.

I guess line:38 is meant for setting every nullable value as `false`, but the it also reversed the booleans.

**Comment by joemcelroy** [comment]
thanks for that bug report! Will fix or happy to accept a PR. I should of defaulted `skip_duplicates` to true and not reversed nullish values
