### ISSUE TITLE
Autocomplete in Searchkit 2.4

### ISSUE THREAD

**Issue by vabatista** [searchkit/searchkit#1143]
## The problem

I'd like to have autocomplete in searchbox using SearchKit 2.4 even if I have to do some custom code, but couldn't find a guide or orientation on how to do that.

## Environment

* Searchkit version 2.4.4
* Node.js version: v.12.14.1
* ElasticSearch/OpenSearch version: 6.8.10

**Comment by joemcelroy** [comment]
I suggest to try upgrade to Searchkit v4 where Searchkit supports Autocomplete via autocomplete.js. See example of this here https://www.searchkit.co/autocomplete and autocomplete docs https://www.searchkit.co/docs/components/autocomplete
