### ISSUE TITLE
Specify field format

### ISSUE THREAD

**Issue by haras-unicorn** [searchkit/searchkit#1147]
## The problem

I want to be able to specify the format of a `geo_point` field. So far, it seems that `elasticsearch` produces `geo_point` fields in the `well-known text` when no format is specified, but this is not very useful when `MapboxGL` is used.

## Environment

* Searchkit version (or git revision) that exhibits the issue: 3.0.0
* Last Searchkit version that did not exhibit the issue (if applicable):
* Node.js version: 16.16.0
* Typescript version: 4.5.3
* Apollo version:
* Next.js version: 12.3.1
* ElasticSearch/OpenSearch version: 8.2.2

## Details

`MapboxGL` accepts either `geojson` or [Mapbox vector tiles](https://docs.mapbox.com/data/tilesets/guides/vector-tiles-standards/), so I would like to be able to set the right format of my `geo_point` field to ensure that this is the case.

## Code To Reproduce Issue

This is my config and how I use it:

```ts
const config: SearchkitConfig = {
  host: <redacted>,
  index: <redacted>,
  hits: {
    fields: ['name', 'coords'],
  }
};

export const ComponentWithinSearchkitProvider() => {
  const variables = useSearchkitVariables();
  const { results, loading } = useSearchkitSDK(config, variables);
  
  return <MapGL hits={results?.hits?.items} />;
}

export const MapGL = ({ hits }) => {
  const geojson = useMemo(
    () =>
      ({
        type: 'FeatureCollection',
        features: hits?.map(hit => ({
          id: `${hit.id}`,
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: pointToCoordinates(hit.fields.coords),
          },
        })),
      } as GeoJSON.FeatureCollection),
    [props.hits]
  );
}
```

The `hits.fields` field affects the `_source.includes` field of the query which doesn't allow specifying formats of fields, so I have to have my `pointToCoordinates` function to convert from `well-known text` format to `geojson`. This is especially bad when there is a `geo_shape` field and the exact `geojson` type of the field is unknown.

Here is what I would like to be able to do:

```ts
const config: SearchkitConfig = {
  host: <redacted>,
  index: <redacted>,
  hits: {
    fields: [
      'name',
      { field: 'coords', format: 'geojson' },
    ],
  }
};

export const ComponentWithinSearchkitProvider() => {
  const variables = useSearchkitVariables();
  const { results, loading } = useSearchkitSDK(config, variables);
  
  return <MapGL hits={results?.hits?.items} />;
}

export const MapGL = ({ hits }) => {
  const geojson = useMemo(
    () =>
      ({
        type: 'FeatureCollection',
        features: hits?.map(hit => ({
          id: `${hit.id}`,
          type: 'Feature',
          geometry: hit.fields.coords,
        })),
      } as GeoJSON.FeatureCollection),
    [props.hits]
  );
}
```

The `hits.fields` field would now affect the `fields` field in the query (which is a bit more intuitive IMO) which allows us to specify the field format. The new data would not come from the `_source` field of each hit, but from the `fields` field. There is one edge-case with this and that is that when you don't specify `hits.fields` in the query there is no `fields` field in the response, so `searchkit` would have to take the `_source` field of the response when there is no `hits.fields` in the config and the `fields` field in the response when there is `hits.fields` in the config.

I'd like to make a PR that does what I proposed here if this is something that you are interested in.

**Comment by joemcelroy** [comment]
Yep good idea, I love the concept of being able to have complex field requirements using an object instead of a string. Make a PR and il review.

**Comment by Hrle97** [comment]
Can you help me commit? I think I solved the issue, but I don't know why the `pre-commit` hook wont work:

```
+ bash -c git commit -m "request use fields"

husky > pre-commit (node v16.16.0)
yarn run v1.22.19
error Command "lint" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
husky > pre-commit hook failed (add --no-verify to bypass)
```
