### ISSUE TITLE
Searchkit support for nested json object

### ISSUE THREAD

**Issue by britisharmy** [searchkit/searchkit#1160]
I have a need to use nested data type https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html

since i have data that looks like this 

```
{
	"files": [{
		"name": "IMG_20221205_164654_4.jpg",
		"size": 1889968,
		"url": "https://example.com/file_uploads/files/IMG_20221205_164654_4.jpg",
		"thumbnailUrl": "https://example.com/file_uploads/files/thumbnail/IMG_20221205_164654_4.jpg",
		"deleteUrl": "https://example.com/file_uploads/index.php?file=IMG_20221205_164654_4.jpg",
		"deleteType": "DELETE"
	}],
	"make": "Toyota",
	"title": "Car",
	"mileage": 45555,
	"year_of_manufacture": "2009",
	"fuel_type": "CNG",
	"transmission": "Automatic",
	"engine_size": 1200,
	"drive_train": "All Wheel",
	"registration_status": "Registered",
	"condition": "Brand New   ",
	"color": "Beige",
	"description": "<p>Good condition</p>",
	"price": 50000
}
```

Does searchkit support faceting nested objects and also ordering by a nested property such as price in my object above?

**Comment by joemcelroy** [comment]
Spoke on discord - will try to look at building facet support for nested fields

**Comment by joemcelroy** [comment]
Supported now in latest version of v4 for both numeric and string based facets. Documented here https://beta.searchkit.co/docs/guides/facets#nested-fields-support and codesandbox example here https://codesandbox.io/s/beta-example-nested-field-support-for-facet-and-filters-n3gp11?file=/pages/api/search.ts
