### ISSUE TITLE
V4: Custom Facet Aggregations

### ISSUE THREAD

**Issue by joemcelroy** [searchkit/searchkit#1174]
## The problem

As a developer, I want to have access to hooks to modify the elasticsearch query to support additional functionality. 

*![Screenshot 2022-12-08 at 20 49 19](https://user-images.githubusercontent.com/49480/208080607-6635238d-4d6f-4fde-a2df-bae117c3c3ff.png)

**Comment by CannonNDic** [comment]
Hi, There must a an attribute(in Facet filter/attributes) that can collect/aggregate a size of array/nested fields. as simple example below:

query: {
         "match_all": {}
        }, 
        "aggs": {
          "total_api": {
            "sum": {
              "script": {
                "source": "params._source.apiSpecification.size()"
              }
            }
          }
        }


***ApiSpecification is the array/nested field that need to be count as per my requirement.

**Comment by joemcelroy** [comment]
In 4.4.0, you will be able to apply custom agg and filter queries to facets and filter attributes. 

Example:

```ts
search_settings: {
      search_attributes: ['title', 'actors', 'query'],
      result_attributes: ['title', 'actors', 'query'],
      facet_attributes: [
        {
          field: 'actors.keyword',
          attribute: 'actors',
          type: 'string',
          facetQuery: (field, size) => ({
            significant_terms: {
              field,
              size: size
            }
          }),
          filterQuery: (field, value) => ({
            match: {
              [field]: value
            }}
          )
        }
      ],
      filter_attributes: [
        {
          field: 'writers',
          attribute: 'writers',
          type: 'string',
          filterQuery: (field, value) => ({
            match: {
              [field]: value
            }}
          )        
        }
      ]
    }
```
