### ISSUE TITLE
Date Range Options Facet

### ISSUE THREAD

**Issue by joemcelroy** [searchkit/searchkit#1195]
// using date range https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-daterange-aggregation.html

```
{
  type: 'date',
  facetType: 'options',
  options: [
    { from: DATEFROM, to: DATETO, label: 'Under $10'},
  ]
}
```

**Comment by joemcelroy** [comment]
If its just date filtering that you need rather than facets, here is an example of doing that here: https://www.searchkit.co/camping-sites-demo

and code https://github.com/searchkit/searchkit/blob/main/apps/web/pages/camping-sites-demo.jsx#L36-L53

Hope that helps!

**Comment by lukew-cogapp** [comment]
Thanks for the response @joemcelroy 

Will this worth with a `date_range` field?

i.e. here's the mapping we have:

```
"PublishedDate": {
          "type": "date_range",
          "format": "yyyy"
        },
```

**Comment by joemcelroy** [comment]
Thats super interesting, thanks for sharing! I didn't know about this field type and unfortunately, Searchkit doesn't support yet. ATM ranges are done with two separate fields. 

This is a good suggestion and will take into account for custom aggregation / filter support.

**Comment by joemcelroy** [comment]
closing this in favour of building better customisation support https://github.com/searchkit/searchkit/issues/1251
