### ISSUE TITLE
RangeFillter, dynamic min and max

### ISSUE THREAD

**Issue by sieppl** [searchkit/searchkit#120]
Currently, min and max are required and static. Thus the RangeFilter will always show the same range, no matter which results are currently filtered.

Optionally dynamic min/max would determine the min/max from the current result set:

- When the user starts to use the RangeFilter for refining, the min and max should remain the same, in order to undo the refinement. 
- When another refinement/filter is changed (while a dynamic RangeFilter is applied) the min and max are readjusted, but the latest settings of this RangeFilter are kept.

**Comment by infacq** [comment]
how to use it?
