### ISSUE TITLE
ComboBox loads no facets when not using ResultSet

### ISSUE THREAD

**Issue by devolt5** [searchkit/searchkit#1216]
## The problem

Note: This problem is related to **Searchkit v3**.

When using more than one index, and thus more than one searchkit Config, the ComboBoxFacet is unable to fetch new facets onSearchChange. I don't know if this is a GraphQL config error because I'm a novice in GraphQL.

## Environment

- "@searchkit/client": "3.0.0-canary.53"
- "@searchkit/elastic-ui": "3.0.0-canary.53"
- "@searchkit/schema": "3.0.0-canary.53"

- "@apollo/client": "^3.3.6"
- "next": "^12.0.0"
- "next-with-apollo": "^5.1.0"

- Node v14.21.1
- TypeScript 4.7.4
- Elasticsearch 7.17.5

## Details

I followed the examples in https://github.com/searchkit/searchkit/tree/v3.0.0-canary.53/examples/next
When adding a `ComboBox` Facet, which is a `RefinementSelectFacet`, to productsConfig and then selecting a facet, searchkit crashes with a runtime error.

## Code To Reproduce Issue

First, add a ComboBoxFacet to `facets` in `productsConfig` in `graphql.js`, e.g.:

```js
new RefinementSelectFacet({
  field: 'category_lvl1.keyword',
  identifier: 'category_lvl1',
  label: 'Category',
  display: 'ComboBoxFacet'
}),
```

Second, type a query or select an entry, to get the following error:

```
Unhandled Runtime Error
TypeError: result.data.results.facet is null
```

The relevant code is in  `/@searchkit/elastic-ui/src/Facets/ComboBoxFacet/index.tsx` in line 47
`const options = result.data.results.facet.entries.map((entry) => ({ label: entry.label }))`
it is fetching result, but this object is calling ResultSet, not `productsResultSet`

```
{
  "data": {
    "results": {
      "__typename": "ResultSet",
      "facet": null
    }
  },
  "loading": false,
  "networkStatus": 7
}
```

and there a no facets.

Call Stack:

```
TypeError: result.data.results.facet is null
Call Stack
onSearchChange/<
node_modules/@searchkit/elastic-ui/lib/esm/Facets/ComboBoxFacet/index.js (50:0)
fulfilled
node_modules/@searchkit/elastic-ui/lib/esm/Facets/ComboBoxFacet/index.js (4:42)
promise callback*step
node_modules/@searchkit/elastic-ui/lib/esm/Facets/ComboBoxFacet/index.js (6:32)
__awaiter</<
node_modules/@searchkit/elastic-ui/lib/esm/Facets/ComboBoxFacet/index.js (7:0)
__awaiter<
node_modules/@searchkit/elastic-ui/lib/esm/Facets/ComboBoxFacet/index.js (3:0)
onSearchChange
node_modules/@searchkit/elastic-ui/lib/esm/Facets/ComboBoxFacet/index.js (39:0)
EuiComboBox/<
node_modules/@elastic/eui/es/components/combo_box/combo_box.js (652:0)
EuiComboBoxInput/<
node_modules/@elastic/eui/es/components/combo_box/combo_box_input/combo_box_input.js (108:0)
callCallback
node_modules/react-dom/cjs/react-dom.development.js (3945:0)
invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js (3994:0)
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js (4056:0)
invokeGuardedCallbackAndCatchFirstError
node_modules/react-dom/cjs/react-dom.development.js (4070:0)
executeDispatch
node_modules/react-dom/cjs/react-dom.development.js (8243:0)
(...)
```

**Comment by joemcelroy** [comment]
Yeh the challenge is this https://github.com/searchkit/searchkit/blob/v3.0.0/packages/searchkit-elastic-ui/src/Facets/ComboBoxFacet/index.tsx#L13

The comboBoxFacet is calling for a gql query assuming you have the default schema for facets. As you're running multiple index configurations, its likely the schema is different.

I would likely just copy the component and change the gql query to match your schema.
