### ISSUE TITLE
Inconsistent naming : title vs label

### ISSUE THREAD

**Issue by GregoryPotdevin** [searchkit/searchkit#122]
Some components use "title" for the options (NumericRefinementListFilter), others use "label" (SortingSelector).

An update strategy could be to deprecate one of them, support both for a while (with a console warning), and remove the deprecated term some time in the distant future when searchkit will have millions of users.

**Comment by joemcelroy** [comment]
@GregoryPotdevin I can close this issue?

**Comment by GregoryPotdevin** [comment]
I haven't checked and I don't think the next version will completely fix this. The default list components are pretty permissive and check for `label`, `title`, and fall back to `key` if none was given. So the UI components are pretty clear. 
The components themselves, though, should have the same conventions as in v0.7, so still using label for some and title for others. No deprecation warning or change in v0.8.
