### ISSUE TITLE
Prepopulate search?

### ISSUE THREAD

**Issue by ColeDCrawford** [searchkit/searchkit#1238]
Trying to persist searches via URL params so that a user can copy the URL and send it to someone else, and when they hit the link they have the search prepopulate with the URL parameters. Is there a recommended pattern for this? I was trying to set the `.ais-SearchBox-input` input to my value, but doing that with Javascript doesn't trigger a search and if I click on the search bar after setting the value, my set value disappears. I couldn't find any recipes for this in the docs.

Seems possibly related to https://github.com/searchkit/searchkit/issues/1151 ?

I'm using JS widgets, no framework.

@rcavezza

**Comment by joemcelroy** [comment]
Hey @ColeDCrawford

So on instantsearch.js, you should be able to enable url persistance via `routing` boolean. See documentation (https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/js/)  

As for a default value, you might be able to use `QueryHook` function in the Searchbox component. You can set the query value here before request. https://www.algolia.com/doc/api-reference/widgets/search-box/js/#widget-param-queryhook
