### ISSUE TITLE
Next.js does not work properly with searchkit v4.

### ISSUE THREAD

**Issue by pixelkoduje** [searchkit/searchkit#1242]
![image](https://user-images.githubusercontent.com/102321542/230042760-e6be7638-904d-49c9-9244-3bd600dcf6a3.png)

https://www.searchkit.co/docs/proxy-elasticsearch/with-next-js#code-sandbox-example

It also doesn't show the map if it wants to implement geo search. Can you please demo with map and next.js that works?

**Comment by pixelkoduje** [comment]
@joemcelroy Any info?

**Comment by pixelkoduje** [comment]
Example with next.js and geolocation - maps don't work, shows errors. https://codesandbox.io/p/sandbox/eloquent-swirles-h6jzsv

**Comment by joemcelroy** [comment]
So caught up on discord on why this is the case. For now we have downgraded next to 12 and investigating a couple of these issues. Its likely down to the instantsearch code rather than searchkit itself. Will update this thread once i know more :)

**Comment by joemcelroy** [comment]
Found the issue, its down to react-instantsearch-dom not supporting strictmode. Check your `next.config.js` to make sure its not enabled. Instantsearch maintainers are advising to move over to the hooks library which is definitely im considering updating our demo code to use.

For now ive disabled strictmode and updated the demos. Should now be fixed.
