### ISSUE TITLE
Support custom snippet lengths

### ISSUE THREAD

**Issue by ColeDCrawford** [searchkit/searchkit#1244]
Currently, Searchkit does not support custom snippet lengths. It would be great to be able to support this as it is part of the Instantsearch API. For example: https://www.algolia.com/doc/api-reference/api-parameters/attributesToSnippet/?client=javascript. In searchKit the Instantsearch syntax doesn't work (e.g. `snippet_attributes: ["section_text:300"]`) and I don't think there is support for the Instantsearch `index.setSettings()` function

**Comment by joemcelroy** [comment]
thanks for the report! I will try build support for specifying custom snippet lengths at query time and configuration time. 

Yes `setSettings` isn't supported here.

**Comment by ColeDCrawford** [comment]
Hey @joemcelroy - just taking a look at this again. It looks like you could either implement this in a couple of places. Maybe a new setting in SearchSettingsConfig? Then update this code to use that setting: https://github.com/searchkit/searchkit/blob/b04ac16b4ac1b799d33e02b48499aa33dcd6a35b/packages/searchkit/src/transformRequest.ts#L270-L280

Otherwise, could create a new `HighlightAttribute` interface which would match the ES syntax (https://www.elastic.co/guide/en/elasticsearch/reference/8.6/highlighting.html), and then the `snippet_attributes` could be modified from `string[]` to `(string | HighlightAttribute)[]`. Not sure what level you'd want to expose this at.

**Comment by joemcelroy** [comment]
Yeh i think this is a quick win for now, be able to configure it at settings and runtime changes can come later :)

**Comment by ColeDCrawford** [comment]
@joemcelroy - are there any changes required to make this work with the Algolia widgets (https://www.algolia.com/doc/api-reference/widgets/snippet/js/)? If I add the new parameter to an item in my `snippet_attributes` array, it seems to break the widget - no text displayed. The Elasticsearch return value seems to be respecting the extra parameter and return longer snippets, but the widget seems broken. Let me know if you can't reproduce or you need more info.

**Comment by joemcelroy** [comment]
there was a bug unfortunately. Fixed in this PR https://github.com/searchkit/searchkit/pull/1254

**Comment by joemcelroy** [comment]
released in v4.6.1. Hopefully fixes the issue.

Im not super happy with how snippet / highlight returns, theres definitely room for improvement in future. Open to suggestions on this too!
