### ISSUE TITLE
Autocomplete Example

### ISSUE THREAD

**Issue by joemcelroy** [searchkit/searchkit#1250]
A working autocomplete example that:
- shows an example of quick hits
- shows an example of querying a seperate suggestions index
- shows an example of searching a hierarchical categories facet

**Comment by ColeDCrawford** [comment]
Adding some more use cases:
- Have a couple of facets with several thousand keywords. Not usable to do anything besides autocomplete. Would like to be able to use autocomplete for multiple of these facets. I'm not using a framework so vanilla examples would be most helpful.

**Comment by joemcelroy** [comment]
@ColeDCrawford just so you're aware, you can add `searchable` to the RefinementList component  https://www.algolia.com/doc/api-reference/widgets/refinement-list/js/

This will enable a search box in the facet which allows you to find a particular filter value. This might help until I provide a good example for selecting a facet via autocomplete
