### ISSUE TITLE
Missing wildcard support in `highlight_attributes`

### ISSUE THREAD

**Issue by McManning** [searchkit/searchkit#1259]
## The problem

Usage of wildcards in the `highlight_attributes` configuration does not add highlight matches to InstantSearch's `HitHighlightResult`

## Environment

* Searchkit version (or git revision) that exhibits the issue: v4

## Details

I have a v4 configuration like the following:

```ts

const sk = new Searchkit({
  search_settings: {
    ...
    highlight_attributes: [
      'name',
      'attributes.*',
    ],

    search_attributes: [
      { field: 'name', weight: 3 },
      { field: 'textDescription', weight: 2 },
      { field: 'attributes.*', weight: 1 },
    ],

    result_attributes: [
      'name',
      'textDescription',
      'attributes.*',
    ]
    ...
})
```

The response from ElasticSearch correctly applies highlights to all discovered nested fields, e.g.:
```json
"highlight": {
  "attributes.Email.email.keyword": [
    "<em>redacted.30@osu.edu</em>"
  ],
  "attributes.__Person.nickname.keyword": [
    "<em>redacted.30</em>"
  ],
  "attributes.Username.text.keyword": [
    "<em>redacted.30</em>"
  ]
}
```

But the fields are not included in the `HitHighlightResult` for InstantSearch. I can explicitly define full paths, such as "attributes.Username.text.keyword" but that's not ideal since we don't have an inventory of exactly what attributes exist on any given document within our dataset.

**Comment by joemcelroy** [comment]
Thanks for the spot! would love a PR to fix this 💯
