### ISSUE TITLE
Incorrect parsing when facet values contain colons

### ISSUE THREAD

**Issue by McManning** [searchkit/searchkit#1260]
## The problem

I have a keyword field where values are in the form `foo:bar`. When trying to apply that field as a facet the generated ElasticSearch query only uses the `foo` portion of the string. 

## Environment

* Searchkit version (or git revision) that exhibits the issue: v4
* InstantSearch Hooks (latest)

## Details

The clause that gets generated looks like the following:

```json

  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "should": [
              {
                "term": {
                  "facets.Test.keyword": "foo"
                }
              }
            ]
          }
        }
      ],
      "must": {
        "match_all": {}
      }
    }
  },
```

If I were to hazard a guess at the culprit, I'd say this string split: https://github.com/searchkit/searchkit/blob/main/packages/searchkit/src/filters.ts#L164

I'm not particularly familiar with how that data comes in from Algolia components but I'd assume (hope) it supports something like `Test:"foo:bar"`.

This may also be my fault. When I update the refinement filter, I'm doing it directly through `setUiState` e.g.:

```ts
const { setUiState } = useInstantSearch();

setUiState((prev) => ({
  ...prev,
  [indexName]: {
    refinementList: {
      ...prev[indexName].refinementList,
      [attribute]: values,
    }
  }
}));
```

Where `attribute = 'facets.Test.keyword'` and `values = ['foo:bar', 'fizz:buzz']`. I might be missing something in terms of how values should be formatted when passed into the state this way.

**Comment by McManning** [comment]
Here's a failing test case for this one:

```ts
it('should ignore quoted colons in instantsearch filters', () => {
  const isFilter = `author:"john:doe"`

  expect(transformBaseFilters(getRequest(isFilter), config)).toMatchInlineSnapshot(`
    [
      {
        "query_string": {
          "query": "author.keyword:"john:doe"",
        },
      },
    ]
  `)
})
```

**Comment by McManning** [comment]
Here's my pitch for a solution - bit of regex magic to split while ignoring quoted delimiters. I'll break it down a bit since regex isn't everyone's cup of tea: 

Match a quoted string, accounting for escaped quotes
`"(?:[^"\\]|\\.)*"`

Match a field name
`([\w.\-_]+):`

Match an unquoted field value:
`:\s*([^\s]+)`
(Note that this doesn't capture `bar` in `fizz:foo bar` since [whitespace needs to be quoted as per Algolia's validator sandbox](https://www.algolia.com/doc/api-reference/api-parameters/filters/#filters-syntax-validator))

Thus we get:

Match a field name followed by an unquoted field value:
`([\w.\-_]+):\s*([^\s]+)`

Match a field name followed by a quoted field value:
`([\w.\-_]+):\s*"(?:[^"\\]|\\.)*"`

Combined to make the final dark incantation of:
`(([\w.\-_]+):\s*"(?:[^"\\]|\\.)*"|([\w.\-_]+):\s*([^\s]+))`

Test cases I used to build out the above:
```
foo:bar
foo: bar
foo: bar fizz: buzz
foo:"bar" fizz: "buzz"
foo:"bar:fizz" buzz:"bar: baz: buzz"
foo:"bar:\"fizz" buzz:"foo"
foo.bar-baz_fizz:buzz
foo:bar fizz buzz
foo:"bar fizz buzz"
```

I didn't add single quote support but it's the same as the double quote, just added a third OR group.

I can implement this in a PR if you'd like (and you don't see any glaring issues I've missed above). I'd also be fine doing a non-regex solution that just does your typical character traversal, quote counting, etc algorithm.

**Comment by joemcelroy** [comment]
Thanks for the detailed suggestion! I hesitant to supporting colon in filter values. My suggestion would that developers should use a delimiter thats not colon and leave this issue for other developers to voice their requirement?

**Comment by qwkkze** [comment]
> should use a delimiter thats not colon
Hello, we have ran into the same issue - the problem is that we work with huge scientific datasets and we can not just modify them and remove all the colons (and why would users adopt their datasets in order for filters to work?)

I didn't dig deep into the implementation, and I am not common with Algolia, but probably the reason for this is in the `.split` operator, as mentioned before:
https://github.com/searchkit/searchkit/blob/main/packages/searchkit/src/filters.ts#L193
`const [facet, value] = filter.split(':')`
I am not sure for the regex magic suggested by OP, but why can't we just replace that line with
`const [facet, value] = filter.split(/:(.*)/)`
So that values that contain colons are not affected by facet name extraction?

**Comment by mirjan-hoffmann** [comment]
> Hello, we have ran into the same issue - the problem is that we work with huge scientific datasets and we can not just modify them and remove all the colons (and why would users adopt their datasets in order for filters to work?)

Yes, same problem here

Please reopen the issue. Colons as filter values are not uncommon.

**Comment by joemcelroy** [comment]
Thanks for the PR. Will try get this merged and released tomorrow.

**Comment by cintek** [comment]
@joemcelroy thank you very much!
