### ISSUE TITLE
Integrating Boolean operators in searchbox

### ISSUE THREAD

**Issue by mostafamohamed198** [searchkit/searchkit#1261]
## The problem

I am creating a website using Django and React. I have setup a search engine using elasticsearch and I showed the data in my website using React-searchkit. I want to integrate boolean search in my searchbox to allow the user to search using boolean operators like the photo.  so how can I do that?
![P8Edy](https://user-images.githubusercontent.com/104721248/233360378-6a8ef2c2-d4ee-4b30-9e52-8bad91ad9061.png)

## Environment

* Searchkit V4.6.1
*Django 
* ElasticSearch 7.9:

## Details

When I submit query string query on the elasticsearch server like this: http://localhost:9200/entries/_search?q=title:(first NOT second) it works well but when I submit the same query in searchbox the results are the products containing NOT, first and second.

**Comment by joemcelroy** [comment]
override the organic query via [getQuery](https://www.searchkit.co/docs/api-documentation/searchkit#getquery-optional-function) and use `query_string` instead. Ideally this should be OOTB support. In future I will detect when a user has done a query_string and rely only on `query_string` clause

**Comment by mostafamohamed198** [comment]
I have Integrated the qetQuery function in the code in this way:
```
`import React, { Component } from "react";
import Client from "@searchkit/instantsearch-client";
import Searchkit from "searchkit";
import {HierarchicalMenu, ToggleRefinement, MenuSelect, Pagination,Stats, Panel,InstantSearch, SearchBox, Hits, RefinementList, Snippet } from "react-instantsearch-dom";


export default function SearchResults(){
  const sk = new Searchkit({
    connection: {
      host: "http://localhost:9200/entries",
  
    },
    search_settings: {
      highlight_attributes: ["title", 'body'],
      snippet_attributes: ['title',"body"],
      search_attributes: [{ field: "title", weight: 3 }, "body", "bibiliography"],
      result_attributes: ['id',"title", "body", "bibiliography", 'entryCover', 'entryauthor.name', 'entryPubDate','entryCategory'],
      facet_attributes: ['title.key',  'entryOrigin.country.raw', 'entryClassification.theclass.key', 'entryauthor.name.key', 'entryCategory.thecategory.key'],
      filter_attributes: [  { attribute: 'title', field: 'title.key', type: 'string' }]
    },
  })
  const searchClient = Client(sk, {
    getQuery: (query, search_attributes) => {
      return {
        query_string: {
          fields: search_attributes,
          query: query
       }
  
    }
  }});

  const hitView = ({ hit }) => {   
    return (
      <div  className="SR--container">
       <div>
       {hit.title}
        </div>
      </div>
    )
  }


    return (
        <div className="ais-InstantSearch">
      
        
    <InstantSearch onSearchStateChange={false} indexName="entries" searchClient={searchClient}>
      <SearchBox
        searchAsYouType={false}
        queryFields={["title", "body"]}
      />
      <div className="SR--pandel--div">

      <div className="right-panel">
 
      
                  <Stats />
      <Hits hitComponent={hitView} /> 
      <Pagination />
      </div>
      </div>
  
  </InstantSearch>
  
</div>
      
    // </div>
    
    )
}`
```


This appeared to me in the console when I search:
![image](https://user-images.githubusercontent.com/104721248/233391791-8c8dbd9b-2ee8-404e-98a0-15b0144a1cce.png)

**Comment by joemcelroy** [comment]
so the issue I should of spotted was how your search_attributes are configured. You use the new object syntax to specify weights.

`search_attributes: [{ field: "title", weight: 3 }, "body", "bibiliography"],`

So what needs to happen is this:

```ts
getQuery: (query, search_attributes) => {
      return [{
        query_string: {
          // or you can map through the search_attributes and derive the fields dynamically
          fields: ["title^3", "body", "bibiliography"],
          query: query
       }]
    }

```

**Comment by mostafamohamed198** [comment]
There is a new problem faced me after applying getquery function
Before applying it I had the ability to search for a part of a word like if I typed the word "firs" it gives me all the results containing "first" .... now I should write the whole word "first" to get the the articles containing the word 'first'

**Comment by joemcelroy** [comment]
i think turn off searchAsYouType for now, thats a prop within the searchbox - that allows the user to fully type what they want to search.
