### ISSUE TITLE
Searchkit VectorSearch

### ISSUE THREAD

**Issue by sathvikbas** [searchkit/searchkit#1265]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Searchkit). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. You can ask them in [Discussions](https://github.com/searchkit/searchkit/discussions).

I am trying to use searchkit for vector search. Right now I have a flask app that is being used as a middleman between searchkit and Elasticsearch in order to convert the query into text embeddings. However, when I return the result from Elasticsearch to searchkit, I am getting a type error saying esResponses is undefined. Is there a way to see the JSON that searchkit needs to function properly?
I am also doing a regular _search instead of _msearch like searchkit does

## Environment

* Searchkit version (or git revision) that exhibits the issue:
* Last Searchkit version that did not exhibit the issue (if applicable):
* Node.js version:
* Typescript version:
* Next.js version:
* ElasticSearch/OpenSearch version:

I am using the elasticsearch v8.7 and the Elastiknn plugin
here are the JS package versions I'm using:
    "@searchkit/api": "^4.7.0",
    "@searchkit/instantsearch-client": "^4.7.0",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "axios": "^1.4.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-instantsearch-dom": "^6.39.1",
    "react-scripts": "5.0.1",
    "searchkit": "^4.7.0",
    "web-vitals": "^2.1.4"

## Details

If necessary, describe the problem you have been experiencing in more detail.
The Flask app doesn't make any changes to the elasticsearch response

## Code To Reproduce Issue

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

You can git clone https://github.com/searchkit/searchkit and from the `examples` directory, use one of the examples to reproduce the issue.

**Comment by joemcelroy** [comment]
What I would do is get it working first with the flask API proxying Searchkit requests to elasticsearch, as mentioned in [with your own api server](https://www.searchkit.co/docs/proxy-elasticsearch/with-your-own-server) docs. It requires access with `/_msearch` API as it does a number of requests (potentially for different indices) to service the UI.

One option is to look at the functional tests to see an example of  `/_msearch`

[Example of mocking the API](https://github.com/searchkit/searchkit/blob/main/packages/searchkit/src/___tests___/functional/index.test.ts#LL39C21-L39C21)
[Example of ES Request](https://github.com/searchkit/searchkit/blob/main/packages/searchkit/src/___tests___/functional/__snapshots__/index.test.ts.snap#L201-L207)
[Example of ES Response](https://github.com/searchkit/searchkit/blob/main/packages/searchkit/src/___tests___/mocks/ElasticsearchResponses.ts#L1C1-L127) 

The other suggestion is in 8.7 Elasticsearch, KNN is supports being able to transform the query into a vector embedding at query time with `query_vector_builder`. You can see an example of this in action [here](https://www.searchkit.co/docs/api-documentation/searchkit#getknnquery-optional-function). You would need to upload the model to Elasticsearch to take advantage.

**Comment by joemcelroy** [comment]
theres now a tutorial on how to do this in our docs https://www.searchkit.co/docs/tutorials/semantic-search
