### ISSUE TITLE
Suggestion : TagFilter component

### ISSUE THREAD

**Issue by GregoryPotdevin** [searchkit/searchkit#127]
When doing a more detailed view of results, it could be interesting to be able to turn the displayed values into clickable items.
![image](https://cloud.githubusercontent.com/assets/1522455/12952441/c336a1fa-d016-11e5-9fc8-b0b002500e4f.png)
In this example, `writers` and `actors` could be filters.

The component could either be the whole list or just one entry, something like 
`<TagFilter field="actors.raw" value={label}>{label}</TagFilter>`

**Comment by GregoryPotdevin** [comment]
Experimented the approach in the playground :
```
export default class TagFilter extends SearchkitComponent<any, any> {

  handleClick() {
    const { field, value } = this.props;
    const accessor = this.searchkit.accessors.statefulAccessors[field]
    accessor.state = accessor.state.toggle(value)
    this.searchkit.performSearch()
  }

  render() {
    return (
      <span onClick={this.handleClick.bind(this) } style={{ cursor: 'pointer', color: '#08c' }}>{this.props.children}</span>
    )
  }
}
```

**Comment by GregoryPotdevin** [comment]
Might be worth pushing that one back to 0.8.1 or 0.9 as we haven't integrated it yet. Here is the current code :
```
export class TagFilter extends SearchkitComponent<any, any> {

  constructor(){
    super()
    this.handleClick = this.handleClick.bind(this)
  }

  handleClick() {
    const { field, value } = this.props
    const accessor = this.searchkit.accessors.statefulAccessors[field]
    if (!accessor) {
      console.error('Missing accessor for', field, 'in TagFilter')
      return
    }
    accessor.state = accessor.state.toggle(value)
    this.searchkit.performSearch()
  }

  render() {
    const { value } = this.props
    return (
      <FastClick handler={this.handleClick}>
        <span key={value} style={{ cursor: 'pointer', color: '#08c' }}>{this.props.children}</span>
      </FastClick>
    )
  }
}
```

I guess most of the time people will want to use this on a list, so rather than doing the list manually, having a TagFilterList component could be nice (and would be aligned with the current listComponent/itemComponent trend). 

These can be used in Hits results, but still need to have an accessor created (either from a RefinementListFilter or another filter). So to handle those rare cases where you want to be able to filter without having a filter defined, we incubated a `FacetEnabler` component

```
class NullComponent extends React.Component<{}, {}> {
  render(){return null}
}

export interface FacetEnablerProps extends SearchkitComponentProps {
  field: string
  operator?: string
  size?: number
  title: string
  id: string
}

export default class FacetEnabler extends React.Component<FacetEnablerProps, {}> {

  render() {
    return <RefinementListFilter {...this.props} size={0} component={NullComponent}/>
  }
}
```

This filter is added like all the other Facets but doesn't display anything. It works well but requires some cleaning up (this version is really hacky) and discussion before integrating into searchkit.

**Comment by PAK90** [comment]
I +1 this, since I was planning on adding it to my code anyway. Especially in list view where I have a lot of details and possible filterable information, this would be valuable. I was hoping to implement it as a hover option where when you hover on it, it gives you three options; add {Value} to current list of filters, remove {Value} from list of filters, and make {Value} the only filter. 
So in the No Country for Old Men example, hover over Joel Coen and you can add "Writer: Joel Coen" to the filter list (if not there already), remove "Writer: Joel Coen" from the filter list (if there already), or remove all other filters and add "Writer: Joel Coen" to the filter list.

**Comment by GregoryPotdevin** [comment]
TagFilter, TagFilterList, and TagFilterConfig (more in the docs) have been added to the develop branch.
