### ISSUE TITLE
Querying ES 6.8.5 is not returning results

### ISSUE THREAD

**Issue by d-g-h** [searchkit/searchkit#1278]
## The problem

We are looking to query via Searchkit for Elasticsearch v6.8

## Environment

* 6.8.5
* Last Searchkit version that did not exhibit the issue (if applicable):
* Node.js version: v18.16.0
* Typescript version: 4.3.2
* Next.js version: 12.3.1
* ElasticSearch/OpenSearch version: 6.8.5

## Details

`_msearch` query seem to not work. For example.

```
[{"indexName":"ES_INDEX_NAME","params":{"facets":[],"query":"the","tagFilters":""}}]
```

## Code To Reproduce Issue
Tried the out of the box query, and `getQuery` via `api/search.ts`
Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

You can git clone https://github.com/searchkit/searchkit and from the `examples` directory, use one of the examples to reproduce the issue.

**Comment by joemcelroy** [comment]
Could you share the error that Elasticsearch responds with?

**Comment by d-g-h** [comment]
```
{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: no requests added;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: no requests added;"},"status":400}
```

**Comment by d-g-h** [comment]
Working query:

```
curl -L 'http://________________________:9200/_msearch' -H 'Content-Type: application/json' -d '{ }
{"query" : {"match" : { "title": "education"}}}
{"index": "________________________"}
'
```

**Comment by d-g-h** [comment]
Unrelated, possible related. In the examples, here, https://github.com/searchkit/searchkit/blob/main/examples/with-ui-nextjs-react/pages/api/search.ts#LL1C1-L1C1

At a glance, I noticed that `MatchFilter` is being imported but not used, I believe has the `query: { match` could that might apply here. Sorry, if I'm totally off here though.

```ts
import API, { MatchFilter } from '@searchkit/api'
```

**Comment by joemcelroy** [comment]
yeh looking at your error response, looks like 6.8 doesn't have bool_prefix.

```
"reason":"failed to parse [multi_match] query type [bool_prefix]. unknown type."}
```

Its used here https://github.com/searchkit/searchkit/blob/main/packages/searchkit/src/transformRequest.ts#L170-L174

Try using a simplified getQuery instead:

```js
const results = await apiClient.handleRequest(req.body, {
  getQuery: (query, search_attributes) => {
    return [
      {
        multi_match: {
          query,
          fields: search_attributes,
        },
      },
    ];
  },
});
```

**Comment by d-g-h** [comment]
> yeh looking at your error response, looks like 6.8 doesn't have bool_prefix.
> 
> ```
> "reason":"failed to parse [multi_match] query type [bool_prefix]. unknown type."}
> ```
> 
> See docs here: https://www.elastic.co/guide/en/elasticsearch/reference/6.8/query-dsl-multi-match-query.html#type-best-fields
> 
> bool_prefix is used here https://github.com/searchkit/searchkit/blob/main/packages/searchkit/src/transformRequest.ts#L170-L174
> 
> Try using a simplified getQuery instead:
> 
> ```js
> const results = await apiClient.handleRequest(req.body, {
>   getQuery: (query, search_attributes) => {
>     return [
>       {
>         multi_match: {
>           query,
>           fields: search_attributes,
>         },
>       },
>     ];
>   },
> });
> ```

Bool is still being returned on

```ts
    const results = await apiClient.handleRequest(req.body, {
      hooks: {
        beforeSearch: async requests => {
          const eslog = createLogger('es request');
          eslog.info(JSON.stringify(req.body, null, 2));
          return requests;
        },
      },
      getQuery: (query, search_attributes) => {
        return [
          {
            multi_match: {
              query,
              fields: search_attributes,
            },
          },
        ];
      },
    });

```
```
{"index":"______________________________________"}
{"aggs":{},"query":{"bool":{"filter":[],"must":[{"multi_match":{"query":"the","fields":["tags"]}}]}},"size":20,"from":0,"_source":{"includes":[]},"highlight":{"pre_tags":["<em>"],"post_tags":["</em>"],"fields":{}}}
```

**Comment by d-g-h** [comment]
Thanks!
