### ISSUE TITLE
Searchbox suggestions

### ISSUE THREAD

**Issue by sieppl** [searchkit/searchkit#128]
SearchBox could make suggestions for common search terms, like amazon does: 

![image](https://cloud.githubusercontent.com/assets/837595/12953011/fa8cae04-d018-11e5-8447-58fe5196f33e.png)

**Comment by GregoryPotdevin** [comment]
Multiple solutions :

1. Just do a quick prefix search with highlighting returning only the title (or a specific field)

2. Could use filters on a term aggregator : https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_filtering_values_2

```
{
    "aggs" : {
        "tags" : {
            "terms" : {
                "field" : "title",
                "include" : "sam.*"
            }
        }
    }
}
```

**Comment by joemcelroy** [comment]
we had a working prototype of searchbox suggestions before release. We used suggesters https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html as they are quick and performant. Its built for sites which have high volume queries and used for autocomplete

https://github.com/searchkit/searchkit/blob/dd56cdfd4ed0ed23fd94de530457fa236ea87291/src/components/search/search-box/src/SearchBox.tsx#L76

In terms of UX, having searchOnChange and an autocomplete component showing results can be overkill. 

This issue is related to #31

**Comment by GregoryPotdevin** [comment]
> In terms of UX, having searchOnChange and an autocomplete component showing results can be overkill.

But you probably wouldn't be using both at the same time. 
Suggesters are good for high volume queries but could be a bit more difficult to configure for newcomers ?

**Comment by joemcelroy** [comment]
Yeh, its up to the user how its configured, we just need to communicate that it isn't advisable or that the component shouldn't provide searchByChange option. 

We hide the use of suggesters within the component accessor, specifying a few fields on which to generate suggestions from. For things like "quick hits", we can communicate how to index the data well in our documents and specify the quick hit fields in the component config

**Comment by ssetem** [comment]
I think if we incubate a couple of variants so we don't have to maintain api compat in research phase, it would be a good start

**Comment by joemcelroy** [comment]
```
<searchbox-autocomplete sources={[
{label:"Suggestions", type:"suggest", component:SuggestionHit, field:"title"},
{label:"Movies", type:"quick-hit", component:MovieQuickHit, field:"movieSuggestions"}
]} />
```
a possible example

**Comment by sieppl** [comment]
> In terms of UX, having searchOnChange and an autocomplete component showing results can be overkill.

I agree. Also it would decrease overall response time.

**Comment by mhilaire** [comment]
Any updates on this component? Would it work with InputFilter? Didn't see updates on https://github.com/searchkit/searchkit-autocomplete. Thanks!

**Comment by joemcelroy** [comment]
not yet :( We have been busy on other projects. Contributions welcome! :)

**Comment by drekli** [comment]
I asked today on Gitter about whether anybody has implemented something like this yet. Are there any updates?

**Comment by joemcelroy** [comment]
linked to this #31. Closing issue
