### ISSUE TITLE
Sort problem

### ISSUE THREAD

**Issue by martines2018** [searchkit/searchkit#1280]
## The problem
How to implement a function: when the keyword is empty, the page initial state or when a facet filter is selected, the data is sorted in a specific attribute order (such as date), and when there is a keyword, it is sorted in reverse order of keyword relevance(such as _score).
Based on Vue searchkit example.

**Comment by joemcelroy** [comment]
Hey theres two options:

**Adjusting UiState `sortBy`**

You might be able to use the `useInstantSearch` hook to[ set the UiState](https://www.algolia.com/doc/api-reference/widgets/use-instantsearch/react-hooks/#widget-param-setuistate) sortBy on these conditions, via [queryhook](https://www.algolia.com/doc/api-reference/widgets/search-box/react-hooks/#widget-param-queryhook) to trigger on search.

**Boosting documents based on attribute**

You could continue to be sorted by score but you boost documents at query time on their date. You can do this in Elasticsearch query.
