### ISSUE TITLE
[Question]: Query sorting

### ISSUE THREAD

**Issue by kristinn93** [searchkit/searchkit#1281]
## The problem
Understanding the difference in sorting on the request body vs making a request to another index with different sorting

As stated in [Opensearch docs, Sort results](https://opensearch.org/docs/2.8/search-plugins/searching-data/sort/) 
It's possible to apply sort to queries that orders the results

You can see the difference when setting up the client 
#### Code example:
```typescript
const searchKit = new Searchkit({
      connection: {
        host: "/search",
      },
      search_settings: {
        ...
        sorting: {
          default: {
            field: "price",
            order: "asc", // or changing this to 'desc'
          },
         // ... more sorting options
        },
      },
    });
```
The results are ordered based on the `order` attribute you provide.

You can also use the `beforeSearch` hook to change the order attribute of the request you are making like this:
#### Code example:
```typescript
    const searchClient = Client(searchKit, {
      hooks: {
        beforeSearch: async (req) => {
          req[0].body.sort = {price: "desc"}
          return req;
        },
      },
    });
```

## The actual question
Why is it not supported to be able to change the sorting that is sent in the request body without changing the index name ? 
In this code https://github.com/searchkit/searchkit/blob/main/packages/searchkit/src/sorting.ts it's only possible to do sorting if I clone `regular_index` to `regular_index_price_asc` without making any changes to the index it self and then I can use the SortyBy component that will also apply the `sort` as seen in the `beforeSearch` hook.

Any information you can provide would be greatly appreciated
(and any general information about index sorting vs query sorting)

**Comment by joemcelroy** [comment]
so you need to setup sorting in the configuration. See example: https://www.searchkit.co/docs/components/sort-by#searchkit-setup

in the example you gave, it should be:

```
search_settings: {
  // ...
  sorting: {
    default: {
      field: '_score',
      order: 'desc'
    },
    _price_desc: {
      field: 'price',
      order: 'desc'
    },
    _price_asc: {
      field: 'price',
      order: 'asc'
    }
  }
}
```

this means it will continue to use the same index but will sort based on the field specified. Hope that makes sense!
