### ISSUE TITLE
Error: [Autocomplete] The Algolia `appId` was not accessible from the searchClient passed.

### ISSUE THREAD

**Issue by alessandrojcm** [searchkit/searchkit#1286]
## The problem
Getting a `Error: [Autocomplete] The Algolia `appId` was not accessible from the searchClient passed.`  while trying to follow the [docs](https://www.searchkit.co/docs/components/autocomplete) to integrate with the autocomplete.

## Environment

* Searchkit version (or git revision) that exhibits the issue: 4.8.0
* Last Searchkit version that did not exhibit the issue (if applicable):
* Node.js version: 19.7
* Typescript version: 5.1.6
* Next.js version: 13.4.8
* ElasticSearch/OpenSearch version: 7.2

## Details

Stack trace:
```
Unhandled Runtime Error

Error: [Autocomplete] The Algolia `appId` was not accessible from the searchClient passed.
Call Stack
invariant
node_modules\.pnpm\@algolia+autocomplete-shared@1.9.4_@algolia+client-search@4.18.0_algoliasearch@4.18.0\node_modules\@algolia\autocomplete-shared\dist\esm\invariant.js (11:0)
fetchAlgoliaResults
node_modules\.pnpm\@algolia+autocomplete-preset-algolia@1.9.4_@algolia+client-search@4.18.0_algoliasearch@4.18.0\node_modules\@algolia\autocomplete-preset-algolia\dist\esm\search\fetchAlgoliaResults.js (35:11)
createAlgoliaRequester<
node_modules\.pnpm\@algolia+autocomplete-js@1.9.4_@algolia+client-search@4.18.0_algoliasearch@4.18.0_search-insights@2.6.0\node_modules\@algolia\autocomplete-js\dist\esm\requesters\createAlgoliaRequester.js (10:28)
execute
node_modules\.pnpm\@algolia+autocomplete-preset-algolia@1.9.4_@algolia+client-search@4.18.0_algoliasearch@4.18.0\node_modules\@algolia\autocomplete-preset-algolia\dist\esm\requester\createRequester.js (9:0)
resolve/values<
node_modules\.pnpm\@algolia+autocomplete-core@1.9.4_@algolia+client-search@4.18.0_algoliasearch@4.18.0_search-insights@2.6.0\node_modules\@algolia\autocomplete-core\dist\esm\resolve.js (79:0)
resolve
node_modules\.pnpm\@algolia+autocomplete-core@1.9.4_@algolia+client-search@4.18.0_algoliasearch@4.18.0_search-insights@2.6.0\node_modules\@algolia\autocomplete-core\dist\esm\resolve.js (71:0)
promise callback*onInput/request<
node_modules\.pnpm\@algolia+autocomplete-core@1.9.4_@algolia+client-search@4.18.0_algoliasearch@4.18.0_search-insights@2.6.0\node_modules\@algolia\autocomplete-core\dist\esm\onInput.js (80:5)
promise callback*onInput
node_modules\.pnpm\@algolia+autocomplete-core@1.9.4_@algolia+client-search@4.18.0_algoliasearch@4.18.0_search-insights@2.6.0\node_modules\@algolia\autocomplete-core\dist\esm\onInput.js (71:3)
onFocus
node_modules\.pnpm\@algolia+autocomplete-core@1.9.4_@algolia+client-search@4.18.0_algoliasearch@4.18.0_search-insights@2.6.0\node_modules\@algolia\autocomplete-core\dist\esm\getPropGetters.js (129:15)
```

## Code To Reproduce Issue
```typescript

const client= client({
  url: '/api/search', // Proxying with Nextjs Route Handlers
})


 const autocomplete = React.useMemo(
    () =>
      createAutocomplete({
        onStateChange({ state }) {
          setAutocompleteState(state)
        },
        getSources({ query, state }) {
          if (!query) {
            return []
          }
          return [
            {
              sourceId: 'entities',
              getItems({ query }) {
                return getAlgoliaResults({
                  searchClient: client,
                  queries: [
                    {
                      indexName: '*',
                      query,
                    },
                  ],
                  transformResponse({ hits }) {
                    const [entitiesHits] = hits
                    return entitiesHits
                  },
                })
              },
            },
          ]
        },
      }),
    [client],
  )
```

EDIT: tried with `@algolia/autocomplete-js`  1.9.4 and 1.9.2

**Comment by alessandrojcm** [comment]
Ok so apparently my issue was that I was trying to use the autocomplete state instead of the hooks provided by `react-instantsearch-hooks`. Which bears the question, is it possible to use the autocomplete state directly? Forgive me if I am missing something, but I don't see what's the benefit of using the autocomplete.js library if all the state needs to be handled manually with the hooks.

**Comment by joemcelroy** [comment]
thanks for digging in further @alessandrojcm - The autocomplete js library is decoupled from instantsearch. Its by design so that even vue / angular implementations can use autocomplete.js library. So to update the state, its expected to use the framework specific instantsearch implementatiion. I agree it could be better. Hope that makes sense!

**Comment by joemcelroy** [comment]
Probably not. Its really just a standalone autocomplete. theres limited value on top if you're using your own UX.

**Comment by jongacnik** [comment]
Hi @alessandrojcm currently running into the same `appId` issue. Did you end up resolving this using autocomplete.js?

**Comment by jongacnik** [comment]
@alessandrojcm It appears autocomplete.js [expects some Algolia headers](https://github.com/algolia/autocomplete/blob/b7606d57dcdfeac99e7161b280790ac20ddc3c48/packages/autocomplete-preset-algolia/src/search/fetchAlgoliaResults.ts#L27). It’s not the cleanest solve, but if you spoof the transporter headers for the client passed to autocomplete, the request works as expected:

```js
const autocompleteClient = client({
  url: '/api/search'
})

autocompleteClient.transporter.headers = {
  'x-algolia-application-id': 'NULL',
  'x-algolia-api-key': 'NULL'
}
```

**Comment by joemcelroy** [comment]
noticed this also broken on the autocomplete demo so showed the example of using the above patch. In future i will have a client for the autocomplete which will spoof the transporter headers internally, so doesn't need the developer to do this :)

**Comment by seyanaracore** [comment]
please, somebody, give me working example searchkit with algolia. [This example](https://www.searchkit.co/docs/components/autocomplete) is shit. pseudo code. Where use? How use?...
