### ISSUE TITLE
Server error when requesting a demo page directly

### ISSUE THREAD

**Issue by nitinl-cogapp** [searchkit/searchkit#1297]
## The problem

Server error when requesting a demo page directly, but not when navigating from the `/demos` page.

## Environment

* The deployed version of your site.

## Code To Reproduce Issue

1. Server error when visiting [the ecommerce demo directly](https://www.searchkit.co/demo-ecommerce) (try opening in incognito mode directly).
2. No error when click through from the [`/demos` page](https://www.searchkit.co/demos).

Not sure if this is a Searchkit issue, some sort of Next routing issue.

**Comment by joemcelroy** [comment]
thanks for heads up! Will investigate - curiously also doesn't affect the `/demo` page either. Something slightly different in their setup.

**Comment by joemcelroy** [comment]
resolved
