### ISSUE TITLE
Accessibility features for SearchKit components Inquiry

### ISSUE THREAD

**Issue by PrettyLegit0101** [searchkit/searchkit#1298]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Searchkit). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. You can ask them in [Discussions](https://github.com/searchkit/searchkit/discussions).

I'm pretty new to searchkit, and i find myself jumping in at a time where I'm looking around the internet on help migrating Searchkit v2 to v4... but thats a topic for another story.

The inquiry: I could not find a way to make SearchBox accessible in terms of looking at **chrome dev tools -> accessibility tree**. I see that the SearchBox renders a **form -> input html element**, but i don't know how to pass `id="search"` that far down a pre-built package component compared to how [MDN Input Docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) does it.

## Environment

* Searchkit version (or git revision) that exhibits the issue: SearchKit version 2 is what I'm using, but I am reading though [The latest Search Kit Docs](https://www.searchkit.co/docs/getting-started/with-react) (which is v4 i think...).

* Last Searchkit version that did not exhibit the issue (if applicable): N/A
* Node.js version: 18
* Typescript version: No typescript.... lol 😅😰, only javascript.
* Next.js version: Good ole gatsby.js V5
* ElasticSearch/OpenSearch version: v16.7.2

## Code To Reproduce Issue

I don't necessarily have a code examples aside from reading over the typescript package components and trying to pass the "id" attribute down the to SearchBox component in hopes of reaching the `input element` in the DOM. 

I'm just an intern trying to figure this out :) 
Any and all help pointing me closer to the right direction helps!
// I also have a discussion post if you could graciously help there too :P

Thank you in advance!

**Comment by joemcelroy** [comment]
Hey! Take a look at the component docs for [searchbox](https://www.algolia.com/doc/api-reference/widgets/search-box/react/).

Likely only way if using the hooks is to create a custom SearchBox react component and use the [searchbox hook](https://www.algolia.com/doc/api-reference/widgets/search-box/react/#hook) for the methods

**Comment by PrettyLegit0101** [comment]
Thank you :)
