### ISSUE TITLE
ImmutableQuery should support all top level elastic fields

### ISSUE THREAD

**Issue by ssetem** [searchkit/searchkit#130]
add "fields", "script_fields" among others

**Comment by andymac4182** [comment]
Is there an easy way to access `script_fields` without this work?

**Comment by Leaf-Lin** [comment]
Reopening this issue as this will add more flexibility to the query request body.


The other one that would be useful to have is [`runtime_mappings`](https://www.elastic.co/guide/en/elasticsearch/reference/current/runtime-search-request.html)
