### ISSUE TITLE
queryPostProcess hook 

### ISSUE THREAD

**Issue by ssetem** [searchkit/searchkit#131]
Ability for plain query object to be intercepted before its sent to elastic.
Just incase it needs to be processed by elastic expert etc

**Comment by GregoryPotdevin** [comment]
Should this be a "set" or an "add/remove" ? ie, if I have multiple postProcesses, will the system take care of combining them or do I have to do it myself ?

**Comment by ssetem** [comment]
not sure, I think simple single function is enough for now
