### ISSUE TITLE
Add runtime_mappings to the top level of request_body

### ISSUE THREAD

**Issue by Leaf-Lin** [searchkit/searchkit#1310]
## The problem

It would be great to have `runtime_mappings` available at the top-level elasticsearch query request body. This is similar to the enhancement request described in https://github.com/searchkit/searchkit/issues/130

## Details

In Elasticsearch, `runtime_mappings` may be used to define fields not currently available in the documents. This is related to https://github.com/searchkit/searchkit/issues/1309 where the output of the runtime fields also needs to be available for display and filter.

An example can be found in https://www.elastic.co/guide/en/elasticsearch/reference/current/runtime-search-request.html
```
GET my-index-000001/_search
{
  "runtime_mappings": {
    "day_of_week": {
      "type": "keyword",
      "script": {
        "source": "emit(doc['@timestamp'].value.dayOfWeekEnum.getDisplayName(TextStyle.FULL, Locale.ROOT))"
      }
    }
  },
  "aggs": {
    "day_of_week": {
      "terms": {
        "field": "day_of_week"
      }
    }
  }
}
```
[Map a runtime field in the mappings](https://www.elastic.co/guide/en/elasticsearch/reference/current/runtime-mapping-fields.html) wouldn't have helped in my use case because my `runtime_mappings` depends on the query input. 
```
GET my-index-000001/_search
{
  "runtime_mappings": {
    "query_input": {
      "type": "double",
      "script": {
        "source": "emit(query_input*2)"
      }
    }
  }
}
```

**Comment by joemcelroy** [comment]
runtime support was added. See documentation https://www.searchkit.co/docs/api-documentation/searchkit#search_settings-configuration
