### ISSUE TITLE
"Does Searchkit for Vue 2 support or have an implementation of 'searchOnLoad' for creating a manager?"

### ISSUE THREAD

**Issue by Barolina** [searchkit/searchkit#1314]
"Does Searchkit for Vue 2 support or have an implementation of 'searchOnLoad' for creating a manager?".

Please: (

**Comment by joemcelroy** [comment]
Worth looking at the docs for vue2 https://www.algolia.com/doc/api-reference/widgets/instantsearch/vue/#props. AFAIK, it should search by default.
