### ISSUE TITLE
Not able to implement latest version (4.0.0) of searhkit, earlier had serchkit-carnary version

### ISSUE THREAD

**Issue by Mehak-Singla** [searchkit/searchkit#1315]
## The problem
Error: Error transforming Elasticsearch response for index
    at transformResponse (/home/unthinkable/Work/NeGd/myscheme-search-service/node_modules/searchkit/src/transformResponse.ts:243:11)
    at /home/unthinkable/Work/NeGd/myscheme-search-service/node_modules/searchkit/src/index.ts:82:16
    at Array.map (<anonymous>)
    at Searchkit.handleInstantSearchRequests (/home/unthinkable/Work/NeGd/myscheme-search-service/node_modules/searchkit/src/index.ts:77:50)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SearchService.searchSchemesData (/home/unthinkable/Work/NeGd/myscheme-search-service/src/search-v3/search.service.ts:778:21)
    at SearchSchemeController.searchSchemes (/home/unthinkable/Work/NeGd/myscheme-search-service/src/search-v3/search.controller.ts:103:20)
>>> Error: Error transforming response. Check the afterSearch hook function is correct. Likely you are not returning the correct response object.
    at Searchkit.handleInstantSearchRequests (/home/unthinkable/Work/NeGd/myscheme-search-service/node_modules/searchkit/src/index.ts:95:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SearchService.searchSchemesData (/home/unthinkable/Work/NeGd/myscheme-search-service/src/search-v3/search.service.ts:778:21)
    at SearchSchemeController.searchSchemes

## Environment

* Searchkit version (or git revision) that exhibits the issue: 4.11.0
* Last Searchkit version that did not exhibit the issue (if applicable): @searchkit/sdk": "^3.0.0-canary.55"
* Node.js version:20.0.0
* Typescript version:
* Next.js version:
* ElasticSearch/OpenSearch version:

## Details
 async searchSchemesData(q: any, lang: string, sort: string, keyword: string, from: any, size: any) {
  
    try{
    const client = Client({
      connection: {
        host: process.env.OPENSEARCH_NODE_V3 + '/' + process.env.ELASTICSEARCH_INDEX_V3, // elasticsearch instance url
        headers: { 
          'Authorization': process.env.OPENSEARCH_KEY_V3 ? process.env.OPENSEARCH_KEY_V3 : ''
        }
      },
      search_settings: {
        highlight_attributes: ['schemeName','tags','briefDescription'],
        search_attributes: ['schemeName', 'briefDescription', 'tags'],
        result_attributes: ['schemeName', 'nodalMinistryName', 'briefDescription', 'schemeShortTitle', 'schemeCategory', 'schemeCloseDate', 'tags', 'slug', 'beneficiaryState'],
        facet_attributes: [
          { attribute: 'beneficiaryState.raw', field: 'beneficiaryState', type: 'string' }
        ]
      },
    });

    const results = await client.handleRequest([{"identifier":"benificiaryState","value":"Punjab"}], {
      hooks: {
        afterSearch: async (searchRequests, searchResponses) => {
          console.log(searchResponses);
          return Promise.resolve(searchResponses);
        },
      },
    });
    console.log(">>>>", results)
    } catch(err) {
      console.log(">>>",err)
    }
  }
Trying to achieve simple connection n search state wise scheme but contatntly getting above error 

## Code To Reproduce Issue
 async searchSchemesData(q: any, lang: string, sort: string, keyword: string, from: any, size: any) {
    var casteValue = "";
    if(q !== "" && q !== null && q !== undefined && q !== "undefined"){
      q = JSON.parse((q));
      casteValue = await this.SearchDataModificationService.getCasteValues(q);
    }
    
    let facetsFields = "age.general";
    let facetsValue = "General";
    let identifierVal = "age-general";
    if(casteValue === "Scheduled Tribe (ST)"){
        facetsFields = 'age.st';
        identifierVal = "age-st";
        facetsValue = "Scheduled Tribe (ST)";
    }else if(casteValue === "Other Backward Class (OBC)"){
      facetsFields = 'age.obc';
      identifierVal = "age-obc";
      facetsValue = "Other Backward Class (OBC)";
    }else if(casteValue === "Particularly Vulnerable Tribal Group (PVTG)"){
      facetsFields = 'age.pvtg';
      identifierVal = "age-pvtg";
      facetsValue = "Particularly Vulnerable Tribal Group (PVTG)";
    }else if(casteValue === "Scheduled Caste (SC)"){
      facetsFields = 'age.sc';
      identifierVal = "age-sc";
      facetsValue = "Scheduled Caste (SC)";
    }

    const skConfig = {
      host: process.env.OPENSEARCH_NODE_V3, // elasticsearch instance url
      connectionOptions: {
        headers: {
          'Content-Type': 'application/json',
          'Authorization': process.env.OPENSEARCH_KEY_V3 ? process.env.OPENSEARCH_KEY_V3 : ''
        }
      },
      index: ((lang) && (lang === "hi") ? process.env.ELASTICSEARCH_INDEX_V3_HI : process.env.ELASTICSEARCH_INDEX_V3), // search indices name
      hits: {
        fields: ['schemeName', 'nodalMinistryName', 'briefDescription', 'schemeShortTitle', 'schemeCategory', 'schemeCloseDate', 'tags', 'slug', 'beneficiaryState'],
        highlightFields: ['schemeName','tags','briefDescription']
      },
      query: new MultiMatchQuery({
        fields: [
          'schemeName',
          'briefDescription',
          'tags'
        ]
      }),
      sortOptions: [
        {
          id: 'multiple_sort',
          label: 'Relevance',
          field: [
            // {'priority': 'asc'},
            {'_score': 'desc'},
          ],
          defaultOption: true
        },
        {
          id: 'schemename-asc',
          label: 'Scheme Name (A->Z)',
          field: {'schemeName.raw2': 'asc'}
        },
        {
          id: 'schemename-desc',
          label: 'Scheme Name (Z->A)',
          field: {'schemeName.raw2': 'desc'}
        }
      ],
      facets: [
        new RefinementSelectFacet({
          field: 'beneficiaryState.raw',
          identifier: 'beneficiaryState',
          label: ((lang) && (lang === "hi") ? "राज्य" : "State"),
          size: 36,
          display: 'ComboBoxFacet',
          multipleSelect: true
        }),
        new RefinementSelectFacet({
          field: 'schemeCategory.raw',
          identifier: 'schemeCategory',
          label: ((lang) && (lang === "hi") ? "योजना श्रेणी" : "Scheme Category"),
          size: 20,
          multipleSelect: true,
        }),
        new RefinementSelectFacet({
          field: 'gender.raw',
          identifier: 'gender',
          label: ((lang) && (lang === "hi") ? "लिंग" : "Gender"),
          multipleSelect: true,
        }),
        new RangeFacet({
          field: facetsFields,
          identifier: identifierVal,
          label: ((lang) && (lang === "hi") ? "आयु" : "Age"),
          display: 'ComboBoxFacet',
          range: {
            interval: 1,
            max: 100,
            min: 1,
          },
        }),
        new RefinementSelectFacet({
          field: 'caste.raw',
          identifier: 'caste',
          size: 20,
          label: ((lang) && (lang === "hi") ? "जाति" : "Caste"),
          multipleSelect: true,
        }),
        new RefinementSelectFacet({
          field: 'nodalMinistryName.raw',
          identifier: 'nodalMinistryName',
          label: ((lang) && (lang === "hi") ? "मंत्रालय का नाम" : "Ministry Name"),
          display: 'ComboBoxFacet',
          size: 56,
          multipleSelect: true,
        }),
        new RefinementSelectFacet({
          field: 'level.raw',
          identifier: 'level',
          label: ((lang) && (lang === "hi") ? "स्तर" : "Level"),
          multipleSelect: true,
        }),
        new RefinementSelectFacet({
          field: 'residence.raw',
          identifier: 'residence',
          label: ((lang) && (lang === "hi") ? "निवास स्थान" : "Residence"),
          multipleSelect: true,
        }),
        new RefinementSelectFacet({
          field: 'minority.raw',
          identifier: 'minority',
          label: ((lang) && (lang === "hi") ? "अल्पसंख्यक" : "Minority"),
          multipleSelect: true,
        }),
        new RefinementSelectFacet({
          field: 'disability.raw',
          identifier: 'disability',
          label: ((lang) && (lang === "hi") ? "अलग रूप से सक्षम" : "Differently Abled"),
          multipleSelect: true
        }),
        new RefinementSelectFacet({
          field: 'benefitTypes.raw',
          identifier: 'benefitTypes',
          label: ((lang) && (lang === "hi") ? "लाभ प्रकार" : "Benefit Type"),
          multipleSelect: true,
        }),
        new RefinementSelectFacet({
          field: 'dbtScheme.raw',
          identifier: 'dbtScheme',
          label: ((lang) && (lang === "hi") ? "डीबीटी योजना" : "DBT Scheme"),
          multipleSelect: true,
        }),
        new RefinementSelectFacet({
          field: 'maritalStatus.raw',
          identifier: 'maritalStatus',
          label: ((lang) && (lang === "hi") ? "वैवाहिक स्थिति" : "Marital Status"),
          multipleSelect: true,
        }),
        new RangeFacet({
          field: 'disabilityPercentage',
          identifier: 'disabilityPercentage',
          label: ((lang) && (lang === "hi") ? "विकलांगता प्रतिशत" : "Disability Percentage"),
          display: 'ComboBoxFacet',
          range: {
            interval: 10,
            max: 100,
            min: 1,
          },
        }),
        new RefinementSelectFacet({
          field: 'isBpl.raw',
          identifier: 'isBpl',
          label: ((lang) && (lang === "hi") ? "गरीबी रेखा के नीचे" : "Below Poverty Line"),
          multipleSelect: true,
        }),
        new RefinementSelectFacet({
          field: 'isEconomicDistress.raw',
          identifier: 'isEconomicDistress',
          label: ((lang) && (lang === "hi") ? "आर्थिक संकट" : "Economic Distress"),
          multipleSelect: true,
        }),
        new RefinementSelectFacet({
          field: 'isGovEmployee.raw',
          identifier: 'isGovEmployee',
          label: ((lang) && (lang === "hi") ? "सरकारी कर्मचारी" : "Government Employee"),
          multipleSelect: true,
        }),
        new RefinementSelectFacet({
          field: 'employmentStatus.raw',
          identifier: 'employmentStatus',
          label: ((lang) && (lang === "hi") ? "रोज़गार की स्थिति" : "Employment Status"),
          multipleSelect: true,
        }),
        new RefinementSelectFacet({
          field: 'isStudent.raw',
          identifier: 'isStudent',
          label: ((lang) && (lang === "hi") ? "विद्यार्थी" : "Student"),
          multipleSelect: true,
        }),
        new RefinementSelectFacet({
          field: 'occupation.raw',
          identifier: 'occupation',
          label: ((lang) && (lang === "hi") ? "व्यवसाय" : "Occupation"),
          multipleSelect: true,
        }),
        new RefinementSelectFacet({
          field: 'applicationMode.raw',
          identifier: 'applicationMode',
          label: ((lang) && (lang === "hi") ? "आवेदन का माध्यम" : "Application Mode"),
          multipleSelect: true,
        }),
        new RefinementSelectFacet({
          field: 'schemeType.raw',
          identifier: 'schemeType',
          label: ((lang) && (lang === "hi") ? "योजना का प्रकार" : "Scheme Type"),
          multipleSelect: true,
        })
      ],
    };
    
    const request = Searchkit(skConfig);
    const response = await request
      .query(keyword ? keyword : '')
      .setFilters(q ? q : '')
      .setSortBy(sort ? sort : 'multiple_sort')
      .execute({
        facets: true,
        hits: {
          from: from ? parseInt(from) : 0,
          size: size ? parseInt(size) : 10,
        },
      });
    return response;
  }
  
  this was the old version which was working correctly

**Comment by joemcelroy** [comment]
- the host should be just the host, not include the index
- you can switch on debug mode if you want to see the full response https://www.searchkit.co/docs/api-documentation/api#debug-mode

**Comment by Mehak-Singla** [comment]
index is in the previous version which was implemented 
 current code is this which is not working 
   async searchSchemesData(q: any, lang: string, sort: string, keyword: string, from: any, size: any) {
  
    try{
    const client = Client({
      connection: {
        host: process.env.OPENSEARCH_NODE_V3 + '/' + process.env.ELASTICSEARCH_INDEX_V3, // elasticsearch instance url
        headers: { 
          'Authorization': process.env.OPENSEARCH_KEY_V3 ? process.env.OPENSEARCH_KEY_V3 : ''
        }
      },
      search_settings: {
        highlight_attributes: ['schemeName','tags','briefDescription'],
        search_attributes: ['schemeName', 'briefDescription', 'tags'],
        result_attributes: ['schemeName', 'nodalMinistryName', 'briefDescription', 'schemeShortTitle', 'schemeCategory', 'schemeCloseDate', 'tags', 'slug', 'beneficiaryState'],
        facet_attributes: [
          { attribute: 'beneficiaryState.raw', field: 'beneficiaryState', type: 'string' }
        ]
      },
    });

    const results = await client.handleRequest([{"identifier":"benificiaryState","value":"Punjab"}], {
      hooks: {
        afterSearch: async (searchRequests, searchResponses) => {
          console.log(searchResponses);
          return Promise.resolve(searchResponses);
        },
      },
    });
    console.log(">>>>", results)
    } catch(err) {
      console.log(">>>",err)
    }
  }

**Comment by Mehak-Singla** [comment]
Performing search with requests:
POST /_msearch
{}
{"query":{"bool":{"filter":[],"must":{"match_all":{}}}},"size":20,"from":0,"_source":{"includes":["schemeName","nodalMinistryName","briefDescription","schemeShortTitle","schemeCategory","schemeCloseDate","tags","slug","beneficiaryState"]},"highlight":{"pre_tags":["<em>"],"post_tags":["</em>"],"fields":{"schemeName":{"number_of_fragments":0},"tags":{"number_of_fragments":0},"briefDescription":{"number_of_fragments":0}}}}

Elasticsearch response:
{"took":3,"responses":[{"took":3,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":536,"relation":"eq"},"max_score":1,"hits":[{"_index":"dev_my_scheme_v3","_type":"_doc","_id":"W2-SnIkBY4joYqdttLNa","_score":1,"_source":{"beneficiaryState":["Arunachal Pradesh"],"schemeShortTitle":"DK","nodalMinistryName":null,"schemeCategory":["Social welfare & Empowerment"],"schemeName":"Dulari Kanya","schemeCloseDate":null,"slug":"dk","briefDescription":"“Dulari Kanya” is a scheme for the girl child by the Govt. of Arunachal Pradesh. The objective of the scheme is to end the preference between male and female child, encouragement of institutional delivery, immunization of children, to end child marriage and overall empowerment of females.","tags":["Girl Child","Social Welfare","Financial Assistance"]}},{"_index":"dev_my_scheme_v3","_type":"_doc","_id":"cW-SnIkBY4joYqdttLNg","_score":1,"_source":{"beneficiaryState":["Jammu and Kashmir"],"schemeShortTitle":"ISSS-PPCP","nodalMinistryName":null,"schemeCategory":["Social welfare & Empowerment"],"schemeName":"Integrated Social Security Scheme - Pension For Physically Challenged Persons","schemeCloseDate":null,"slug":"isss-ppcp","briefDescription":"ISSS-PPCP is a State Sponsored Scheme by the Social Welfare Dept. of the Govt. of J&K wherein financial assistance is provided to Physically Challenged Person who have meager support or no source of livelihood. A pension of ₹1000 per pensioner per month is deposited into their bank account.","tags":["Pension","PwD","Disability","Social Welfare"]}},{"_index":"dev_my_scheme_v3","_type":"_doc","_id":"bG-SnIkBY4joYqdttLNg","_score":1,"_source":{"beneficiaryState":["Uttar Pradesh"],"schemeShortTitle":"BBY","nodalMinistryName":null,"schemeCategory":["Social welfare & Empowerment"],"schemeName":"Berojgari Bhatta Yojna","schemeCloseDate":null,"slug":"bby","briefDescription":"The UP government has implemented the UP Unemployment Allowance 2022 scheme in Uttar Pradesh. The government has implemented this scheme only for those candidates who belong to the state and is unemployed despite being educated.","tags":["Berojgari Bhatta","Financial Assistance","Rojgaar Samgam",null]}},{"_index":"dev_my_scheme_v3","_type":"_doc","_id":"cm-SnIkBY4joYqdttLNh","_score":1,"_source":{"beneficiaryState":["Rajasthan"],"schemeShortTitle":"RCMRF-KP","nodalMinistryName":null,"schemeCategory":["Social welfare & Empowerment"],"schemeName":"Rajasthan Chief Minister's Relief Fund - Kargil Package","schemeCloseDate":null,"slug":"rcmrf-kp","briefDescription":"Rajasthan Chief Minister’s Relief Fund – Kargil package scheme launched on April 1999 under Chief Minister’s Relief Fund in Rajasthan for the Individual and family.","tags":[]}},{"_index":"dev_my_scheme_v3","_type":"_doc","_id":"dG-SnIkBY4joYqdttLNi","_score":1,"_source":{"beneficiaryState":["Delhi"],"schemeShortTitle":"SMSSS","nodalMinistryName":null,"schemeCategory":["Education & Learning"],"schemeName":"Scholarship/merit Scholarship To Sc/st Students From Class I To Xii","schemeCloseDate":null,"slug":"smsss","briefDescription":"The Department for the Welfare of SC/ST/OBC is implementing 9 types of Scholarship Schemes for the SC/ST/OBC/Min, including CSS schemes & five State- Funded Schemes, online, on e-district Portal. Scholarship/Merit Scholarship to SC/ST/OBC/Minorities students (Class I TO XII) scheme is one of these.","tags":["Scholarship","Merit Scholarship","Students","Direct Benefit Transfer","Class I To XII"]}},{"_index":"dev_my_scheme_v3","_type":"_doc","_id":"eW-SnIkBY4joYqdttLNj","_score":1,"_source":{"beneficiaryState":["Odisha"],"schemeShortTitle":"E-M","nodalMinistryName":null,"schemeCategory":["Education & Learning"],"schemeName":"E-Medhabruti","schemeCloseDate":null,"slug":"e-m","briefDescription":"The scheme \"e-Medhabruti\" is a Scholarship Scheme by the Higher Education Department, Government of Odisha. The objective of the scheme is to provide financial assistance of up to ₹ 20,000 to meritorious students of Odisha whose parental income does not exceed ₹ 6,00,000.","tags":["Scholarship","Undergraduate","Postgraduate"]}},{"_index":"dev_my_scheme_v3","_type":"_doc","_id":"im-SnIkBY4joYqdttbMc","_score":1,"_source":{"beneficiaryState":["All"],"schemeShortTitle":"AFFDF","nodalMinistryName":"Ministry Of Defence","schemeCategory":["Health & Wellness"],"schemeName":"AFFDF-Financial Assistance For Procuring Mobility Equipment To Disabled Ex-Servicemen(All Ranks)","schemeCloseDate":null,"slug":"affdf","briefDescription":"A scheme to provide financial assistance for procurement of modified scooter for those Ex-Servicemen, who are disabled after their retirement from service with disability of 50% or more.","tags":["Ex-Servicemen","Differently Abled"]}},{"_index":"dev_my_scheme_v3","_type":"_doc","_id":"jG-SnIkBY4joYqdttbMf","_score":1,"_source":{"beneficiaryState":["All"],"schemeShortTitle":"SR","nodalMinistryName":"Ministry Of Agriculture and Farmers Welfare","schemeCategory":["Education & Learning","Agriculture,Rural & Environment"],"schemeName":"Students Ready","schemeCloseDate":null,"slug":"sr","briefDescription":"The Student Rural Entrepreneurship Awareness Development Yojana (READY)  was launched by Hon'ble Prime Minister on 25 July 2015.\n","tags":["Student","Ready","Agriculture"]}},{"_index":"dev_my_scheme_v3","_type":"_doc","_id":"j2-SnIkBY4joYqdttbMf","_score":1,"_source":{"beneficiaryState":["Arunachal Pradesh"],"schemeShortTitle":"CMAAY","nodalMinistryName":null,"schemeCategory":["Health & Wellness"],"schemeName":"Chief Minister Arogya Arunachal Yojana(cmaay)","schemeCloseDate":null,"slug":"cmaay","briefDescription":"    Under this scheme coverage of upto 5 lakh per family per year is made available by the State Government. In addition to that Pre-hospitalization expenses for up to 3 days and post-hospitalization expenses for up to 10 days are covered.","tags":[]}},{"_index":"dev_my_scheme_v3","_type":"_doc","_id":"mm-SnIkBY4joYqdttbMj","_score":1,"_source":{"beneficiaryState":["Uttarakhand"],"schemeShortTitle":"MUKUY","nodalMinistryName":null,"schemeCategory":["Sports & Culture"],"schemeName":"Mukhyamantri Udiyaman Khiladi Unnayan Yojana","schemeCloseDate":null,"slug":"mukuy","briefDescription":"Uttarakhand Chief Minister Pushkar Singh Dhami ji started the Mukhyamantri Udeeyman Khiladi Unnayan Yojana 2022 by participating in the program organized on the occasion of National Sports Day.","tags":["Udiyaman","Khiladi Unnayan","Sports","Uttarakhand"]}},{"_index":"dev_my_scheme_v3","_type":"_doc","_id":"tW-SnIkBY4joYqdttbO8","_score":1,"_source":{"beneficiaryState":["All"],"schemeShortTitle":"SBM - G II","nodalMinistryName":"Ministry Of Jal Shakti","schemeCategory":["Utility & Sanitation","Health & Wellness"],"schemeName":"Swachh Bharat Yojana – Grameen Phase II","schemeCloseDate":null,"slug":"sbm-g-ii","briefDescription":"A sanitation scheme for Visual cleanliness through Open Defecation Free (ODF) sustainability and effective management of solid and liquid waste in villages","tags":["Swachh Bharat","Toilet","Sanitation","Rural","Grameen"]}},{"_index":"dev_my_scheme_v3","_type":"_doc","_id":"w2-SnIkBY4joYqdttbPA","_score":1,"_source":{"beneficiaryState":["All"],"schemeShortTitle":"MCM-MIN","nodalMinistryName":"Ministry Of Minority Affairs","schemeCategory":["Education & Learning","Social welfare & Empowerment"],"schemeName":"Merit Cum Means Based Scholarship For Students Belonging To The Minority Communities","schemeCloseDate":null,"slug":"mcm-min","briefDescription":"A scholarship scheme by the Ministry of Minority Affairs for students from minority communities pursuing technical and professional courses at undergraduate and postgraduate levels in a listed institute. A total of 60,000 scholarships are targeted to be distributed as ‘Fresh’ Scholarships.","tags":["Student","Scholarship","Minority","Higher Education"]}},{"_index":"dev_my_scheme_v3","_type":"_doc","_id":"xG-SnIkBY4joYqdttbPA","_score":1,"_source":{"beneficiaryState":[],"schemeShortTitle":"PRE-SC","nodalMinistryName":"Ministry Of Social Justice and Empowerment","schemeCategory":["Education & Learning","Social welfare & Empowerment"],"schemeName":"Centrally-Sponsored Scheme Of Pre-Matric Scholarship For Scheduled Caste Students Studying In Classes 9th & 10th","schemeCloseDate":null,"slug":"pre-sc","briefDescription":"A scholarship scheme by Ministry of Social Justice & Empowerment for regular, full-time students from Scheduled Castes studying in Class 9th and 10th in a Govt. School / a School recognized by Govt. / CBSE / State Board of Secondary Education.","tags":["Pre Matric","Scholarship","Scheduled Caste","Student","Social Welfare","Person With Disability"]}},{"_index":"dev_my_scheme_v3","_type":"_doc","_id":"y2-SnIkBY4joYqdttbPD","_score":1,"_source":{"beneficiaryState":["Karnataka"],"schemeShortTitle":"SLG","nodalMinistryName":null,"schemeCategory":["Education & Learning"],"schemeName":"Stipend To Law Graduates","schemeCloseDate":null,"slug":"slg","briefDescription":"Under this scheme, the Social Welfare Department, Govt of Karnataka will give a stipend to the Law Graduates belonging to SC/ST Community residing in Karnataka. This will help them to practice law in various courts and training courses will also be organized under the guidance of senior advocates.","tags":["SC","ST","Stipend","Law Graduates","Karnataka"]}},{"_index":"dev_my_scheme_v3","_type":"_doc","_id":"4G-SnIkBY4joYqdttbPl","_score":1,"_source":{"beneficiaryState":["Maharashtra"],"schemeShortTitle":"GSGOS","nodalMinistryName":null,"schemeCategory":["Business & Entrepreneurship","Skills & Employment"],"schemeName":"Group Supply Of Goats And Sheep","schemeCloseDate":null,"slug":"gsgos","briefDescription":"Group supply of goats and sheep refers to the practice of selling or distributing goats and sheep in groups, rather than as individual animals. In Maharashtra, this practice is common among farmers, livestock traders, and cooperative organizations. ","tags":["Tribal Scheme","Goat Supply","Sheep Supply","Maharashtra Scheme","State Scheme"]}},{"_index":"dev_my_scheme_v3","_type":"_doc","_id":"7m-SnIkBY4joYqdttbPs","_score":1,"_source":{"beneficiaryState":["Telangana"],"schemeShortTitle":"KCR NUTRITION KIT","nodalMinistryName":null,"schemeCategory":["Health & Wellness","Social welfare & Empowerment"],"schemeName":"KCR Nutrition Kit","schemeCloseDate":null,"slug":"kcr-nutrition-kit","briefDescription":"KCR Nutrition Kits Scheme is a welfare initiative launched by the Government of Telangana, India, aimed at providing nutritious food to pregnant. The primary objective of the scheme is to improve the nutritional status of pregnant women. ","tags":["Pregnant Women Care Kit","Providing Nutritious Food To Pregnant Women And Children","Anganwadi Centers","Improve The Nutritional Status Of Pregnant"]}},{"_index":"dev_my_scheme_v3","_type":"_doc","_id":"72-SnIkBY4joYqdttbPs","_score":1,"_source":{"beneficiaryState":["Assam"],"schemeShortTitle":"ADOW","nodalMinistryName":null,"schemeCategory":["Business & Entrepreneurship"],"schemeName":"Aamar Dukan On Wheels","schemeCloseDate":null,"slug":"adow","briefDescription":"The Assam Government proposes to introduce a new module of “Aamar Dukan” namely “AAMAR DUKAN ON WHEELS” in the same line as the existing ‘Aamar Dukan’ on 22.02.2017.","tags":["Aamar Dukan","Wheels","Business","Startup"]}},{"_index":"dev_my_scheme_v3","_type":"_doc","_id":"8G-SnIkBY4joYqdttbPu","_score":1,"_source":{"beneficiaryState":["Mizoram"],"schemeShortTitle":"MRF","nodalMinistryName":null,"schemeCategory":["Education & Learning"],"schemeName":"Mizoram Research Fellowship","schemeCloseDate":null,"slug":"mrf","briefDescription":"The \"Mizoram Research Fellowship\" aims to provide financial assistance to research workers and teachers, preferably below the age of 45 years, who have established their reputation for research OR have obtained a doctorate degree OR have published research work to their credit.","tags":["Fellowship","PhD","Research","Postgraduation"]}},{"_index":"dev_my_scheme_v3","_type":"_doc","_id":"8W-SnIkBY4joYqdttbPu","_score":1,"_source":{"beneficiaryState":["Jharkhand"],"schemeShortTitle":"NPY-JBOCWWB","nodalMinistryName":null,"schemeCategory":["Banking,Financial Services and Insurance","Social welfare & Empowerment"],"schemeName":"Nishaktata Pension Yojana (JBOCWWB)","schemeCloseDate":null,"slug":"npy-jbocwwb","briefDescription":"\"Nishaktata Pension Yojana (JBOCWWB)\" is a scheme by the Department of Labour, Employment, Training & Skill Development Govt of Jharkhand. The scheme provides a pension of ₹ 1,000/- per month to the registered beneficiary who is permanently disabled due to paralysis/leprosy/tuberculosis/accident.","tags":["Pension","Disability","Construction Worker","Social Welfare"]}},{"_index":"dev_my_scheme_v3","_type":"_doc","_id":"Ym-SnIkBY4joYqdttLNb","_score":1,"_source":{"beneficiaryState":["Assam"],"schemeShortTitle":"SS-A","nodalMinistryName":null,"schemeCategory":["Health & Wellness"],"schemeName":"Sneha Sparsha","schemeCloseDate":null,"slug":"ss-a","briefDescription":"\"Sneha Sparsha\" is a healthcare scheme by the Dept. of Health & Family Welfare, Govt. of Assam. In this scheme, financial assistance shall be provided for specialized treatment of children below 12 years of age affected with some serious ailments.","tags":["Disease","Child","Financial Assistance"]}}]},"status":200}]}
[
  {
    took: 3,
    timed_out: false,
    _shards: { total: 1, successful: 1, skipped: 0, failed: 0 },
    hits: { total: [Object], max_score: 1, hits: [Array] },
    status: 200
  }
]
Error: Error transforming Elasticsearch response for index
    at transformResponse (/home/unthinkable/Work/NeGd/myscheme-search-service/node_modules/searchkit/src/transformResponse.ts:243:11)
    at /home/unthinkable/Work/NeGd/myscheme-search-service/node_modules/searchkit/src/index.ts:82:16
    at Array.map (<anonymous>)
    at Searchkit.handleInstantSearchRequests (/home/unthinkable/Work/NeGd/myscheme-search-service/node_modules/searchkit/src/index.ts:77:50)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SearchService.searchSchemesData (/home/unthinkable/Work/NeGd/myscheme-search-service/src/search-v3/search.service.ts:779:21)
    at SearchSchemeController.searchSchemes (/home/unthinkable/Work/NeGd/myscheme-search-service/src/search-v3/search.controller.ts:103:20)
>>> Error: Error transforming response. Check the afterSearch hook function is correct. Likely you are not returning the correct response object.
    at Searchkit.handleInstantSearchRequests (/home/unthinkable/Work/NeGd/myscheme-search-service/node_modules/searchkit/src/index.ts:95:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SearchService.searchSchemesData (/home/unthinkable/Work/NeGd/myscheme-search-service/src/search-v3/search.service.ts:779:21)
    at SearchSchemeController.searchSchemes (/home/unthinkable/Work/NeGd/myscheme-search-service/src/search-v3/search.controller.ts:103:20)







Also in debug mode true it is bringing all results,
1)  though I am asking for one particular state {"identifier":"benificiaryState","value":"Punjab"},
2) And if query is incorrect n bringing all result it should return but i am getting error.

**Comment by joemcelroy** [comment]
closing issue, resolved on discord.
