### ISSUE TITLE
Is there any GraphQL support?

### ISSUE THREAD

**Issue by wyxcoder** [searchkit/searchkit#1319]
## The problem

I tried to find a lib to handle search UI with GraphQL backend. I found a few entries mentioning SearchKit and GraphQL. But I didn't see any GraphQL related topics on SearchKit page.

**Comment by wyxcoder** [comment]
Hi Joe,

 Thanks for you detail reply.

 I am pretty new here, I wonder if you can confirm my understand here. So InstantSearch is an UI Lib that is created to work with Algolia server. And you created SearchKit so the InstandSearch can connect to ElasticSearch server.

**Comment by joemcelroy** [comment]
Correct @wyxcoder - its an adapter which allows you to use instantsearch with Elasticsearch and not need Algolia.

**Comment by wyxcoder** [comment]
@joemcelroy Thanks! That is what I got. I actually have a legacy SQL server DB in backend, I thought I will just add a GraphQL to it and then use the popular frontend React. 
Maybe I should use your SearchKit V3.
Just checked the server component of NextJS 13, it seems the React front end plus API is not the only option now. Instead maybe I can just connect NextJS server side to SQL server directly without any API.
