### ISSUE TITLE
hitsPerPage not updated

### ISSUE THREAD

**Issue by GregoryPotdevin** [searchkit/searchkit#132]
The number of hits displayed doesn't update when hitsPerPage is updated. This is problematic to implement a selector with the number of items to display per page.

**Comment by joemcelroy** [comment]
This is fixed right @GregoryPotdevin?

**Comment by GregoryPotdevin** [comment]
The value was pushed into an accessor. Manually changing the hitsPerPage probably still doesn't work but there's a nice workaround.
For the record, the current approach (which will hopefully be generalized in v0.9) is have accessors/states manage the search values or options which can change. For now there's 1 accessor/component per value (pageNumber, hitsPerPage, view, etc.) but we need to converge towards a generic solution (auto-update query and components, and serialize state in the queryString, which you wouldn't get for free if you handled those values yourself as state). The stateful accessor pattern reduces the required boilerplate to link components together (ex : `<ViewSwitcher />`)
