### ISSUE TITLE
Unable to access event listeners for DateRangeFacet in v3

### ISSUE THREAD

**Issue by dvanpelt-hub** [searchkit/searchkit#1330]
## The problem
It would be beneficial to provide access to the event listeners associated with the DateRangeFacet in SearchKit v3. For example, if I select a date in the 'from' section I need to select a date in the 'to' section to initialize the search. After the results are generated, if I want to change either the 'from' or 'to' date, I must change both in order to initialize the search. Ideally, I should be able to adjust one or the other, as long as there are dates set for both. It does not seem possible to adjust this with the v3 DateRangeFacet implementation.

## Environment
* Searchkit Version 3.0
* Node.js: v16.15.1
* Typescript: Version 4.6.3
* "@elastic/elasticsearch": "^8.4.0"

## Code to reproduce issue
In this sandbox we can see the behavior:

https://codesandbox.io/s/searchkit-cra-xj25o0

Thank you!

**Comment by joemcelroy** [comment]
Closing this issue as not supporting new features for v3.
