### ISSUE TITLE
How to distinct your index ?

### ISSUE THREAD

**Issue by fvsadem** [searchkit/searchkit#1332]
Hi,

I try to migrate form algolia to elasticsearch and keep using instantsearch.
I face a problem with distinct attribute. 
In Algolia index, i could add a distinct attribute "attributeForDistinct".
When i configure the instantsearch "configure" widgets, i could activate the distinct or not.

_For the context_ : I manage a marketplace where all the merchants have the same offers (same price, same everything).
On our website, our customer could search a product but only one offer could be show on the search page (for example the first merchant offer of the list). With algolia i could distinct with "sku" attribute (this is the same for all merchant offers for a product). 

How could i add the same function with searchkit ?
Do i have to add something to elasticsearch index ? 

Any example would be apreciate.

THX

## Environment

* Searchkit : 4.11.0
* searchkit/instantsearch-client : 4.12.0
* ElasticSearch : 7.10.0
* Algolia Instantsearch.js : 4.2.0

**Comment by fvsadem** [comment]
After some research, I found that Typesense uses a grouping strategy to do what I want to do...
https://typesense.org/docs/0.25.2/api/search.html#group-results

Is there a similar grouping method in Searchkit?

**Comment by joemcelroy** [comment]
i haven't tried this but you could use the field collapse feature (https://www.elastic.co/guide/en/elasticsearch/reference/current/collapse-search-results.html) and send this param via the beforeSearch hook (to add the parameter) and afterSearch hook (to transform the `collapse` field into hits that searchkit expects)

see https://www.searchkit.co/docs/api-documentation/searchkit#beforesearch-hook-function
