### ISSUE TITLE
Algolia v7 API and date filter not working

### ISSUE THREAD

**Issue by tomisicm** [searchkit/searchkit#1334]
## The problem

There is a newer version of Algolia components ( v7 ) which has the new API, compared to the v6.
 
Please update the docs, 
https://github.com/searchkit/searchkit/blob/4267524ba0d07a2117de5539a075004f5157e64f/apps/web/pages/camping-sites-demo.jsx
as they are outdated. 

All of the existing filters work as expected, the only issue I have found is with date components.  

filter_attributes: [
      { field: 'created_at', attribute: 'created_at', type: 'date' },
    ],

Please provide examples with date filter. 

Nice to have:
filter for gte and lte filter for created_at
date format of the date is in timestamps ( covering conversion between different formats )

## Environment

* Searchkit version (or git revision) that exhibits the issue: 4.11 
* Last Searchkit version that did not exhibit the issue (if applicable):
* Node.js version: any
* Typescript version: any
* Next.js version: any
* ElasticSearch/OpenSearch version: any

**Comment by joemcelroy** [comment]
spoken over discord - Suggested to look at the `useConnector` https://www.algolia.com/doc/api-reference/widgets/connector/react/ to build a custom widget that applies filters.

Love to have a PR from someone to update the demo to v7 code :)
