### ISSUE TITLE
Using Searchkit on local (.json) data?

### ISSUE THREAD

**Issue by PAK90** [searchkit/searchkit#134]
I want to create a page similar to your [demo movie page](http://demo.searchkit.co/), but using local data; all the data is stored in a .json file. [The docs](http://docs.searchkit.co/stable/docs/setup/elasticsearch.html) only mention 'using local ES server' and since I don't have one of those, how can I hook up my .json file to the Searchkit manager? I tried setting ```const host = "./path/to/data.json"``` but that didn't work, dev tools showed that it was appending '_search' at the end of that string.

**Comment by joemcelroy** [comment]
Hi there,

Searchkit relies on an ElasticSearch service, either hosted locally or externally accessible. Searchkit creates an elasticsearch query and renders the response from Elasticsearch. You might be able to mock the first response in a local json file but will fall apart when you try interacting with the components like searching.

Any reason why you need it to use local data? You can sign up to a free Elasticsearch instance like http://www.searchly.com/pricing/ or use our Elasticsearch movies host http://demo.searchkit.co/api/movies if you want to experiment on Searchkit.

Joe

**Comment by GregoryPotdevin** [comment]
There are several use cases I would have for working with local data :
- preload menu/admin page data in the html and do local queries for a quick admin panel search menu
- offline mode : select documents to store offline and still have the ability to search them

There are currently no ES-like offline javascript libraries. The closest you can get is Lunr (Solr-like in JS) and alaSQL (full SQL with offline storage and json querying). Both of these would lack the aggregators features that are required for searchkit to work. I guess someone could get to work and try to build a sort of "ES.js" using one of these products, but it's a lot of work (though probably fun).

**Comment by PAK90** [comment]
I guess the reason I wanted to use local data is that I had the .json file right there, ready to use. But if that won't work, fair enough.

If I wanted to try the free instance, how does one go about setting it up? I have all the data I want to search in my .json file, do I just upload it to the instance and it does all the work from there? Also, what's an 'index' and how does it affect my usage of SearchKit? That seems to be literally the only difference between price levels (aside from storage space, which with my few-MB data file is really irrelevant).

**Comment by joemcelroy** [comment]
Hey, 

Have a readup on indexing data into elasticsearch. Its pretty easy to get started. A good indexer example would be our searchkit-demo (https://github.com/searchkit/searchkit-demo/blob/master/movie-index/indexer.coffee). This takes a JSON file and indexes it into an ES server. 

You can start on the free one. I had searchkit.co running on it with 5000 docs for a while! 

Joe

**Comment by PAK90** [comment]
I presume the json file you're referring to is in fact the .js file [imdbMoviesNew.js](https://raw.githubusercontent.com/searchkit/searchkit-demo/master/movie-index/imdbMoviesNew.js)? 

I set up a Vagrant vm running an instance of elasticsearch, but it's empty. Your code shows this indexer.coffee file which I have a few questions about... 
I get that you first declare a bunch of helper functions (though what's with the empty function [on line 26?](https://github.com/searchkit/searchkit-demo/blob/master/movie-index/indexer.coffee#L26)), then you parse the movies (how do you deal with missing fields? My dataset omits fields that contain the equivalent of N/A data). But what's ```getMultiFieldDef``` for? What's the random ```def``` on line 82? What are ```settings``` doing, especially the arcane stuff on line 92? And the last part of the code is making a command per movie and presumably sending it to the ES server, which also makes sense. A few comments in the file wouldn't go amiss...

Thanks for the help by the way, this stuff is pretty overwhelming at first.

**Comment by joemcelroy** [comment]
Hey

These helper methods prepare the data thats in imdbMoviesNew so that its searchable and can generate good aggregations to power our filter components.

To summarize, the indexer deletes the movie index, recreates the movie index with a mapping (mapping is the index field definitions) and pushes all the movies documents to the index.

- We omit fields when there is no data. The compact fn returns an object with null data omitted. See lodash fn compact.
- coffeescript does implicit returns in functions so l82 is equivalent to `return def`
- `getMultiFieldDef` is a helper function which creates a multifield mapping definition for a field, one field which is passed through the standard analyzer and one field which is the raw data. Analyzed field is used for when we want to use the field for searching and the raw data one is when we want to use it for our filter components

Indexer was our own quick hack to get data in quick, not to be used as a boilerplate with good practices. This is all generic elasticsearch concepts which are not to do with Searchkit and you can find help in other places like Stackoverflow, blogs etc. 

Definitely want to revisit the story on helping new developers get started quicker on ES soon though!

Joe

**Comment by PAK90** [comment]
OK, so if I have a Card object which doesn't have one of the fields (e.g. 'artist') that the initial parser is looking for, Card.artist would return undefined, and this script would be able to handle that?
What determines whether you want a field to be multifield mapped? Is it obligatory for fields that you want to both search and filter by?
Also, is the 'settings' variable pretty generic (so I could copy it into my script) or is it specific for the movie data? I'm not quite sure what it's doing.
In both the mapping var and the initial parser I see a property called ```suggest```;  ```input``` and ```output``` are pretty easy but what's ```payload``` and the other ones?

**Comment by ssetem** [comment]
@PAK90  :) do you want to pop on https://gitter.im/searchkit/searchkit
we can do more informal quick chat over this then

**Comment by ssetem** [comment]
@PAK90 your project looks good now with indexer and ui, I am going to close the issue for now
