### ISSUE TITLE
Dynamic bemBlocks

### ISSUE THREAD

**Issue by GregoryPotdevin** [searchkit/searchkit#136]
bemBlocks are currently computed when the component is mounted and won't change. This breaks hot reloading and using props updating to update the bemBlocks.

Using a javascript getter (get bemBlocks(){...}) would offer backwards compatibility and dynamic bemBlocks.

**Comment by joemcelroy** [comment]
thanks. fixing this

**Comment by joemcelroy** [comment]
done
