### ISSUE TITLE
Wrong content type: "application/json"

### ISSUE THREAD

**Issue by eliasbaixas** [searchkit/searchkit#1360]
## The problem

I am proxying the searchkit requests through a Rails controller, but it breaks because Rails tries to parse the request.body as json (as the content-type: application/json suggests). But JSON.parse(request.raw_body) blows because the body is actually not proper json, its a concatenation of 2 or more json strings, which on itself is not proper json.

## Environment

* Searchkit version (or git revision) that exhibits the issue: 4.11.2
* Last Searchkit version that did not exhibit the issue (if applicable):
* Node.js version: 20.6.1
* Typescript version:5.4.5
* ElasticSearch/OpenSearch version: Opensearch 2.11.1

## Details

from inspecting the requests and code, the request body sent is built from:
https://github.com/searchkit/searchkit/blob/a2b9df68a9e460992dd594fcc2c344c73d228c72/packages/searchkit/src/utils.ts#L90

and the wrong content-type: application/json is sent from:
https://github.com/searchkit/searchkit/blob/a2b9df68a9e460992dd594fcc2c344c73d228c72/packages/searchkit/src/Transporter.ts#L45

## Code To Reproduce Issue

Just any searchkit request is technically invalid: if the content-type header is 'application/json' the request body shoud adhere to RFC 7159 and be a proper JSON string (not a newline concatenation).

One way to fix this would be to send `application/x-ndjson` as content-type.

**Comment by eliasbaixas** [comment]
There are some examples of using curl to insert records to elasticsearch in the searchkit page, and they correctly use application/x-ndjson content-type:

https://www.searchkit.co/docs/getting-started/setup

**Comment by joemcelroy** [comment]
yeh i think the fix here is that it needs to send as content-type `application/x-ndjson`. Will need to test this or happy to accept a PR for it.

**Comment by eliasbaixas** [comment]
PR created: https://github.com/searchkit/searchkit/pull/1377
