### ISSUE TITLE
Incompatible types between `InstantSearchElasticsearchAdapter` and `SearchClient`

### ISSUE THREAD

**Issue by italodirenzo93** [searchkit/searchkit#1388]
## The problem
I'm following the [Build a Next.js app](https://www.searchkit.co/docs/tutorials/with-nextjs) guide in the documentation. The [Setup the Frontend](https://www.searchkit.co/docs/tutorials/with-nextjs#setup-the-frontend) section indicates that a a search client can be created using `createClient` and passed to the `InstantSearch` component's `searchClient` prop. However this produces the following type error:
```
TS2322: Type InstantSearchElasticsearchAdapter is not assignable to type SearchClient
```

## Environment

* Searchkit version (or git revision) that exhibits the issue: 4.14.0
* Last Searchkit version that did not exhibit the issue (if applicable):
* Node.js version: 18.18.0
* Typescript version: 5.5.3
* Next.js version: 14.2.12
* ElasticSearch/OpenSearch version: 8.13.0

## Code To Reproduce Issue
```tsx
import { InstantSearch, SearchBox, Hits } from "react-instantsearch";
import createClient from "@searchkit/instantsearch-client";
 
const searchClient = createClient({
  url: "/api/search",
});
 
export default function Search() {
  return (
    <InstantSearch
      searchClient={searchClient}
      indexName="<elasticsearch index or alias name>"
    >
      <SearchBox />
      <Hits />
    </InstantSearch>
  );
}
```

**Comment by joemcelroy** [comment]
Thanks for reporting the issue. Yeh this is a recent issue which i've noticed too. Will take a look.

**Comment by joemcelroy** [comment]
released as "@searchkit/instantsearch-client" at "4.14.1"

**Comment by joemcelroy** [comment]
our next website now deploying so working for us too :)
