### ISSUE TITLE
dropdown, checkbox, switch display components

### ISSUE THREAD

**Issue by joemcelroy** [searchkit/searchkit#142]
- implement display components which take in an array of items, displays and handles interactions.

**Comment by ssetem** [comment]
SortingSelector, ViewSwitcher, PageSizeSelector are all candidates to accept either toggle or selectbox or custom component.

**Comment by GregoryPotdevin** [comment]
Note that the implementation will need to pass both toggleFilter and setFilters, depending on how the display component works.

**Comment by ssetem** [comment]
yeh we can pass 2 functions, but these components typically have a single selection rather than multi select behaviour. I think anything which can multiple select, we pass in both toggle + full set functions so can reuse any multiple select based component

**Comment by joemcelroy** [comment]
This is done in 0.8 :)
