### ISSUE TITLE
Add support for multiple SearchBoxes, or 'search filters'.

### ISSUE THREAD

**Issue by PAK90** [searchkit/searchkit#149]
[Supported by ES](https://www.elastic.co/guide/en/elasticsearch/guide/current/multi-query-strings.html). The ability to have multiple ```SearchBox``` components would be useful to refine a current result set.

**Comment by GregoryPotdevin** [comment]
As discussed, this could take the form of an `InputFilter` even if it would work like the normal `Searchbox`.

**Comment by GregoryPotdevin** [comment]
This has been added to Searchkit 0.9.X
