### ISSUE TITLE
Searchkit can be decoupled from ElasticSearch?

### ISSUE THREAD

**Issue by IronArthur** [searchkit/searchkit#15]
Hi,

I really like how searchkit works, but right now i have some REST api of products that i would like to make a front with searchkit but ElasticSearch is not an option for me.

It can be decoupled from ElasticSearch? or at least "intercept" with some proxy the calls to ElasticSearch to another component that has the Data?

Thanks

**Comment by ssetem** [comment]
Searchkit components currently do have knowledge of elasticsearch in some form., 
do you want to join  https://gitter.im/searchkit/searchkit to discuss your usecases more fully?

Thanks
