### ISSUE TITLE
 improvements to the library distribution practices

### ISSUE THREAD

**Issue by datapimp** [searchkit/searchkit#156]
I would love the ability to incorporate searchkit into my own webpack and react setup, but am having a lot of trouble doing so because of conflicts between my own webpack and loader configuration.  

It seems to use searchkit in development as a library consumer, I need to adopt aspects of the searchkit development environment decisions of the library author.

I will admit with the complex tooling environment that this is a hard thing to get right as a library author, especially when the development you do on the library is driven by your business' needs for the library and the effort required to optimize the open source experience is hard to consistently maintain.

I would love some advice in how to solve this, if you have already. I could be doing it wrong.  

However, if you guys would like me to spend some time doing the chores to make this a possibility I am more than willing.  I think there are things that could be done with the webpack configuration, using their externals setup, or other plugin tricks, and it would make a big improvement.

**Comment by joemcelroy** [comment]
Hi there,

Are you using typescript or ES6? Could you paste us the webpack loader configuration you use and suggest how you would like it improved.

If you're referring to how we load our styles, this has been improved in 0.7. The styles are no longer required within a component and if you're happy with the existing styles, you simply need to include the theme.css file within the release folder in your app. If you want to change the existing theming, you have access to the scss files within searchkit to include in your own styles.

**Comment by datapimp** [comment]
Hi Joe,

I'm using es6 through babel and babel-loader.  A common `babel-preset-react-hmre` setup.  This project in particular uses bootstrap with less.  

This is roughly it:

https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack.config.js#L107

I think styles are the primary culprit given that the projects which are having trouble use less and less-loader and not node-sass and sass-loader.   I'm glad this has been addressed in 0.7.

Using webpack's module aliasing I am able to set an alias for `searchkit` to `searchkit/release/bundle` and this lets me use the library in a development setting with no detectable problems.  However when it comes time to build there are a lot of warnings related to webpack not being able to remove dead or unused code -- which is expected given that I'm an already bundled version, but is still less than ideal and I'm sure is a fixable problem 

I've still got some investigating to do though.

**Comment by joemcelroy** [comment]
Hi

Are you using es6 module imports? Shown here in our docs: http://docs.searchkit.co/stable/docs/setup/project-setup.html. We dont support importing the bundle in your app if you're using ES6 and webpack.

Joe

**Comment by datapimp** [comment]
yes i am.

**Comment by joemcelroy** [comment]
Ok we will have a look at the issues that show at the end of webpack build. Is there anything else you feel could be improved on?

**Comment by datapimp** [comment]
at the moment nothing comes to mind but the more i use it I am sure I can come up with some constructive feedback if it helps.  overall i think it is a great product and would love to help make it better any way i can.

**Comment by ssetem** [comment]
thanks :D, feel free to jump on our gitter chat room if you want to brainstorm stuff.

https://gitter.im/searchkit/searchkit

**Comment by joemcelroy** [comment]
Thanks il close this issue
