### ISSUE TITLE
Action Bar Layout improvement

### ISSUE THREAD

**Issue by joemcelroy** [searchkit/searchkit#160]
- [ ] Remove hard widths to components within the action bar

**Comment by GregoryPotdevin** [comment]
Using flex also means it might not work correctly in IE (haven't checked) and that when 1 component overflows and becomes taller, the other components try to match the height. And that's how you get this :
![image](https://cloud.githubusercontent.com/assets/1522455/13111745/cead3410-d587-11e5-87b4-04ece0cb62da.png)

(same problem in the pager)

**Comment by joemcelroy** [comment]
For now ive fixed the height of the select dropdowns to prevent this issue. In the future we need a responsive theme for mobile / tablet / desktop. Im going to close this issue for now and create a responsive theme issue.
