### ISSUE TITLE
Prop to Hits component

### ISSUE THREAD

**Issue by bulleric** [searchkit/searchkit#169]
Hallo Together,

Is it possible to render custom prop types to an Hit component.
In my current solution i try to implement an onClick handler to an hit.

for me it'ts not possible to get the result inside the hit component with custom handlers?

```
<Hits  itemComponent={CustomHitComponent} hitsPerPage={10}  customHandler= {myCustomHanlder}/>

class CustomHitComponent extends Hits{                                                                                                                        
   // this.props doesn't contain result 
}
```

**Comment by joemcelroy** [comment]
Hey,

The item component should not extend the hits component. See http://docs.searchkit.co/stable/docs/components/basics/hits.html. Just needs a react component, either functional or extending the react component class.
