### ISSUE TITLE
Responsive Theme

### ISSUE THREAD

**Issue by joemcelroy** [searchkit/searchkit#176]
Current theme isn't responsive to different browser widths. Should support Mobile, Tablet sizes.

**Comment by infacq** [comment]
perhaps flexbox is a must

**Comment by EtienneK** [comment]
This would be fantastic to get implemented. Anyone currently looking at it?

**Comment by ispooky83** [comment]
is there any news right here?
mobile audience is increasing everyday, I can not think anyone is ignoring the fact that searchkit is not responsive.

**Comment by gauravt** [comment]
Is there any update on this thread?

**Comment by ssetem** [comment]
We have begun looking at responsive, will need alot of thought and perhaps change.
It would be good to get feedback on what kind of mobile view you guys have been thinking of.
Wireframes and notes would help us alot.

Thanks!

**Comment by rolele** [comment]
I was looking how other search websites are doing it. I was looking at amazon.com or indeed.com.
I found out that m.ebay.com is actually very close to the current experience of searchkit.
Once you have done a text search you have Filter and Sort. The result and pagination look similar.

**Comment by dcworldwide** [comment]
Please... this is really important.

I think that overall, searchkit should decouple the view and model completely so that we can switch out the UI with customer components.

Refactoring the components to use react hooks would be the solution here I think.

**Comment by Fluorz** [comment]
+1
