### ISSUE TITLE
Nested key/value field support for refinement lists

### ISSUE THREAD

**Issue by munkt0n** [searchkit/searchkit#183]
some of the aggregate field names I'm using are dynamic, so I don't know the name of the fields to supply to the Refinement Lists. Probably best to show some examples.
example output
![output](http://i.imgur.com/V6CAgDu.png)
example ES query

```
{
  "query": {
    "match": {
      "category": {
        "query": "projectors",
        "type": "phrase"
      }
    }
  },     
  "aggs": {
    "brand": {
         "terms": {
            "field": "brand"
         }
    },
    "category": {
        "terms": {
          "field": "category"
        }
    },
    "attributes": {
      "nested": {
        "path": "attributes"
      },
      "aggs": {
        "key": {
          "terms": {
            "field": "attributes.key"
          },
          "aggs": {
            "value": {
              "terms": {
                "field": "attributes.value"
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by ssetem** [comment]
@munkt0n  we have got a prelease 0.10.0-5 with nested support

some docs about it are here  [FieldOptions documentation](https://github.com/searchkit/searchkit/blob/develop/docs/core/FieldOptions.md)

Dunno if its an exact fit to your requirements, maybe you could give it a try?

Thanks!
