### ISSUE TITLE
Duplicate key breaks SelectedFilters

### ISSUE THREAD

**Issue by mcs07** [searchkit/searchkit#187]
The key used for components in SelectedFilters is only based on the value, so a duplicate key occurs if two fields are filtered by the same value, leading to the selected filters not displaying properly.

As an example, try filtering by "Quentin Tarantino" as both an actor and a writer on the demo app:
http://demo.searchkit.co/imdb?actors[0]=Quentin%20Tarantino&writers[0]=Quentin%20Tarantino

This could probably be fixed by incorporating the field name into the key also?

**Comment by ssetem** [comment]
thanks for reporting, using the field also is probably the best idea
