### ISSUE TITLE
React 0.15

### ISSUE THREAD

**Issue by joemcelroy** [searchkit/searchkit#188]
Update from 0.14 to 0.15

Potential issues
- 0.15 now no longer inserts spans for text blocks for our unit tests
- 0.15 doesn't inject noscript tag

**Comment by jamiedumont** [comment]
Hey all! Any idea when we can expect this to become part of the build? Is there anything I can do to help?

**Comment by ssetem** [comment]
Hi @jamiedumont 

Its on my list :D, hopefully in 0.10 or 0.11, alot of our unit tests will need to be updated, so I will try to get through that soon.

Thanks!

**Comment by Vanuan** [comment]
It's called 15, not 0.15 :)

**Comment by shaialon** [comment]
Any update on this? It's making starting with searchkit in a new project impossible :(

**Comment by Vanuan** [comment]
Well, it works for me with version override

**Comment by shaialon** [comment]
@Vanuan What do you mean? How can I do a version override?
Adding a 
`<SearchBox />`
Broke the functionality in my case

**Comment by Vanuan** [comment]
Well, I use jspm to manage dependencies. I overrode the version of react using this config:
```
 "npm:searchkit@0.10.1": {
       "map": {
...
         "react": "npm:react@15.3.1",
...
       }
  }
```

I don't know if other dependencies managers have this feature.

**Comment by shaialon** [comment]
Thanks @Vanuan , I will try

**Comment by shaialon** [comment]
@Vanuan your approach was good. In regular npm you need to create a file named
`npm-shrinkwrap.json` with the following:

```json
{
  "dependencies": {
    "searchkit": {
      "version": "0.10.1",
      "dependencies": {
        "react": {
          "version": "15.3.2"
        },
        "react-dom": {
          "version": "15.3.2"
        }
      }
    }
  }
}
```

I also added an alias via Webpack but I'm not sure it's necessary:
```javascript
const webpackConfig = {
   ...
  resolve : {
    ...
    alias: { 'react$': 'react/lib/ReactWithAddons.js', 'react-dom$': 'react/lib/ReactDOM.js' }
  }
}
```

That said, searchkit still seems to be working with impaired functionality (though now it's not breaking the app completely like before).

**Comment by ppearcy** [comment]
Curious @shaialon or others, can you elaborate on which functionality is impaired running in react 15? Trying to understand what to expect if I go this route. Also, thanks for the override workaround.

**Comment by shaialon** [comment]
@ppearcy for instance the refinement filters are ok but once I add text search errors start flying about sliders and all.
Basically it's so delicate that I decided not to touch this part of my project for now.
I see React 15 + Searchkit as a non-starter in the current state of things

**Comment by joemcelroy** [comment]
done in the beta release.

**Comment by shaialon** [comment]
@joemcelroy Thank you!
We'll work on integrating it and let you know how it went!
