### ISSUE TITLE
Pagination ellipsis click causes reset

### ISSUE THREAD

**Issue by mcs07** [searchkit/searchkit#190]
Currently, clicking on an ellipsis in the pagination (when showNumbers=true) triggers a reset of the pagination. Instead, this should probably do nothing.

It looks like the Pagination `setPage` method gets passed `ellipsis-X`, which `normalizePage` converts to NaN. Then `isDisabled` returns false for NaN, so the accessor state value actually gets set to NaN, resulting in the reset.

To fix, `isDisabled` could return true for NaN (although it looks like checking for NaN is a bit weird in Javascript?) Alternatively, `normalizePage` could return 0 for a string input other than prev/next...

**Comment by ssetem** [comment]
thanks again :), and for looking into the codebase to help us solve

**Comment by ssetem** [comment]
thanks @mcs07  its fixed in our develop branch, will be in 0.9

feel free to jump on our gitter.im/searchkit/searchkit  chat if you want to brainstorm improvements to Searchkit

**Comment by mcs07** [comment]
Thanks for the quick fixes, I'm finding searchkit very useful.
