### ISSUE TITLE
ListFilter to change queryFields in SearchBox 

### ISSUE THREAD

**Issue by drewdresser** [searchkit/searchkit#193]
I would love to have an list filter that allows a user to select the exact Elasticsearch fields that the search should be executed on.

Use Case:
I have three different columns that I would like to search: movie title, description, genre.  By default we search all fields; however, a user does not always want to search all three columns at once. Sometimes they want to search the description by itself, sometimes they want to search the title and the genre, etc.

I tried creating a custom filter that does this; however, the SearchBox does not seem to update the query fields with a change in state.

**Comment by ssetem** [comment]
hi @drewdresser 

We have an input filter landing in 0.9, hopefully released very soon

![screen shot 2016-03-25 at 14 00 56](https://cloud.githubusercontent.com/assets/703938/14045426/143ba4d6-f292-11e5-8f3c-4bac4564ab33.png)

You can add as many of these on left hand side with facets.

Controlling the primary searchbox query fields is something we would make easier in future releases

**Comment by drewdresser** [comment]
Thank you for the quick response!

I think that last line is really what I'm after. Is it doable now? 

For instance, I have an array of search field strings in state named searchFields. The user is able to change which fields is in the array. We keep state current with the currently selected search fields.

I then have this code, hoping to dynamically change which fields we are searching; however the SearchBox's queryFields are not dynamically changing. 
<```
Searchbox searchOnChange={true} 
				queryOptions={{analyzer: "standard"}} 
				queryFields={this.state.searchFields}/>			
```

Any suggestions to make this work or comments would be much appreciated.

**Comment by ssetem** [comment]
Sure, 

you wanna jump on gitter.im/searchkit/searchkit
and we can try and help you with a work around now?

Thanks

**Comment by drewdresser** [comment]
The solution here was to extend the SearchBox. It sounds like this functionality may be included by default in future releases. Code is below: 
`class CustomSearchbox extends SearchBox {
  componentDidUpdate(prevProps) {
    if (prevProps.queryFields.toString() != this.props.queryFields.toString()){
      this.accessor.options.queryFields = this.props.queryFields;
      this.searchkit.performSearch();
    }
  }
}`

**Comment by drewdresser** [comment]
Is the CustomSearchBox seen above, replaceable in Searchkit .9? I am not able to find documentation that directly states it but I may be missing something. Thanks!

**Comment by joemcelroy** [comment]
Hi Drew, 

For 0.9, we have only added the ability to add additional search filter components that work alongside the main searchbox http://docs.searchkit.co/stable/docs/components/navigation/input-filter.html.

For future releases we will address being able to dynamically update the query fields.
