### ISSUE TITLE
RangeFilter with showHistogram={false} is broken

### ISSUE THREAD

**Issue by GregoryPotdevin** [searchkit/searchkit#199]
When using showHistogram={false}, the aggregator doesn't compute the buckets, so 
```
const maxValue = computeMaxValue(this.accessor.getBuckets(), "doc_count")
```
=> maxValue is 0, and thus `disabled: maxValue == 0` the component is disabled.

**Comment by GregoryPotdevin** [comment]
Quick update : showHistogram={false} passes `loadBuckets: false` to the accessor, which doesn't generate the aggregator. This is a nice optimisation but it just means that the accessor shouldn't rely on the bucket's content for it's disabled state. 
`InputFilter` uses `(this.searchkit.getHitsCount() == 0) && (this.getValue() == "")` so a similar strategy could be used (disabled the facet if there are no hits and the accessor's state is empty)

**Comment by joemcelroy** [comment]
Thanks. I've seen this issue too when I was setting up the demo but forgot to report. 

So used to "disable" the rangeFilter when filter cannot be used to filter further. Using `getHitsCount` check only wouldn't work for when we have results but the results do not index the field we are filtering by (Example would be metaScore for tv shows).

**Comment by r007-1** [comment]
Even with showHistogram={true}, the slider still doesn't seem to be connected with the results. http://codepen.io/r007/pen/JXyyZw

Also, how are NaN values handled? Are they ignored?

**Comment by GregoryPotdevin** [comment]
In that case could we use `CardinalityMetric(this.key+"_count", this.key)` and filter the aggregator on the global range (min/max) ?

**Comment by joemcelroy** [comment]
Yeh that will work. CardinalityMetric on range when histogram is false. When histogram is true, we use the histogram aggregation.

**Comment by joemcelroy** [comment]
taking this

**Comment by joemcelroy** [comment]
merged
