### ISSUE TITLE
Hits: support _source

### ISSUE THREAD

**Issue by GregoryPotdevin** [searchkit/searchkit#20]
Most of the time the results displayed only use a few of the source's fields. Specifying `_source` filter would allow to save bandwidth and could speed up the search.

Relevant ES page : https://www.elastic.co/guide/en/elasticsearch/reference/2.0/search-request-source-filtering.html

**Comment by joemcelroy** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-source-filtering.html
