### ISSUE TITLE
Codepens on docs need to be updated from React.render to ReactDOM.render

### ISSUE THREAD

**Issue by r007-1** [searchkit/searchkit#200]
While the current codepen for section 1.1 in the docs works fine, it throws off this error 'TypeError: Cannot read property 'unstable_renderSubtreeIntoContainer' of undefined' once RangeFilter is added. It might confuse muggles like me who are new to React. Hihi! I've been stuck for days. :sweat_smile: 

React.render doesn't work for some cases. ReactDOM.render, however does. So I added ReactDOM in the dependencies and changed React.render. Hope this helps! :)

Here's the codepen I was experimenting with: http://codepen.io/r007/pen/JXyyZw

Btw, great job with searchkit! It's helping me tons in my project. Would love to help out a bit with the documentation to give back. You can reach me at lovette@nuyolk.com. :)

**Comment by joemcelroy** [comment]
Thanks! Yep our codepens do need updating. We try and keep track of these codepens under the searchkit username (http://codepen.io/searchkit/). Il update them once next release happens!

We have an active chatroom on searchkit (which ive just seen you are on now). There are alot of members which will help you out!

Documentation is available here: https://github.com/searchkit/searchkit/tree/develop/docs. Feel free to contribute and do a PR. 

A big win for us would be devs writing blog posts on using searchkit. The issues to be aware of, the development environment, adding your own components etc. This serves as documentation to other members and doesn't put burden on us needing to keep up to date.

Great you're loving Searchkit! :smile:

**Comment by r007-1** [comment]
The blog post is a good idea! I'll make one one of these days. I'll keep
you posted. :)
