### ISSUE TITLE
Make the RefineLists filterable.

### ISSUE THREAD

**Issue by PAK90** [searchkit/searchkit#213]
I've got quite a few RefineLists which have a large number of items (100+ in some cases). Not a bad thing, but I've had feedback that browsing through all of those is a pain, just to find the one you want. So it'd be good to have a small searchbox that can be used to narrow the results down.

**Comment by GregoryPotdevin** [comment]
As discussed, I'll be posting a "Multiselect" component that uses react-select and provides scrolling + filtering. The filtering is done client side, though, so you have to return all those 100+ items in the query, which can be a bit slower than having just 10-20.
There could be another solution using an asynchronous query to filter the list. This would be required for 200+ items I think (it would be slower to use for less than 100 items), so both solutions will probably coexist.

**Comment by GregoryPotdevin** [comment]
Here's a first version of such a component. Keep in mind the API could change but it would be pretty easy to update.

# searchkit-multiselect

https://github.com/GregoryPotdevin/searchkit-multiselect

2 possible different directions for this component : 
1. Embrace react-select and expose all of it's API
2. Embrace searchkit components, hide react-select's API, and make it compatible with `itemComponent` and other idiomatic searchkit props.

## Usage

```
<RefinementListFilter
  id="actors"
  title="Actors"
  field="actors.raw"
  operator="AND"
  listComponent={MultiSelect}
  size={200}/>
```

## Preview 

![Preview](https://github.com/GregoryPotdevin/searchkit-multiselect/blob/master/doc/dropdown.png?raw=true)

**Comment by joemcelroy** [comment]
Looks good! Thanks Greg.

**Comment by GregoryPotdevin** [comment]
Can this issue be closed ?

**Comment by joemcelroy** [comment]
cool, il close.

**Comment by joemcelroy** [comment]
also @GregoryPotdevin, can you make a blog post for this feature? I would love to post it on HN.

**Comment by GregoryPotdevin** [comment]
I didn't communicate much on it yet as it's pretty basic and is just a thin wrapper. We made a few enhancements to it in mtg-hunter, which basically just forwards more props to react-multiselect. 
I'll try to start a blog post about it next week. Might not be just on searchkit-multiselect but also on the general concepts : having a common API for a group of components (listComponents in this case) and building simple adapter components to plug in external React components.

**Comment by joemcelroy** [comment]
Yeh, I would say that its two blog posts then, one on release of multiselect and the concepts of Searchkit components extensibility.
