### ISSUE TITLE
InputFilter disappears

### ISSUE THREAD

**Issue by vladimir-tikhonov** [searchkit/searchkit#221]
Steps to reproduce:
1) Render InputFilter with `searchOnChange = false`
2) Search for something so that the search results are empty
3) Manually clean InputFilter content (without using the cross)
Result: InputFilter disappears

More info: bug is caused by this line: https://github.com/searchkit/searchkit/blob/develop/src/components/search/filters/input-filter/InputFilter.tsx#L149

**Comment by ssetem** [comment]
thanks @vladimir-tikhonov , will fix this soon

**Comment by ssetem** [comment]
@vladimir-tikhonov  we just released v0.9.2 which fixes this issue.

Thanks!

**Comment by vladimir-tikhonov** [comment]
Wow, that was quick! Thanks for your amazing work, guys!

**Comment by ssetem** [comment]
np :D, 

also we introduced a prop blurAction="search" or blurAction="restore" as fixing the issue could have 2 behaviours, so we gave a choice
