### ISSUE TITLE
Attach handler for form onSubmit

### ISSUE THREAD

**Issue by infacq** [searchkit/searchkit#229]
When `<Searchbox>` is rendered, we notice there is a submit button but we're unable to put any action in it. How to attach action on form submit

**Comment by GregoryPotdevin** [comment]
The use case is to have a SearchBox with autocomplete results and jump to a search page on validation.

Possible solutions : 
- subclass SearchBox and redefine the render method to add the custom handlers
- add handlers to SearchBox, like `<SearchBox onSubmit={...} onItemClick={...} />`

**Comment by joemcelroy** [comment]
We're working on autocomplete functionality as a component for Searchbox. Hopefully we will release soon. Be great if you could comment on #31 on your usecases!

Joe

**Comment by ronydj** [comment]
What is the current status of this feature ?

**Comment by joemcelroy** [comment]
Closing this issue and a more extensible searchbox will come in with the autocomplete in future.
