### ISSUE TITLE
Blog Posts

### ISSUE THREAD

**Issue by joemcelroy** [searchkit/searchkit#230]
Developers, I need your help in promoting Searchkit!. One easy thing for Searchkit would be to reduce the friction on using searchkit for their project. So im proposing a few blog posts which I wouid love the community to be able to write.
- [ ] Getting started with Searchkit (Using boilerplate, dev environment, connecting to ES)
- [ ] Steps to building a custom component
- [ ] Extending Searchkit Components

**Comment by GregoryPotdevin** [comment]
There 2 different concepts : building a custom UI component (fairly easy and doesn't require any specific searchkit knowledge) and building a custom filter component (with the accessor and all).

**Comment by joemcelroy** [comment]
Yeh i imagine them being in two parts, beginner and progressively more advanced. part 1, part 2 for example.

**Comment by PAK90** [comment]
What format would you want these in, and how would you like these to be submitted? I don't have a blog on which to post these, but I may be able to attempt something for the custom component (UI, not filter) and also maybe the 'getting started', since that was an onerous process.

**Comment by joemcelroy** [comment]
Hey @PAK90 

I suggest using the medium platform (www.medium.com) to post your blog posts. You can give us the link to review and we can help you shape the blogpost. As for style, i would look at blog posts about react and read how devs write about their experience for inspiration. 

Getting started blog post is badly needed so i suggest that first!

Thanks!
