### ISSUE TITLE
long number on label cause handler of rangeFilter not align

### ISSUE THREAD

**Issue by infacq** [searchkit/searchkit#231]
<img width="375" alt="screen shot 2016-04-08 at 20 56 48" src="https://cloud.githubusercontent.com/assets/1596891/14384260/a5e7cdf2-fdcc-11e5-92eb-59cc681a727b.png">

any idea how to reformat long number

**Comment by ssetem** [comment]
hi @infacq 

We need to provide better support for this, but in the mean time you can try something like this

make sure you import `RangeComponentBuilder`
```jsx
            <RangeFilter min={100000} max={500000}
              field="someField"
              id="someId"
              title="Some Title"
              showHistogram={true}
              rangeComponent={RangeComponentBuilder({
                showHistogram: true, showSlider: true, marks:{100000:"100k", 50000:"500k"}
              })}/>

```

**Comment by infacq** [comment]
<img width="347" alt="screen shot 2016-04-08 at 21 55 39" src="https://cloud.githubusercontent.com/assets/1596891/14385763/ab8392e8-fdd4-11e5-9955-a0a6a68255bc.png">
 any idea why it turn out like this

**Comment by ssetem** [comment]
did you use the right numbers

**Comment by infacq** [comment]
ahh my bad. Is this documented somewhere? :smile_cat: but i'm still having little problem with outbound
<img width="347" alt="screen shot 2016-04-08 at 21 55 39" src="https://cloud.githubusercontent.com/assets/1596891/14386090/f7c14582-fdd5-11e5-8453-37ef871c2f43.png">

and try to modify the step as well formatting the tooltip number

**Comment by ssetem** [comment]
yeh, we need to add further support for this, probably next release

**Comment by ssetem** [comment]
@infacq  prerelease 0.10.0-4 supports rangeFormatter now, it would be great if you tested this new feature :)

Thanks!

**Comment by infacq** [comment]
how do I pull it?

**Comment by ssetem** [comment]
npm install 0.10.0-4

**Comment by infacq** [comment]
is it documented somewhere on how to use it
