### ISSUE TITLE
Include/Exclude filters in SelectedFilter

### ISSUE THREAD

**Issue by GregoryPotdevin** [searchkit/searchkit#233]
The SelectedFilter displays all selected filters, but depending on how they are displayed and applied you might want to be able to hide some.

One example is when displaying a Filter as tabs over the results
![image](https://cloud.githubusercontent.com/assets/1522455/14406225/5284d4c6-fea2-11e5-9aa5-ec33d4772655.png)
Here the selected filter feels redundant... The "clear all filters" button still needs to by activated, though.

**Comment by GregoryPotdevin** [comment]
This could be handled either at the filter level or as include/exclude on the SelectedFilters.

## On Filters
- might be easier to right maintain if you add/remove filters (or the SelectedFilter itself), all the information for a given filter is centralized
- would need to pass information down to the accessors, so that adds boilerplate code + accessor code, not great
- would give flexibility to show/hide some specific filter values (is that really useful ?)

# On SelectedFilters
Pretty much the opposite...
- some Filter information gets split between the Filter itself and the SelectedFilters component. Introduces some coupling between the filters and SelectedFilters
- very localized and simple change

Adding to SelectedFilters seems better because it's just much easier to add and doesn't add complexity to the other components and accessors.

**Comment by joemcelroy** [comment]
My thought would be a boolean on the filter `isVisible`, with default being false. Here is an example from an accessor.

```     
        .addSelectedFilter({
          name:this.options.title || this.translate(this.key),
          value: this.options.label || this.translate("checkbox.on"),
          id: this.options.id,
          remove:()=> this.state = this.state.setValue(false),
          isVisible: false
        })
```

and components like SelectedFilter will chose to not render. I think this is the better way as we are already passing in configuration which is focused for the SelectedFilter component (name, value props)

**Comment by GregoryPotdevin** [comment]
This is cleaner but it means that all the filter components + accessors need to be updated to receive the new props. Maybe this could be automated at the Component level by having SearchkitComponent inject options taken from the props in defineAccessor but that would involve too much magic :-/

Just found a different (real) use case where this solution doesn't work : multiple SelectedFilters. In most of my previous search projects the list of selected filters was in the sidebar before the other filters. Might be useful to have 1 SelectedFilters there and another before the search results, each displaying different filters (general "important" filters over the search results, and extra minor filters in the sidebar). This wouldn't be achievable with the isVisible pattern.

Just checked the code for SelectedFilters, I guess subclassing SelectedFilters and redefining getFilters to apply a filter function would be pretty easy. 

So the safest solution right now might be to not add anything, give an example in the doc (or elsewhere) of SelectedFilters filter filtering (this sounds awkward ^^), maybe publish as external component for now and just see if there's an real world use for other people.
