### ISSUE TITLE
Geo based components

### ISSUE THREAD

**Issue by joemcelroy** [searchkit/searchkit#236]
Ideally would go in a separate repo. 
- [ ] Location search (powered by google locations api)
- [ ] Distance filter ( + 0 / 5 / 10 miles / km )
- [ ] geo based results on a map
- [ ] geo based clustering and filtering of results on a map

**Comment by infacq** [comment]
would love to see this in mapboxgl based

**Comment by SabeehY** [comment]
+1 Really looking forward to this

**Comment by SabeehY** [comment]
Any suggestions on how I can implement a solution for geo searching for the time being?

**Comment by joemcelroy** [comment]
have a look at our components and some of the custom components our contributors have built (https://github.com/GregoryPotdevin/searchkit-multiselect). 

theres also a crime demo app http://demo.searchkit.co/crime, code here https://github.com/searchkit/searchkit-demo/tree/master/src/app/src/crime

**Comment by SabeehY** [comment]
Thanks! I'll look into it.

**Comment by infacq** [comment]
is these two available ?

`GeohashBucket,GeoBoundsMetric,`

**Comment by gaving** [comment]
FWIW I knocked together https://github.com/gaving/searchkit-geomap using mapbox-gl for visualising some data I had, should work with the demo.searchkit.co crime API out of the box.

I'd like to add some other components in the future, distance filter etc.

**Comment by joemcelroy** [comment]
@gaving looks awesome 👍

**Comment by SmileSydney** [comment]
> have a look at our components and some of the custom components our contributors have built (https://github.com/GregoryPotdevin/searchkit-multiselect).
> 
> theres also a crime demo app http://demo.searchkit.co/crime, code here https://github.com/searchkit/searchkit-demo/tree/master/src/app/src/crime

Crime Demo site is broken (renders just a blank page in Chrome). Any chance this could be a quick fix?

**Comment by Fluorz** [comment]
+1
