### ISSUE TITLE
Searchkit Event

### ISSUE THREAD

**Issue by infacq** [searchkit/searchkit#237]
is there any event mechanism

**Comment by joemcelroy** [comment]
Can you explain what type of events you need to listen on?

**Comment by infacq** [comment]
onDataFound
onNoData

**Comment by joemcelroy** [comment]
searchkitManager has an emitter which is triggered on response from ES.

```
sk.emitter.addListener(fn)
```

`onNoData`, you could check `sk.getHitsCount()`. 

This is completely unsupported however (can change in later versions) but if more people ask for more features, we can support this.

**Comment by GregoryPotdevin** [comment]
I think this has already been asked once or twice on gitter. 

@infacq what would be your use case ? 

Currently searchkit is very UI-focused to it's missing a few hooks for external but I think we need to focus on actual use cases to avoid adding too many random hooks that would lock down the implementation.

**Comment by ssetem** [comment]
I think we could add a resultsListener, the onNoData event wouldn't be needed, you can check results length or interogate searchkit whne that event is recieved, should be enough for most cases

**Comment by infacq** [comment]
thanks
