### ISSUE TITLE
Add a Date Filter

### ISSUE THREAD

**Issue by GregoryPotdevin** [searchkit/searchkit#24]
I haven't tried fooling around with date fields and the current filters, but date field support could make sense in :
-  Menu (with the possibilité to set the format and filter on just year, or year/month, etc.)
- Hierarchical Menu (year, then month, etc.)
- Range Filter

Other possibilities include having a small calendar to pick a date, or 2 to pick a range.

**Comment by joemcelroy** [comment]
We were thinking of having a Date Range filter, picking two dates to filter the results. Using this component http://react-component.github.io/calendar/examples/antd-range-calendar.html

**Comment by GregoryPotdevin** [comment]
Also found this one : http://www.gpbl.org/react-day-picker/examples/#range Haven't played with any of them yet.

**Comment by joemcelroy** [comment]
The good thing about react-component ones is that we use the rc-slider component from them. Some of the dependencies used in rc-slider would be reused in rc-calendar so potentially be a smaller footprint than other libraries.

**Comment by driesvancraen** [comment]
It would be sensible for us to have a "year filter" using the rc-slider.

Parsing the dates to a int which represents the year. 

![image](https://cloud.githubusercontent.com/assets/1028036/12718309/181cf08c-c8ee-11e5-9bf1-c16551f87840.png)

**Comment by joemcelroy** [comment]
a workaround would be to index a year field and set a sensible min - max
```
<RangeFilter min={1990} max={2016} interval={1} field="yearField" title="First Registration" id="firstReg" />
```

**Comment by GregoryPotdevin** [comment]
I think RangeFilter could provide support for year aggregation without using a special field : https://www.elastic.co/guide/en/elasticsearch/reference/2.1/search-aggregations-bucket-datehistogram-aggregation.html
Something like `<RangeFilter type="date" dateInterval="year" />` (not sure for `dateInterval` vs `interval`, maybe we should rename `interval` to avoid the name clash)

**Comment by GregoryPotdevin** [comment]
Looks like it would also be possible to have a nice slider with month intervals but year marks : http://react-component.github.io/slider/examples/marks.html

**Comment by GregoryPotdevin** [comment]
0.9 maybe ?

**Comment by xinghengwang** [comment]
+1. bump.

**Comment by ivarref** [comment]
+1

**Comment by ssetem** [comment]
Hi @xinghengwang , @ivarref  have you got examples, screenshots etc of what you would like from this?

I ask as a DateFilter can be interpreted in many ways

Thanks!

**Comment by xinghengwang** [comment]
sure. I like your range filter for numbers. 
although most dash or search field have something like this: 
For example, this is using react-bootstrap-daterangepicker
So one of the fields is a data time field for the data. So it would be nice to be able to directly filter on that in the searchKit. (For example, could be the user sign up date/time). 

![screen shot 2016-06-01 at 5 44 05 pm](https://cloud.githubusercontent.com/assets/6666687/15730354/be944e2e-2820-11e6-8526-1bb15f7140e9.png)

**Comment by ivarref** [comment]
Hi @ssetem , and thanks for the quick reply.

I have a simple suggestion. When you use a DynamicRangeFilter and refer an ElasticSearch field of type date, it shows milliseconds since 1970. It would be good if you could supply a formatting function to DynamicRangeFilter to format those milliseconds into something more readable for humans.

The same applies to RangeFilter.

Also - on a side note - it would be nice not having to specify min and max for RangeFilter.

**Comment by ssetem** [comment]
Thanks for the feedback!

@xinghengwang  I will look at this style of date filter soon

@ivarref we recently added a rangeFormatter prop to DynamicRangeFilter  in prerelease 0.10.0-5

**Comment by timmetj** [comment]
Hi,

I'm also looking for a date-filter, not necessarily a range, but a "simple" datepicker would be nice.
We are working with calendar based events, so we want our customers to see/select in a datepicker when a event is taking place. A range/multiselect can be optional (in the same datepicker then), if you want to look this weekend for example.
Then a highlight of the date when a events is taking place, and/or a disabled date when no event is taking place.
It then must use elastics timestamp format as input.

So what @joemcelroy mentioned seems nice (the rc-calendar), too bad it wasn't in the 0.6 release :p

Looking forward for this extra filter.

**Comment by Fluorz** [comment]
+1
