### ISSUE TITLE
Support for aggregation/filtering on nested objects

### ISSUE THREAD

**Issue by bgphipps** [searchkit/searchkit#247]
We need some support for aggregating and filtering on nested objects in ES. Per discussions on the [searchkit chat](https://gitter.im/searchkit/searchkit), the proposition was adding a `NestedMenuFilter` component to handle this use case. 

@GregoryPotdevin brought up that there may be api changes needed to support this feature.

**Comment by GregoryPotdevin** [comment]
Sample mapping : 
```
          "category" : {
            "type" : "nested",
            "properties" : {
              "id" : {
                "type" : "long"
              },
              "name" : {
                "type" : "string"
              }
            }
          },
```

The aggregation and filter should be done on the id, but the facet should display the name. 
Apparently the recommended solution is to use nested aggregators (the first one to aggregate on the id, and the second to get the name (the nested bucket will only have 1 value)
```
            "buckets": [
               {
                  "key": 123,
                  "doc_count": 3,
                  "name": {
                     "doc_count_error_upper_bound": 0,
                     "sum_other_doc_count": 0,
                     "buckets": [
                        {
                           "key": "biscuits",
                           "doc_count": 3
                        }
                     ]
                  }
               },
```

http://stackoverflow.com/questions/30728583/how-to-get-an-elasticsearch-aggregation-with-multiple-fields/30919229#30919229

**Comment by ssetem** [comment]
@bgphipps would aggregating on name work? as that would allow.a generic solution

aggregating on id but returning name might need a tophits or scripts field

**Comment by GregoryPotdevin** [comment]
@ssetem We discussed it on gitter and apparently it's not an option. The stackoverflow link I posted shows how to use sub-aggregation to get the "label" while aggregating on the key.

**Comment by ssetem** [comment]
cool, i will do the feature based on aggregating name or arbitrary field, sub aggregation will need to be custom work outside of searchkit for now

**Comment by fabiofumarola** [comment]
Below my proposal, I can try to work on a pull request after a discussion.

This requires to add nestedQueryFields as attribute to SearchBox

```
  <SearchBox
                autofocus={true}
                searchOnChange={true}
                queryFields={['title^5', 'description', 'categories', 'keywords',]}
                nestedQueryFields={['annotations.name', 'focusLocation.cityName',
                  'focusLocation.regionName']} />
```

Then for each aggregation component It can be add a `nestedField` attribute to show that the component is aggregating on a nested field.

Finally we need to update query building phase to support nested aggregations like the example below.

```
{
  "size" : 0,
  "aggs": {
    "annotations": {
      "nested": { 
        "path": "annotations"
      },
      "aggs": {
        "age_group": {
          "terms": { 
            "field":    "annotations.name"
          }
        }
      }
    }
  }
}
```

**Comment by bgphipps** [comment]
@fabiofumarola seems like a solid approach to me 👍

**Comment by ssetem** [comment]
also look at the queryBuilder prop for SearchBox which allows you to customise the query going to elastic, it would allow nesting etc already if you use the right queryDSL

**Comment by ssetem** [comment]
@fabiofumarola im thinking of more generic fieldOptions prop for facet components, so we can allow parent child also, and allow further options without conflating the component props.

'''jsx
fieldOptions={
  type:"embedded(default) | nested | child",
  ...
}
'''

I have got some local code for this, will try to get more done in next few days

**Comment by fabiofumarola** [comment]
@ssetem, Yes  I like the idea. Thanks

**Comment by gregdurham** [comment]
Thank you for this, I just tested this on a MenuFilter, can we add the fieldOptions to other filters? For instance the range filter? is this pattern extensible in that way, and would you except PRs for that functionality?

**Comment by ssetem** [comment]
yeh we will add to RangeFilter, does the MenuFilter work ok?

**Comment by gregdurham** [comment]
Works perfectly! And the configuration is a breeze.

**Comment by ssetem** [comment]
@gregdurham just did another prereleased 0.10.0-2

should now support fieldOptions in NumericRefinementListFilter and RangeFilter 

ping if there are any issues or improvements needed.

Thanks!

**Comment by gregdurham** [comment]
This looks awesome. Thank you, Ill get it added to my project today. One other thing that could be really useful now that this exists is [inner_hits](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-inner-hits.html) which are used to send back the hits specific to the inner object that matched. I am thinking, we could add a inner_hits: {} to the fieldOptions, which would allow us to configure how those are returned. Should I create a new issue for that for tracking? Thank you so much for your responsiveness, it is impressive how useful this library is for integrating into ES.

**Comment by ssetem** [comment]
yep, inner_hits looks good, I think with the fieldOptions.options object we can allow further properties which are basic pass through to Elastic.

I will track with this current issue, to support inner_hits and other nested/parent/child options in generic way to round of this issue.

Thanks!

**Comment by ssetem** [comment]
@gregdurham we have done a prerelease 0.10.0-5

- Allows inner_hits as part of the options
- Added nested/parent child support to DynamicRangeFilter 

Also some docs here  [FieldOptions documentation](https://github.com/searchkit/searchkit/blob/develop/docs/core/FieldOptions.md)

**Comment by king-of-the-ring** [comment]
@ssetem I think nested aggregation should apply [reverse nested](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-reverse-nested-aggregation.html)

As right now, the field return the count of the inner-hits / nested documents and not the main / parent documents

**Comment by PAK90** [comment]
Agree with @king-of-the-ring here, we need reverse_nested aggs (made a separate issue here https://github.com/searchkit/searchkit/issues/351). @ssetem or @GregoryPotdevin any chance we could get this added?

**Comment by ssetem** [comment]
going to close as implemented.

Reverse nested will be tracked in #351
