### ISSUE TITLE
RangeSliderHistogramInput has display problem in Firefox

### ISSUE THREAD

**Issue by PAK90** [searchkit/searchkit#250]
![image](https://cloud.githubusercontent.com/assets/1844422/14663170/d7f1ecf4-067a-11e6-9157-3f4fe7e61c13.png)
Basically what it says on the tin. This is the same in Chrome:
![image](https://cloud.githubusercontent.com/assets/1844422/14663180/f1df229e-067a-11e6-8da0-87fc0672fbb2.png)
It could use some adjustments, seeing as how 9500 gets cut off by the editing box.

**Comment by joemcelroy** [comment]
Thanks, il look into these issues
