### ISSUE TITLE
DynamicRangeFilter has a few issues.

### ISSUE THREAD

**Issue by PAK90** [searchkit/searchkit#251]
First first, this is the config I'm using: `<DynamicRangeFilter id="paperPrice"  title="Paper Price" field="multiverseids.medPrice"/>`.
First off, inconsistent (and surprising) rounding:
![image](https://cloud.githubusercontent.com/assets/1844422/14663215/7086c728-067b-11e6-9c95-95b2af3674a2.png)
The actual value is 9494.98. Why does the filter add an extra '04something'? Another example:
![image](https://cloud.githubusercontent.com/assets/1844422/14663264/44d05d82-067c-11e6-9c8a-c70cafb83ef6.png)
Not even sure what the original number is meant to be here, until I checked dev tools and it's apparently 0.14000000059604645. Yikes.
Secondly: I got that range by searching for a name. At that point in time, I have no filters. I search for a different name and suddenly, filter!
![image](https://cloud.githubusercontent.com/assets/1844422/14663293/90d1bbea-067c-11e6-8b38-570c6661022c.png)
I never touched the price range filter, and it spontaneously activated itself. After a few random search terms, it becomes this:
![image](https://cloud.githubusercontent.com/assets/1844422/14663299/b3dbf2ae-067c-11e6-9e5e-3a81f0c246b3.png)
Not sure what's happening here with this filter. I really want to be able to use it (with histogram and input, if possible) since it's by far the best suited filter to my large range of numbers.
In case it matters, the raw data generating the range is defined as a 'float' in the mapping, and it's possible for some items to have 'null' as the value when there's no data.

**Comment by joemcelroy** [comment]
- precise number issue: we can resolve this by rounding the number in searchkit and present a more readable number to the user
- Magically appearing filter: The filter will hide when the user cannot use the filter i.e the results brought back by ES do not have any value for the filter field. 
- Range filter applying filters magically: Il have a look at code to make sure this doesn't happen

**Comment by PAK90** [comment]
Post-0.10.0-10 update: the rounding fix doesn't seem to have had an effect...
![image](https://cloud.githubusercontent.com/assets/1844422/15271053/b7817f3e-19f3-11e6-9f6d-1d5427107560.png)
The one labelled 'Paper Price' seems to be working fine, but the 'MTGO Price' one, as you can see in the picture, has weird rendering problems and dragging it causes unpredictable results.
