### ISSUE TITLE
Nested filters

### ISSUE THREAD

**Issue by GregoryPotdevin** [searchkit/searchkit#252]
Would it make sense to allow adding Filters inside other Filters to build Hierarchical menus with custom rendering ? Something like 

```
<MenuFilter id="type" title="Type" field="type.raw">
  <RefinementListFilter id="genres" title="Genres" field="genres.raw" listComponent={GridList}/>
</MenuFilter>
```

This example would render the first level with a normal list and the second level (when a first level entry is selected) as a Grid.

**Comment by joemcelroy** [comment]
Good idea. One thing is reselecting a different parent option ( for example selecting movies instead of Episodes ) will need to clear any child selections. Would be good instead of the #32 issue.
