### ISSUE TITLE
History dependency problems

### ISSUE THREAD

**Issue by allizad** [searchkit/searchkit#255]
I'm testing out searchkit with the [pro-react book examples](https://github.com/pro-react/sample-code). Unable to use it because of dependency issues with history: cannot load modules.

**package.json:**
- https://gist.github.com/allizad/43546487ed7f4692476ee83a7f6027f0

**webpack.config.js:**
- https://gist.github.com/allizad/f78f58cc0cfe5797129df4410052748c

**Main App.js where I'm importing SearchKit**
- https://gist.github.com/allizad/6698be265fc5ef007060095428269556

**Terminal errors on running `npm start` or `webpack`:**
- https://gist.github.com/allizad/6e19a883f3c92126e61282c7bed2117e

The repeated error is basically that it cannot resolve modiule `invariant`, `warning`, `query-string`, or `deep-equal` for the dependency `history`:
```
ERROR in ./~/searchkit/~/history/lib/createBrowserHistory.js
Module not found: Error: Cannot resolve module 'invariant' in /Users/alli/code/pro-react/node_modules/searchkit/node_modules/history/lib
 @ ./~/searchkit/~/history/lib/createBrowserHistory.js 9:17-37
```

The Chrome console shows the same errors, with a deeper trace:
- https://gist.github.com/allizad/bd293a05db9370ce1fb3c27eef4e4716

I tested this with a couple of other projects using npm and webpack and got the same errors.

**Comment by joemcelroy** [comment]
Hi,

What npm version are you running?

**Comment by allizad** [comment]
That was it - I was still on 2. Updating to 3 seems to have ironed it out. Thanks!
