### ISSUE TITLE
ItemHistogramList as a listComponent not working in NumericRefinementListFilter

### ISSUE THREAD

**Issue by osthafen** [searchkit/searchkit#259]
I'm trying to use ItemHistogramList as a listComponent in NumericRefinementListFilter.
But it doesn't seem to work.
doc_count should be included in the response.
I altered the NumericRefinementListFilter example to use ItemHistogramList:
http://codepen.io/anon/pen/VaVrBW

**Comment by GregoryPotdevin** [comment]
Thanks, will take a look
