### ISSUE TITLE
Module not found: Error: Cannot resolve module 'invariant'

### ISSUE THREAD

**Issue by infacq** [searchkit/searchkit#260]
I hit this error when develop react app with Meteor as backend.

**Comment by GregoryPotdevin** [comment]
Is this client-side or server-side ?

**Comment by GregoryPotdevin** [comment]
Not sure what the problem is, but have you tried installing the invariant package to see what happens ?

**Comment by infacq** [comment]
if I install it tru npm install it will work but not with `meteor npm install`
