### ISSUE TITLE
FastClick onClick stopPropagation

### ISSUE THREAD

**Issue by GregoryPotdevin** [searchkit/searchkit#262]
FastClick's onClick handler calls `preventDefault` but not `stopPropagation`. When nesting `TagFilter` in a Hit component that has an onClick event handler, clicking on the TagFilter triggers the item-level click handler.

It looks like stopPropagation should be there by default, do you guys see any reason NOT to have it ?

**Comment by joemcelroy** [comment]
stopPropagation will stop click / touch events from bubbling up to the body so for example having a context dialogs listening on the body when visible so they cannot close. That said, I would hope most "widgets" would not rely on event bubbling (newer context dialogs use a invisible backdrop to intercept the click event)

Im fine with adding this in.

**Comment by GregoryPotdevin** [comment]
Ok. 

If at some point we need it we can add an onClick prop to FastClick to bypass the default handler.

**Comment by joemcelroy** [comment]
On more thought of this, its best for now to defer actually adding stopProp and improve the item level click handler to say only the title.

**Comment by GregoryPotdevin** [comment]
Actually this is to fix an issue @PAK90 has. His items are clickable (to expand/contract) and he has TagFilters in them. When clicking on the TagFilter, the item contracts, which is not desired. In this case FastClick is already just on the title itself. 
Or we can just remove FastClick from the TagFilter and use normal clicks.

**Comment by joemcelroy** [comment]
OK. I would suggest having a dropdown icon for toggling expand collapse rather than the whole item but I dont know the UI. Not sure if using normal onClick handler would help this? You could override the default clickhandler, inspect event target and stopProp if tagFilter is target (this customised in PAK90 app).
