### ISSUE TITLE
React-router

### ISSUE THREAD

**Issue by sherryxiao1988** [searchkit/searchkit#266]
I couldn't get searchkit to work with react router. I tried it out using the searchkit boilerplate.
routes:
```
  <Router history={browserHistory}>
    <Route path="/" component={Home}>
      <Route path="search" component={Search}/>
    </Route>
  </Router>
```
home:
```
import React from 'react';

export default class Home extends React.Component {
  render() {
    return (
      <div>{this.props.children}</div>
    );
  }
}
```

Search component is renamed from the App component. When I go to http://localhost:3000/, the browser changed the address bar to http://localhost:3000/#/?_k=ui2jdu and showed me an empty page.

Can anyone show me an example how to make them work together? Did I miss anything?

**Comment by joemcelroy** [comment]
Search should be accessible on #/search then. You need to read up on react router. Look into using indexroute or redirect so / will show search.

**Comment by sherryxiao1988** [comment]
@joemcelroy thanks for replying. sorry I meant I went to http://localhost:3000/serach. it showed http://localhost:3000/serach#/?_k=znhpst and an empty page.

I've read react router and tried many alternative ways but still got the same thing. Any clue what's happening? Could you try downloading the boilerplate and quickly try it out with react router? I want to know if it's just me.

Thanks.

**Comment by joemcelroy** [comment]
Could you commit your code somewhere and I can check it out. Btw you spelt
search wrong, maybe could be your issue.

**Comment by sherryxiao1988** [comment]
@joemcelroy here you go:
https://github.com/sherryxiao1988/searchkit-react-router

lol I didn't spell it wrong in the browser thought. Double checked it.
Thanks a lot!

**Comment by sherryxiao1988** [comment]
Thanks @joemcelroy for helping me figure this out.
The following tweaks work great for now:
```
const createBrowserHistory = require('history/lib/createBrowserHistory')

ReactDOM.render((
  <Router history={createBrowserHistory()}>
    <Route path="/" component={Home}>
      <Route path="search" component={App}/>
    </Route>
  </Router>
), document.getElementById('root'));
```

**Comment by joemcelroy** [comment]
some issue with browserHistory being null. Needs investigation from us. Thanks!
