### ISSUE TITLE
Serializing operators for RefinementListFilters

### ISSUE THREAD

**Issue by PAK90** [searchkit/searchkit#267]
Currently the operator (AND/OR) is defined as a prop of a `RefinementListOperator` and is never changed. In my use case I have a `<select>` component for each `RefinementListOperator` I use which changes the AND/OR. Since this isn't serialized in the URL, however, trying to share search results generated with OR (since the default is AND), is impossible. 

I took a brief look at the Accessor code to see if it would be a trivial endeavor for me to add this, but I don't think it is. It would be extremely useful to have, though.

**Comment by jomarquez** [comment]
@PAK90 were you able to solve this?
