### ISSUE TITLE
Add translation for All key for MenuFilter to documention

### ISSUE THREAD

**Issue by r9b9rt** [searchkit/searchkit#270]
Hello,

I tried to find the translations key for the text "All" for the MenuFilter component.

By going through the Code I found the key is called "All" as well.
I'm passing this as translations to the component and it's working.
Is there a global translations key for this as well?

I was not able to find either in your documentation. If it's there please excuse my lack of attention and point me to the right location.
Thanks

**Comment by joemcelroy** [comment]
Hey

http://docs.searchkit.co/stable/docs/core/Translate.html

**Comment by r9b9rt** [comment]
Thanks,
can you point me to the right key for the global mapping?

``"MenuFilter.All"`` is not working

I tried with upper case and lower case as well.

**Comment by ssetem** [comment]
@r9b9rt I think its "All" for global also

**Comment by r9b9rt** [comment]
That's fast. :+1: 
It's working now, thanks.
