### ISSUE TITLE
error given was: TypeError: _searchkit.SearchKitManager is not a function

### ISSUE THREAD

**Issue by xinghengwang** [searchkit/searchkit#276]
I am using babel ES6. this is my code. People see any issues? 

`import {
  SearchBox,
  RefinementListFilter,
  Hits,
  HitsStats,
  SearchkitComponent,
  SelectedFilters,
  MenuFilter,
  HierarchicalMenuFilter,
  Pagination,
  ResetFilters,
  SearchKitManager
} from 'searchkit';
import config from '../../config'

const sk = new SearchKitManager('http://' + config.searchHost + '/' + config.searchPort);

class Search extends Component {
  render() {
    return (
      <SearchKitProvder searchkit={sk}>
        <SearchBox/>
        <Hits/>
        <Pagination showNumbers={true}/>
      </SearchKitProvder>
    )
  }
}`

**Comment by ssetem** [comment]
SearchkitManager needs lowercase K

**Comment by xinghengwang** [comment]
lol. I feel stupid now.
