### ISSUE TITLE
Pass props to itemComponent and listComponent

### ISSUE THREAD

**Issue by r9b9rt** [searchkit/searchkit#277]
Hello,

is it possible to pass custom props to my itemComponent?

```
var myprops = {
    title: "Title"
}
```

Like

`<Hits hitsPerPage={72} itemComponent={ProductSetCard} itemComponentProps={myprops} mod="sk-hits-grid" />`

or

`<Hits hitsPerPage={72} itemComponent={ProductSetCard, myprops} mod="sk-hits-grid" />`

And then in ProductSetCard:
`this.props.title == "Title"` => `true`
or
`this.props.userProps.title == "Title"` => `true`

**Comment by ssetem** [comment]
@r9b9rt you could use a higher order component which wraps your component and returns the component bound to title. 

You could also pass in <ProductSetCard title="Title"/> to itemComponent.

**Comment by GregoryPotdevin** [comment]
`itemComponent={<ProductSetCard ...myprops />}` should work

**Comment by r9b9rt** [comment]
Thanks for your fast reply.

@GregoryPotdevin your solution works for me.
Although it might me standard react which I didn't know, maybe it's worth putting in the searchkit docs?

**Comment by GregoryPotdevin** [comment]
It's not really standard React, the *Component props in Searchkit work with 
- components
- *elements* (like this)
- functions (pretty much like functional components)

I think it's already in the doc but maybe not everywhere we have the *Component props
