### ISSUE TITLE
Allow formatting bucket counts in HierarchicalMenuFilter and HitsStats

### ISSUE THREAD

**Issue by aleybovich** [searchkit/searchkit#278]
Currently I can format number (e.g. display 3,500 for 3500 items) of items in a bucket for a <RefinementListFilter> by overriding itemComponent. The same is not currently possible for <HierarchicalMenuFilter> (according to @ssetem). Can you please add a way to format counts for HierarchicalMenuFilter as well as HitsStats?

**Comment by ssetem** [comment]
hi @aleybovich we just did a prerelease 0.10.0-4 with `countFormatter` support, which was added too
`RefinementListFilter`, `MenuFilter`, `NumericRefinementListFilter`, `HierarchicalMenuFilter`, `HierarchicalRefinementFilter`, `HitsStats`

Would you mind testing this for us?:D Thanks!
