### ISSUE TITLE
Store the state of multiple searchkits in the URL

### ISSUE THREAD

**Issue by jblom** [searchkit/searchkit#280]
Hi there, working on a use-case where a researcher would be able to search through different datasets on the same page, using two searchkits (see attached image). The plan is to also be able to store these multiple queries, so the researcher can get back to them via a URL.

It seems that the current 'useHistory' option in the SearchKitManager cannot monitor more than one searchkit at a time. 

The possible URL structure I currently have in mind would look something like:

http://localhost:5302/recipes?app1__q=amsterdam&app1__broadcaster[0]=VARA&app2__q=london&app2__genre[0]=drama

After coming up with a good solution, I might be able to help out with the code if needed.

![schermafbeelding 2016-05-18 om 09 51 50](https://cloud.githubusercontent.com/assets/917310/15359117/278a3b10-1d08-11e6-8414-7895f3ac3b0d.png)

**Comment by joemcelroy** [comment]
hey @jblom, is this still needed?

**Comment by jblom** [comment]
Nope! Actually I'm currently (still) working on a UI/page where it's possible to compare the search results of two or more search queries (from different collections) and at this moment it seems that reflecting all these (possibly huge) queries in the URL is something that I'll avoid for the moment. I want to figure out with the users first (after they start using the 1st version of the system) if they think it is crucial to be able to share their findings via the URL. 

I guess this issue comes down to figuring out whether to build an easy to use import/export function or do try to put all the information in the URL in a clever way.

If you have any experience with this kind of problem or have any hints on how to deal with this, I'm all ears.

Thanks

**Comment by jblom** [comment]
Oh yeah, also I'd say this functionality would only overcomplicate SearchKits code and wouldn't benefit a lot of people.

**Comment by joemcelroy** [comment]
yeh i agree, it was more of an functionality edge case.  an import / export search state would be a great feature in searchkit. Closing this for now.
