### ISSUE TITLE
CDN file not found

### ISSUE THREAD

**Issue by nirchernia** [searchkit/searchkit#281]
cdn.jsdelivr.net/searchkit/latest/styles.css gives "not found".

Is there anywhere the style sheet is provided in the repo? I cannot seem to find it.

**Comment by nirchernia** [comment]
I did manage to rip the css from the Demo: http://demo.searchkit.co/static/styles.css

**Comment by ssetem** [comment]
its called theme.css rather styles now

**Comment by joemcelroy** [comment]
Hi @nirchernia 

Have a look on jsdelivr website http://www.jsdelivr.com/?query=searchkit

**Comment by nirchernia** [comment]
@ssetem  @joemcelroy Thanks!
