### ISSUE TITLE
showNumbers=true for pagination, but numbers not showing. 

### ISSUE THREAD

**Issue by xinghengwang** [searchkit/searchkit#282]
I am on the latest version of searchkit. 0.9.2. 

I have this. 
 <Pagination showNumbers={true}/>

I also already apply the searchkit styling sheet.  

For pagination, the previous and next shows, and it works great. But the numbers do not show: 

![screen shot 2016-05-19 at 2 16 01 pm](https://cloud.githubusercontent.com/assets/6666687/15409993/441d2656-1dcc-11e6-9dc3-9ab3c476d033.png)

Anyone know what I did wrong?

**Comment by xinghengwang** [comment]
figured it out.

**Comment by ssetem** [comment]
@xinghengwang what was the fix in the end? just so we know :) thanks!

**Comment by xinghengwang** [comment]
had to make sure that hitsPerPage prop is set for Hits component. thanks.
