### ISSUE TITLE
Changing the searchUrlPath dynamically. 

### ISSUE THREAD

**Issue by xinghengwang** [searchkit/searchkit#283]
Hi 

Since the searchKit doesn't have a date based search filter/range, and because for security reasons users can only access data of certain groups (as indicated by the organziation.id) below. For I am encoding the parameters for organization data and date range in the searchUrlPath itself. 

So in the render function of my search page (container react component), I have this:  

      const storedToken = localStorage.getItem('id_token');
      const fromDate = this.state.startDate.format("YYYY-MM-DDTHH:mm:ss.SSS");
      const toDate = this.state.endDate.format("YYYY-MM-DDTHH:mm:ss.SSS");
      const searchUrlPath = `/${organization.id}/search?from=${fromDate}&to=${toDate}`;

      const sk = new SearchkitManager(
        '/api/search',
        {
          httpHeaders: {
            Authorization: 'Bearer ' + storedToken,
           'Content-Type': 'application/json'
          },
          searchUrlPath: searchUrlPath
        });

       return (
          <SearchkitProvider searchkit={sk}>
               ....
          </SearchkitProvider>
       )

Problem: 
First time it load, it works fine. however, whatever the initial fromDate or toDate I set, the searchkik still keep that around, the searchUrl doesn't seem to update. (I used to debugger, I determined for sure, I am passing new searchUrlPath in.  

Does anyone know what is going on? Is the searchUrlPath kept persistent by searchkitManager somewhere?

**Comment by ssetem** [comment]
@xinghengwang you can keep mutating this property

sk.transport.options.searchUrlPath

**Comment by xinghengwang** [comment]
Hm.., I think I see the issue. If I pass a new searchKitManager object to serviceProvider as a prop, the newly constructed searchKitManager object isn't pass down (or used). 

Originally, I construct a new SearchKitManager in the render() function. 
For two reasons:  make sure I am on the client side first before render the searchKit components (due to issue  https://github.com/searchkit/searchkit/issues/4, I want to check in my render function to see if I am in browser vs. server side render), and because the searchUrlPath is changing depends on the organization/group that user have have access to.  So each time render is called a new SearchKitManager object is constructed, and pass to serviceProvider as a prop. 

Now, I put sk as a global variable. and it is only constructed once. I just mutate the sk.transport.options.searchUrlPath each time. It seems to work.  However, it doesn't feel very elegant solution, because render suppose to be a pure function with no side effects. 

Is there any reason, that the searchkit prop of searchKitProvider can't be updated with new objects? Is this by design or a bug?

**Comment by GregoryPotdevin** [comment]
You could have a "Search" component that would create the SearchkitManager (in componentWillMount ?) and all of your search UI (in render). If you need to flush the whole Search you could then put a key on search and change it depending on the organization/group. Or do you need something more dynamic ?

**Comment by xinghengwang** [comment]
ok, I'll try that. thanks,
