### ISSUE TITLE
Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by nirchernia** [searchkit/searchkit#285]
I am attempting to make a connection to my Elastic Search. I would like to add in the header 'Origin', but SearchkitManager throws the error `Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response.
` My Elasticsearch requires this header, is there any way to allow this header within searchkit

The code:
```
render() {

    const headers = {Authorization: 'user:pw', 'Origin': 'origin-url'}
    const searchKitManager = new SearchkitManager('http://url-to-es, {httpHeaders: headers})

    return (<SearchkitProvider searchkit={searchKitManager}>
                 ...
                </SearchkitProvider>)
```

Note: I have tried basicAuth.

**Comment by ssetem** [comment]
have you set up cors correctly on your es instance?

**Comment by nirchernia** [comment]
Yes I have. 

I have tested my reaching my es instance with curl and have tested with ajax requests in the browser. Both work. Only the searchKitManager seems to throw errors.

**Comment by ssetem** [comment]
you might need to add Authorization to the allowed cors headers in your ES config

**Comment by joemcelroy** [comment]
hi @nirchernia 

See our documentation: http://docs.searchkit.co/stable/docs/setup/elasticsearch.html

**Comment by nirchernia** [comment]
@ssetem That seemed to do the trick. Thanks!

**Comment by ssetem** [comment]
nice! I will add a note to our docs
