### ISSUE TITLE
Call elasticsearch from the server-side ?

### ISSUE THREAD

**Issue by sieutruc** [searchkit/searchkit#287]
Hi,

I like your package searchkit.

However, I see that the only way to define the elasticsearch server is on client-side . Doest it raise a problem of security ?

Normally, i think that the server methods will send the query to the local elasticsearch and returns the results to the client navigator. By this way, we will have a granular permission system. For example: user A can view index X, ( type Y) , user B can view index X1 ( type Y1). 

Is there another way that does not need to query directly elasticsearch server ? but it will be like what i propose as above ?

**Comment by ssetem** [comment]
@sieutruc I agree, we use and advice having a proxy on the server.

http://docs.searchkit.co/stable/docs/server/searchkit_express.html

we ship a proxy library for node.js, here are the docs
