### ISSUE TITLE
react context no longer available for itemComponent or listComponent for Hits

### ISSUE THREAD

**Issue by xinghengwang** [searchkit/searchkit#294]
context, a feature of react, seems no longer available in itemComponent or listComponent, when rendered by the Hits component. 

Background: 
I have some context provided by a top level components that wraps my application. To render the links properly from the search results, I need the context in addition to the id's passed back from the search result. The itemComponent is passed to Hits, even though the itemComponent is all under the subtree of the top level component that have the context, the context is always null for the itemComponent.

**Comment by GregoryPotdevin** [comment]
Weird, I'm not aware of anything in React that could prevent context from propagating. Can you post the code using itemComponent

**Comment by GregoryPotdevin** [comment]
(Might be a problem with our use of React.cloneElement, will do some testing)

**Comment by xinghengwang** [comment]
my code is here: 
`
// Hit Render is a pure render component
function HitRender({result}, context) {
  // the context turn out null. So I used to work around to return the orgId and appId through the elastic search results. 
  
  return (
    <div>
      <h4>Element</h4>
      <Link to={`/wrap/app/${result._source.org_id}-${result._source.app_id}/user?userId=${result._id}`}>
        {result._id}</Link>
        <pre>
          {JSON.stringify(result, null, ' ')}
        </pre>
    </div>
  );
}

HitRender.contextTypes = {
  orgId: PropTypes.string,
  appId: PropTypes.string
};
`

Then in render of the search component I have is there: 

`
<Hits itemComponent={HitRender} />
`

**Comment by GregoryPotdevin** [comment]
Ok, that explains it. When we detect if it's a component, we only take into account React.createClass and React.Component subclasses. For functions we just call them directly and in that case we don't pass the context. I'll check that out.

**Comment by ssetem** [comment]
@xinghengwang  we did a prerelease 0.10.0-5 with a fix for this

Could you test it out when you get a chance?

Thanks!

**Comment by xinghengwang** [comment]
Yep, tested. It works!! thanks!
