### ISSUE TITLE
Caching of queries

### ISSUE THREAD

**Issue by Jellyfrog** [searchkit/searchkit#3]
Maybe something like this would be enough?

``` js
this.cache = {}

if (this.cache[query] !== undefined)
  return this.cache[query]

this.cache[query] = response
```

**Comment by ssetem** [comment]
Hi :), Thanks for the feedback.
A query cache would definitely help performance, we would probably want to an aggressive LRU cache size with aggressive expiry as responses may grow to a large memory usage.
