### ISSUE TITLE
Single choice of date like Goolge

### ISSUE THREAD

**Issue by kinhunt** [searchkit/searchkit#300]
<img width="745" alt="2016-06-06 8 34 46" src="https://cloud.githubusercontent.com/assets/1231514/15809358/e0d5a01a-2bc1-11e6-94bf-0a5965c28cef.png">

New to searchkit. Which component should I use to build something like this? I tried checkbox, but it's a true/false toggle. Is there a radiobox like component?

Thank you.

**Comment by GregoryPotdevin** [comment]
That would need a NumericRefinementListFilter but for dates. We'll be working on date filters this week so hopefully you'll have a beta you can test very soon ;)

**Comment by kinhunt** [comment]
Thank you. Close for the moment

**Comment by infacq** [comment]
is there any documentation for it?
