### ISSUE TITLE
Searchkit to display no hits until typed into

### ISSUE THREAD

**Issue by nirchernia** [searchkit/searchkit#302]
I'd like to to know if it is possible to display no hits until Searchkit is being interacted with (typed into). That way, searchkit could be a passive component until it is used. Anyway to do this currently?

I have looked `<Initial Loader>`, but that seems to do something different than what I was looking for.

**Comment by ssetem** [comment]
@nirchernia you can pass searchOnLoad:false into SearchkitManager so it doesnt perform initial search

**Comment by jacksonp2008** [comment]
I must be doing it incorrectly, still loading on start here:

const host = "http://172.28.128.3:9200/twitter,slack,email"
const searchOnLoad = false
const searchkit = new SearchkitManager(host,searchOnLoad)

**Comment by joemcelroy** [comment]
```
const host = "http://172.28.128.3:9200/twitter,slack,email"
const searchkit = new SearchkitManager(host, { searchOnLoad: false })
```
