### ISSUE TITLE
Create tag filter from the searchbox term

### ISSUE THREAD

**Issue by ronydj** [searchkit/searchkit#303]
Hi guys,

Is there any way to create a tag filter using the searchbox typed term?

For example,

The user type anything in the searchbox. When this user press enter that term is used as a tag filter, and then the user can use the searchbox again to search things over the previously search result.

**Comment by GregoryPotdevin** [comment]
Should this be placed like a normal searchbox or is this a filtering component ?

This one might be close to what you want : https://github.com/GregoryPotdevin/searchkit-multiselect

**Comment by ronydj** [comment]
It is close.  I want it as a normal searchbox. I thanks for sharing this component. 

I will try to build a component based on this one.

**Comment by ronydj** [comment]
No success. I would need to extend the input filter in some way to achieve what I want. O thought about overriding the onSubmit event and call the addToFilter method.

But I don't know how do it.

**Comment by joemcelroy** [comment]
We want to do something like this in future with the autocomplete component, hopefully be released soon!

**Comment by joemcelroy** [comment]
#31 linked to this. Closing this issue
