### ISSUE TITLE
react router's <Link to{}> doesn't work with searchkit

### ISSUE THREAD

**Issue by xinghengwang** [searchkit/searchkit#307]
Hi, 
a common scenario is that when you generate search results, you can say find similar. So like if you find a good movie say "Finding Nemo".  it is a animation, it would be like to have a link as part of the result with `<Link to>` where the url is preconfigured with the filter setting categoryto Animiations. (Which is create the query parameters for the url, given you already support searchFromQuery, and the query format is well defined.)  

Howerever `<Link to>` uses push to change the history state. 

So I noticed in the code under searchKitManager. 

```
    this._unlistenHistory = this.history.listen(after(callsBeforeListen,(location)=>{
      //action is POP when the browser modified
      if(location.action === "POP") {
        this.registrationCompleted.then(()=>{
            this.searchFromUrlQuery(location.query)
        }).catch((e)=> {
          console.error(e.stack)
        })
      }
    }))
```

You only trigger searchFromUrlQuery if location.action is "POP". 

I think that is because you do use push (or replacestate) to change the history, in performSearch(), which is triggered by various filters changes.  

```
    this._search()
    if(this.options.useHistory){
      const historyMethod = (replaceState) ?
        this.history.replace : this.history.push
      historyMethod({pathname: window.location.pathname, query:this.state})

    } 
```

So, I understand in those scenarios, you probably don't want do have the history change trigger a new search, since you are doing search already. 

I am playing and changing the code for searchkit, but I am curious, what is the best approach? 

(Btw, the approach I am thinking is that If the option uses history, I won't do this._search() in the performSearch method, but just trigger the change in the history, and let the change in history to trigger "searchFromUrlQuery" by doing these changes: 

In performSearch(query), I do these changes: 

```
  performSearch(replaceState=false, notifyState=true){
    if(notifyState && !isEqual(this.accessors.getState(), this.state)){
      this.accessors.notifyStateChange(this.state)
    }
      // original code, commented out.
      // this._search()
    if(this.options.useHistory){
      const historyMethod = (replaceState) ?
        this.history.replace : this.history.push
      historyMethod({pathname: window.location.pathname, query:this.state})
      //I'll rely on trigger history change change to trigger searchFromUrlQuery

    } else {
        //if this doesn't use history, I'll do _search here.
        this._search()
    }
  }
```

In ListenToHistory(). I just allow for  `if(location && (location.action === "POP" || location.action === "PUSH" || location.action === "REPLACE"))`

So I thought this approach would work, unfrotunately, I run into a lot of wierd behavior (especially with filters. Any hints on I could have done wrong?

**Comment by SickSAMA** [comment]
@xinghengwang in ```performSearch``` you need to set ```this.state = this.accessors.getState();```, you can refer to my post in #297 . Fell free to comment.

**Comment by ssetem** [comment]
i need to look at all these history reports from high level, you could use the TagFilter component which supports what you need
