### ISSUE TITLE
rangeFormatter function not applied for DynamicRangeFilter

### ISSUE THREAD

**Issue by thebadplus** [searchkit/searchkit#308]
When incorporating a DynamicRangeFilter component, if a rangeFormatter function is created, the formatting function is not applied to the filter labels at the top of the hits page. This has not been tested with the static RangeFilter filter component, but likely effects the other components as well.

In the interm, I use a workaround which is to replace the text in jQuery on the rendering function of the hits component to manually alter the filter text.

```

  correctStartDateLabel() {
    let startdateSelector = '.selected-filter--startDate .sk-selected-filters-option__name span:nth-child(3)'
    let startDateText = $(startdateSelector).text()
    let start = startDateText.split('-')[0].trim()
    let end = startDateText.split('-')[0].trim()
    $(startdateSelector).html( '&nbsp; ' + dateFormatter(start) + ' - ' + dateFormatter(end))
  }
```

**Comment by joemcelroy** [comment]
thanks. Yep we will take a look at this issue. Also you can provide a react component to render the selected filter items via the `itemComponent` prop for SelectedFilter component rather than hacking it via jQuery. http://docs.searchkit.co/stable/docs/components/navigation/selected-filters.html.
