### ISSUE TITLE
Display error on search request timeout

### ISSUE THREAD

**Issue by mcs07** [searchkit/searchkit#310]
Consider increasing the version of the axios dependency so search timeouts are treated as errors. See the axios pull request https://github.com/mzabriskie/axios/pull/227 for details - this seems to be available in axios 0.10.0 and higher.

**Comment by gaving** [comment]
👍 

Additionally I'd like a way to configure this since [the default](https://github.com/searchkit/searchkit/blob/f59f28398928c47ef0ec3b25706c224b008766b5/src/core/transport/AxiosESTransport.ts#L13) 5000ms is too short for my ES instance.

**Comment by joemcelroy** [comment]
fixed in #396 . Shows the error component when exceeded
