### ISSUE TITLE
Search Multiple Indices

### ISSUE THREAD

**Issue by chrisdebug** [searchkit/searchkit#317]
Is it possible to search multiple indices with one Searchbox?

**Comment by GregoryPotdevin** [comment]
Should work by changing the host : 
https://www.elastic.co/guide/en/elasticsearch/guide/current/multi-index-multi-type.html
``` 
/gb,us/user,tweet/_search
```

**Comment by chrisdebug** [comment]
Awesome! Thanks! I should have figured out to use an Elasticsearch solution instead of searching for a searchbox option.
