### ISSUE TITLE
multiple (conflicting) copies of React loaded

### ISSUE THREAD

**Issue by chenchengwork** [searchkit/searchkit#325]
Hi,I use react1.5.3.0, but searchkit dependent on react0.14.7,so my app display error

addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's render method, or you have multiple copies of React loaded.

Suggested use：

  "peerDependencies": {
    "react": "^0.14.0 || ^15.0.0-0"
  },

**Comment by darkadept** [comment]
See #188

**Comment by joemcelroy** [comment]
closing issue as already reported in another issue. Investigating this as part of 1.0.0 release.
