### ISSUE TITLE
Ability to hide Searchkit components during the initial load

### ISSUE THREAD

**Issue by aleybovich** [searchkit/searchkit#326]
This came up in my project - the client wants HitsStats, SelectedFilters, ResetFilters and some other components hidden during the initial load. Currently I have to subclass those and conditionally render null when this.isInitialLoading == true. It would be very handy to expose a property .hideOnInitialLoad on any searchkit.

**Comment by GregoryPotdevin** [comment]
Another way to do it could be by using utility functions. Though it's probably the same thing as you're doing 
```jsx
function autoHideWrap(Component){
  return class extends Component {
    render(){
      if (this.isInitialLoading) return null
      return super.render()
    }
  }
}  

const AutoHideRefinementListFilter = autoHideWrap(RefinementListFilter)
const AutoHideHitsStats = autoHideWrap(HitsStats)
...
```

(haven't tried but should work).

**Comment by joemcelroy** [comment]
Closing this issue as temp workaround. linking with #32 as potential feature
