### ISSUE TITLE
Pb with bucketsTransform props on MenuFilter

### ISSUE THREAD

**Issue by Baltox** [searchkit/searchkit#327]
Hi,
I want to use the "bucketsTransform" props of the MenuFilter.
When i use it nothing happens, here's my code :

`<MenuFilter field="languages.raw" title="Languages" id="languages" bucketsTransform={((buckets)=> console.log(buckets))}/>`

**Comment by GregoryPotdevin** [comment]
Thanks. 

Potential fix : 
https://github.com/searchkit/searchkit/blob/c84bc997d40c17adebae324abd54bde7905ee6cb/src/components/search/filters/facet-filter/MenuFilter.tsx#L51

`this.accessor.getBuckets()` should be replaced by `super.getItems()`

**Comment by bcruddy** [comment]
@GregoryPotdevin @joemcelroy any progress on this? I'm seeing the same issue:

```javascript
const bucketTransforms = {
    productTypes: (buckets) => {
        // if (!buckets.length) {
        //     return buckets;
        // }

        console.log(buckets);

        return buckets;
    }
};

...

<MenuFilter
    id="productTypes"
    title=""
    operator="AND"
    field="productTypes.raw"
    bucketsTransform={bucketTransforms.productTypes}
    listComponent={Tabs} />
```

This works fine with `RefinementListFilter` but I want to keep the "All" facet.
