### ISSUE TITLE
Ability to customize/template hit item key

### ISSUE THREAD

**Issue by aleybovich** [searchkit/searchkit#329]
The problem we are facing is that we have two indices where some document _id's duplicate between the two indices. We get a React error about key being duplicate - this happens when HitsList renders items and assigns keys. As a temporary solution we have ovrrridden HitsList.prototype.render and changed `key: result._id` to `key: result._index + result._id` . 
It would be great if you could add a hook instead for generating a key. Maybe a property on Hits component where I can provide a custom function with `result` as an argument that will return a custom key, or fallback to `result._id` if no function is provided

**Comment by joemcelroy** [comment]
hey @aleybovich, you could also override the `listComponent` prop and implement your own list rendering + key (https://github.com/searchkit/searchkit/blob/a9b5abd2a17ac45c7e1eecf4c29f52ca18e6afe8/src/components/search/hits/src/Hits.tsx#L112)
