### ISSUE TITLE
Option to not search immediately

### ISSUE THREAD

**Issue by joemcelroy** [searchkit/searchkit#33]
- An option within searchkitManager to not search immediately
- Will only render results from ES once the user is querying (via searchbox for example
- initial loading view is shown instead

**Comment by joemcelroy** [comment]
searchOnLoad boolean option is in, we just need SearchkitManager to aware no search has been completed yet and NoHits to render "intro" view.

**Comment by thomasmodeneis** [comment]
Hi @joemcelroy 
Any idea when this will be released ? +1 for this feature.
Thanks.

**Comment by joemcelroy** [comment]
http://docs.searchkit.co/stable/docs/core/SearchkitManager.html

`searchOnLoad` option has been released and http://docs.searchkit.co/stable/docs/components/basics/initial-loader.html component renders before any search query has been performed.

**Comment by joemcelroy** [comment]
closing issue. @thomasmodeneis let me know if you need extra functionality.

**Comment by thomasmodeneis** [comment]
Oh thanks @joemcelroy , thats all for me :D

**Comment by thomasmodeneis** [comment]
e pHi,

I've just realised that this option is actually not doing what I wanted.

What I expected this behaviour:
Given searchOnLoad is false, and user opens search page and there is a no query argument, then don't search anything.
Given searchOnLoad is false, and user opens search page and there is a query argument, search and show results on page.

The main problem for me right now, is when the user opens the search pag, searchkit triggers a full search on ELK that is taking about 3s. But the user haven't requested anything, he still want to search so its not using the resources very efficient. This is not  for ex. how google works, in other words: no query no search, with query do search.

Is there any way I could get this behaviour maybe with another option to clarify the behaviour ?

Thanks

**Comment by joemcelroy** [comment]
You could make `searchOnLoad` boolean could be true / false depending if the url has a query param. If url has a query param, `searchOnLoad` is true and should trigger a search to ES, otherwise false.

**Comment by thomasmodeneis** [comment]
oh right so this is on my side of the logic, that will work.
Thanks @joemcelroy
