### ISSUE TITLE
Prevent empty searches

### ISSUE THREAD

**Issue by heylookalive** [searchkit/searchkit#330]
Hey, this is a feature we'd be interested in. Are you open to pull requests?

Thanks!

**Comment by infacq** [comment]
do you mean this?

```js
const searchkit = new SearchkitManager(process.env.ES_URL, {searchOnLoad: true}) 
```

**Comment by heylookalive** [comment]
Kind of, I suppose we don't want an open search to happen, but a `searchOnLoad` to happen if there are values in the query string.

**Comment by kud** [comment]
I would like the same thing but never found a way.

`searchOnLoad` is cool but only works the first time. If the user writes something and erases everything, it searches again with no query string.

I want : no request if no query string.

**Comment by infacq** [comment]
is it happen on [demo](http://demo.searchkit.co/) site?

**Comment by kud** [comment]
It's not a bug, it's a feature request / help request. I think @heylookalive and I would like not to make a request when query string is empty. :)

**Comment by kud** [comment]
@heylookalive did you find a workaround by any chance?

**Comment by kud** [comment]
I found a workaround for the first call, if you have an empty query string or not:

```javascript
    const parsed = queryString.parse(location.search)
    const q = parsed.q

    const sk = new SearchkitManager(API_URL + "/search/", {
      searchOnLoad: q !== undefined // hack in order not to load the first call
    })
```

I still need to find a way not to make a request if you insert something, it makes a query and you remove all the input.

**Comment by ahmb84** [comment]
@kud I wait for the feature. It will be a big help. Thanks.

**Comment by ssetem** [comment]
I need to understand more about this feature request.

I understand searchOnload, but what would behaviour be after a few searches have been done on the page?, would it keep the previous result still visible?

We could add a shouldSearch:Function option where you decide what should happen

**Comment by kud** [comment]
For my case, I just want not to do anything if the query is empty.

For the moment in my company, we return an empty result via the backend in this case, but it's not really the best way IMO.

Indeed, shouldSearch could be great.

**Comment by ssetem** [comment]
cool, we will add shouldSearch option to SearckitManager

that way all kinds of searches can be disabled, not just empty query.

The default doc examples will show empty query tho :D

**Comment by kud** [comment]
Yes! yes! yes!

**Comment by ssetem** [comment]
@heylookalive @kud @ahmb84 @infacq 

this should be fixed in beat version 2.3.0-0
we have added `shouldPerformSearch` function which can be overriden, and is called with an instance of `ImmutableQuery`

Here is example of preventing on empty search
```js
  searchkit.shouldPerformSearch = (query)=> {
    return !!query.getQueryString()
  }
```

let me know if there are any issues

thanks!

**Comment by kud** [comment]
Cool, thanks!

**Comment by inostia** [comment]
This feature is currently undocumented. I will try to make a PR to document it.
