### ISSUE TITLE
Is there a way we can have some IONIC juice in here to create Mobile Apps with searchkit?

### ISSUE THREAD

**Issue by Panthro** [searchkit/searchkit#334]
I really love searchkit and I already have a web app up'n running with it, but now I need to convert it into a mobile app.

Just to have the issue open, I'm investigating it.

**Comment by Vanuan** [comment]
What about React Native?

**Comment by Vanuan** [comment]
Related to #176

**Comment by joemcelroy** [comment]
closing this issue, tracking in 176. 
fyi i think having it behave nicely on mobile web is the way to go for us. React-native support is a definite bonus.
