### ISSUE TITLE
rc-slider dependency update

### ISSUE THREAD

**Issue by SickSAMA** [searchkit/searchkit#337]
I'm using 0.10.1. It uses `rc-slider@3.3.2` and `rc-slider` uses `rc-util@3.x`. However `rc-util` deprecated a few functions in it's lastest 3.x versions so 4 warnings are thrown
![screen shot 2016-09-27 at 3 38 19 pm](https://cloud.githubusercontent.com/assets/10954688/18864340/71f010ee-84c8-11e6-8e6d-d77ebfd153c0.png)
rc-slider should be updated to latest version to solve the issue.

**Comment by mbm-rafal** [comment]
@SickSAMA  did you try to build version 0.10.1 of searchkit, this component produce error as described https://github.com/searchkit/searchkit/issues/375

**Comment by joemcelroy** [comment]
Yep thanks, ive updated rc-slider in searchkit soon to be released beta.
