### ISSUE TITLE
BaseQueryAccessor : Singe instance issue

### ISSUE THREAD

**Issue by rohit-raj** [searchkit/searchkit#338]
I am working with searchkit, while refreshing the page, it shows 
**"Only a single instance of BaseQueryAccessor is allowed"**

This happens only when I use:

```
const searchkit = new SearchkitManager(host, {
useHistory: false,
});
```

I need to use "useHistory as false" because
When I use
`const searchkit = new SearchkitManager(host);`

to initialize searchkit, it shows :
**"Invariant Violation: Browser history needs a DOM"**
which is due to history conflict between my app and searchkit, since there is no provision of passing custom history.
Any leads will be really helpful

**Comment by GregoryPotdevin** [comment]
Can you post which components/filters you are using ?

**Comment by rohit-raj** [comment]
I am using the following filters:
`MenuFilter`
`DynamicRangeFilter`
`RefinementListFilter`

```
<Hits
   mod="sk-hits-grid" hitsPerPage={6} listComponent={this.hitsGridItem}
   sourceFilter={['title', 'status', 'academics']}
/>
```

```
<SearchBox
    autofocus
    searchOnChange
    placeholder="Search..."
    prefixQueryFields={['status^2', 'title^10']}
    name="page"
   queryFields={['type']}
 />
```

Is there any problem with the component or filters that I am using ?

**Comment by ssetem** [comment]
@rohit-raj are you using SearchBox twice by any chance?

**Comment by rohit-raj** [comment]
@ssetem No, I am using it just once.

**Comment by ssetem** [comment]
would be useful to see a project, hard for us to investigate, your package.json would be useful also

**Comment by rohit-raj** [comment]
I have added the search page implementation and the package json. 
[project.zip](https://github.com/searchkit/searchkit/files/498744/project.zip)

**Comment by rohit-raj** [comment]
I have figured out the issue, it is due to server rendering.
```
componentWillMount () {
    if (!isServer()) {
      this.sKit = new SearchkitManager(ELASTICSEARCH_URL);
      this.sKit.addDefaultQuery((query)=> {
        return query.addQuery(FilteredQuery({
          filter:BoolShould([
            TermQuery("status", 1)
          ])
        }));
      });
    } else {
      this.sKit = new SearchkitManager(ELASTICSEARCH_URL, {
        useHistory: false,
      });
    }
  }
```

checking the env as server we need to render the useHistory as false.

**Comment by rohit-raj** [comment]
@ssetem I am facing one more issue with respect to the history. the url generated after searching or filtering, if copied and pasted to another window will fetch the same result but in my case it is not. 
in SearchkitManager.js
```
SearchkitManager.prototype.listenToHistory = function () {
        var _this = this;
        var callsBeforeListen = (this.options.searchOnLoad) ? 1 : 2;
        this._unlistenHistory = this.history.listen(after(callsBeforeListen, function (location) {
            //action is POP when the browser modified
            if (location.action === "POP") {
                _this.registrationCompleted.then(function () {
                    _this.searchFromUrlQuery(location.query);
                }).catch(function (e) {
                    console.error(e.stack);
                });
            }
        }));
    };
```
_this.registrationCompleted is not getting resolved during first loading and during url hit with query parameters.

**Comment by rohit-raj** [comment]
@ssetem When I am trying to use `MenuFilter`, it is working with `listComponent` as ItemHistogramList but not with any other option, I have imported the other options that it supports but still the issue persist.

**Comment by ssetem** [comment]
@rohit-raj is it related to the [URGENT] <title> etc?

or is a different issue?

**Comment by rohit-raj** [comment]
@ssetem I am not able to understand whether this is dependent on this issue or not. Once I figured the way out of the main issue, I ended up in this.
Please suggest if I need to open a new issue or is this fine .

**Comment by ssetem** [comment]
when you say the other listComponents don't work, how do they fail? and could you paste the code which is not working?, also have you made show that your imports for listComponents are not undefined etc

**Comment by rohit-raj** [comment]
@ssetem They simply doesn't work, without any error, do not respond on selected item.
[searchPage.zip](https://github.com/searchkit/searchkit/files/503004/searchPage.zip)

PFA the file in zip. 

Please let me know if any thing is required

**Comment by ssetem** [comment]
does it break only on server render? or both client + server

**Comment by tengis** [comment]
Hi guys,
I'm also experiencing same issue.  **_this.registrationCompleted** is not getting resolved during first load.

**Comment by rohit-raj** [comment]
@tengis, this is happening because your version of react js is different than of the searchkit.

soln:
   - fork the searchkit to your account
   - change the version of react js in searchkit's package json as in your project
   - remove the `lib` from gitignore
   - push it to your account
   - import this version from your repo with your hashid to your project's package json

**Comment by ssetem** [comment]
If any of you are using webpack, you can use the alias functionality to fix the version of react.

We need to fix our side too also ofcourse

**Comment by chrisfinch** [comment]
@rohit-raj Did you manage to solve the issue with BaseQueryAccessor?

I'm getting the same issue but can't resolve it...

```javascript
import { createMemoryHistory, createBrowserHistory } from 'history';

let searchKit;

const getSearchKitInstance = () => {
	if (!searchKit) {
		const SearchkitManager = require('searchkit').SearchkitManager;

		if (WEBPACK_CONFIG_IS_NODE) {
		    searchKit = new SearchkitManager("/", {
		        useHistory: false,
		        searchOnLoad: false,
		        createHistory: createMemoryHistory
		    })
			return searchKit;
		} else {
		    searchKit = new SearchkitManager("/", {
		        timeout: 20000,
		        createHistory: createBrowserHistory
		    });
			return searchKit;
		};
	} else return searchKit;
};

export default getSearchKitInstance;

```

**Comment by rohit-raj** [comment]
Hi @chrisfinch ,

I have already posted the solution above in the chain. Please refer it. Do let me know if you still face the same issue after working out the solution.

**Comment by chrisfinch** [comment]
@rohit-raj yes I saw your switch on server render with `useHistory: false` - if you check the code in my post you can see I'm trying the same thing but it's not working - any assistance would be appreciated!

**Comment by rohit-raj** [comment]
@chrisfinch ,

I think, you might refer to my forked repo, because I faced some react js version incompatibility during the implementation.
You can check the react js versions of searchkit and your project. This was the problem which I encountered. Along with that I had to stop server rendering, hence it fixed my issue. `(!isServer)`

I see that you are not checking the server rendering in your code. Please check it. 

Also, saw your new issue, in which Ash has been working on server rendering part of searchkit. Actually this is the problem base. When searchkit will have a new build, I think this must be solved.

**Comment by chrisfinch** [comment]
@rohit-raj 

This line in my code checks for the server environment:
```javascript
if (WEBPACK_CONFIG_IS_NODE) {
```
