### ISSUE TITLE
Accessing searchkit through my personal repository

### ISSUE THREAD

**Issue by rohit-raj** [searchkit/searchkit#339]
Hi,

I had to add a few things in `searchkitmanager.js`, for which, I have forked searchkit and made some changes to `searchkitmanager.ts` related to my personal implementation.
I see that the `lib` folder is not present in the project.
Can you please let me know how to generate the `lib` folder and access the same.

I pushed the changed code to my repo, and in my `package.json`, i imported it as `https://github.com/rohit-raj/searchkit/tarball/hash-id`
which does not work since the lib folder is not present.

I have read the [developer-guide.md](https://github.com/searchkit/searchkit/blob/develop/docs/developer-guide.md) and followed exactly same. I see that a `release` folder gets created with `lib` in it.

Do I need to run `release.sh` ?

Any insight will really be helpful.

Thanks,
Rohit

**Comment by joemcelroy** [comment]
should be able to run `npm run build`. Closing this issue
