### ISSUE TITLE
Elasticsearch 5.0

### ISSUE THREAD

**Issue by nikieshady** [searchkit/searchkit#349]
Not works with elastic search 5.0. Especially the filters do not work dynamically.

**Comment by nikieshady** [comment]
when i click in one filter appears in console

"type: parsing_exception, reason: Unknown key for a START_OBJECT in [filter]..."

**Comment by thomasmodeneis** [comment]
I'm also facing it same issue here, besides and the changes on the mapping for keyword and fielddata:true.
```
{"error":{"root_cause":[{"type":"parsing_exception","reason":"Unknown key for a START_OBJECT in [filter].","line":1,"col":190}],"type":"parsing_exception","reason":"Unknown key for a START_OBJECT in [filter].","line":1,"col":190},"status":400}
```

**Comment by sebolek** [comment]
I'm having exact same issue "Unknown key for a START_OBJECT in [filter]." any update on this yet?

**Comment by LucaWintergerst** [comment]
I just pushed a PR for the filter issue.

https://github.com/searchkit/searchkit/pull/363

You can change the file yourself until the PR is accepted.

Disclaimer: I did not test all scenarios, I really only tested the faceting since that was something I was working on right now

**Comment by joemcelroy** [comment]
this change @LucaWintergerst is now available in `1.0.0-4`.

**Comment by LucaWintergerst** [comment]
Thanks for taking over 👍

**Comment by thomasmodeneis** [comment]
Hi,
I'm using 2.3.0-6 and when using a RefinementListFilter together with EL 5.x its returning me a error. 
I'm not sure how to deal with the provided fix, is there any example for it ?

```
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [nick] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"test","node":"iKR72_FEQNeN1NbfFVcmPg","reason":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [nick] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}}]},"status":400}
```

Thanks.

**Comment by joemcelroy** [comment]
The field needs to be of type `keyword`https://www.elastic.co/guide/en/elasticsearch/reference/5.6/keyword.html

**Comment by thomasmodeneis** [comment]
I see now, thanks for the heads-up :D
