### ISSUE TITLE
How to get RefinementListFilters to use reverse_aggregation for nested values?

### ISSUE THREAD

**Issue by PAK90** [searchkit/searchkit#351]
I have a `nested` property in my mapping, and it's great that I can use it with RefinementListFilters (as discussed here http://docs.searchkit.co/stable/docs/core/FieldOptions.html). However, the aggregations it returns are aggregating on all the `inner_hits` of the returned docs, not the docs themselves, so I end up with counts that are too high. Is there a way to pass `reverse_aggregation` as an option to the aggs part of the query? From my reading of the ES docs, that's the way to get it to aggregate on the parent docs instead of the `inner_hits`.

**Comment by timtutt** [comment]
Was this issue every addressed or did it die. Looking for a solution to this myself.

**Comment by ssetem** [comment]
I am unfamiliar with this feature, I need more concrete es query examples, before and after.

**Comment by timtutt** [comment]
Sure  - I mentioned this in the gitter chat a while back - Here is what my mapping looks like:

```
"user": {
//....
"name": {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          },
"skills": {
            "type": "nested"
          },
//...
}
```

The problem I'm having is with aggregations and the Refinement component with the Skills nested object in particular, the component returns the counts for the nested documents, but does not provide the parent doc counts (which is what i actually want to display)


This is doable by using the reverse_nested{} agg like so:

```
"aggs": {
    "nestedSkills": {
      "nested": {
        "path": "skills"
      },
      "aggs": {
        "skillNames": {
          "terms": {
            "field": "skills.name.keyword",
            "size": 100
          },
          "aggs": {
            "parentCount": {
              "reverse_nested": {}
            }
          }
        },
        "skillXP": {
          "terms": {
            "field": "skills.experience.keyword",
            "size": 100
          },
          "aggs": {
            "parentCount": {
              "reverse_nested": {}
            }
          }
        }
      }
    }
  }
```

Would be nice if one of the field options was to return the parent count perhaps? I'm not entirely sure how to extend the RefinementListFilter to include the nested sub agg. I don't mind doing the work and submitting the PR, but would need a little guidance on the how.

**Comment by ssetem** [comment]
thanks,

A couple of things which would help alot, is if you paste the agg query without reverse, and then adding reverse query, i think thats what you also pasted.

The next thing that would help is if there was a public ES index with data and mapping, so its easy to ensure we adding correct feature.

Thanks

**Comment by timtutt** [comment]
Sure thing - updated the comment. I don't currently have a public ES index with data and mapping. Will have to generate something sharable.

**Comment by ssetem** [comment]
looks good, i think FieldOptions would likely need a new type to handle this., once there is public index with expected result described, i can try and add it

**Comment by timtutt** [comment]
@ssetem  - sorry for just getting back to you. There's a publicly accessible index located here:

http://ec2-54-84-225-235.compute-1.amazonaws.com:8080/

**Comment by timtutt** [comment]
@ssetem - Was wondering if there's any update on this. Is there anything I can do to assist with testing/dev?
