### ISSUE TITLE
Query for start and end date 

### ISSUE THREAD

**Issue by infacq** [searchkit/searchkit#352]
<img width="628" alt="screen shot 2016-11-03 at 12 27 46 pm" src="https://cloud.githubusercontent.com/assets/1596891/19955921/3ea9be7c-a1c1-11e6-8c71-e59613ecc1c9.png">

how do I get this to connect to ES using searchkit

**Comment by alx** [comment]
There is this `searchkit-daterangefilter` component available:

https://github.com/GregoryPotdevin/searchkit-daterangefilter/

**Comment by PAK90** [comment]
@alx It is available but it's purely a slider, no date picker. Makes it a lot harder to use.

**Comment by infacq** [comment]
@GregoryPotdevin can help?

**Comment by GregoryPotdevin** [comment]
@infacq Sure. I've been wanting to improve on this for a while but have been stuck on other projects. Do you need any pointers ?

**Comment by infacq** [comment]
yes sure

**Comment by drekli** [comment]
I also need a datepicker like this, been checking in to see if the conversation as progressed anywhere yet?

If the pointers can be added to this ticket, I'm happy to try and help out too.

**Comment by drekli** [comment]
Hi @infacq and @GregoryPotdevin... Did you discuss the pointers off record yet?

**Comment by joemcelroy** [comment]
#24 tracked in here. Closing this issue
