### ISSUE TITLE
React 15.4 compatibility

### ISSUE THREAD

**Issue by aliceriot** [searchkit/searchkit#354]
Hey y'all,

I'm working on upgrading to React 15.4 and having some issues with Searchkit. Basically, I'm getting warnings of this type:  [https://facebook.github.io/react/warnings/dont-call-proptypes.html]() which are, I think, being driven by some of the dependencies searchkit pulls in (specifically `rc-slider` is one I've diagnosed).

Is there a timeline for React 15.4 support? These warnings are going to become errors in React 16, so while it's not super essential to fix right now it would be good to know!

thanks!

**Comment by thomasmodeneis** [comment]
@aliceriot I believe https://github.com/searchkit/searchkit/pull/369 will address this and other issues related to 15+

**Comment by aliceriot** [comment]
It looks like it will! We're getting build failures on Heroku related to this problem now, so it would be :100: to see that get merged.

**Comment by joemcelroy** [comment]
15.4 support is in the beta release. If you spot any warnings, I welcome any PR fixes 👍

**Comment by bcruddy** [comment]
I'm seeing this warning in react 15.5.4 with searchkit 2.0.0-9

` Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

I'd be happy to put up a PR but I don't want to do duplicate work if someone else is already handling it.
