### ISSUE TITLE
Cannot install searchkit with npm

### ISSUE THREAD

**Issue by pcolmer** [searchkit/searchkit#358]
I get the following error when trying to install searchkit with npm:

npm ERR! Error: No compatible version found: qs@'ssetem/qs'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.1.0","0.2.0","0.3.0","0.3.1","0.3.2","0.4.0","0.4.1","0.4.2","0.5.0","0.5.1","0.5.2","0.5.3","0.5.4","0.5.5","0.5.6","0.6.0","0.6.1","0.6.2","0.6.3","0.6.4","0.6.5","0.6.6","1.0.0","1.0.1","1.0.2","1.1.0","1.2.0","1.2.1","1.2.2","2.0.0","2.1.0","2.2.0","2.2.1","2.2.2","2.2.3","2.2.4","2.2.5","2.3.0","2.3.1","2.3.2","2.3.3","2.4.0","2.4.1","2.4.2","3.0.0","3.1.0","4.0.0","5.0.0","5.1.0","5.2.0","6.0.0","6.0.1","6.0.2","6.1.0","6.2.0","5.2.1","6.2.1","6.3.0"]

Being a complete newbie with npm, I have no idea how to fix this :(

This is on ubuntu 14.04.

**Comment by PAK90** [comment]
What's the command you're running? Is it simply `npm install searchkit`?

**Comment by pcolmer** [comment]
It is actually "sudo npm install searchkit --save" but leaving "--save" off doesn't make any difference.

**Comment by joemcelroy** [comment]
could you check the version of npm you are using? We support npm v3.

**Comment by pcolmer** [comment]
Thanks - that was it. Ubuntu ships (by default) with a really old version of npm. After updating it *any* nodejs, I've managed to get searchkit to install.
