### ISSUE TITLE
Searchkit is not accessible

### ISSUE THREAD

**Issue by singingwolfboy** [searchkit/searchkit#359]
Searchkit looks and works great for sighted users who can use a mouse, but not everyone is in that situation. In order to be accessible to a wider audience, Searchkit should have the following features:

* The UI should be fully navigable using only a keyboard.
* Any text elements that respond to mouse clicks should be [`<button>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button) elements, so that the browser knows that they should be focusable when tabbing through the page. (They can be styled using CSS so that they don't visually appear to be buttons, if that is preferred.)
* All checkboxes and other input elements should have associated [`<label>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label) elements, so that screen readers can announce what the checkbox is for.
* Lists should use `<ul>` or `<ol>` elements, and list items should use `<li>` elements. (This allows a screen reader to announce how long the list is.)
* Lists of options should be grouped using a [`<fieldset>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset) element, and the list header should be a [`<legend>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/legend) element in that `<fieldset>`.

I'm happy to provide more information or help out with this effort, if the Searchkit team is open to these changes.

**Comment by joemcelroy** [comment]
Thanks for this issue. Would be great if you could start a PR for these changes and we can review them 👍

**Comment by benjamingrobertson** [comment]
@joemcelroy are you still open for PR's related to some of the issues mentioned above?

**Comment by joemcelroy** [comment]
sure @benjamingrobertson!
