### ISSUE TITLE
Unknown Prop Warning in NumberInput

### ISSUE THREAD

**Issue by yih-en** [searchkit/searchkit#367]
Hi there,

I encounter this warning while using ```RangeSliderHistogramInput``` :

<img width="1435" alt="screen shot 2017-01-02 at 3 24 02 pm" src="https://cloud.githubusercontent.com/assets/21019282/21586511/df637400-d10c-11e6-9dc3-e29ea37356f3.png">

This is not happening when I use ```RangeSliderHistogram```.

Any idea how I can fix the warning? Thanks!

**Comment by joemcelroy** [comment]
Thanks, il take a look at this.

**Comment by juan-fdz-hawa** [comment]
Hi Joe,

Have you started working on this?

If not, I'll see if I can take a look tonight.

**Comment by joemcelroy** [comment]
Yeh sorry, working on something else for Searchkit. Would be great if you could do a PR for this!

**Comment by juan-fdz-hawa** [comment]
Seems like this issue has been fixed on Beta release 1.0.0-2 [(take a look here)](https://github.com/searchkit/searchkit/commit/a9b5abd2a17ac45c7e1eecf4c29f52ca18e6afe8#diff-9d9508f6e97fcd4877a4bfb130297b6c) 

Yih-en, this should be fixed once 1.0.0 is released, so hang in there!

**Comment by yih-en** [comment]
Thanks:)

**Comment by joemcelroy** [comment]
you can also use the betas `npm install searchkit@1.0.0-7`. They are pretty stable. Soon we will be doing RCs
