### ISSUE TITLE
Highlight Fragment Size

### ISSUE THREAD

**Issue by MyraBaba** [searchkit/searchkit#371]
Hi,

I didnt find a way to ask highlighted and fragment_size ' ed solution in the search box 

I dont know is it the right place to ask.

`{
    "_source": ["indexDate", "title", "url"],
    "query" : {
        "match": { "content": "patlama" }
    },
    "highlight" : {
        "fields" : {
            "content" : {"fragment_size" : 350, "number_of_fragments" : 3}
        }
    }
}`

**Comment by ppearcy** [comment]
This PR should add support once merged:
https://github.com/searchkit/searchkit/pull/355
