### ISSUE TITLE
More 'universal' for different API's

### ISSUE THREAD

**Issue by yarnball** [searchkit/searchkit#373]
Hi,

Very nice work on this kit.

I'd like it to be a little more "adaptable".

Basically, I want to make it more usable for a variety of API's.

The main issue is here (https://github.com/searchkit/searchkit-boilerplate/blob/master/src/SearchPage.jsx#L16)

`const searchkit = new SearchkitManager(host)`

Even if it slows it down/stops search working properly- it means the user can much more quickly get this up and running to filter/sort results very nicely.

Any ideas on how to remove that?

**Comment by joemcelroy** [comment]
hey, we have been talking about this alot lately and want to address this in the future, able for searchkit to be powered by an extension of ES ie your API. Big change however and needs alot of thought.
