### ISSUE TITLE
Using with rollup

### ISSUE THREAD

**Issue by sadovnychyi** [searchkit/searchkit#374]
I've tried to import it using [rollup](https://github.com/rollup/rollup) and my bundle got super huge since many node related dependencies were included.

Did anybody get it working? It's definitely needs some proper configuration, but I'm not experienced enough.

**Comment by sadovnychyi** [comment]
https://github.com/rollup/rollup-plugin-commonjs/issues/105.

**Comment by ssetem** [comment]
@sadovnychyi yet to try rollup with searchkit, hopefully we can take a look soon
