### ISSUE TITLE
Invariant Violation: addComponentAsRefTo while building

### ISSUE THREAD

**Issue by mbm-rafal** [searchkit/searchkit#375]
Invariant Violation: addComponentAsRefTo while building searchkit

v0.10.1

Case is that if I build with:
searchkit/src/core/react/SearchkitProvider.tsx

```
export class SearchkitProvider extends React.Component<SearchkitProps,any> {
	render(){
		return (
			<div>asdasd</div>
		);
	}
}

```

using by

```
return (
        <div>
        <SearchkitProvider searchkit={searchkit}>
            <div>
              ssss
            </div>
          </SearchkitProvider>          
          </div>
      );
```

I get proper response, but If I change source to 

```

export class SearchkitProvider extends React.Component<SearchkitProps,any> {
	render(){
		return (
			<div><input ref="asdasd" /></div>
		);
	}
}
```

i get error Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded

**Comment by joepsz** [comment]
I had a similar error.

This often means that multiple React instances were loaded. 

We managed to solve this by explicitly importing one single version of react:

```` javascript
// In webpack.config.js

  resolve: {
    alias: {
      react: path.resolve('node_modules/react/react.js'),
    },
  },
````

**Comment by mbm-rafal** [comment]
@joemcelroy please advise

**Comment by joemcelroy** [comment]
We encountered this issue aswell and as joepsz mentioned the workaround is being explicit with the react import. We are looking at why its importing multiple now.

**Comment by inostia** [comment]
@joepsz that path did not work for me. I needed `node_modules/react`. 

Haven't tested fully but before I was getting `Cannot resolve 'file' or 'directory' [...]/node_modules/react/react.js/lib/ReactDOM` errors when compiling webpack.

**Comment by mbm-rafal** [comment]
Same issue on develop branch atm. Resolve alias did not fix issue.

**Comment by ssetem** [comment]
@mbm-rafal have you got example usage project so we can replicate?

**Comment by joemcelroy** [comment]
OK i got a starter project based off `create-react-app` and using beta-4. This doesn't have the multiple ref issue. https://github.com/searchkit/searchkit-starter-app

**Comment by vincentfretin** [comment]
I got the same error some days ago where I had in package.json "searchkit": "^1.0.0-4" and it actually installed a old? version (in src: common, components, domain folders). Fixing "searchkit": "1.0.0-4" (without the ^) in package.json fixed the issue for me.

**Comment by joemcelroy** [comment]
im going to close this issue for now as cant replicate it within our starter-app boilerplate with latest and this issue does crop up on other UI frameworks

**Comment by mbm-rafal** [comment]
@joemcelroy weird. I'm still getting this error.

![image](https://cloud.githubusercontent.com/assets/19263109/23077437/d2f58404-f544-11e6-956e-47c4f7e0d6d8.png)

**Comment by joemcelroy** [comment]
which project are you using? I suggest you use the starter-app one.

**Comment by mbm-rafal** [comment]
I forked 1.0.0-4 and applied some default usage isn't that starter-app ?
