### ISSUE TITLE
[Feature] Shared Accessor

### ISSUE THREAD

**Issue by mbm-rafal** [searchkit/searchkit#379]
@joemcelroy @ssetem 

At this point different components are using their own accessors, when they only applies query and filters through buildOwnQuery / buildSharedQuery methods. The case is to share accessor between search components to apply valid filter related to same field/or nested one.

```
<RefinementListFilter
  id="event_name"
  title="Events"
  operator="AND"
  field="events.name"
  fieldOptions={{
    type:'nested',
    options:{
      path:'events'
    }
  }} />
```

and

```
<MenuFilter
    id="role"
    title="Role"
    field="events.role.name"
    showCount={true}
    fieldOptions={{
      type:'nested',
      options:{
        path:'events.role'
      }
    }}
    listComponent={Tabs}
/>
```

will not build a proper filter. Even through the nestedfacetaccessor must be available so that this could be built in reliable way.

**Comment by ssetem** [comment]
@mbm-rafal 
Accessors would be shared if same type of accessor is used with same id field.

I need to take a look more at the nested query stuff so it builds query more like how you want.

As soon as we finish some house cleaning on the repo, I will take a look at enhancing these features.

Might ping you on gitter when I get round to this

**Comment by mbm-rafal** [comment]
@ssetem it does not seem this works as expected. I'm reconsidering flattening structure.
