### ISSUE TITLE
[Feature] SearchBox debounce feature

### ISSUE THREAD

**Issue by mbm-rafal** [searchkit/searchkit#380]
Configureable timeout for executing query, so that user can setup all attributes without experiencing search while he does not want to. Instant search perform is not always expected.

Also would be nice to provide manual trigger for search.

**Comment by ssetem** [comment]
@mbm-rafal dunno if follow configurations help.
- `searchThrottleTime` prop for SearchBox
- `searchOnLoad` prop to SearchkitManager
- `searchkitInstance.performSearch()` for manual trigger
