### ISSUE TITLE
ElesticSearch 5.1 support

### ISSUE THREAD

**Issue by MyraBaba** [searchkit/searchkit#381]
Is searchkit supporting ES 5.1  version ?

**Comment by joemcelroy** [comment]
That's the plan for the next release :-)

**Comment by MyraBaba** [comment]
when we could expect :)

**Comment by joemcelroy** [comment]
Soon, prepping up a beta now. Should be available in next couple of weeks

**Comment by MyraBaba** [comment]
any news for ES 5  support :)

**Comment by joemcelroy** [comment]
for now use this hotfix detailed here #363 . I haven't yet got a ES5 env to test with yet. Once i do, il do another beta release for it.

**Comment by joemcelroy** [comment]
Those changes were merged and released `1.0.0-4`. Should be ready for you to try out!

**Comment by MyraBaba** [comment]
I will try..

there is only 

#363
+      query.post_filter = BoolMust(this.index.filters)

changes as far as I saw.


thx

**Comment by MyraBaba** [comment]
bythe way have you any idea for :  

#382


thx

**Comment by joemcelroy** [comment]
so these changes we are doing for searchkit beta is only compatibility for ES 5, not adding features which ES5 now has.

**Comment by joemcelroy** [comment]
closing issue for now. Report any issues with ES5 and il raise a new issue.
