### ISSUE TITLE
Improving aggregations and filtering performance

### ISSUE THREAD

**Issue by sadovnychyi** [searchkit/searchkit#386]
I got pretty bad performance when I turned searchkit on production index with ~1M documents and ~20 tags per document. But here's good news – I managed to improve it by up to 11 times (from tens of seconds to under a second). I do understand that you can just make your cluster bigger but it seems like waste of resources. So the bottleneck is how most of aggregations are made, e.g. by `RefinementListFilter`:

```json
{
  "aggs": {
    "actors.raw6": {
      "filter": {},
      "aggs": {
        "actors.raw": {
          "terms": {
            "field": "actors.raw",
            "size": 10
          }
        },
        "actors.raw_count": {
          "cardinality": {
            "field": "actors.raw"
          }
        }
      }
    }
  }
}
```

When you apply filters – aggregations are filtered individually, instead of filtering all documents to make search request much lighter, we also have another aggregation here to count number of documents to provide pagination – which is very useful, but we don't really need another aggregation for it.

Improved query with applied filter:
```json
{
  "aggs": {
    "actors.raw6": {
      "terms": {
        "field": "actors.raw",
        "size": 10
      }
    }
  },
  "query": {
    "bool": {
      "filter": [{
        "term": {
          "actors.raw": "Naveen Andrews"
        }
      }]
    }
  }
}
```

This provides filtering for both aggregations and documents (before we have `post_filter` applied to filter out the documents).
The workaround for pagination is to use `sum_other_doc_count` value provided for each aggregation. It's going to be zero if there's no more possible aggregations, and going to be some other number if there is. It's likely that we won't be able to correctly display `View all`, but we will be able to display `View more` and `View less` when it's zero, and it's more than enough.

I don't know about other use cases for those additional aggregations, but I think it's should be possible to avoid them, at least with dedicated component. I'm providing the code that I use to build a custom component below. I did similar RangeAccessor modifications as well. Note that all this applied only for "AND" queries, I have no idea about "OR".

Would you consider improving this either by improving existing components or by adding additional ones e.g. `HighPerformanceRefinementListFilter` or something?

```javascript
import {map, omitBy, isUndefined, isEmpty, isArray, filter} from 'lodash'
import {FacetAccessor, TermsBucket, TermQuery, RefinementListFilter} from 'searchkit'


function BoolFilter(val) {
  if (isArray(val)) {
    // Remove empty filters
    val = filter(val, f => !isEmpty(f))
    if (val.length === 0) {
      return {}
    }
  }
  return {
    bool: {
      'filter': val
    }
  }
}


class CustomFacetAccessor extends FacetAccessor {
  getRawBuckets() {
    return this.getAggregations([
      this.uuid,
      this.fieldContext.getAggregationPath(),
      'buckets'], [])
  }

  getDocCount() {
    // not used at all afaik
    return this.getCount()
  }

  getCount() {
    return this.getAggregations([
      this.uuid,
      this.fieldContext.getAggregationPath(),
      'sum_other_doc_count'], 0)
  }

  buildSharedQuery(query) {
    var filters = this.state.getValue()
    var filterTerms = map(filters, (filter)=> {
      return this.fieldContext.wrapFilter(TermQuery(this.key, filter))
    })
    var selectedFilters = map(filters, (filter) => {
      return {
        name: this.options.title || this.translate(this.key),
        value: this.translate(filter),
        id: this.options.id,
        remove: () => this.state = this.state.remove(filter)
      }
    })
    if (filterTerms.length > 0) {
      query = query.addQuery(BoolFilter(filterTerms))
        .addSelectedFilters(selectedFilters)
    }
    return query
  }

  buildOwnQuery(query) {
    if (!this.loadAggregations){
      return query
    } else {
      return query
        .setAggs(TermsBucket(
          this.uuid,
          this.key,
          omitBy({
            size: this.size,
            order: this.getOrder(),
            include: this.options.include,
            exclude: this.options.exclude,
            min_doc_count: this.options.min_doc_count
          }, isUndefined)))
    }
  }
}


export class CustomRefinementListFilter extends RefinementListFilter {
  accessor: CustomFacetAccessor

  defineAccessor() {
    return new CustomFacetAccessor(
      this.props.field, this.getAccessorOptions())
  }
}
```

**Comment by joemcelroy** [comment]
thanks for creating this issue. Its definitely one thing we want to look at. il take a look at your findings soon.

**Comment by ssetem** [comment]
@sadovnychyi  we got some old commit with a similar optimisation, where we would pull up all common aggregator queries from post_filter to query.filter, definitely will improve performance, we just need to make sure there is no knockon effects etc, I like the optimisation for pagination on aggregators

**Comment by sadovnychyi** [comment]
@ssetem Well for example for RefinementFilter with Tabs I had to make a global aggregation filtering it by whole current query except the filter produced by itself. So yeah, it's definitely not a simple fix.
