### ISSUE TITLE
How to use ref for component

### ISSUE THREAD

**Issue by infacq** [searchkit/searchkit#387]
Let's say I  use theme and I want to ref on `SideBar` like this

```js
<SideBar ref={(el) => this.SideBar = el}>...</SideBar>
```

but this cannot be achieve. How to get ref for such component

**Comment by joemcelroy** [comment]
what is the reason for needing a reference to the sidebar element?

**Comment by infacq** [comment]
to toggle hide/show in mobile mode

**Comment by joemcelroy** [comment]
what about omiting the `SideBar` component in React when closed? for example `{ this.state.showSideBar && <SideBar ... /> }`

**Comment by GregoryPotdevin** [comment]
@joemcelroy You can't really do that as the SideBar has some filters as children, and hiding it would remove the children and the corresponding accessors. That could have unexpected results when running a new query and then showing the sidebar

What you do want, though, is to have all the prebuilt components that work like plain "div" elements with custom presets.

This is your current LayoutBuilder :
```jsx
export const LayoutBuilder = (className)=> {
  return (props)=> (
      <div className={mixClasses(className, props.className)}>
        {props.children}
      </div>
  )
}
```

It doesn't allow adding style or other attributes. What would be better is something like 
```jsx
export const LayoutBuilder = (baseClassName)=> {
  return ({className, children, ...props})=> (
      <div className={mixClasses(baseClassName, className) {...props}}>
        {props.children}
      </div>
  )
}
```

With something like this (untested) all the extra props get transfered to the div. So now you can add a ref or `style={{display: 'none'}}` (I wouldn't recommend using the ref for that, it's always better to stay in the React world)

**Comment by infacq** [comment]
ohh just pass the props. Hopefully can see this in all components

**Comment by joemcelroy** [comment]
yep thats true, yeh we need to extend the layoutbuilder component to past the props to the div element. You could also wrap the sidebar in a div and toggle the class / style properties depending on state.

not the best as its doing the aggregations always even when hidden.

**Comment by joemcelroy** [comment]
closing this issue

**Comment by infacq** [comment]
So I have to produce extra div?
