### ISSUE TITLE
Invalid 'reference' directive syntax with xenon build

### ISSUE THREAD

**Issue by mbm-rafal** [searchkit/searchkit#393]
```
ERROR in /Users/rafal/Documents/Work/mybusinessmatches/laravel/node_modules/searchkit/node_modules/xenon/lib/src/components/Component.d.ts
(1,1): error TS1084: Invalid 'reference' directive syntax.
```

➜  searchkit git:(develop-beta-release) ✗ npm list | grep xenon
└── xenon@0.1.5

had to remove first line in file.

**Comment by joemcelroy** [comment]
Thanks Rafal. How did you get this error? on build?

**Comment by mbm-rafal** [comment]
Yes, I had this before. Seems like typescript version missmatch. 
I've pruned and reinstalled all deps so it cannot be reproduced.
