### ISSUE TITLE
Pagination pages

### ISSUE THREAD

**Issue by joemcelroy** [searchkit/searchkit#40]
- [x] Show pages as options to select from
- [x] Unit tests
- [x] Documentation

**Comment by hkirsman** [comment]
Do I understand correctly that this was closed although "Pagination should use links " was not dealt with?

**Comment by ssetem** [comment]
yes looks like it, do you need the Pagination as links functionality?

**Comment by hkirsman** [comment]
I don't need it for my project but I think it's important to have for usability. If you're blind you won't be using mouse. You'll be tab'ing through the site and you can't focus div's. Try it out yourself at http://demo.searchkit.co/imdb. You can't go to next page with keyboard.

**Comment by ssetem** [comment]
yep we can put it on the backlog and if we get more votes we can prioritise accordingly
