### ISSUE TITLE
Invariant Violation: addComponentAsRefTo when using SearchBox

### ISSUE THREAD

**Issue by mbm-rafal** [searchkit/searchkit#400]
Searchkit: 1.0.0-7
I had to rebuild it with aliases for react.
```
resolve: {
    alias: {
      react: path.resolve('../react'),
    },
    extensions:[".js", ".ts", ".tsx","", ".webpack.js", ".web.js", ".scss"]
  },
```

I have this error, but commenting:
https://github.com/mbm-rafal/searchkit/blob/6185a817106eca985ac0e1ba3224efca4da1a3b9/src/components/search/search-box/SearchBox.tsx:169 fixed issue.

**Update:** 

I'm getting this error as well using RangeFilter, but there is no `ref` param

**Comment by joemcelroy** [comment]
lets take this up on gitter. I believe its an issue with your setup.

**Comment by aabanaag** [comment]
Hi, I know this is closed but looking at gitter either I couldn't back track to the solution. I encountered the same error when adding <code>SearchBox /></code> into my code. Its in meteor + react.

**Comment by joemcelroy** [comment]
This is due to webpack loading two versions of react. Try using the beta version of searchkit `npm install searchkit@2.0.0-9` or using this project (https://github.com/searchkit/searchkit-starter-app) as a starter boilerplate.

**Comment by aabanaag** [comment]
Thanks! 👍
