### ISSUE TITLE
How to access query string?

### ISSUE THREAD

**Issue by radomirml** [searchkit/searchkit#401]
I'm working on integration of PDF Highlighter with SearchKit and need to access query string. What's the best way to do that?

Do I need to create a component that extends SearchkitComponent or is there a simpler way around?

**Comment by ssetem** [comment]
if you want to read the query string, the state might be good to read.

```js
searchkitInstance.accessors.getState()
```

if you need to write to the query, you will need to implement a subclass of StatefulAccessor

**Comment by radomirml** [comment]
Thanks @ssetem , I've found similar approach:

`searchkitInstance.getQueryAccessor().getQueryString()`
