### ISSUE TITLE
Question: Pagination listComponent

### ISSUE THREAD

**Issue by florianbepunkt** [searchkit/searchkit#402]
Thank you for this library. I'm having troubel understanding the docs for pagination.

I need a custom compoent for rendering the pagination. The rendering itself works fine, but the functionality is gone. Clicking on pagination links does nothing. Can you point me to the right docs or explain how to proceed?

Here's what I have so far

in my parent component…
`<Pagination showNumbers={true} listComponent={ Pagi }/>`

my custom pagination list component
```
class Pagi extends SearchkitComponent {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <div className="pagination">
        {this.props.items.map((item) => {
          return (
            <div className="page-item" key={ item.key }>
              <a className="page-link">{ item.label}</a>
            </div>
          );
        })}
      </div>
    );
  }
}
```

**Comment by ssetem** [comment]
need to use onclick like this
onClick={()=> this.props.toggleItem(item.key)}

**Comment by florianbepunkt** [comment]
@ssetem Thank you!
