### ISSUE TITLE
Cannot use searchkit in typescript when outputting ES6

### ISSUE THREAD

**Issue by davireis** [searchkit/searchkit#404]
When you use the `compilerOptions.target = ES6` in your tsconfig.json, tsc will bundle some definitions by itself, including the definition of Promise, which will be duplicate with the one provided by `@types/es6-promise`.

See the discussion here for the same thing happening with angular2: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/5015

And check here for a minimal repro (simply run `npm install && tsc`): https://github.com/davireis/searchkit/tree/tsclient

I believe that either making `@types/es6-promise` a peer or a dev dependency would be good options.

**Comment by ssetem** [comment]
thanks @davireis I will take a look, thanks for providing that repo

**Comment by sheilagithub** [comment]
Any updates on this?  Is there a workaround?

**Comment by ssetem** [comment]
we are removing es6-promise + polyfil from our library.
and expect downstream bundlers to solve

will be part of 2.3.0
