### ISSUE TITLE
Please bump version above 1.0.1

### ISSUE THREAD

**Issue by davireis** [searchkit/searchkit#405]
Unfortunately it seems that searchkit was released as 1.0.1 in npm by the end of 2015:

https://libraries.io/npm/searchkit

This can easily be fixed by pinning the version in package.json, like `"searchkit": "1.0.0-6"`, but things get very confusing when you use the more usual syntax `"searchkit": "^1.0.0-6"` and end up with a very old version of the library.

If the current beta gets promoted to version 1.0.2 or 2.0.0, or if that old dangling version gets killed, I believe you will save your clients a lot of time.

**Comment by joemcelroy** [comment]
thanks for the heads up. Il take a look

**Comment by ssetem** [comment]
@davireis thanks for raising, I think 2.x will likely be version we go with

**Comment by joemcelroy** [comment]
done
