### ISSUE TITLE
RefinementListFilter with nested field gives error when an item selected

### ISSUE THREAD

**Issue by Alfreddd** [searchkit/searchkit#406]
searchkit: v1.0.0-7
ES: 5.x

Error from ES `[nested] query does not support [filter]`.

Part of the Query generated when an item selected from the RefinementList looks like
```
    "nested": {
        "path": "actors",
        "filter": {
            "term": {
                "actors.name": "foo bar"
            }
        }
    }
```

Googling the issue showed that [The nested filter has been replaced by the Nested Query](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/query-dsl-nested-filter.html)

**Comment by joemcelroy** [comment]
thanks, il take a look.

**Comment by Alfreddd** [comment]
Just a note, the issue is not just limited to RefinementListFilter but also MenuFilter.

example of using the component that when selecting an item from the list yields the error
```
<Searchkit.MenuFilter
    field="actors.name"
    fieldOptions={{"type":"nested", "options": {"path":"actors"}}}
    title="Actors"
    listComponent={Searchkit.Select}
    id="type"/>
```

**Comment by joemcelroy** [comment]
this should be fixed in #413 . Il do a beta release soon with this fix.

**Comment by Alfreddd** [comment]
Brilliant!

**Comment by Alfreddd** [comment]
Any news on a beta release coming soon ?

**Comment by joemcelroy** [comment]
hey @Alfreddd sorry for delay, was waiting on an issue before releasing. I made a new release, `searchkit@2.0.0-9`. Let me know if this remains an issue and il take a look to see anywhere else that needs fixing.

Thanks

**Comment by Alfreddd** [comment]
Thanks!
