### ISSUE TITLE
trouble with npm install searchkit

### ISSUE THREAD

**Issue by wagger301** [searchkit/searchkit#418]
When running npm install searchkit lags after "npm verb afterAdd" and won't finish.

**Comment by joemcelroy** [comment]
Which version of npm are you using? Turn on additional logging whilst installing to see if can indicate any issues.

**Comment by giskarda** [comment]
```
➔  npm --version
4.1.2
➔
```

...incredible amount of noise...
web-search@0.1.0 /Users/giskard/src/github.com/giskarda/totc/web-search
└─┬ searchkit@0.10.1
  ├── qs@6.0.1  (git://github.com/ssetem/qs.git#fb2b80ac750fa375e0d69643adb0840e7e04d1d3)
  └── UNMET PEER DEPENDENCY react@0.14.8

npm WARN react-addons-update@0.14.8 requires a peer of react@^0.14.8 but none was installed.

My understanding from that line, but keep in mind I have no clue about how versioning is done via npm, is that the project requires a specific version of react instead of >= or maybe this is intentional and searchkit support only 0.14.8

```
➔  npm list  | grep react
├─┬ react@15.4.2
├── react-dom@15.4.2
├─┬ react-scripts@0.9.5
```

**Comment by joemcelroy** [comment]
The newer beta release supports the latest version of react. You can install it via `npm install searchkit@1.0.0-7`

**Comment by giskarda** [comment]
can confirm I was able to install it using that specific release.

**Comment by joemcelroy** [comment]
Great! The beta will be out shortly, its probably catching alot of people out.

**Comment by wagger301** [comment]
why was this closed? I've already tried installing the beta (npm install searchkit@1.0.0-7) and it still stops mid install and hangs.

The end of my log:

npm verb afterAdd ~/.npm/@types/react-router/2.0.49/package/package.json not in flight; writing
npm verb correctMkdir ~/.npm correctMkdir not in flight; initializing
npm sill cache afterAdd @types/react-dom@0.14.23
npm verb afterAdd ~/.npm/@types/react-dom/0.14.23/package/package.json not in flight; writing
npm verb correctMkdir ~/.npm correctMkdir not in flight; initializing
npm sill cache afterAdd @types/source-map@0.5.0
npm verb afterAdd ~/.npm/@types/source-map/0.5.0/package/package.json not in flight; writing
npm verb correctMkdir ~/.npm correctMkdir not in flight; initializing
npm sill cache afterAdd @types/jasmine@2.5.45
npm verb afterAdd ~/.npm/@types/jasmine/2.5.45/package/package.json not in flight; writing
npm verb correctMkdir ~/.npm correctMkdir not in flight; initializing
npm sill cache afterAdd @types/enzyme@2.7.5
npm verb afterAdd ~/.npm/@types/enzyme/2.7.5/package/package.json not in flight; writing
npm verb correctMkdir ~/.npm correctMkdir not in flight; initializing
npm sill cache afterAdd @types/react-addons-create-fragment@0.14.16
npm verb afterAdd ~/.npm/@types/react-addons-create-fragment/0.14.16/package/package.json not in flight; writing
npm verb correctMkdir ~/.npm correctMkdir not in flight; initializing
npm sill cache afterAdd @types/sinon@1.16.35
npm verb afterAdd ~/.npm/@types/sinon/1.16.35/package/package.json not in flight; writing
npm verb correctMkdir ~/.npm correctMkdir not in flight; initializing
npm sill cache afterAdd @types/history@2.0.48
npm verb afterAdd ~/.npm/@types/history/2.0.48/package/package.json not in flight; writing
npm verb correctMkdir ~/.npm correctMkdir not in flight; initializing
npm sill cache afterAdd @types/lodash@4.14.55
npm verb afterAdd ~/.npm/@types/lodash/4.14.55/package/package.json not in flight; writing
npm verb correctMkdir ~/.npm correctMkdir not in flight; initializing
npm sill cache afterAdd @types/classnames@0.0.32
npm verb afterAdd ~/.npm/@types/classnames/0.0.32/package/package.json not in flight; writing
npm verb correctMkdir ~/.npm correctMkdir not in flight; initializing
npm sill cache afterAdd @types/jasmine-ajax@3.1.33
npm verb afterAdd ~/.npm/@types/jasmine-ajax/3.1.33/package/package.json not in flight; writing
npm verb correctMkdir ~/.npm correctMkdir not in flight; initializing
npm sill cache afterAdd @types/react@0.0.0
npm verb afterAdd ~/.npm/@types/react/0.0.0/package/package.json not in flight; writing
npm verb correctMkdir ~/.npm correctMkdir not in flight; initializing
npm verb afterAdd ~/.npm/@types/es6-promise/0.0.32/package/package.json written
npm verb afterAdd ~/.npm/@types/source-map/0.5.0/package/package.json written
npm verb afterAdd ~/.npm/@types/react-router/2.0.49/package/package.json written
npm verb afterAdd ~/.npm/@types/selenium-webdriver/2.53.42/package/package.json written
npm verb afterAdd ~/.npm/@types/react-dom/0.14.23/package/package.json written
npm verb afterAdd ~/.npm/@types/jasmine/2.5.45/package/package.json written
npm verb afterAdd ~/.npm/@types/enzyme/2.7.5/package/package.json written
npm verb afterAdd ~/.npm/@types/sinon/1.16.35/package/package.json written
npm verb afterAdd ~/.npm/@types/react-addons-create-fragment/0.14.16/package/package.json written
npm verb afterAdd ~/.npm/@types/lodash/4.14.55/package/package.json written
npm verb afterAdd ~/.npm/@types/history/2.0.48/package/package.json written
npm verb afterAdd ~/.npm/@types/classnames/0.0.32/package/package.json written
npm verb afterAdd ~/.npm/@types/jasmine-ajax/3.1.33/package/package.json written
npm verb afterAdd ~/.npm/@types/react/0.0.0/package/package.json written

**Comment by joemcelroy** [comment]
I believe this isn't an issue with searchkit. Google issues with hanging npm and see if you can find out more details of why its hanging. 

Which version of NPM do you use? You can also use yarn to install your dependencies.
