### ISSUE TITLE
npm install searchkit --save fails on a newly freshed create react app

### ISSUE THREAD

**Issue by giskarda** [searchkit/searchkit#419]
Running:
``npm install searchkit --save``

Returns
``npm WARN react-addons-update@0.14.8 requires a peer of react@^0.14.8 but none was installed.``

```
➔  create-react-app --version
1.3.0
➔
```

**Comment by joemcelroy** [comment]
npm install searchkit will install the 0.10 release, not 1.0.0 betas. Have a look at https://github.com/searchkit/searchkit-starter-app
