### ISSUE TITLE
[Feature] defineAccessor() as Filter option

### ISSUE THREAD

**Issue by mbm-rafal** [searchkit/searchkit#420]
I'd like to provide different accessor for specific Filter Component without having to extending Filter class with overloaded defineAccessor() method.

@ssetem  @joemcelroy  how do you think about that ? I could implement this.

**Comment by ssetem** [comment]
@mbm-rafal , this is a good idea, will just need to think on  how to make consistent across all components, as it would be nice to dynamically pass accessor in consistent way

**Comment by mbm-rafal** [comment]
@ssetem Great! let me do a proposal
