### ISSUE TITLE
Numeric Range Filter Does Not Support Floating Point Numbers

### ISSUE THREAD

**Issue by timtutt** [searchkit/searchkit#422]
Attempting to use the RangeFilter Component on a field that has numeric values between 0.0 and 1.0. I'm setting the Interval component to 0.01 and the histogram shows appropriately, but unfortunately I am unable to use the actual slider. Code sample and image below... Is there something I'm missing or is this a bug in the functionality of the component?

```javascript
<RangeFilter min={0.0} max={1.0} field="myField" id="myField" interval="0.01" title="myField" showHistogram={true}/>
```

![image](https://cloud.githubusercontent.com/assets/1517492/24086148/7394924e-0ce0-11e7-8ae3-c52d2f4e60bb.png)
 
**Edit:**

I'm using version 1.0.0-7 by the way.

**Comment by ssetem** [comment]
I will double check, but I think its elasticsearch which doesn't support floating point for ranges

**Comment by timtutt** [comment]
@ssetem  - ES accepts floats for a range type field for certain. With numeric fields, I suspect the range aggregation does as well given the returned histogram above.  I was assuming that perhaps the slider itself does not support floating points for ranges?

**Comment by KunmyonChoi** [comment]
Hi, I also faced the same issue with following code. 
`<RangeFilter min={0.0} max={1.0} field="confidence" id="confidence" title="confidence" interval={0.1} step={0.1} showHistogram={true}/>`

**Comment by ssetem** [comment]
I see, elastic 2.4 supported only Integers, and elastic 5 allows floating point.

We will try to get it working with floating point

**Comment by Xrampino** [comment]
@ssetem Do you remember why step prop was removed ? https://github.com/searchkit/searchkit/commit/f957c3310eae3260b35df732e4be47b659fafcf6

It could fix this issue
