### ISSUE TITLE
ES 5.1 deprecation warning

### ISSUE THREAD

**Issue by ThaDafinser** [searchkit/searchkit#423]
Getting this deprecation message with `v1.0.0-7`
`[2017-03-22T08:06:05,439][WARN ][o.e.d.i.q.QueryParseContext] query malformed, empty clause found at [1:87]`

The reason is the empty filter statement as far as i understand.
![image](https://cloud.githubusercontent.com/assets/533017/24186078/dbb03e12-0ed6-11e7-8d0f-929d9e9060f6.png)

Releated https://github.com/elastic/elasticsearch-perl/issues/113#issuecomment-261220638

**Comment by ssetem** [comment]
thanks @ThaDafinser looks like we need to omit filter if its {}
