### ISSUE TITLE
Highlighting a TagFilterList + TagFilterConfig adds visible <em> tags

### ISSUE THREAD

**Issue by TheDolo** [searchkit/searchkit#424]
With highlighting enabled, a TagFilterList + TagFilterConfig doesn't actually highlight the field but adds visible < em > < em /> tags.  It also adds them into the active filter menu with < em > < em /> tags, causing the filter to fail.

 1.0.0 Beta 7 ES 5.2, thank you so much for your work!

**Comment by TheDolo** [comment]
Fixed by stripping out <em> </em> tags into the "values" arg in TagFilterList.

Edit:
Oh gawd, turns out using this code sample from the docs const source: any = extend({}, result._source, result.highlight)
and removing result.highlight obviously fixes my problem

**Comment by TheDolo** [comment]
Fixed in my local source by rendering values using dangerouslySetInnerHTML.  I also look for a strip out the tags when the tag is clicked and added to filter.  Not the best solution I know :(

**Comment by ssetem** [comment]
yep, html created outside of searchkit needs to use dangerouslySetInnerHTML (for highlight)
