### ISSUE TITLE
Default to 'View All' with <MenuFilter />

### ISSUE THREAD

**Issue by inostia** [searchkit/searchkit#425]
Hi, first off, thanks for all your fantastic work with this library! It's incredibly easy to work with and has helped my team out a bunch.

I'd like to see if there's a way to default to 'View All'/eliminate the need for that toggle. Is there a prop I can pass to `<MenuFilter />` that will default to showing all of the options?

Thanks

**Comment by ssetem** [comment]
@inostia I think this is possible by increasing the size property so pagination doesn't kick in

**Comment by inostia** [comment]
@ssetem thanks. I have a user directory with 4,500 records, so I need some pagination unless I do infinite scroll and use something like react-virtualize. I just want to display all options in a `<MenuFilter component={Select} />` without the View All toggle. So the only way currently is to increase the `hitsPerPage` to show all records?

**Comment by TheDolo** [comment]
+1

**Comment by ssetem** [comment]
I see, yeh react-virtualize might be good, also we probably need a auto complete for facets in the future

**Comment by GregoryPotdevin** [comment]
I have some code I built for contexte.com
https://www.contexte.com/chercher/

![image](https://cloud.githubusercontent.com/assets/1522455/24322548/9bb35b5e-1166-11e7-9a57-cbf0f9e5a966.png)

Works ok, seems fast enough, could probably be upgraded to support infinite scrolling. Not sure if ES supports aggregator pagination, though, or if it would require querying a greater number of entries.

**Comment by inostia** [comment]
Ended up just loading all records and optimizing with react-virtualized.
