### ISSUE TITLE
New query/filter `ExistsQuery`

### ISSUE THREAD

**Issue by ThaDafinser** [searchkit/searchkit#426]
Dunno yet a lot of react, so i'm suggesting it with an issue, instead of a proably wrong PR
https://www.elastic.co/guide/en/elasticsearch/reference/5.2/query-dsl-exists-query.html

```
export function ExistsQuery(key){
  return {
    exists:{
      field: key
    }
  }
}
```

**Comment by ssetem** [comment]
@ThaDafinser  we can add this to the core
