### ISSUE TITLE
add a DateHistogramBucket for date_histogram aggregations

### ISSUE THREAD

**Issue by olf** [searchkit/searchkit#427]
Could you add support for the [date_histogram](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html) aggregation?

Currently, I'm using the one that @GregoryPotdevin has implemented in [searchkit-daterangefilter](https://github.com/GregoryPotdevin/searchkit-daterangefilter/blob/master/src/DateHistogramBucket.js) which is working fine, but I think it'd be nicer to have it directly as part of searchkit along the other Bucket types.

**Comment by ssetem** [comment]
@olf  sure we can add this to the core

**Comment by ssetem** [comment]
thanks @olf 
your PR is merged and available in beta 2.3.0-0
