### ISSUE TITLE
Searchkit is overriding query string

### ISSUE THREAD

**Issue by mbm-rafal** [searchkit/searchkit#428]
I feel like, custom url parameters (query string) should be available if set, event thought that they are not a part of Searchkit definition. At this point searchkit is simply removing any custom part while building own query string.

**Comment by ssetem** [comment]
agreed, just a little complex as keys used are dynamic, but i think its possible

**Comment by xinghengwang** [comment]
is this the behavior where as I do filtering: 
the url changes to ?fooFilter=bar
but if I hit reload the page, the "?fooFilter=bar" part is gone, and the search filter is not taken into account? 
(This used to work in an old version, ie. I can remember the URL of ?fooFilter=bar and then when refresh page, the fooFilter=bar is still there and take account of in the search result. ).
Did this feature get removed?

**Comment by ssetem** [comment]
@xinghengwang feature should still be there, as long as useHistory is not false as part of the options.

If not if you can make a repo which replicates, then I can take a look
