### ISSUE TITLE
Boolean fields display

### ISSUE THREAD

**Issue by Jaikant** [searchkit/searchkit#432]
My ES document is something like below (just kept the relevant parts)

 ` {
        "_index" : "treks",
       ...
        "_source" : {
        ....
          "attractions" : {
            "snow" : true,
            "camping" : true,
            "waterbody" : true
          },
       ....
        }
}`

I want to have a RefinementListFilter which will filter if a trek has snow or camping or a waterbody.

If I add a RefinementListFilter as below -

`<RefinementListFilter id="attractions" title="Attractions Snow" field="attractions.snow" operator="OR" size={10}/>
<RefinementListFilter id="attractions" title="Attractions Camping" field="attractions.camping" operator="OR" size={10}/>
<RefinementListFilter id="attractions" title="Attractions Waterbody" field="attractions.waterbody" operator="OR" size={10}/>`

I get the following:

<img width="239" alt="screen shot 2017-04-03 at 11 02 31 am" src="https://cloud.githubusercontent.com/assets/3472565/24596471/29ee6c86-185d-11e7-9e91-6b764fcd43b6.png">

But I would like to have something like 
    **Attractions**
          snow     3
          camping   12
          waterbody  1

I realize that if I change my data to an array of strings which contain the attraction, this works out of the box, I just wanted to know if there is way to do this without changing my database schema?

 ` {
        "_index" : "treks",
       ...
        "_source" : {
        ....
          "attractions" : [
            "snow",
            "camping",
            "waterbody",
          ],
       ....
        }
}`

Can anyone suggest what I should be doing?

**Comment by joemcelroy** [comment]
Hey, check out the checkbox filter component (http://docs.searchkit.co/stable/docs/components/navigation/checkbox-filter.html). Not exactly what you need as would be great if the checkbox filter could support an array of filters to display. You can override the `containerComponent` and with some custom css, get it styled to how you want

**Comment by Jaikant** [comment]
@joemcelroy Thanks it works great!
