### ISSUE TITLE
rc-slider tooltip styling

### ISSUE THREAD

**Issue by Jaikant** [searchkit/searchkit#433]
The Tooltip on the Metascore in the demo app, gets its styling mangled when changed a couple of times. It happens for both the Metascore and imdbRating.

<img width="243" alt="screen shot 2017-04-03 at 6 14 40 pm" src="https://cloud.githubusercontent.com/assets/3472565/24609830/e060e6ba-1899-11e7-83b9-631223f6389a.png">

            `<DynamicRangeFilter field="metaScore" id="metascore" title="Metascore" rangeFormatter={(count)=> count + "*"}/>
            <RangeFilter min={0} max={10} field="imdbRating" id="imdbRating" title="IMDB Rating" showHistogram={true}/>`

Any tips/suggestion on how to get this right?

**Comment by joemcelroy** [comment]
thanks! Seems the dependency update for rangeslider has some styling issues. il look at this in a future beta release. Thanks

**Comment by Jaikant** [comment]
Actually this seems to be working all right now. The tool tip is nicely placed above the slider. Btw, this is in my project which uses bootstrap. I am not sure how much of a bug this is and maybe we should just close this off. I am closing it for now.

**Comment by joemcelroy** [comment]
ah that might be it. Thanks!

**Comment by bjlange** [comment]
I've just run into this same problem. @Jaikant how did you resolve it? Was it Bootstrap interfering, or did including the Bootstrap styles _help_?

**Comment by bjlange** [comment]
Nevermind, I resolved it by adding `import 'rc-slider/assets/index.css';` to the top of my file, as in the `rc-slider` docs examples.
