### ISSUE TITLE
Using synonym token filter

### ISSUE THREAD

**Issue by leandermelms** [searchkit/searchkit#436]
Hi,

is there a way to integrate the [synonym token filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-synonym-tokenfilter.html#analysis-synonym-tokenfilter)? 

It is as easy as:

```json 
{
    "index" : {
        "analysis" : {
            "analyzer" : {
                "synonym" : {
                    "tokenizer" : "whitespace",
                    "filter" : ["synonym"]
                }
            },
            "filter" : {
                "synonym" : {
                    "type" : "synonym",
                    "synonyms_path" : "analysis/synonym.txt"
                }
            }
        }
    }
}
```

I had a quick look on the documentation and haven't found out how to customize the search query (yet). Any help is greatly appreciated.

**Comment by ThaDafinser** [comment]
@leandermelms you do this step at the indexing. So this will work with searchkit out of the box then

**Comment by leandermelms** [comment]
Thanks you!
