### ISSUE TITLE
History not taking into account the hash

### ISSUE THREAD

**Issue by Bornlex** [searchkit/searchkit#438]
Hi guys,

I was using SearchKit recently but I had to set useHistory to false because it was pushing a wrong url to the history list.
To be more precise, it was pushing :
`let url = this.options.getLocation().pathname + "?" + encodeObjUrl(this.state)
`But in my app, the url contained a hash and something after the hash that was important.
So, when I was calling the previous page, it was not gicing me the actual previous page but another page, because of the missing hash parameter.

It could be fixed by appending it at the end a the url string :
`let url = this.options.getLocation().pathname + "?" + encodeObjUrl(this.state) + "#" + this.options.getLocation().hash`

This is declared in src/core/SearchkitManager.ts.

Julien

**Comment by ssetem** [comment]
Hi,

this is similar to preserve query string not related to searchkit.

will try to include preserve hash when we submit a fix

**Comment by tristanreid** [comment]
For those of you out there waiting for this (it seems unlikely to happen soon, I'm guessing), I needed this same thing, and worked around it by monkey-patching the history that SearchkitManager uses.  It's not the prettiest thing, but works fine.

```
    const oldPush = history.push
    history.push = (p) => {
        oldPush.call(history, pathReplace(p))
    }
    const oldReplace = history.replace
    history.replace = (p) => {
        oldReplace.call(history, pathReplace(p))
    }
    const searchkit = new SearchkitManager("/api/query/es_reactive", {
        createHistory: () => history 
    })

```
