### ISSUE TITLE
Searchkit Manager update httpHeader in order to pass Authorization token

### ISSUE THREAD

**Issue by florianbepunkt** [searchkit/searchkit#439]
Is there a way to update the httpHeaders of a SearchkitManager Component? I use the http headers to pass an authorization token, so I would need to update / change the headers based on user's login status.

**Comment by TheDolo** [comment]
I also am curious on the authors thoughts on this.  How can we pass in a new token without reinitializing SearchkitManager.

You may find this fork helpful I've found:
https://github.com/yarnball/SearchKitJWT

**Comment by florianbepunkt** [comment]
Can someone from the Searchkit team help?

**Comment by joemcelroy** [comment]
i did a couple of changes on the ESTransport to work with new version of axios. let me get back to you guys.

**Comment by joemcelroy** [comment]
Yeh isn't possible with our API right now. Workaround is you implement your own `ESTransport` class and pass the instance into `SearchkitManager` options. See [Searchkit Manager](https://github.com/searchkit/searchkit/blob/develop/src/core/SearchkitManager.ts#L76) and [AxiosESTransport](https://github.com/searchkit/searchkit/blob/develop/src/core/transport/AxiosESTransport.ts)

We can think about providing a helper method on transport class to be able to update request options like headers.

**Comment by ssetem** [comment]
you can reinstantiate the transport prop like this when ever your http headers change

```js
    import {AxiosESTransport} from "searchkit"
    searchkitManager.transport =  new AxiosESTransport(host, {
      headers:{...}
    })
```

**Comment by florianbepunkt** [comment]
Thank you guys.
