### ISSUE TITLE
ResetFilters Component: Simplify to only reset when visible filters or query string

### ISSUE THREAD

**Issue by joemcelroy** [searchkit/searchkit#44]
- [x] disabled if no selected filters or query string
- [x] disregard defaultQueries
- [x] disregard sorting selection

**Comment by ssetem** [comment]
adding disregarding defaultFiters/Queries

**Comment by GregoryPotdevin** [comment]
I think the default should be to reset the filters and not the query. It's a common use case to type a search, start filtering, and just want to reboot the filters. And that's what the name itself suggests : "ResetFilters".
