### ISSUE TITLE
How to onClick an item and refresh the list to outline a selection

### ISSUE THREAD

**Issue by grandmore** [searchkit/searchkit#441]
I want to be able to click on a found item and draw a highlight around the selection. However how do I get the list to refresh/render after I click.

I have added a function that Overrides the rendering and captures the click but cannot find a way to re-render the searchkit selection.

```
HitsGridItem(props) {
    const {bemBlocks, result} = props
    const poster = 'https://cdn/' + result._source.filename + '?w=170'
    const source: any = _.extend({}, result._source, result.highlight)
    const id = result._source.id
    const selected = this.state.selected
    const selectedStyle = selected === id ? styles.selected_item : '';

    return (
      <div
        className={bemBlocks.item().mix(bemBlocks.container("item")).mix(selectedStyle)}
        data-qa="hit"
      >
        <a onClick={this.handleSelect.bind(this, id)} style={{cursor: 'pointer'}}>
          <imgdata-qa="poster"className={bemBlocks.item("poster")}src={poster}width="170"/>
          <div data-qa="title" className={bemBlocks.item("title")}
               dangerouslySetInnerHTML={{__html: source.name}}></div>
        </a>
      </div>
    )
  }
```

Is there a baked in method I can use? I cannot find anything in the documentation.

**Comment by joemcelroy** [comment]
You could do this in a number of ways. Either using a state management like redux or use a stateful React component for `ItemComponent`. Closing this issue as more of a user implementation issue.
