### ISSUE TITLE
PropTypes in React 15.5

### ISSUE THREAD

**Issue by bcruddy** [searchkit/searchkit#443]
I left a comment in #354 yesterday, I'm hoping this gets more visibility.

I'm getting the following warning when running tests in my project with jest 19 (React 15.5.4, node 6.10.1, yarn 0.23.2):

`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

This isn't urgent as `React.PropTypes` won't be removed until React 16 but seeing all of these warnings is driving me a bit crazy. I'd be happy to put up a fix if this isn't currently being addressed. I put together two gists of every instance of `React.PropTypes` in [`master`](https://gist.github.com/bcruddy/bbdeb094da43ab8e5835e92ff5976010) and [`develop`](https://gist.github.com/bcruddy/71a00e2b53f2a0685a4b19ec193e581e) (they appear to be the same).

I'll need to get approval at work to put up the PR which could take 2-3 days so the sooner I know if I should fix it I can start that process.

Thanks for the awesome library!

**Comment by bcruddy** [comment]
After some investigation, this test would need to be removed as PropTypes are no longer "callable" to validate - https://github.com/searchkit/searchkit/blob/develop/src/__test__/core/react/SearchkitComponentSpec.tsx#L17-L34

**Comment by joemcelroy** [comment]
Yeh i see this issue aswell. We will try and get this issue resolved soon. Thanks!
