### ISSUE TITLE
Add a GreaterThanInput and LesserThanInput for the DynamicRangeFilter

### ISSUE THREAD

**Issue by leroy0211** [searchkit/searchkit#446]
We have a use case where the user is required to search for a length, width or height. Whatever the user inputs (as input field), the results must be Greater or Lesser than that. 

For example when the user inputs `100` on the `height` field. All items on which the `height` is larger than (and/or equal to) 100 must be displayed.

I have found that the rangeComponent `RangeInput` almost holds the things we want, but we only want to display one input field and without a button. 
Sure you can hide them with CSS or something, but it would be much nicer to have another rangeComponent to display a `RangeGreaterThanInput` or `RangeLesserThanInput` (or a property to the `RangeInput` to disable the `min` or `max`  field (and the `button`).

Or is there already such a component?

**Comment by joemcelroy** [comment]
You're best off extending the `RangeComponent` to do what you need. Also without a button, would you require the user to hit enter to apply the new search criteria?
