### ISSUE TITLE
Is it possible to display filters based on just a prefix?

### ISSUE THREAD

**Issue by leroy0211** [searchkit/searchkit#448]
Is it possible to display filters based on just a prefix? 

For example all my filters in elasticsearch are prefixed with `filter_*`. Is it possible to render all `MenuFilters` for all those fields prefixed with `filter_*`?

**Comment by joemcelroy** [comment]
No, not possible with searchkit. What you could do is create an ES query retrieving all the filters matching filter_* outside of searchkit and then render the searchkit `menuFilter` component for each filter.
