### ISSUE TITLE
ES 5.1 - search hit results are empty when mounting

### ISSUE THREAD

**Issue by florianbepunkt** [searchkit/searchkit#449]
Testing the latest searchkit from npm (2.0.0-9)…

I have a view that conatins a Searchbox and a Hits component that displays the results in a table. When I mount this view my hits results are empty until I enter something in the searchbox. I can also clear the searchbox and then it will show me all hits.

Exspected behaviour: Until I enter something in the searchbox all hits are shown
Actual behaviour: There are no hits until I enter something in the searchbox

**Comment by joemcelroy** [comment]
Are there any network errors in dev tools thats prevented from rendering the results?

**Comment by florianbepunkt** [comment]
Hi @joemcelroy, no network errors. But I use server side rendering. ES 5.1

**Comment by joemcelroy** [comment]
Yeh there are issues with server side rendering and searchkit. See #4.
