### ISSUE TITLE
Hierarchical Refinement Filter with multi select support

### ISSUE THREAD

**Issue by jasonl83** [searchkit/searchkit#452]
I need to build a Hierarchical Refinement filter to support product category filtering, but the build-in one only support single select.  Any plan to add multi select? Kind of like RefinementListFilter with tree hierarchy.

Thanks,
Jason

**Comment by TheDolo** [comment]
https://github.com/GregoryPotdevin/searchkit-multiselect

**Comment by joemcelroy** [comment]
Yeh for now the hierarchical refinement filter only supports single select.
