### ISSUE TITLE
alternate hitsPerPage depending on view (switch)

### ISSUE THREAD

**Issue by zeitvertrieb** [searchkit/searchkit#454]
If I'm using ViewSwitcherHits – and I want to have different hitsPerPage for grid and list – how would I do that?

**Comment by TheDolo** [comment]
As of right now, even when using multiple  <Hits hitsPerPage={10} listComponent={Compon}/> <Hits hitsPerPage={15} listComponent={Compon}/>, you'll still only get 10 or 15 for both.  Perhaps pass in the max hits needed, then discard the extra rows passed in (need to use listComponent and not itemComponent).

**Comment by ssetem** [comment]
hi, i think a bit tricky as it may have side effects, such as if your in page 2 and change view

it would probably need to reset pagination etc.

what kind of behaviour would you like in this case?

**Comment by mcastre** [comment]
@TheDolo @ssetem I'd like to expound on this question, as I am running into the same issue. Is there a way to determine which view you are currently in? Say I have 2 hitComponents in my ViewSwitcherHits: MapView and ListView. I want to set the size to 0 if on the MapView, and set size to 10 if on the ListView. Is that possible?
