### ISSUE TITLE
Incorrect query format for Elasticsearch 5.3 when filtering

### ISSUE THREAD

**Issue by CWolfAnderson** [searchkit/searchkit#455]
When using a MenuFilter Searchkit uses this as a query:
```
"filter": {
  "term": {
    "status.raw": "Low"
  }
}
```
but according to Elasticsearch's documentation *this* should be the query:
```
"query": {
  "bool": {
    "filter": {
      "term": {
        "status.raw": "Low"
      }
    }
  }
}
```
as seen here: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-filter-context.html

I also get this error message:

![error message](https://files.gitter.im/searchkit/searchkit/cZr1/Screen-Shot-2017-05-18-at-1.11.25-PM.png)

**Comment by waternoodlle** [comment]
I'm seeing the same exact issue. I'm using ES 5 and see that the "filter" now needs to be wrapped in "query" and then "bool".

**Comment by ssetem** [comment]
thanks, will investigate.

**Comment by ssetem** [comment]
which version of searchkit are you using?

**Comment by CWolfAnderson** [comment]
I'm using 2.0.0-10 but I'll update to 2.0.0 right now.

**Comment by CWolfAnderson** [comment]
It turns out updating searchkit to 2.0.0 solved the problem. Thanks!
