### ISSUE TITLE
searchkit.co RC docs

### ISSUE THREAD

**Issue by bcruddy** [searchkit/searchkit#458]
I can't seem to find docs for anything beyond version 0.10.0 here - http://docs.searchkit.co/stable/. "stable" tells me they may exist but I'm not sure where to find them.

**Comment by joemcelroy** [comment]
Yep - we released 2 yesterday, having a couple of issues deploying the newest docs but should be resolved soon. Ill let you know when they are up. Otherwise youll can see the /docs folder for now.

**Comment by bcruddy** [comment]
Awesome thanks!

**Comment by joemcelroy** [comment]
2.0.0 docs been released now. Thanks!
