### ISSUE TITLE
Facet sorting

### ISSUE THREAD

**Issue by GregoryPotdevin** [searchkit/searchkit#46]
Aggregators can also be sorted on `_term` rather than `_count` : https://www.elastic.co/guide/en/elasticsearch/guide/current/_intrinsic_sorts.html
API suggestion : `<RefinementListFilter ... sort="count|term|key" sortOrder="asc|desc" />`

**Comment by joemcelroy** [comment]
Thanks Gregory, 

Yeh this will be a good addition. HierarchicalRefinementFilter supports order aswell using the `orderKey` and `orderDirection` props so we should align the props to that.

**Comment by GregoryPotdevin** [comment]
Great
