### ISSUE TITLE
Which branch gets deployed?

### ISSUE THREAD

**Issue by bcruddy** [searchkit/searchkit#460]
I see that I'm installing `2.0.1` but https://github.com/searchkit/searchkit/blob/develop/package.json#L3 says `2.0.0`.

The change to [this line](https://github.com/searchkit/searchkit/blob/develop/src/components/search/filters/facet-filter/MenuFilter.tsx#L51) isn't appearing in the installed `v2.0.1` in my project.

The `develop` branch the one that actually gets deployed? I'm unfamiliar with CircleCI so the config file wasn't a huge help.

**Comment by joemcelroy** [comment]
Thanks for headsup, the changes were in a branch I was on. Now pushed this up to develop. thanks again @bcruddy

**Comment by bcruddy** [comment]
Needs to be deployed to npm again (2.0.2). This library is amazing - thanks for everything that's gone into it!

**Comment by joemcelroy** [comment]
thanks! yeh we have a script which does the deploy script, its definitely work looking again on how to make it more automated.

**Comment by bcruddy** [comment]
The only downside to the automated deploys on merges to `develop` (`master` in my case) is that every single merge needs at least a patch bump or it will fail to deploy (which may be fine if you don't want to deploy every change).

**Comment by joemcelroy** [comment]
btw @bcruddy v2.1 has been released.
