### ISSUE TITLE
When using TagCloud as a listComponent in a RefinementListFilter, sorting settings like orderKey are ignored

### ISSUE THREAD

**Issue by bjlange** [searchkit/searchkit#461]
It looks like the sorting is defined in the render function, so overriding that could resolve this, but it's not the behavior I would expect.

**Comment by ssetem** [comment]
I see, i think to make tag cloud more balanced it was overridden.

I think defaulting to orderKey is probably best

**Comment by bjlange** [comment]
Happy to submit a PR if you want, I think it just involves removing the sorting code.
