### ISSUE TITLE
UX problem Scrollto: Different events for filters and pagination

### ISSUE THREAD

**Issue by MarcoTroost** [searchkit/searchkit#463]
Hi!

Thanks for the great work on searchkit! Perhaps you would consider the following:

**The Scollto method is activated whenever a user chooses a filter OR clicks on the pagination. Pagination is treated the same as an activated filter. This is bad UX in my view since the behaviour of those elements are fundamentally different.**

When a user clicks on a filter (in the left column), he would probably want to activate even more filters,  especially with searchkit's speed and ease of use. (e.g.  i'm searching for brown shoes - with laces - sneakers - size 45). The user therfore wants want **the retain the current position on screen**, since he is still busy choosing filters.

When a user click on the pagination however (which is usually below the searchresults), there is **no need or want to stay at the current location**. One would want to got to the top of the results to browse the new resultset.

Could you please offer two different events that activate the scollto method?

- Filter-event: stay where u are
- Pagination-events: scroll to top

kind regards, Marco

**Comment by joemcelroy** [comment]
yeh, this has come up a few times. We have a scrollTo prop on Hits component, this could also support a function with a "changeSource" argument, a value of either pagination or filter. That will allow anyone to control when to scroll up or not.

**Comment by MarcoTroost** [comment]
Hi Joel,

Thank you for your reply. I would love to see a feature like that!

gr Marco

**Comment by Nostres** [comment]
@joemcelroy 

I would like to suggest just throw event types when you apply filter or search or apply pagination, which can catch in setQueryProcessor listener because I have similar issue, I need to do something when I apply filter or search but not when applying pagination

Thanks
