### ISSUE TITLE
[Feature] Allow FacetFiler to hide entirely when no results are provided

### ISSUE THREAD

**Issue by mbm-rafal** [searchkit/searchkit#466]
I'd like to hide entire facet filter (with title and container) if no buckets are fetched for it. Now title is sustained by component.

![image](https://user-images.githubusercontent.com/19263109/26893222-01e8c5b0-4bbb-11e7-9017-02dfd7451a69.png)

vs

![image](https://user-images.githubusercontent.com/19263109/26893200-f513e626-4bba-11e7-8be8-a9b14bb4f457.png)

**Comment by joemcelroy** [comment]
Each filter should add a `.is-disabled` class if there are no filters. Searchkit theming hides these filters by css. We will be implementing soon a way to control the display of the filters when there are no results.
