### ISSUE TITLE
Sorting - add support for nested objects

### ISSUE THREAD

**Issue by arnvol** [searchkit/searchkit#467]
Add support for nested objects in SortingSelector.
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_nested_sorting_example

**Comment by voke** [comment]
The following markup
```
<SortingSelector options={[
  {label:"Relevance", field:"_score", order:"desc", defaultOption:true},
  {label:"Color", key:"whatever", fields: [
    { field:"offer.price", options: {
      order:"asc", nested_path: 'offer',
      nested_filter: { term: { "offer.color": "blue" } }}}
  ]}
]}/>
```
will generate this query:
```json
"sort":[  
   {  
      "offer.price":{  
         "order":"asc",
         "nested_path":"offer",
         "nested_filter":{  
            "term":{  
               "offer.color":"blue"
            }
         }
      }
   }
]
```
which seems to correspond to the sorting example you linked to. I found it in [Advanced Sorting section](http://docs.searchkit.co/stable/components/sorting/sort.html).

**Comment by arnvol** [comment]
Great, thanks voke! I read that section in the documentation but didn't realize it was possible to send the nested_path as an option.
