### ISSUE TITLE
how to debug : "We're sorry, an issue occurred when fetching your results. Please try again"

### ISSUE THREAD

**Issue by harveyaot** [searchkit/searchkit#470]
Hi team, 

Could you please help me to figure out how to debug or where can I see the log when I encountered this error "We're sorry, an issue occurred when fetching your results. Please try again"?

Thanks

**Comment by joemcelroy** [comment]
Have a look at the network tab in developer tools. The response from elasticsearch should tell you the reason for the error. Also you can join our chat (on our homepage) for help.
