### ISSUE TITLE
Passing credentials with requests

### ISSUE THREAD

**Issue by aleybovich** [searchkit/searchkit#477]
I have an express middletier running that the searchkit UI is pointing to. The middletier authenticates the requests based on an SSO cookie. The cookie isn't being passed so the requests fail. I see that there was a recent change to support withCredentials, but I can't figure out how to actually set that flag from my code. Any ideas?

**Comment by joemcelroy** [comment]
We use axios andsuport basicAuth and withCredentials. This is passed in the searchkitmanager options. https://github.com/searchkit/searchkit/blob/e22647fd22c48fa8a828d713d6b79e1b87c2c6ad/src/core/transport/AxiosESTransport.ts
