### ISSUE TITLE
aggregations with filtering on additional fields

### ISSUE THREAD

**Issue by Benadev** [searchkit/searchkit#478]
Hey!

We want to create two different RefinementListFilter's but want to filter the data before aggregation.
Our request looks like this and works well.
But we have problems to realize this in react with searchkit.

This is our request:
One aggregates on "itemTypeId" and one on "slotItemKeyId".
The filters are realized with "bool" "should" and "must_not".

```
{
  "aggs": {
    "itemTypeId2": {
      "filter": {
        "bool": {
          "should": [
            {
              "term": {
                "projectId": 0
              }
            },
            {
              "term": {
                "sheetSlotItemId": 0
              }
            }
          ]
        }
      },
      "aggs": {
        "itemTypeId": {
          "terms": {
            "field": "itemTypeId",
            "size": 10
          }
        },
        "itemTypeId_count": {
          "cardinality": {
            "field": "itemTypeId"
          }
        }
      }
    },
    "slotItemKeyId3": {
      "filter": {
        "bool": {
          "should": [
            {
              "term": {
                "projectId": 1775
              }
            }
          ],
          "must_not": {
            "term": {
              "slotItemKeyId": 0
            }
          }
        }
      },
      "aggs": {
        "slotItemKeyId": {
          "terms": {
            "field": "slotItemKeyId",
            "size": 10
          }
        },
        "slotItemKeyId_count": {
          "cardinality": {
            "field": "slotItemKeyId"
          }
        }
      }
    }
  },
  "size": 12,
  "_source": [
    "caption",
    "renderedContent"
  ]
}
```

And this is what we tried to implement in react/searchkit:

We thought we create our own RefinementListFilter component for the two aggrgations.
For every own RefinementListFilter we created an Accessor and implemented the buildSharedQuery() function.

Like this:

```
class MyRefinementListFilter extends RefinementListFilter {
	defineAccessor() {
		const {id, title, fields, size, orderKey, orderDirection} = this.props
		return new MyCheckboxFilterAccessor(id, {
			id, title, fields, size, orderKey, orderDirection
		})
	}
}

class MyCheckboxFilterAccessor extends FacetAccessor {
	buildSharedQuery(query){
		query = query.addFilter("itemTypeId", BoolShould([
		  TermQuery("projectId", 0),
		  TermQuery("sheetSlotItemId", 0)
		]))
    return query
  }
}
```

The listComponent should be a CheckboxItemList.

Is this the right way and if so, what are we doing wrong, because it does not work.
What is with the buildOwnQuery() function? Would this be the right function to do this? Or does it not extend the search query in general?

All hints are welcome ;)

Thanks and Regards,
Ben

**Comment by ssetem** [comment]
I think that your doing it correctly, buildOwnQuery is used for the aggregators, and buildSharedQuery is used for the act of filtering as its needed earlier to build disjunctive queries.

We do have an issue or 2 to make passing custom accessor much easier without inheritance
