### ISSUE TITLE
Only a single instance of BaseQueryAccessor is allowed w/server side rendering

### ISSUE THREAD

**Issue by chrisfinch** [searchkit/searchkit#479]
Getting the error `Only a single instance of BaseQueryAccessor is allowed`.

First load works fine, subsequent loads trigger error on server.

Here's the file I've made to try and ensure that only one instance of `SearchKitManager` is ever created on the server/client. Still no joy!

```javascript
import { createMemoryHistory, createBrowserHistory } from 'history';

let searchKit;

const getSearchKitInstance = () => {
	if (!searchKit) {
		const SearchkitManager = require('searchkit').SearchkitManager;

		if (WEBPACK_CONFIG_IS_NODE) {
		    searchKit = new SearchkitManager("/", {
		        useHistory: false,
		        searchOnLoad: false,
		        createHistory: createMemoryHistory
		    })
			return searchKit;
		} else {
		    searchKit = new SearchkitManager("/", {
		        timeout: 20000,
		        createHistory: createBrowserHistory
		    });
			return searchKit;
		};
	} else return searchKit;
};

export default getSearchKitInstance;
```

Any ideas would be greatly appreciated.

Thanks!

**Comment by ssetem** [comment]
@chrisfinch we are just in the process of making Searchkit server friendly

hopefully can get a beta out soon

**Comment by chrisfinch** [comment]
@ssetem thanks - that would be great!

**Comment by TheDolo** [comment]
Same :) this would be huge.

**Comment by vvo** [comment]
FWIW this is how we did it in react-instantsearch: https://community.algolia.com/react-instantsearch/guide/Server-side_rendering.html

Since we had a declarative API that was then translated to search queries, we had to render it twice somehow and that was a challenge with ReactDOMServer.

Done by @mlthuret

**Comment by joemcelroy** [comment]
Yep thats what we do for https://github.com/searchkit/searchkit-universal. You know guys, universal works, just in alpha and we want to push some of the internal calls we do in this project down into core.

**Comment by ssetem** [comment]
@TheDolo @chrisfinch @vvo 

thanks for help, version 2.3.0-0 should be server render friendly

example usage can be found here

https://github.com/searchkit/searchkit-examples/tree/master/searchkit-ssr-express-example

thanks!
