### ISSUE TITLE
Scroll results to top on pagination change

### ISSUE THREAD

**Issue by GregoryPotdevin** [searchkit/searchkit#48]
The current code uses `window.scrollTo(0,0)`, but the demo has a scrolling `layout__results`. 
A "scrollResultsToTop" event should probably be triggered to let the corresponding component react to it.

**Comment by joemcelroy** [comment]
and probably needs to more deep than within the component as more components which update search state like selecting filters needs to return to the top.

**Comment by ssetem** [comment]
this might be an accessor which behaves like a listener and does the scrolltotop

**Comment by GregoryPotdevin** [comment]
I'm wondering if the Hits component couldn't just scroll to top when the data changes
