### ISSUE TITLE
Passing credentials with requests 

### ISSUE THREAD

**Issue by aleybovich** [searchkit/searchkit#481]
It's a follow-up to https://github.com/searchkit/searchkit/issues/477 closed by @joemcelroy 

Joe's answer doesn't work - I am passing `withCredentials` as an option into SearchkitManager but the `withCredentials` option isn't there at all in `this.options` on line 27 (https://github.com/searchkit/searchkit/blob/e22647fd22c48fa8a828d713d6b79e1b87c2c6ad/src/core/transport/AxiosESTransport.ts) when I debug thru the code. It gets lost somewhere on the way. 

This is how I initialise SearchkitManager:

`this.searchkit = new SearchkitManager(host, { multipleSearchers: false, searchUrlPath: '/search', withCredentials: true });`

And this is the `this.options` object I see in AxiosESTransport module:

```
{"headers":{},"searchUrlPath":"/search","timeout":60000}
```

As you can see, `withCredentials` is not present there at all.

**Comment by aleybovich** [comment]
Ok, digging deeper, I found the bug in searchkit code causing `withCredentials` getting lost. SearchkitManager.ts line 70:

```
this.transport = this.options.transport || new AxiosESTransport(host, {
      headers:this.options.httpHeaders,
      basicAuth:this.options.basicAuth,
      searchUrlPath:this.options.searchUrlPath,
      timeout: this.options.timeout
    })
```

As you see, `withCredentials` value doesn't get passed to axios. Can you please fix it?

**Comment by aleybovich** [comment]
I created a pull request for the issue, please review and merge it

**Comment by joemcelroy** [comment]
#482 created a PR for this. There was already tests for axios transport layer for credentials.

**Comment by aleybovich** [comment]
@joemcelroy - Thank you. Any ideas when is this code fix going to be released? I.e. when are you releasing the next version?

**Comment by chrisfinch** [comment]
👍 also having this issue - any plans for a release?

**Comment by aleybovich** [comment]
They have, get the latest version. It works fine for me now

**Comment by joemcelroy** [comment]
thanks for testing the beta release. Il release it soon.
