### ISSUE TITLE
Navigating back and forth

### ISSUE THREAD

**Issue by MarcoTroost** [searchkit/searchkit#486]
Hi Joseph,

We've  just deployed a project that utilises Searchkit. Filtering a large resultset works with lightining speed, it's instant! ( [http://www.zeelandnet.nl/prikbord/zoeken?rubriek[0][0]=Auto%27s](url) )

However, if one is to click a product in the list and subsequently view the item on the productpage, the whole speedy-effect is ruined if one hits the back-button:

_The whole (shadow) DOM needs to be rendered again from scratch, whereas we previously had the listview available in the cache of the browser (showing the list, where one came from, directly)._ 

Is it possible to create something that 'remembers' the last compiled version of the list (activated after you click on the productlink)?

Thanks again for your great work on Searchkit!

kind regards,

Marco Troost

**Comment by ssetem** [comment]
Is the product detail page part of the same react Router, or completely different server page?

**Comment by MarcoTroost** [comment]
Hi Ash,

The product detailpage is a completely different server page, but that is beside the point. 

Rendering a full serverpage will paint the DOM once again, unless this page is already cached. This is obviously not the case with Searchkit.

I'm looking for ways to take advantage of the realtime searchkit-filtering, but still keep the browsing experience similar to what users are used to. 

grtz Marco

**Comment by ssetem** [comment]
I think if the product detail page was part of the react router, you will get the experience you want.

We also are investing time in serverside rendering, so this could help the initial impression alot
