### ISSUE TITLE
Autocomplete match query

### ISSUE THREAD

**Issue by chrisfinch** [searchkit/searchkit#487]
Hi all,

I'm currently trying to extend the already excellent searchkit to allow me to issue autocomplete queries and am running up against some blockers.

I need to issue queries under the `match` key like so: https://www.elastic.co/guide/en/elasticsearch/guide/current/_index_time_search_as_you_type.html#_querying_the_field

Unfortunately it seems that ImmutableQuery does not allow for this as only certain keys are copied over:

https://github.com/searchkit/searchkit/blob/a9b5abd2a17ac45c7e1eecf4c29f52ca18e6afe8/src/core/query/ImmutableQuery.ts#L44

Could anyone give me some pointers as to where to go from here?

(have attempted forking and modifying searchkit locally but have run up against compilation issues...)

Thanks in advance for any help.

**Comment by ssetem** [comment]
a quick way would be to modify without forking ImmutableQuery.prototype.buildQuery
to include the new key, and then if it works can submit a issue/pr to add into searchkit

**Comment by chrisfinch** [comment]
@ssetem thanks for the response. I thought of modifying ImmutableQuery but how would I then ensure that the modified version is used by the rest of searchkit?

**Comment by ssetem** [comment]
if you directly modify ImmutableQuery.prototype.buildQuery, it will affect all uses
