### ISSUE TITLE
Elasticsearch 5.5 Unknown key for a START_OBJECT in [filter].

### ISSUE THREAD

**Issue by webmagicc** [searchkit/searchkit#489]
Hello
I am use Elasticsearch 5.5 and when i use filters i get 400 Bad request and Unknown key for a START_OBJECT in [filter].

**Comment by webmagicc** [comment]
work if i wrap query in 
{"query": { 
    "bool": { 
// my query
}
}
}

For example
{
  "query": { 
    "bool": { 
      
      "filter": [ 
        { "term":  { "brand": "ventolux" }}
      ]
    }
  }
}
This example work

**Comment by TCMiranda** [comment]
@webmagicc seems like a difference between es versions. https://stackoverflow.com/questions/40996266/elasticsearch-5-1-unknown-key-for-a-start-object-in-filters

Did you manage to fix it using some post processing feature of searchkit?
