### ISSUE TITLE
Can we expect any kind of visualization/charts in searchKit ? 

### ISSUE THREAD

**Issue by samdash** [searchkit/searchkit#490]
I liked sample https://www.npmjs.com/package/searchkit-recharts for pieChart,
are there any plans to have more charts within searchKit ?

**Comment by joemcelroy** [comment]
not in this project but would love the community to build components for searchkit. always here to help those who want to contribute!

**Comment by jacksonp2008** [comment]
Where is the community support?  the https://gitter.im/searchkit/searchkit is crickets...  I don't mean to sound insulting, I think this has major potential for us.  But before I spend a bunch of time on this I'm looking for some reassurance that it's not a dead end project?

**Comment by joemcelroy** [comment]
Im here and the top contributors still help but with everyone, we help when we have free time.
