### ISSUE TITLE
I love your component but please also give an API to use it without jsx

### ISSUE THREAD

**Issue by kud** [searchkit/searchkit#492]
Your component is amazing but when you want to  get off the beaten track, it's hard to get informations.

For instance I would like:

- not to request at all when I've got empty strings (not just in the first load)
- if you `searchOnLoad: false`, it doesn't work anymore if you come from another page to `/search/q?blah`
- get the count of results (except if you go to `searchkit.getHitsCount()`)
- to know what the current query string (searchkit.query.index.queryString, a bit long)

etc etc.

An API could be great like `searchkit.whateverMethod()`

Cheers!

**Comment by kud** [comment]
Apparently you've got some stuff there: `searchkit.accessors.getState()` but the doc isn't enough in my opinion.

**Comment by joemcelroy** [comment]
Well you can change that! Help us add more documentation 😄

**Comment by kud** [comment]
I'll do yes but I've got to read a lot the code done in typescript. :D
