### ISSUE TITLE
[Problem] Come back on search when it was already instanced doesn't search

### ISSUE THREAD

**Issue by kud** [searchkit/searchkit#494]
If you are like me having like 2 pages, one search, one another page, you come on search page, it does the default result, you go on another page (with react router), and you come back on search page, you've got the initial loader and no trigger to request a search. You have to type something in the searchbox to make it happen.

Any idea?

**Comment by kud** [comment]
Doesn't work:

```javascript
const sk = new SearchkitManager(API_URL + "/search/")

class SearchPage extends React.Component {
  render() {
    return (
      <SearchkitProvider searchkit={sk}>
        <WrappedSearchApp />
      </SearchkitProvider>
    )
  }
}
```

---

Works:

```javascript
class SearchPage extends React.Component {
  render() {
    const sk = new SearchkitManager(API_URL + "/search/")

    return (
      <SearchkitProvider searchkit={sk}>
        <WrappedSearchApp />
      </SearchkitProvider>
    )
  }
}
```

**Comment by ssetem** [comment]
Best place is to use the constructor to create the searchkit instance
