### ISSUE TITLE
TypeError: this.history is undefined

### ISSUE THREAD

**Issue by kud** [searchkit/searchkit#495]
Do you have any idea where this error comes from?

**Comment by joemcelroy** [comment]
can you please explain more?

**Comment by kud** [comment]
I would like but I have no idea how it happens. :) Maybe it's a bug with react hot loader.

**Comment by kud** [comment]
I'll let you know if I've got any more information. But it happens quite often.

**Comment by joemcelroy** [comment]
ok. one thing, if you struggle / new with typescript, use es6. its fair less headaches for those who just want to implement an application using searchkit. Use the searchkit-starter-app boilerplate we have in our repo.

**Comment by kud** [comment]
Yeah I use es6 right now ;)

I'll have a look to searchkit-starter-app so.
