### ISSUE TITLE
RefinementListFilter Checkboxes Not Persisting State

### ISSUE THREAD

**Issue by mcastre** [searchkit/searchkit#497]
Hello! I have a question about the RefinementListFilter. I have a few filters that are booleans, for example: `{field: 'hasChildren': {'1' : 'Yes', '0': 'No'}}` to give an example of the translation for that field. For some reason, I can persist the correct selected filters in the url, and in the SelectedFilters/GroupSelectedFilters, but the actual checkboxes in the RefinementListFilter are not checked after you refresh the view. An example of the url query string: `&hasChildren[0]=1`, where `hasChildren` is true. Do you have an idea why the checkboxes arent reflecting the state of the query correctly? I can provide more info if you need. Thank you!

PS: My ES mappings has that `hasChildren` field as a type boolean if that helps any.

**Comment by ssetem** [comment]
I need to check more, but I reckon its because of '1', '0', something is getting confused and converting to numerical key when deserializing Url

**Comment by ssetem** [comment]
hi @mcastre possible to show more details on component you are using, and mapping of field?

thanks

**Comment by ssetem** [comment]
@mcastre 
this should be fixed in beta 2.3.0-0
