### ISSUE TITLE
RefinementListFilter with must_not.

### ISSUE THREAD

**Issue by samdash** [searchkit/searchkit#498]
I have one RefinementListFilter  which handles AND and OR operation for category attribute , but i also want NOT operation for the same category attribute. 

example : i want to select everything with AND or OR categories ( iPhone, iPod ..etc ) but NOT ( having bluetooth)

example each document will have set of categories ( iPhone, bluetooth) or just ( iPhone) 
Document 1 : has [ iPhone, bluetooth)
Document 2: has [iPhone]

i want all documents with iPhone but NOT bluetooth , which will return only Document 2 and not Document 1.

Thanks to Mtg-Hunter ( Peter Klavins @PAK90 ) for below sample : 

Below is what i currently have , and it works great, wanted to add NOT operation as well here, as explained above and this is very important feature we need.

```
<RefinementListFilter id="categoryKeys" title="Categories" field="categoryKeys" size={5} listComponent={MultiSelect}  operator={this.state.categoryOperator}
                            containerComponent={<TogglePanel rightComponent={(<div style={{display:"flex", maxHeight: 26}} onClick={(evt) => this.suppressClick(evt)}>
                              <Toggle items={[{key:"AND",title:"And"},{key:"OR",title:"Or"}]} selectedItems={this.state.categoryOperator} toggleItem={this.handleToggleOperatorChange.bind(this, "categoryOperator")}/>
                              </div>
                            )} collapsable={true} defaultCollapsed={true}/>}/>
```

**Comment by xinghengwang** [comment]
There is already an discussion on this: 

https://github.com/searchkit/searchkit/issues/150#issuecomment-285835166
