### ISSUE TITLE
HierarchicalRefinementFilter with expanded children

### ISSUE THREAD

**Issue by daviddahl** [searchkit/searchkit#499]
**Question**: Can the HierarchicalRefinementFilter display by default its top level filter & children in `lvl-1` without triggering a query? These things seem inseparable to me.

**Comment by johnecon** [comment]
Just posted the bellow question in [gitter](https://gitter.im/searchkit/searchkit?source=all-rooms-list) and I have I feel it relates with your question:


I have an hierarchy with 4 levels (level 1: country, level 2: region, level 3: subregion, level 4: city).
Some cities do not belong in a subregion or a region but they all belong to a country and for this I have assigned level 2 or level 3 to some cities.
My hierarchy works great when no starting level is applied.
When a user lands in a country page I want to render an HierarchicalRefinementFilter ideally starting from level 2 and expandable to level 4.
I would expect that start level in HierarchicalRefinementFilter specifies the root level to start from as mentioned [here](http://docs.searchkit.co/stable/components/navigation/hierarchical-refinement-filter.html). Instead when I specify startLevel = 2 then what I get is a non expandable refinement list - when I click to a region the filter does not expand.
Please see below working example:
```
<HierarchicalRefinementFilter id="geo" field="geo"  title="Geo" />
```

 ![workingExample](https://i.imgur.com/x922ZcR.png)

and startLevel issue:

```
<HierarchicalRefinementFilter id="geo" field="geo" title="Geo"startLevel="2"/>
```

 ![startLevelIssue](https://i.imgur.com/dp4hrNi.png)

**Comment by PRANAYDALALA4** [comment]
@daviddahl  any luck till now.

**Comment by daviddahl** [comment]
No, I had to change the data received

**Comment by PRANAYDALALA4** [comment]
Can you please provide the sample of data that you received and what changes have you done with the data?
