### ISSUE TITLE
Adding component propType?

### ISSUE THREAD

**Issue by Jimexist** [searchkit/searchkit#5]
Is it possible that `propType` gets added to e.g. https://github.com/searchkit/searchkit/blob/master/src/core/react/SearchkitProvider.tsx?

I am getting an error while using that component saying that `render` returns a non react component. And it turns out that I put more than one `<div>` under `SearchkitProvider` as children. This would've been caught easily by especifying that `props.children` is of instance of react `Component`.

**Comment by ssetem** [comment]
Thanks for the heads up, we will be adding correct propTypes to all components very soon :)

**Comment by Jimexist** [comment]
Great - looking forward to it!

**Comment by ssetem** [comment]
just released 0.3.2, where all component should have propTypes now
