### ISSUE TITLE
Significant Terms Aggregation

### ISSUE THREAD

**Issue by paweloque** [searchkit/searchkit#502]
First of all thanks so much for the searchkit. It's a great toolbox for building search UIs and Prototypes where I can show our customers how to implement a nice search experience!

I'm implementing search Projects for various clients in Switzerland and I'm currently working on search for a teaching materials platform: https://unterrichtsmaterial.ch/ 
My current searchkit based prototype is: https://umat.iterativ.ch/

I'm currently experimenting with `significant_terms` aggregation to show users which terms are relevant for a subset of documents. In this case for example for a specific school subject. I want to show this significant terms in the ui and I've implemented a very first prototype of a SignificantTermsFilter and SignificantRefinementListFilter which return the results of a significant_terms aggregation and display to the user. For that purpose I've used your SignificantTermsBucket class which seems not to be used elsewhere. You can find the code here: https://github.com/iterativ/searchkit-signterms  and especially here: https://github.com/iterativ/searchkit-signterms/blob/master/src/SignTermsAccessor.js#L108 and https://github.com/iterativ/searchkit-signterms/blob/master/src/SignFacetAccessor.js#L162

It's really a prototype and doesn't work in general situations. What I want to ask you is whether you plan to implement the significant_terms aggregation in your components and if yes, what are your ideas on that? If you have ideas on how to implement this, I'd like to contribute by implementing such a component. 

A possibility that I see is to specify the type of aggregation like the following example:

```
              <HierarchicalMenuFilter
                id="subject"
                title="Fach"
                fields={["meta.subject:terms", "meta.text:significant_terms"]}
                size={10} />

```
Another way would be to specify them as an additional param:

```
              <HierarchicalMenuFilter
                id="subject"
                title="Fach"
                fields={["meta.subject", "meta.topic"]}
                aggs={["terms", "significant_terms"]}
                size={10} />

```
But in both cases I'm not yet fully convinced.. 

You can install the prototype for the significant terms filters with npm:
`npm install searchkit-signterms`

Would be great to hear your thoughts on this!

**Comment by joemcelroy** [comment]
Thanks for your email BTW. Sorry haven't responded yet! Il have a quick look over weekend but my advice is to build an external component to suit your needs, open source it and see what the feedback is from others. For me, I think the best I can do is provide a section in the readme with all external components there are on github and hopefully others will find you and give feedback to people like you.

Thanks for your contribution!

Joe

**Comment by paweloque** [comment]
Hi Joe

Thanks for your response. That's great, I'm looking forward to hear about your thoughts on this component. 

It's a reasonable approach to provide this as an additional component and see whether and how others use it!

Cheers
pawel
