### ISSUE TITLE
Can't resolve 'vertx'

### ISSUE THREAD

**Issue by bradennapier** [searchkit/searchkit#503]
When trying to use this package on initial install and addition, I get the following:

```
client?e4ca:126 ./node_modules/es6-promise/dist/es6-promise.js
Module not found: Error: Can't resolve 'vertx' in '/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/es6-promise/dist'
 @ ./node_modules/es6-promise/dist/es6-promise.js 138:16-26
 @ ./node_modules/searchkit/lib/src/core/SearchkitManager.js
 @ ./node_modules/searchkit/lib/src/core/index.js
 @ ./node_modules/searchkit/lib/src/index.js
 @ ./app/shared/components/Search/Search.js
 @ ./app/screens/Dashboard/screens/ProjectDashboard/screens/ProjectEvents/ProjectEvents.js
 @ ./app/screens/Dashboard/screens/ProjectDashboard/routes.js
 @ ./app/screens/Dashboard/routes.js
 @ ./app/routes.js
 @ ./app/index.js
```

From rresearch it appears this is due to using older es6-promise dependencies and they have apparently fixed it?  Not sure - also not sure why this is necessary - shouldn't you allow passing in a Promise implementation and use the native Promise if not provided at this point?

**Comment by ssetem** [comment]
@bradennapier i tried updating to 4.x, i also get same issue.

```        new webpack.IgnorePlugin(/vertx/),
```
 in my webpack fixed it.

will keep eye out for better solution
