### ISSUE TITLE
bucketsTransform should allow text transforms

### ISSUE THREAD

**Issue by bradennapier** [searchkit/searchkit#504]
Awesome package!  Thanks for your hard work on this!

While `bucketsTransform` does allow transforming values in a way that allows changing the labels but not the underlying search query.  For example,  in my case I have "IDS" that I want to render as the name of the value it actually points to.  

If I use bucketsTransform to adjust the label then the search itself will fail because it changes the search to use the new term.  

If I use the itemComponent to handle the rendering of the text then it works but the "selected filters" now shows the ID instead of the new name of the item.

So the only solution is to have a HUGE switch for everysingle possible filter and combination to try to accomplish this.

Instead, we should be able to transform the buckets by adding a "label" key to a bucket to adjust the DISPLAY while maintaining the underlying value that is used for search.

![image](https://user-images.githubusercontent.com/15365418/29690662-b1ad02fa-88dc-11e7-8fd0-fde01b33ef92.png)

Essentially I would like to be able to specify the transform like this:

```js
bucketsTransform: <T: Object>(buckets: Array<T>): Array<T> => {
          const { data } = this.props;
          if (data && data.projects) {
            const { projects } = data;
            return buckets
              .map(bucket => {
                if (projects[bucket.key]) {
                  return {
                    ...bucket,
                    label: _.get(projects, `${bucket.key}.meta.name`, bucket.key),
                  };
                }
                return bucket;
              })
              .sort((a, b) => a.label.localeCompare(b.label));
          }
          return buckets;
        }
```

Either that or we need some sort of way of transforming back into the raw value before the query executes but that would be far more complex and probably wouldn't really work in the grand scheme of things.

I also would rather not have to index the names as well as it will add a ton of extra data to the index that doesn't really need to be there.

**Comment by ssetem** [comment]
I need to look bit deeper.

One solution is to provide translate function to the GroupedSelectedFilters component

it should allow you to translate the value

**Comment by joemcelroy** [comment]
Another way is extending the
