### ISSUE TITLE
Document using-components.md outdated?

### ISSUE THREAD

**Issue by hsinewu** [searchkit/searchkit#509]
I'm new to this project and had some errors running the code in doc.

```jsx
ReactDOM.render((
    <SearchkitProvider searchkit={searchkit}>
    <div>
      <SearchBox/>
      <RefinementListFilter id="actors" field="actors.raw"/>
      <Hits/>
    </div>
    </SearchkitProvider>
),  document.getElementById('root'))
```
The doc says `This should render the standard searchbox and hits to the page.` but actually there is only searchbox.

Then I figured out I need to specify `hitsPerPage` attribute in order to show hits, cuz it's required.

Also, getting a warning: RefinementListFilter prop title required, although it still renders the filter.

**Comment by joemcelroy** [comment]
Thanks, yeh hitsPerPage should have a default value of 12 so shouldn't be required. Ill look into the issue.
