### ISSUE TITLE
ES5 Fielddata not enabled on text fields

### ISSUE THREAD

**Issue by jmrichardson** [searchkit/searchkit#510]
Hello,

When using the RefinementListFilter on a string field, I received the following error in the browser developer tools console:

```
POST http://localhost:9200/idrive/_search 400 (Bad Request)
SearchkitManager.js:205 Error: Request failed with status code 400
    at createError (createError.js:15)
    at settle (settle.js:18)
    at XMLHttpRequest.handleLoad (xhr.js:80)
```

The failure was related to this: https://www.elastic.co/guide/en/elasticsearch/reference/current/fielddata.html:

`Fielddata is disabled on text fields by default. Set fielddata=true on [your_field_name] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory.`

Enabling fielddata=true fixed the problem:

```
PUT idrive/_mapping/doc
{
  "properties": {
    "meta.title": { 
      "type":     "text",
      "fielddata": true
    }
  }
}
```

Is this the right thing to do given keyword support?

Thanks

**Comment by jmrichardson** [comment]
Using keyword.  Close

**Comment by dcworldwide** [comment]
See https://www.elastic.co/blog/strings-are-dead-long-live-strings
