### ISSUE TITLE
Help / Blank page on no search input

### ISSUE THREAD

**Issue by jmrichardson** [searchkit/searchkit#512]
Hello,

Can someone please help me figure out how to display a search help page when there is no text in the search box (no search hits with pagination).  Thanks for any help.

John

**Comment by jmrichardson** [comment]
Any help here?

**Comment by joemcelroy** [comment]
hey

Implement an initial loader: http://docs.searchkit.co/stable/components/basics/initial-loader.html and configure `searchOnLoad` to false in the searchkitManager configuration object.  http://docs.searchkit.co/stable/core/SearchkitManager.html
