### ISSUE TITLE
Update default query via searchbox

### ISSUE THREAD

**Issue by BorsukIvan** [searchkit/searchkit#515]
Hi could you help me with it!

in first render my component I create Searchkit Manager with
```javascript 
 searchkit.addDefaultQuery((query) => {
    return query.addQuery(BoolMust(TermQuery('name', 'value')))
}))
```
finish result is 

```javascript 
"query":{  
   "bool":{  
      "must":{  
         "term":{  
            "name":"value"
         }
      }
   }
}
```

then when I use serchbox I need to update my query to 

```javascript 
"query":{  
   "bool":{  
      "must":{  
         "term":{  
            "name":"value"
         }
      },
    "should":{  
         "term":{  
            "search":"searchValue"
         }
      }
   }
}
```

when I trying to update it via such parameters of SearchBox as queryBuilder  or queryFields 

for example queryBuilder function

```javascript 
function queryBuilder(searchValue) {
return BoolShould(TermQuery('search', searchValue))
}  
```
I get result like this

```javascript 
"query":{  
   "bool":{  
      "must":{  
         "term":[  
            "should":{  
               "term":{  
                  "search":"searchValue"
               }
            }
         ]
      },
   }}
```

How I should update on maybe rewrite query for searshkit manager ????

Thank you
Ivan Borsuk

**Comment by joemcelroy** [comment]
When you search, defaultQuery is no longer used. You will need your queryBuilder fn to include the defaultQuery aswell.

**Comment by Nostres** [comment]
Thank you @joemcelroy 
but how I should add the additional filter to the first request? 
How do I understand search kit manager send the first request when a mounting component, then when you use search box you can change it?

**Comment by ssetem** [comment]
Maybe try something along these lines

```jsx
<SearchBox                
        queryBuilder={(query, options)=> {
          if(query){
            return SimpleQueryString(query, options)
          } else {
            return BoolMust(TermQuery('name', 'someDefault'))
          }
        }}/>
