### ISSUE TITLE
React 16.0.0 Errors

### ISSUE THREAD

**Issue by bradennapier** [searchkit/searchkit#519]
```
warning.js:33 Warning: Invalid value for prop `className` on <div> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://fb.me/react-attribute-behavior
    in div (created by SearchBox)
    in form (created by SearchBox)
    in div (created by SearchBox)
    in SearchBox (at SearchBase.js:24)
    in div (at SearchBase.js:23)
    in div (at SearchBase.js:13)
    in SearchBase (at Search.js:412)
    in div
    in div
    in Unknown (at Search.js:411)
    in div
```

As far as I can tell, the bemBlocks feature is 100% broken.  None of my classes are added anymore.  Was perfect before:

![image](https://user-images.githubusercontent.com/15365418/30890031-0b1500e2-a2df-11e7-9f91-90760a18155d.png)

**Comment by chrisfinch** [comment]
Cause of error is this: https://github.com/albburtsev/bem-cn/issues/43

**Comment by chrisfinch** [comment]
Solution could be to upgrade `bem-cn`?

**Comment by kud** [comment]
By the way, the pagination components is obsolete with this latest react version. classNames aren't in the DOM so no style on the component.

**Comment by joemcelroy** [comment]
Yeh a few people have mentioned issues with React 16 and bem-cn library. Il try and upgrade soon.

**Comment by kud** [comment]
I hoped updated myself the lib via `npm install bem-cn --save` resolved it but no. Sad.

**Comment by ssetem** [comment]
@bradennapier 

I am going to debug this ASAP, also working on other react 16 compat issues

**Comment by ssetem** [comment]
cool, almost fixed in the core now, so doesn't require toString()

**Comment by ssetem** [comment]
@chrisfinch @kud @bradennapier 
I have just pushed beta version 2.3.0-0

hopefully it is react 16 compat, with fix to Bem also

possible to try it out?

thanks!

**Comment by kud** [comment]
Cool, I'll try it tomorrow at work. :)

**Comment by chrisfinch** [comment]
@ssetem great work! Have tested this with my project and can say anecdotally that it seems to work fine alongside react 16. Will be going further in depth this week and will report back on any weirdness.

**Comment by Phocea** [comment]
Hello, Is there any effort planned to push a React 16 compatible version to npm ?
Searchkit is the last of the component we use in our application which is not ready for React 16.x.
Is there a @next branch we could grab from now with that beta maybe?

**Comment by ssetem** [comment]
Hi Greg,

v2.3.0 should be v16 compat

**Comment by Phocea** [comment]
Thanks Ash. I actually realised this (got wrong information from my team), which is why I removed my comment.

We are going to try it out asap
________________________________
