### ISSUE TITLE
Doc about listComponent on Pagination is clearly needed

### ISSUE THREAD

**Issue by kud** [searchkit/searchkit#528]
There's no doc to custom listComponent on Pagination.

I don't mind as I read directly the code and did my own listC and itemC but for people who need more help, it could be great.

**Comment by joeldavuk** [comment]
Agree, there's no way to easily show the current page e.g the template I'm working to has < currentPage > 

had to extend Pagination and override the render method

`   let pages = this.getPages();
        pages.splice(1,0,{disabled: false, key: "current", label:pages[pages.length - 1].page - 1, page: pages.length - 1});
`
passing that to items in the renderComponent
