### ISSUE TITLE
How to change and translate SearchBox button label?

### ISSUE THREAD

**Issue by hkirsman** [searchkit/searchkit#531]
I could not find any option for that. I understand that the default theme is using icon for the button but some might want to use text.

**Comment by ssetem** [comment]
Seems to be hardcoded atm, we will introduce translation for button

**Comment by ssetem** [comment]
@hkirsman this should be fixed in beta 2.3.0-0
have added the 'search.button' translation
```jsx
<SearchBox translations={{'search.button':"My button"}} ..... />
```

possible to test when you get a chance?
Thanks!

**Comment by hkirsman** [comment]
I get error: 

TypeError: Cannot read property 'object' of undefined
Object../node_modules/rc-align/lib/Align.js
node_modules/rc-align/lib/Align.js:53
  50 | displayName: 'Align',
  51 | 
  52 | propTypes: {
> 53 |   childrenProps: _react.PropTypes.object,
  54 |   align: _react.PropTypes.object.isRequired,
  55 |   target: _react.PropTypes.func,
  56 |   onAlign: _react.PropTypes.func,
View compiled
__webpack_require__
/Users/hannes/Sites/vap-ria/sites/default/modules/contrib/simple_elasticsearch/js/app/webpack/bootstrap 2c5ad5ee92ceabe3c637:669
  666 | };
  667 | 
  668 | // Execute the module function
> 669 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  670 | 
  671 | // Flag the module as loaded
  672 | module.l = true;
...

**Comment by ssetem** [comment]
could you try a clean npm install on your project?

**Comment by hkirsman** [comment]
Is there also prefered npm I should be using?

**Comment by ssetem** [comment]
Npm 5 or yarn is good, just make sure you delete node_modules first

**Comment by hkirsman** [comment]
Npm 5 is enough or 6, 7 and 8 also work? I discovered today that my sass was compiling really strange with npm 6 so I upgraded it to 7

**Comment by ssetem** [comment]
I think you meaning node version, best to use latest node 8.x, and latest npm 5.x

**Comment by hkirsman** [comment]
Tx, It works! Only that it's not search.button but searchbox.button.

Also, I didn't get it working when I deleted node_modules and yarn.lock and generating the node_modules with yarn again. Instead I changed the versions in yarn.lock

      searchkit@^2.3.0-0:
    -  version "2.3.0-3"
    -  resolved "https://registry.yarnpkg.com/searchkit/-/searchkit-2.3.0-3.tgz#a876384b996ecb5cb88a4f0015714ddbd5bbe439"
    +  version "2.3.0-4"
    +  resolved "https://registry.yarnpkg.com/searchkit/-/searchkit-2.3.0-4.tgz#a876384b996ecb5cb88a4f0015714ddbd5bbe439"

I don't know what's wrong. It's still 2.3.0-4 in yarn but some other thing is breaking it. The error is:

    Module not found: Error: Can't resolve 'searchkit' in '../src'
