### ISSUE TITLE
The DynamicRangeAccessor doesn't use the rangeFormatter to format the min/max.

### ISSUE THREAD

**Issue by richtera** [searchkit/searchkit#533]
https://github.com/searchkit/searchkit/blob/689737cec96c762f3da417ffe190c8653ec4f285/src/core/accessors/DynamicRangeAccessor.ts#L46

The dynamic range shows up without passing the numbers through the rangeFormatter when displaying the filter item.

**Comment by ssetem** [comment]
yep, this needs fixing, and also selected filters using rangeFormatter.

**Comment by ssetem** [comment]
@richtera 
this should be fixed now in beta version 2.3.0-0

thanks!

**Comment by richtera** [comment]
Works in 2.3.0-0

**Comment by richtera** [comment]
FYI I forked a built version to npm install "git+https://github.com/richtera/searchkit.git#develop"
