### ISSUE TITLE
Query autocompletion 

### ISSUE THREAD

**Issue by tienthanhdhcn** [searchkit/searchkit#539]
Is this possible to have a query autocompletion function with the search box?

**Comment by ssetem** [comment]
yep, this is on our list, hopefully in near future

**Comment by TheDolo** [comment]
This one is the bees knees :) + 1 million

**Comment by yassminesakhri** [comment]
Hello, 
Can i use elasticsearch 5.6 with searchkit ? 
i'am actually using ES 2.4.3 and i would like to upgrade it to ES 5.6.2
 Will searchkit still be working? 
thanks
