### ISSUE TITLE
Geographical Filter

### ISSUE THREAD

**Issue by driesvancraen** [searchkit/searchkit#54]
A filter where there is searched on a range around a postal code. (10km, 50km, 100km, ...)
We have lat & long float's that can be searched with a Maps API.

https://developers.google.com/maps/documentation/distance-matrix/intro

![image](https://cloud.githubusercontent.com/assets/1028036/12718374/8c26c5ac-c8ee-11e5-9f9d-902bb1f38927.png)

**Comment by joemcelroy** [comment]
closing this issue, linked to this #236
