### ISSUE TITLE
How to customize "see more / less" on facet?

### ISSUE THREAD

**Issue by kud** [searchkit/searchkit#544]
I could use classes but there's not class added when it's "see more" or "see less".

**Comment by TheDolo** [comment]
Yea this is one of the irks with SK.  I too also want to customize every rendered component, yet few have the ability to be passed custom components.  To the source!

**Comment by ssetem** [comment]
We can look into adding a class when refinement component is expanded

**Comment by joemcelroy** [comment]
thanks @devolt5 for reminding. I will try look over it this weekend and give you feedback.
