### ISSUE TITLE
Suggestions on how to update elements?

### ISSUE THREAD

**Issue by wirtsi** [searchkit/searchkit#545]
Hi all

this is not really a bug but rather me being unable to understand how SearchKit works.

I am working on a system where the returned entities should be updatable. Ie., I can click on an item and this opens a form which allows editing the data (with validation, ajax file uploads etc). The data is then sent to ES which should update the entry, changes should be displayed.

So in my mind this would require copying the props of an item to the state of a modal/form thingy. How would I go about to feed the changes back into SearchkitManager so that my list re-renders when I close the modal?

I obviously want to keep this  in sync with how SearchKit works. I kind of fail to understand how changes in the returned hits are fed into the components. There are the accessors which appear to receive the new results and there is an Event emitted. But why is eg. <Hits /> using the getHits method on the SearchkitManager instead of having it passed in through the props.

Bests & thanks for any advise

Wirtsi

**Comment by TheDolo** [comment]
You might be better off using an REST API to call which using ES Index API to add/edit the result (upsert).  Then reload search and it should appear, rather than calling the ES Index add/edit (waiting for confirmation of success) and removing it from local SK state.

**Comment by ssetem** [comment]
Yeah I agree that reloading the search when you feel something has changed is the safest.

we have an api `searchkitInstance.reloadSearch()`

**Comment by wirtsi** [comment]
Cool, thanks for the suggestions ... I will go that way then.

 Just one last thing, how do Searchkit components know that they should re-render? 

Since they all derive from PureComponent and they receive SearchkitManager as their context, the only thing that changes is SearchkitManager is loading true/false. Is this what triggers a redraw?

Bests & Thanks!

**Comment by ssetem** [comment]
other state changes also, like state, results, loading, error

**Comment by wirtsi** [comment]
@ssetem helped me in the chat, thanks for the support!
