### ISSUE TITLE
Documentation requested: Full usage example with CDN and no transpiler

### ISSUE THREAD

**Issue by jameskhamil** [searchkit/searchkit#546]
Documentation requested: Full usage example with CDN and no transpiler

Documentation with a quick start via CDN should be the first working example, IMO. It would be nice to know how to hack around without having to dip into a build system immediately.

**Comment by ssetem** [comment]
Yep
```html
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/searchkit@2.2.0/release/theme.css">
  <script type="text/javascript" src="//cdn.jsdelivr.net/npm/searchkit@2.2.0/release/bundle.js"></script>
```

```js
SearchkitManager = Searchkit.SearchkitManager
```
