### ISSUE TITLE
RangeInput needs searchOnChange

### ISSUE THREAD

**Issue by ghost** [searchkit/searchkit#548]
From docs: "Range component containing only min/max input fields. Requires pressing "Go" to update the filter."

Why do all other inputs get searchOnChange?  Including most Range Components!

**Comment by ssetem** [comment]
We did initially have searchOnChange, but we felt the UX was too jarring, 
I do see a case perhaps for search onBlur but we need to look into it.

**Comment by TheDolo** [comment]
Thanks for the reply!  I understand exactly what you mean in the bullet point.  onBlur would be nice, I think I'm going to try trigger a search once the user is done typing vs every letter.
