### ISSUE TITLE
Is it possible to remove the "All" tab from the tabs MenuFilter?

### ISSUE THREAD

**Issue by jmrichardson** [searchkit/searchkit#550]
I would like to be able to remove the All tab when using the MenuFilter:

```
           <MenuFilter
              field="_type"
              id="tabs"
              listComponent={Tabs}
             />
```

Is this possible?  Thanks

**Comment by ssetem** [comment]
@jmrichardson not without extending some components, It wouldn't be a lot of code.

But which tab will be selected by default, the All tab is useful to always have something selected

**Comment by jmrichardson** [comment]
Thank you for your response.  I was able to remove the all tab with the code below (not sure if this is a good way to do it or not).  But, I am having trouble with selecting the default tab (as you mentioned above).  I can't figure out where that is done in the code?  Can you point me in the right direction?

Thanks for any help and here is the code I used to remove the all tab:

```
export class NewMenuFilter extends MenuFilter {
  getItems() {
    var obj = super.getItems()
    var i
    for (i in obj) {
      if (obj[i].label === "All") {
        obj.splice(i,1)
      }
    }
    return (obj)
  }
}
```

**Comment by jmrichardson** [comment]
I got the following to work:

```
const isUndefined = require("lodash/isUndefined")
export class NewMenuFilter extends MenuFilter {

  getSelectedItems() {
    let selectedValue = this.accessor.state.getValue()[0]
    return [!isUndefined(selectedValue) ? selectedValue:"Documents"]
  }

  getItems() {
    var obj = super.getItems()
    var i
    for (i in obj) {
      if (obj[i].label === "All") {
        obj.splice(i,1)
      }
    }
    return (obj)
  }
}
```
