### ISSUE TITLE
Why does <SearchBox> searchOnChange={false} still search when you unfocus input?

### ISSUE THREAD

**Issue by hkirsman** [searchkit/searchkit#554]
I was pulling my hair trying to understand why it still auto-searches, not realising it works only for typing. As soon you unfocus the input, search is triggered.
So basically if you press the button, the search is triggered because of unfocus, not because there's an actual click event on button?
I guess I was expecting behaviour more similar to plain old php scripts.

**Comment by ssetem** [comment]
it shouldn't be behaving like that, when searchOnChange is false it should search on submit when you press enter key
