### ISSUE TITLE
How do you make 2 different field conditions on Elasticsearch 5?

### ISSUE THREAD

**Issue by hkirsman** [searchkit/searchkit#555]
Here's http://docs.searchkit.co/stable/setup/default-query.html an example that is using FilteredQuery and it's using the same field. I need to filter by 2 fields: type and language.
Also I understand filtered query is deprecated:
https://www.elastic.co/guide/en/elasticsearch/reference/5.5/query-dsl-filtered-query.html

So say I want to select type=news and lang=en then, how would you write the default query for ES5?

**Comment by ssetem** [comment]
i think can do this

```js
searchkit.addDefaultQuery((query)=> {
  return query.addQuery(
    TermQuery("type", "news"),
    TermQuery("language", "en"),
  )
})
```

**Comment by hkirsman** [comment]
Only the first is set in actual query: TermQuery("type", "news"),

    {"query":{"term":{"type":"news"}},"aggs":{"type-filter3":{"filter":{"match_all":{}},"aggs":{"field_news_subject":{"terms":{"field":"field_news_subject","size":50,"order":{"_term":"asc"}}},"field_news_subject_count":{"cardinality":{"field":"field_news_subject"}}}},"years-filter4":{"filter":{"match_all":{}},"aggs":{"year_when_created":{"terms":{"field":"year_when_created","size":50,"order":{"_term":"desc"}}},"year_when_created_count":{"cardinality":{"field":"year_when_created"}}}}},"size":20,"_source":["title","simple_elasticsearch_teaser"]}

**Comment by ssetem** [comment]
oh yeh forgot to add the BoolMust or BoolShould

```js
searchkit.addDefaultQuery((query)=> {
  return query.addQuery(
    BoolMust([
      TermQuery("type", "news"),
      TermQuery("language", "en"),
    ])
  )
})
```

**Comment by hkirsman** [comment]
Wow, I must have tried something similar many times but your code works. Thank you!

1 more question. Here the last example: https://ssetem.gitbooks.io/searchkit/docs/core/ImmutableQuery.html

It must be
    new ImmutableQuery(). setSort([
not
    new ImmutableQuery().setSize([  
right?

**Comment by ssetem** [comment]
yep it is a type, I need to overhaul some of this documentation
