### ISSUE TITLE
Allow RefinementListFilter to display 0 count filters?

### ISSUE THREAD

**Issue by mcastre** [searchkit/searchkit#562]
Hello all!

I'm not sure if this issue has been looked at or opened already, but I was wondering if searchkit allowed the ability to show checkbox filters inside the `RefinementListFilter` even if they have 0 counts? Currently, in order to bypass this behavior, I have to add each individual `CheckboxFilter` instead of using the `RefinementListFilter`.

Thank you!

**Comment by ssetem** [comment]
@mcastre its not currently configurable by a prop, but you can extend an existing class and use it like a `RefinementListFilter`
```jsx
import { RefinementListFilter } from "searchkit"

export class CustomRefinementListFilter extends RefinementListFilter {
    getAccessorOptions(){
        return Object.assign({
            min_doc_count:0
        }, super.getAccessorOptions())
    }
}

//<CustomRefinementListFilter ...../>
```

**Comment by mstalfoort** [comment]
To be honest, I could use a more worked out example then showed here since I'm also struggling with this issue.
What I'm trying to achieve is to have the 0 count checkboxfilter to render as disabled yet visible to the user so any further help on this issue would be very much appreciated

**Comment by mcastre** [comment]
+1
