### ISSUE TITLE
Feature Request: Combine stores

### ISSUE THREAD

**Issue by florianbepunkt** [searchkit/searchkit#564]
Can I combine the searchkit store with my own redux store? If so, I haven't seen this in the docs, how can this be done? If not, please see this as a feature request.  Thanks.

**Comment by ssetem** [comment]
@florianbepunkt 
Which components do you need to connect with redux?

You can use a connected component for Hits and should work

**Comment by florianbepunkt** [comment]
@ssetem I would like to have the hits and all apllied filters in my store. Can you give me a bare-bones example?

**Comment by ssetem** [comment]
The filters state is managed in searchkit, would require custom code to sync state with redux

**Comment by Fluorz** [comment]
+1
