### ISSUE TITLE
Switching between two hits displays. how to get the hit results to rerender? 

### ISSUE THREAD

**Issue by xinghengwang** [searchkit/searchkit#565]
__background:__

I have two views for displaying the same results. (basically two different ways of display or visualizing the same data results). 

So I have some thing like this: 

```
                  {
                    this.state.displayType === 'A' ? (
                      <SearchResultsDisplayA  />
                    ) : (
                      <div>
                        <SearchResultsDsiplayB />
                      </div>
                    )
             }

```

Of course, I have a switch to switch from one displayType to another. 
SearchResultsDisplayA and B are both implemented very similiarly like this: 

```
class SearchResults extends SearchkitComponent {
  componentDidMount() {
    const { location } = this.props;
    this.forceUpdate();
  }

  render() {
    return (
      <div>
        <Pagination showNumbers />
        <div className="tutorial-search-results">
          <Hits hitsPerPage={50} itemComponent={HitEvent} scrollTo={false} />
          <NoHits
            translations={{
              'NoHits.NoResultsFound': 'No results found. '
            }}
          />
        </div>
        <Pagination showNumbers />
      </div>
    );
  }
}
```

**Problem:** 
On intial load, the results are rendered fine. but when I switch back from A to B, and then from B to A. All the hits disppears.  

I think the issue is that the <HIts> does not render with the existing results, when it is re-mounted. 

**Question**
What is the best solution to get to re-render?  (I want to avoid reloadSearch, because it seems to reset all the search filters and reset the url). 

Thanks.

**Comment by xinghengwang** [comment]
I wrote a custom reload search function to force search regardless if the "query state" changed or not. Bit hacky that seems to solve the problem.

**Comment by ssetem** [comment]
@xinghengwang you can also use ViewSwitcherHits
