### ISSUE TITLE
Set Default Filter Options

### ISSUE THREAD

**Issue by bleep-io** [searchkit/searchkit#569]
How can I set default filter options - instead of just defaulting to all?

**Comment by ssetem** [comment]
have you got an example of what you would default too

**Comment by bleep-io** [comment]
Yes I'd like to do something like this:

`<MenuFilter
                field="hidden.keyword"
                title="Hidden"
                id="hidden"
                default="true"
                />`

**Comment by ssetem** [comment]
Still not understanding the usecase, have you looked at the `CheckboxFilter`?

**Comment by bleep-io** [comment]
So in my UI if I load it as a checkbox it looks like this and will default to "ALL"

![image](https://user-images.githubusercontent.com/1321647/32897668-262ddc6a-cade-11e7-8a65-8bf68995e548.png)

I would like it to default to "Hidden"

**Comment by ssetem** [comment]
cool I see now

**Comment by ssetem** [comment]
right now only way is through the url until we implement the feature.

**Comment by bleep-io** [comment]
Thanks never thought of that!
