### ISSUE TITLE
Search after minimal characters 

### ISSUE THREAD

**Issue by BorsukIvan** [searchkit/searchkit#570]
I wanna ask about Search Box configuration, Do we have the ability to call search request after user input minimum number of approved characters?

for example
if minimal is 2

when I input 'ab' - do nothing
after when I input 'abc' then call search request

**Comment by ssetem** [comment]
@BorsukIvan not currently as a prop,
but you can implement custom queryBuilder, with if statement

**Comment by BorsukIvan** [comment]
@ssetem 
What should I do in this case? 
don't return anything, right?

**Comment by ssetem** [comment]
yep, I think return null or undefined and it should work

**Comment by BorsukIvan** [comment]
@ssetem 
Thanks it works!
