### ISSUE TITLE
Remove query dynamically

### ISSUE THREAD

**Issue by DavidMagem** [searchkit/searchkit#575]
I want to dinamically  create or remove a query from searchkit. I manage to create the query but I don't find the way to delete the query. Does anyone have an example of how to delete a query created previously?

var listID = ["1", "2", "3"];
searchkit.addDefaultQuery((query)=> {
      return query.addQuery(TermsQuery("numberID", listID));
})

**Comment by joemcelroy** [comment]
`addDefaultQuery` isn't designed for this. Its for adding queries that never change. `Query Processor` might be better fit for your usecase as executed on every search. 

What do you need to do exactly? How is `listIds` provided and when does it need to be toggled on and off? Could it be done in a custom Searchkit filter component?

**Comment by DavidMagem** [comment]
I want to filter through a list of items in an array that is not in ElasticSearch. For this reason I can not use a Searchkit filter and I do not want to use the SearchBox either. The behavior would be closer to being able to activate or deactivate the user request through a UI component that incorporates a query or can remove it on user request.
Maybe an alternative would be to use a CheckBoxFilter? but I preferred to be able to control how to present the list of items to filter in the UI.
Is there a simple example of the setQueryProcessor?

**Comment by joemcelroy** [comment]
Yeh i would use a CheckboxFilter or build a custom filer component for this. Then you can control the filter UI visibility. Its fairly easy to build your own filter. Have a look at a custom filter component (https://github.com/GregoryPotdevin/searchkit-daterangefilter/tree/master/src)

have a look at `setQueryProcessor` in docs http://docs.searchkit.co/stable/core/SearchkitManager.html

**Comment by DavidMagem** [comment]
A CheckboxFilter just work great!
Thanks for your help!
