### ISSUE TITLE
Using github fork with lerna monorepo

### ISSUE THREAD

**Issue by jayshah123** [searchkit/searchkit#576]
I recently forked searchkit at 2.3.0-9 and modified it to use only "core" to see if it works with react-native, the problem is using github url as npm dependency -
 https://github.com/jayshah123/searchkit/tree/rn2.3.0-9, 

But being a monorepo, it doesn't work as expected to install searchkit/packages/searchkit. There is a long standing issue in npm https://github.com/npm/npm/issues/2974 but without any action to support install github fork at subdirectories. 

Is there anyway to work around this problem? I am relatively new to lerna and npm ecosystem.
Or should I fork it at a point before it turned into a monorepo style?

**Comment by joemcelroy** [comment]
if you want searchkit core, i believe you should be able to navigate to the core folder on searchkit via import, for example  `import { SearchkitManager } from 'searchkit/lib/core'`. Make sure you use the latest searchkit `npm install searchkit@beta --save`

**Comment by jayshah123** [comment]
Works like a charm. Thanks!
I'll update any progress regarding use in react native in https://github.com/searchkit/searchkit/issues/357.
