### ISSUE TITLE
Not working in IE

### ISSUE THREAD

**Issue by tienthanhdhcn** [searchkit/searchkit#577]
Thanks guys for a great job but I don't know why it is not working on IE (9 and 11).
Please can you let me know why and how to fix it?

**Comment by joemcelroy** [comment]
what is the error? I would assume it needs babel-polyfill to be included on the page for legacy browsers

**Comment by motordigital** [comment]
Hello. Regarding IE11: It even does now run on your public website examples.
![bildschirmfoto 2018-02-18 um 22 41 28](https://user-images.githubusercontent.com/2326534/36357344-e932719a-14fc-11e8-82e7-583ca3d57e78.png)

**Comment by motordigital** [comment]
The hint of @joemcelroy is valid and adding babel polyfill solves the compatibility issue on ie11.
