### ISSUE TITLE
Feature request: Recent/saved searches

### ISSUE THREAD

**Issue by arnvol** [searchkit/searchkit#580]
A saved searches component would be really useful. Twitter has an easy to use component for this, could be used as an inspiration. In addition to twitters functionality I would like to be able to give a name to the saved search. The saved searches menu should perhaps not be tied to the search box, the menu could optionally be opened by another UI element.  In my solution we are not using the search box component.

Twitters recent/saved searches:
![image](https://user-images.githubusercontent.com/20162988/33663010-8ab66fca-da8e-11e7-8127-6ea5ad9292a4.png)

**Comment by jmrichardson** [comment]
+1
