### ISSUE TITLE
Problems updating searchKit

### ISSUE THREAD

**Issue by richtera** [searchkit/searchkit#581]
It looks like the SearchKitProvider doesn't re-initialize correctly when passing in a new searchKit it props. i.e. there is no support for componentWillReceiveProps and in fact the searchKit is captured only once and then used. Trying to update searchKit or defaultQuery needs a bunch of hacks.
For example our site has a user roles which can be changed from a menu. Changing the menu will create a new searchKit with a new defaultQuery, but SearchKitProvider will keep returning the old searchKit even though the provider is passed
```javascript
... searchKit={this.state.searchKit} ...
```

**Comment by arnvol** [comment]
Which version of searchkit are you using? Don't know if it's related but going from 2.2.0 to 2.3.0 introduced a problem for me. I'm using searchOnLoad, but in version 2.3.0 it doesn't search on load the second time I open the search view, in 2.2.0 it does.

**Comment by richtera** [comment]
I am using latest. It's not that it doesn't load the second time when I go to the page. My problem is that I am providing the searchkit using mobx or redux and I want the page to search again if the manager interface changes. But looking at the code the searchkitprovider doesn't handle componentWillReceiveProps
