### ISSUE TITLE
what data structure i need?

### ISSUE THREAD

**Issue by Bonobomagno** [searchkit/searchkit#583]
I'm pretty new on ES and i still miss the defined data structure to search. How is defined on searchkit? also, there is a demo data for populate a localhost ES instance?
thanks

**Comment by joemcelroy** [comment]
hey this is the indexer we use for the movies demo (https://github.com/searchkit/searchkit-demo/blob/master/movie-index/indexer.coffee).

**Comment by Bonobomagno** [comment]
i see, but that demo is old, did this is still up to date with version 2?

**Comment by joemcelroy** [comment]
Yep this is still up to date with version 2. It more of a question with compat with Elastic search 6. ATM our demo site runs on ES5.4
