### ISSUE TITLE
Feature request:  Dynamic input/refinement filter

### ISSUE THREAD

**Issue by jmrichardson** [searchkit/searchkit#586]
Would really like to have the ability to dynamically switch from an InputFilter to a RefinementListFilter based on record count.  Currently, because there are too many options for a select/checkbox refinement filter, I use an inputfilter.  However, as the number of records drop to a certain amount, would like to dynamically switch to a RefinementListFilter.

Thanks for your consideration

**Comment by ssetem** [comment]
hi @jmrichardson 

maybe could try our beta version `@searchkit/refinement-autosuggest`
```bash
npm install @searchkit/refinement-autosuggest@0.0.1-6
```
```js
import {
    RefinementAutosuggest
} from "@searchkit/refinement-autosuggest"
```


```js
<RefinementAutosuggest
       id="actors"
       title="Actors"
       field="actors.raw"
       multi={true}
  />```

**Comment by ssetem** [comment]
this is clip of how it works

![ezgif-5-2ebb060900](https://user-images.githubusercontent.com/703938/32674418-1aa6f24c-c64b-11e7-9f1c-2b221576949b.gif)

**Comment by jmrichardson** [comment]
Thank you @ssetem , that looks really nice :) I actually have that functionality with the searchkit-multiselect from Gregory Potdevin.  However, I was hoping for more of a dynamic way to change from your RefinementAutosuggest to a RefinementList Checkbox.  So lets say there are 100 different/unique platform choices in your example, it would initially be a RefinementAutosuggest as well as for the others.  Then, when you refine the search, when any of the select boxes become less than say a definable number of choices say 7, it displays checkboxes/radios.
