### ISSUE TITLE
Nested list query

### ISSUE THREAD

**Issue by arnvol** [searchkit/searchkit#592]
Hi, looking for a suggestion to solve a bit of a complex query. Given the following structure for the type "item", with nested properties: 

```
{
    "_index": "test",
    "_type": "item",
    "_id": "101058132",
    "_source": {
        "id": "101058132",
        "details": {
            "parts": [
                {
                    "size": "small",
                    "color": "blue",
                },
                {
                    "size": "medium",
                    "color": "red",

                }
            ]
        }
    }
}
```

I've got two RefinementListFilters for size and color, and I would like to list all items that has one or more parts which are both small and red. The listed item above should not give me a hit since not one single part is both small and red. Searchkit produces the following query: 

```
{
	"post_filter": {
		"bool": {
			"must": [{
				"nested": {
					"path": "details.parts",
					"query": {
						"term": {
							"details.parts.size": "small"
						}
					}
				}
			},
			{
				"nested": {
					"path": "details.parts",
					"query": {
						"term": {
							"details.parts.color": "red"
						}
					}
				}
			}]
		}
	}
}

```
Which gives me one hit and is not correct for my case. I would need the following query: 
```
{
	"post_filter": {
		"bool": {
			"must": [{
				"nested": {
					"path": "details.parts",
					"query": {
						"bool": {
							"must": [{
								"term": {
									"details.parts.size": "small"
								}
							},
							{
								"term": {
									"details.parts.color": "red"
								}
							}]
						}
					}
				}
			}]
		}
	}
}

```
Any ideas on how this could be accomplished? The structure of the type item is what it is. (The "item" is just a simplification of more complex type)
I'm guessing I would have to manually manipulate the query right before the search is executed, is there a property I can access with the query in plain text? Or is there perhaps a better way?

**Comment by Toksa** [comment]
Create new custom Accessor and use buildOwnQuery function where you can manipulate the query. In your RefinementListFilters use defineAccessor function to define your custom Accessor.

**Comment by arnvol** [comment]
Thanks a lot for your response Toksa! Sounds managable.

**Comment by arnvol** [comment]
I need some more advice. 
I've extended RefineMentListFilter and added a custom Accessor (FilterBasedAccessor<ArrayState> )
In buildSharedQuery in the accessor I'm adding a filter:
 query = query.addFilter(this.uuid, {
        bool: 
          {
            must: [
              {
                nested: {
                  path: 'details.parts',
                  query: {
                    bool: {
                      must: [
                        {
                          term: { "details.parts.size": "small" } //Needs to be set from filterTerms? 
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }        
      });

The QueryDSL with NestedQuery misplaced the nested part for my case so had to create object manually. So I have multiple custom RefinementListFilters. How would I add the next term. Only thing I can think of is to check for the existence of the filter and then try to add the next term as a sibliing to the first term. But this is ugly as hell, does anyone see a less ugly way to sew together the terms from multiple filters inside the must clause? Or just a completely different way of doing this :)

**Comment by arnvol** [comment]
Hmm, should perhaps try to change the NestedQuery function so that it meets my needs.

**Comment by chrishan1995** [comment]
For anyone who meet the same requirements, you can use [Query Processor](http://docs.searchkit.co/stable/core/SearchkitManager.html), which mutates the query just before its sent to ElasticSearch. 

Here is my implementation:
```
searchkit.setQueryProcessor(plainQueryObject => {
  // modify post_filter before sending to ElasticSearch
  if (plainQueryObject.post_filter && plainQueryObject.post_filter.bool && plainQueryObject.post_filter.bool.must) {
    const filters = plainQueryObject.post_filter.bool.must;

    const refinedFilters = filters.reduce((acc, filter) => {
      const pathOfMust = filter.nested && filter.nested.path;
      const pathOfShould = filter.bool && filter.bool.should && filter.bool.should[0].nested.path;
      if (pathOfMust) {
        acc[pathOfMust] = acc[pathOfMust] || {};
        acc[pathOfMust].musts = acc[pathOfMust].musts || [];
        acc[pathOfMust].musts.push(filter.nested.query);
      } else if (pathOfShould) {
        acc[pathOfShould] = acc[pathOfShould] || {};
        acc[pathOfShould].musts = acc[pathOfShould].musts || [];
        acc[pathOfShould].musts.push({ bool: { should: filter.bool.should.map(should => should.nested.query) } });
      }
      return acc;
    }, {});

    plainQueryObject.post_filter.bool.must = Object.keys(refinedFilters).map(path => {
      return {
        nested: {
          path,
          filter: {
            bool: {
              must: refinedFilters[path].musts,
            },
          },
        },
      };
    });
  }

  return plainQueryObject;
});
```
Hope it's not that ugly for you.
