### ISSUE TITLE
Docs are missing about advanced queries

### ISSUE THREAD

**Issue by kud** [searchkit/searchkit#599]
Hello,

Okay, we've got docs about ImmutableQuery and Query DSL builders, but in my point of view, it's not fully enough.

For instance, I would like to sort all my queries wit this:

```
{"position" : {"order" : "asc"}}
```

So I've tried this:

```
this.sk.addDefaultQuery(
      (query) => {
        query.addQuery(
          BoolMust([
            {"match": {"bill.id": billId}},
            {"match": {"step.position": stepPosition}},
          ])
        )

        query.setSort([
          {"position" : {"order" : "asc"}}
        ])

        return query
      }
    )
```

However, it doesn't work, it doesn't sort. I've got a result but without any sorting.

And to be honest, it's not the first time I spend times to understand how searchkit works on advanced method.

I've read the code of searchkit but it doesn't help me so much there.

Could you explain a bit more how to make queries and sorts via searchkit object?

**Comment by kud** [comment]
I've done something like this:

```
this.sk.setQueryProcessor((rawQuery) => {
        rawQuery.query = {
          "bool":
          {
            "must": [
            {
              "match":
              {
                "bill.id": nextMatch.params.billId
              }
            },
            {
              "match":
              {
                "step.position": nextMatch.params.stepPosition
              }
            }]
          }
        }

        rawQuery.sort = [
          { "position" : {"order" : "asc"} },
        ]

        return rawQuery
      })
```

which works.

I've replaced the default query by this. I don't see the point of defaultQuery to be honest.

I only use `setQueryProcessor` with an object `rawQuery` I could exchange between some calls of `setQueryProcessor`.

**Comment by omulriain** [comment]
Do you know how to just add MustNot from a list variable to the existing query that the other filters are updating. I can't really piece together how to add a custom part to the search kit query.
