### ISSUE TITLE
Extending SearchBox component

### ISSUE THREAD

**Issue by kdabo** [searchkit/searchkit#601]
Hi,

I see that some components have the feature to override the display component using the `itemComponent` props, however `SearchBox` is not one of them.

I was wondering if you were planning on adding support for this feature in the near future? 

Thank you in advance. :)

**Comment by chrisfinch** [comment]
@kdabo I'm not part of the searchkit team but if you want to do this you can simply extend the base `SearchBox` class with your own implementation like so:

```typescript
class MyCustomSearchBox extends SearchBox {

    // override the render method with your own
    render() {
        // ... be sure to follow the original implementation closely to make sure all the necessary event bindings are in place
    }
}
```

**Comment by kdabo** [comment]
@chrisfinch thank you for your help! I am going to give it a try!
