### ISSUE TITLE
React16 async ComponentWillUnmount + accessor addition/removal bug

### ISSUE THREAD

**Issue by chrisfinch** [searchkit/searchkit#602]
My team has encountered this issue today whilst working on a refactor of our application using searchkit.

Moving parts involved:
Searchkit v2.3.0
React v16.2.0
ReactRouter v4.2.0 

## Problem

Consider this codepen: https://codesandbox.io/s/08o3y7wxv

When re-rendering components (due to react-router route change) [this error is hit](https://github.com/searchkit/searchkit/blob/develop/packages/searchkit/src/core/AccessorManager.ts#L50): `Only a single instance of BaseQueryAccessor is allowed`

This occurs because `componentWillMount` and `componentWillUnmout` from [`SearchkitComponent`](https://github.com/searchkit/searchkit/blob/develop/packages/searchkit/src/core/react/SearchkitComponent.ts#L70) are no longer guaranteed to occur in synchronous order in React 16: https://github.com/facebook/react/issues/11106

The new entering instance of `SearchkitComponent` fires `componentWillMount` before the old exiting instance fires `componentWillUnmout` and when this component is an instance of `SearchBox` the above error is generated.

[React devs advise against side effects](https://github.com/facebook/react/issues/11106#issuecomment-344573660) in `componentWillUnmout` - I can see why it's necessary here but in order to continue working with future versions of react Searchkit will need to work with asynchronous rendering.

In order to work around this issue I've patched the `AccessorManger` runtime in the following way (see comments on 5th line onwards):

```javascript
// Searchkit overwrite
AccessorManager.prototype.add = function(accessor) {
    if (accessor instanceof StatefulAccessor) {
        if (accessor instanceof BaseQueryAccessor && accessor.key == 'q') {
            if (this.queryAccessor !== noopQueryAccessor) {
                // In this scenario no longer throw this error: `new Error("Only a single instance of BaseQueryAccessor is allowed")`.
                // Instead remove current queryAccessor if it exists
                // Then use new queryAccessor due to asynchronous rendering in React16 (https://github.com/facebook/react/issues/11106)
                this.remove(this.queryAccessor);
                this.queryAccessor = accessor;
            } else {
                this.queryAccessor = accessor;
            }
        }
        let existingAccessor = this.statefulAccessors[accessor.key];
        if (existingAccessor) {
            if (existingAccessor.constructor === accessor.constructor) {
                existingAccessor.incrementRef();
                return existingAccessor;
            } else {
                throw new Error(
                    `Multiple imcompatible components with id='${
                        accessor.key
                    }' existing on the page`
                );
            }
        } else {
            this.statefulAccessors[accessor.key] = accessor;
        }
    }
    accessor.incrementRef();
    this.accessors.push(accessor);
    return accessor;
};
``` 

Unfortunately due to our app structure it's not possible to render searchkit and subcomponents outside of react-router and as such re-rendering is unavoidable.

Open to suggestions of a better workaround, but from what I can see this will need a fix in Searchkit itself.

Thanks again for the hard work on a great library. Happy to collaborate on a PR pending discussion here.

cc @andygout

**Comment by chrisfinch** [comment]
@ssetem @joemcelroy would be great to get some feedback on this if you guys have a spare moment - even if the feedback is 'we're too busy so this will have to wait for now'!

If so when I find some availability myself I'll work on a PR.

Thanks!

**Comment by joemcelroy** [comment]
@chrisfinch Could you find some availability to work on this PR? Been on my list to review this issue but haven't had time. Thanks btw for going indepth into the issue.

**Comment by chrisfinch** [comment]
@joemcelroy up against it with deadlines right now but might have some downtime in a couple of weeks 👍
