### ISSUE TITLE
Getting started docs have broken links and appear outdated

### ISSUE THREAD

**Issue by davidklebanoff** [searchkit/searchkit#603]
I was curious about Searchkit, so I started to follow the [Getting Started docs](http://docs.searchkit.co/stable/setup/project-setup.html). It seems the documentation is a bit outdated.

1. The first link on the page, "searchkit boilerplate" leads to a 404. I'm not sure if it's supposed to be referencing the [component-boilerplate](https://github.com/searchkit/component-boilerplate), [searchkit-examples](https://github.com/searchkit/searchkit-examples), or perhaps something that simply doesn't exist anymore.

1. The official docs [here](http://docs.searchkit.co/stable/), imply the latest version is 2.0.0. However, the "CDN Script include" section in the [Getting Started docs](http://docs.searchkit.co/stable/setup/project-setup.html) references 0.10.0, meanwhile [jsdelivr](https://www.jsdelivr.com/?query=searchkit) and [github](https://github.com/searchkit/searchkit/releases) show the latest version as 2.3.0, [component-boilerplate](https://github.com/searchkit/component-boilerplate) is using ^0.8.0. [searchkit-examples](https://github.com/searchkit/searchkit-examples) is using ^2.3.0-3.

1. The [Getting Started docs](http://docs.searchkit.co/stable/setup/project-setup.html) "use" section is missing? The title is there, but there is no content.

**Comment by joemcelroy** [comment]
Yeh documentation is getting out of sync with the current code base. We wanted to do a documentation overhaul on a brand new site. Still WIP as usual.
