### ISSUE TITLE
Reduce Lodash bundle size

### ISSUE THREAD

**Issue by dcworldwide** [searchkit/searchkit#605]
I've used webpack-bundle-analyzer to analysis my build and have noticed the dependency on lodash is large comparative to the size of searchkit itself. 

Will we see reduced library size if we switch from importing the entire lodash library, to using function specific imports? I.e. https://www.npmjs.com/package/lodash.debounce. 

<img width="1237" alt="screen shot 2018-02-17 at 10 40 08" src="https://user-images.githubusercontent.com/4898751/36335870-f80b1de0-13ce-11e8-8e95-b3c160d5befb.png">

**Comment by dcworldwide** [comment]
Will you accept a pr that switches all lodash package deps for lodash function specific deps?

**Comment by joemcelroy** [comment]
yep i will accept that! Could you do the PR against this branch `circle-ci-typescript-update` please. This is a big branch with the latest changes, soon to be released.
