### ISSUE TITLE
unable to build searchkit develop branch

### ISSUE THREAD

**Issue by rajgupt** [searchkit/searchkit#608]
Using develop branch at:
commit ad876728c129959891a18c753dbccdb3db33212c 
Date:   Mon Jan 29 15:29:28 2018 +0100

# Steps followed:
1. git clone 
2. yarn install
3. npm run-script build

## Getting Error 
rajat@DESKTOP-NGUI2BV MINGW64 ~/projects/knowledge/git/searchkit/packages/searchkit (develop)
$ npm run-script build

> searchkit@2.3.0 build C:\Users\rajat\projects\knowledge\git\searchkit\packages\searchkit
> tsc; webpack; rm release/ignore.js

error TS6053: File ';.ts' not found.
error TS6053: File 'rm.ts' not found.
error TS6053: File 'webpack;.ts' not found.
error TS6054: File 'release/ignore.js' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Users\\rajat\\Downloads\\node-v6.11.3-win-x64\\node.exe" "C:\\Users\\rajat\\Downloads\\node-v6.11.3-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "build"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! searchkit@2.3.0 build: `tsc; webpack; rm release/ignore.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the searchkit@2.3.0 build script 'tsc; webpack; rm release/ignore.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the searchkit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc; webpack; rm release/ignore.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs searchkit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls searchkit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\rajat\projects\knowledge\git\searchkit\packages\searchkit\npm-debug.log

## If I run tsc separately, then I get these errors:

`rajat@DESKTOP-NGUI2BV MINGW64 ~/projects/knowledge/git/searchkit/packages/searchkit (develop)
$ tsc
src/__test__/core/react/RenderComponentSpec.tsx(56,7): error TS2416: Property 'render' in type 'Provider' is not assignable to the same property in base type 'Component<any, any>'.
  Type '() => ReactNode' is not assignable to type '() => false | Element'.
    Type 'ReactNode' is not assignable to type 'false | Element'.
      Type 'string' is not assignable to type 'false | Element'.
src/__test__/core/react/RenderComponentSpec.tsx(63,9): error TS2605: JSX element type 'Provider' is not a constructor function for JSX elements.
src/__test__/core/react/RenderComponentSpec.tsx(63,9): error TS2605: JSX element type 'Provider' is not a constructor function for JSX elements.
  Types of property 'render' are incompatible.
    Type '() => ReactNode' is not assignable to type '() => false | Element'.
      Type 'ReactNode' is not assignable to type 'false | Element'.
        Type 'string' is not assignable to type 'false | Element'.
src/components/display/view-switcher/ViewSwitcherHits.unit.tsx(53,31): error TS2322: Type '{ searchkit: any; hitComponents: [{ key: string; title: string; itemComponent: (props: any) => El...' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<ViewSwitcherHits> & Readonly<{ children?: ReactNod...'.
  Type '{ searchkit: any; hitComponents: [{ key: string; title: string; itemComponent: (props: any) => El...' is not assignable to type 'Readonly<ViewSwitcherHitsProps>'.
    Types of property 'hitComponents' are incompatible.
      Type '[{ key: string; title: string; itemComponent: (props: any) => Element; defaultOption: true; }, { ...' is not assignable to type '[{ key: string; title: string; itemComponent?: any; listComponent?: any; defaultOption?: boolean;...'.
        Types of property 'length' are incompatible.
          Type '3' is not assignable to type '1'.
src/components/display/view-switcher/ViewSwitcherHits.unit.tsx(98,31): error TS2322: Type '{ searchkit: any; hitComponents: [{ key: string; title: string; itemComponent: (props: any) => El...' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<ViewSwitcherConfig> & Readonly<{ children?: ReactN...'.
  Type '{ searchkit: any; hitComponents: [{ key: string; title: string; itemComponent: (props: any) => El...' is not assignable to type 'Readonly<ViewSwitcherConfigProps>'.
    Types of property 'hitComponents' are incompatible.
      Type '[{ key: string; title: string; itemComponent: (props: any) => Element; defaultOption: true; }, { ...' is not assignable to type '[{ key: string; title: string; itemComponent?: any; listComponent?: any; defaultOption?: boolean;...'.
        Types of property 'length' are incompatible.
          Type '3' is not assignable to type '1'.
src/components/search/filters/tag-filter/TagFilterList.unit.tsx(49,24): error TS2322: Type '{ field: string; values: [string, string]; searchkit: any; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<TagFilterList> & Readonly<{ children?: ReactNode; ...'.
  Type '{ field: string; values: [string, string]; searchkit: any; }' is not assignable to type 'Readonly<TagFilterListProps>'.
    Types of property 'values' are incompatible.
      Type '[string, string]' is not assignable to type '[string]'.
        Types of property 'length' are incompatible.
          Type '2' is not assignable to type '1'.
src/components/ui/range/RangeComponents.tsx(20,36): error TS2322: Type '{ [x: string]: any; children?: ReactNode; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<RangeSlider> & Readonly<{ children?: ReactNode; }>...'.
  Type '{ [x: string]: any; children?: ReactNode; }' is not assignable to type 'Readonly<RangeSliderProps>'.
    Property 'onChange' is missing in type '{ [x: string]: any; children?: ReactNode; }'.
src/components/ui/range/RangeComponents.tsx(21,34): error TS2322: Type '{ [x: string]: any; children?: ReactNode; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<RangeInput> & Readonly<{ children?: ReactNode; }> ...'.
  Type '{ [x: string]: any; children?: ReactNode; }' is not assignable to type 'Readonly<RangeInputProps>'.
    Property 'onChange' is missing in type '{ [x: string]: any; children?: ReactNode; }'.
src/core/react/FastClick.ts(10,31): error TS2345: Argument of type 'ReactNode' is not assignable to parameter of type 'ReactElement<any>'.
  Type 'string' is not assignable to type 'ReactElement<any>'.
src/core/react/FastClick.ts(73,31): error TS2345: Argument of type 'ReactNode' is not assignable to parameter of type 'ReactElement<any>'.
  Type 'string' is not assignable to type 'ReactElement<any>'.`

Please help me in building searchkit as I would like to add MatchPhraseQuery functionality in search dsl.

thanks
Rajat

**Comment by Jaikant** [comment]
Try using yarn instead.

**Comment by rajgupt** [comment]
I was using latest tsc globally 
I was able to compile after matching tsc with the repository.
Closing the issue.
