### ISSUE TITLE
Remove option

### ISSUE THREAD

**Issue by MavDas** [searchkit/searchkit#613]
I have a client requirement wherein a Remove Button has to be implemented. The Ideal way would be to pick up the ID of the Item to be removed and pass the data to the backend for updating and trigger the ajax call and fetch api response. Since searchkit takes the url and calls it internally, there is no way i can trigger the api call through searchkit so that the data is again populated when the remove button is clicked. If there were a way to make searchkit trigger the API call it would be great.

**Comment by omulriain** [comment]
I need this also and cannot figure out how to do it. I was thinking of doing dangerous inner html with onclick that adds it to a list. then adding the MustNot to the query, but the documentation is very lacking in how to do the last part.
