### ISSUE TITLE
How to sort results by a date field like @timestamp

### ISSUE THREAD

**Issue by megastef** [searchkit/searchkit#62]
Hi,

could pls. provide an example how to sort results by timestamp from a query in a SearchBox? 

Thx.
Stefan

**Comment by ssetem** [comment]
Hi

do you need to do this via a component? or you just want the to be the default query?

**Comment by ssetem** [comment]
if you need it by component you could use
http://docs.searchkit.co/stable/docs/components/sorting/sort.html

or default query

```javascript
    searchkit.addDefaultQuery(function(query){
      return query.setSort([{"@timestamp":"desc"}]);
    })

```

**Comment by megastef** [comment]
Thx. The default query works!
I've tried already http://docs.searchkit.co/stable/docs/components/sorting/sort.html first, but the order did no change when I selected the combobox.

**Comment by ssetem** [comment]
thanks for the heads up  on the combobox.

would you mind pasting your config for your sorting component just to help us debug?

Thanks!

p.s. you can always drop by  https://gitter.im/searchkit/searchkit
if you have further queries
