### ISSUE TITLE
Add browser compatibility to the readme

### ISSUE THREAD

**Issue by TimVen** [searchkit/searchkit#622]
My project needs to be IE11 and Chrome 50 compatibility, providing a list of compatible browsers would be very useful.

is it IE11 and Chrome 50 compatible?

On IE11 your demo page shows 0 results, but elsewhere in the issues it hints at IE9+ compatibility.

**Comment by joemcelroy** [comment]
should be fine in IE11 / chrome 50 with the right polyfills added to your project. We dont bundle these polyfills for you, we let you add them (bloat reasons). babel-polyfill or polyfill.io
