### ISSUE TITLE
Searchkit documentation missing search - Is searchkit obsolete?

### ISSUE THREAD

**Issue by SimpleCookie** [searchkit/searchkit#623]
I'm wondering, since the searchkit documentation doesn't have a search function. That's why I am thinking, SearchKit might be obsolete? 😄 

You'll say "Of course it's not obsolete!" , and I agree.
But where's the search on the documentation page? Is this irony? A search based framework without a search?

**Comment by joemcelroy** [comment]
Yeh i agree, really want a overhaul with our documentation to include features like search, preview of component. We started doing this - but its a big task.

**Comment by SimpleCookie** [comment]
Thank you for commenting @joemcelroy. Perhaps you guys can start with just the search option and include the preview etc in a later stage? I believe it would make a huge difference. It doesn't even have to be a great one.

I do find the irony very funny though 😆

**Comment by joemcelroy** [comment]
yeh same :D, has been a joke for us for a while haha. Let me see what i can do but google search focusing on the docs site might be one choice.

**Comment by SimpleCookie** [comment]
Honestly, that could be a simple temporary solution. You can just create a simple input field that does a google search, with the `site:` dork prefixed.
