### ISSUE TITLE
basic auth to nginx

### ISSUE THREAD

**Issue by jacksonp2008** [searchkit/searchkit#624]
Looking for the best approach:

I have placed AWS ES behind an nginx proxy to remove the CORS issues.

This works well, all secured with SSL.  However, I need to restrict access to the proxy.

Seems like adding basic auth is a good start, however  I am having a devil of time to get it to work with searchkit.  Nginx config is pretty simple:

```
server {
        listen  443 ssl;
        server_name     es.fsu.com;
        ssl_certificate /etc/ssl/certs/fsu.crt;
        ssl_certificate_key /etc/ssl/certs/fsu.key;
        location / {
        auth_basic      "big Search";
        auth_basic_user_file /etc/nginx/conf.d/sesearch.pw;
        proxy_pass https://search-sessdfervices-qasdfasfsafsadfsfdasdf.us-east-1.es.amazonaws.com/;
       }
```
again without the auth_basic* it works great.

On the searchkit side:

```
const searchkit = new SearchkitManager(host, {searchOnLoad: true , withCredentials: true, basicAuth: "USERNAME:PASSWORD"})

```
I added `withCredentials` and `basicAuth` for this part.

The error I am getting now is:

```
{"message":"Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=Basic cG9sbG9jazpzdXNhbjEyMw=="}
```

This is the same when running from localhost or when placed under apache server on another host. 

Is this the correct approach?  Basic Auth from the browser to proxy?

If so, any idea how to get it to work?  Maybe nginx headers...

Thanks!

**Comment by joemcelroy** [comment]
Im not sure but dont think its related to searchkit. Ask on stackoverflow showing the request xhr call.
