### ISSUE TITLE
Detail View

### ISSUE THREAD

**Issue by Seaborg** [searchkit/searchkit#625]
Simple task I've been struggling for a day now. I'm trying to create a custom DetailRecord View for user to get more details, extra images, etc. and having problems with routing. I'm using react-router-dom and trying to use <Link> component in RecordHitsListItem. react-router shows the link OK and changes url but it doesn't render the view.
What's the proper way to implement custom DetailRecord component within searchkit?

**Comment by joemcelroy** [comment]
https://github.com/searchkit/searchkit-starter-app/pull/8 have a look at this PR
