### ISSUE TITLE
Some of the typescript defs not quite right

### ISSUE THREAD

**Issue by richtera** [searchkit/searchkit#626]
Some of the array declarations don't declare arrays of a specific type but just an array of one.
![image](https://user-images.githubusercontent.com/708186/39087861-76bbc2a2-4575-11e8-9ac0-fc04268065f5.png)
In this case the view selections passed into hitComponents will only work with a single one.

**Comment by richtera** [comment]
This one can be fixed by doing:
```javascript
import { SearchkitComponent, ViewOptionsAccessor, RenderComponentType } from "../../../core";
import { HitsProps, HitItemProps, HitsListProps } from "../../";
export interface ViewSwitcherHitsProps extends HitsProps {
    hitComponents?: Array<{
        key: string;
        title: string;
        itemComponent?: RenderComponentType<HitItemProps>;
        listComponent?: RenderComponentType<HitsListProps>;
        defaultOption?: boolean;
    }>;
}
export declare class ViewSwitcherHits extends SearchkitComponent<ViewSwitcherHitsProps, any> {
    accessor: ViewOptionsAccessor;
    static propTypes: any;
    defineAccessor(): ViewOptionsAccessor;
    render(): JSX.Element;
}
```
![image](https://user-images.githubusercontent.com/708186/39087882-c7542790-4575-11e8-9f25-63d57edce3be.png)
Is someone working on this or should I make a pull request?

**Comment by richtera** [comment]
Added pull request

**Comment by joemcelroy** [comment]
thanks for PR
