### ISSUE TITLE
Removing suffix not working in v 2.3.0

### ISSUE THREAD

**Issue by ab-mannan** [searchkit/searchkit#631]
Previoulsy in v.2.1.1 we are removing the suffix using the following piece if code

Utils.guid = () => '';

and that was working fine as a fix to remove the suffix (to avoid issue with concat aggregation name in StateFull Accessor constructor).

But upgrading it to v2.3.0 it no longer works. I would like to know that if there is any sort of configuration available to avoid the above issue, so that no suffix will be added to the aggregation names. Or any hot fix to make our application work as of v2.1.1

Any help will be greatly appreciated.

Thanks

**Comment by ab-mannan** [comment]
@richtera
@joemcelroy
any idea about that fix ?

**Comment by richtera** [comment]
I understand what you were trying to accomplish with Utils.guid = () => ''; in terms of the suffix, but can you explain why you want to remove the suffix. There were code changes around the suffix and I had some struggles before the code changes before with the suffix, but I had never attempted to remove it.

**Comment by richtera** [comment]
Oh the easiest way is to iterate through the accessors since they have the id and actually the full name of the aggregate. That way you'd be getting the correct stuff. It's that's no doable I can check whether there is another hack to remove the suffix, but the part of the discussion I was involved in was to make sure the uuids re-initialized after a searchkit was unmounted and remounted to make sure the URL arguments correctly matched to reinitialize the new query.

**Comment by ab-mannan** [comment]
Can you please mention the while you are talking about, where I need to iterate?

**Comment by ab-mannan** [comment]
Yes, I am able to get the stateful accessors too from the searchKit.accessors. So its OK for now, but I would love to hear some sort of configuration for this or some decent hack to avoid concatenating uuids.

Much appreciated.

**Comment by ab-mannan** [comment]
whoa... just found after debugging alot of different things. In my manager file(entity manager file) where I am managing all functions from searchKit manager like setQueryProcessor etc.. I have added a small hack in listener function like `this.uuid = ( ) => '';` . In this I have context to the searchKitManager of the component where I have access to accessors and statefull accessors too. Thanks @richtera  for pointing me to the right direction. Thanks a lot.

**Comment by joemcelroy** [comment]
thank you @richtera
