### ISSUE TITLE
Perform search on button click - help wanted

### ISSUE THREAD

**Issue by ElviraCB** [searchkit/searchkit#633]
Hello,

I think I'm getting a bit confused.

But I have a div, which has a onClick function. When this function is called a custom search should be performed.

Any tips on how to accomplish this?

I've tried setting the queryProcessor inside the function. But I don't know what to do next.

```
  searchkit.setQueryProcessor((rawQuery) => {
          rawQuery.query = {
            "bool":
            {
              "must": [
              {
                "match":
                {
                  "hoofdtitel": "Forrest Gump"
                }
              }
            ]
          }
        }
          return rawQuery
        });
```

**Comment by Timothylawler** [comment]
Are you getting any errors from this? have you tried reloading the search after setting the queryProcessor?

eg:

```
updateSearch = () => {
  searchkit.setQueryProcessor(() => {
    // set query processor as you showed
  })
  searchkit.reloadSearch() // reloads the search with the new queryProcessor
}
```

**Comment by ElviraCB** [comment]
@Timothylawler  How do I remove the setted query when I want to search again in the searchbox?
Because it's now limited to the query I have.

**Comment by Timothylawler** [comment]
@ElviraCB I think i understand your question and i dont think you want to use `setQueryProcessor` if you want a different search than you provide the function.

if you for example set query processor in `componentWillReceiveProps` then you will always have control over what you set by passing the data as a prop. 

you can access what searchkit would put as query processor through the `query` prop in `searchkit.setQueryProcessor(query => {})`. Most likely contained in `query.should` by default. I extend the search by taking what searchkit would like to send and tweak that
