### ISSUE TITLE
Could I view switch toggle by programmitically?

### ISSUE THREAD

**Issue by skout90** [searchkit/searchkit#645]
Thanks for awesome open source.
I use searchkit very well!

in this switcher component(http://docs.searchkit.co/stable/components/display/switcher.html)
I want to toggle switcher when certain element is clicked
so I wonder that how to toggle view-switcher by programmitically.

I did this
```javascript
import { ViewSwitcherToggle } from 'searchkit' 
...
ViewSwitcherToggle.prototype.setView('list');

```
then i got this error
> Cannot read property 'getAccessorByType' of undefined

Could you give me some tip?
Thanks for reading!

**Comment by joemcelroy** [comment]
I would customise the listComponent renderer of the ViewSwitcherToggle
http://docs.searchkit.co/stable/components/display/switcher.html

see `listComponent` prop, you can pass in your own react component here for rendering the ViewSwitcher
