### ISSUE TITLE
Get data from multiple indexes

### ISSUE THREAD

**Issue by AYWK** [searchkit/searchkit#646]
Get data from multiple indexes and integrate them together to render a line chart. Can searchkit be used here?

**Comment by joemcelroy** [comment]
Sounds pretty custom so would suggest building it outside of Searchkit. Do you need searchkit state? If you do, I would build a custom searchkit component so it can access searchkit state but do the querying outside of the main searchkit instance.

**Comment by AYWK** [comment]
Thanks for your suggestion, I decided to build it outside of Searchkit and do some analysis-related work with elasticsearch.js and Echarts.
 thanks.
