### ISSUE TITLE
Group by field

### ISSUE THREAD

**Issue by dgastudio** [searchkit/searchkit#654]
Hello! 
it's possible to group results by any field? 

thanks

**Comment by Timothylawler** [comment]
@dgastudio What do you want to accomplish with this? render the grouped results separately or you just want to aggregate on a specific field? 

Latter is possible and quite simply done by just aggregating on the desired field [Aggregation Elastic search](https://www.elastic.co/guide/en/elasticsearch/reference/current/_executing_aggregations.html). The former will be a bit trickier but please elaborate

**Comment by dgastudio** [comment]
Hello Timothy, and, thank you for your response.

i would like to acomplish this: https://c2n.me/3VTylyT.png

**Comment by Timothylawler** [comment]
@dgastudio A little late back to the party but future people might get some help. 

The searchkit library does not include any component for that kind of layout no. But what you could do is just extract the search result with a simple wrapper and treat it the way you want.

Eg: 
`export default class HitsExtractor extends SearchkitComponent {
  render() {
    const { results } = this.searchkit
    const hits = _get(results, 'hits.hits', [])
    const hitCount = _get(results, 'hits.total', 0)

    return this.props.children({ hits, hitCount })
  }
}`

And use it as:
`
<SearchkitProvider>
  <HitsExtractor>
    {({ hits, hitCount }) => (
      <SomeComponent data={hits} />
    )}
  </HitsExtractor>
</SearchkitProvider >
`
