### ISSUE TITLE
Unmounting searchkit filter components modifies the query

### ISSUE THREAD

**Issue by florianbepunkt** [searchkit/searchkit#666]
Not really sure if this is a bug or if this is by design:

I have (a) several filters (RefinementListFilter, SortingSelector) in a dynamic sidebar component that is toggled by user and (b) a main component that shows a searchbox and hits component.

The hits are displayed and the searchbox works.

However: If the sidebar is not initially mounted/shown, then the RefinementListFilter options are empty (there are no options). Also the filters do not persist, for example if set a filter, hide sidebar component with filters and use pagination to go to second page of results, the filter is not active anymore.

**Comment by florianbepunkt** [comment]
It seems that this behaviour happends if the RefinementListFilter component is unmounted.

Haven't found this in the docs, but is this intentional? Unmounting an UI component should not modify the query in my opinion, especially since this is the React-recommended way for conditional items

**Comment by florianbepunkt** [comment]
Okay, in case anyone has the same problem. This is a rather hacky workaround and more of an react-antipattern, but seems like the only solution.

The problem is that unmounting a searchkit component does modify the query. So if you dynamically want to show hide filters in an own component, for example a modal that contains all filters, you would need to hide it without unmounting it.

This is a HOC that would get a ref to a component that would show/hide it via css style. This makes use of the new React ref api (>= 16.3), but you could backport it to use the former way to create refs.

Besides IMO there should be an option to disable the current behaviour (which seems like an anti-pattern in itself)

```
import React, { Component } from "react";
import ReactDOM from "react-dom";

export default class ReactNoUnmountHide extends Component {
  constructor() {
    super();

    this.ref = React.createRef();
  }

  toggle(value) {
    this.dom.style.display = value ? null : "none";
  }

  componentDidMount() {
    this.dom = ReactDOM.findDOMNode(this.ref.current);
    this.toggle(this.props.value);
  }

  componentWillReceiveProps(nextProps) {
    if (nextProps.value !== void 0) {
      this.toggle(nextProps.value);
    }
  }

  render() {
    return React.cloneElement(this.props.children, { ref: this.ref });
  }
}

```

**Comment by batFormat** [comment]
@florianbepunkt Tell me you have not found a more correct solution?

**Comment by florianbepunkt** [comment]
@batFormat No, I went with this rather hacky workaround. But probably searchkit behaviour has changed in the meantime. Not sure if the query still changes if the component unmounts
