### ISSUE TITLE
Material UI with Searchkit

### ISSUE THREAD

**Issue by rajarameshvarma** [searchkit/searchkit#667]
How can I use Material UI components with Searchkit? For example, using Material UI Autocomplete in place of SearchBox.

**Comment by dcworldwide** [comment]
It is an interesting question...more generally...is it possible to use searchkit with a custom ui...either in whole or part.

**Comment by 24ma13wg** [comment]
[This page](http://docs.searchkit.co/stable/setup/extending-components.html) suggests that the component markup can be altered.

**Comment by 24ma13wg** [comment]
You can alter components, also by extending their class. See this example: http://docs.searchkit.co/v0.3.5/docs/components/basics/hits.html. So, you should be able to add any necessary wrappers too.

**Comment by dcworldwide** [comment]
Should this not override the  renderResult(result:any) method instead of specifying it's own render?

**Comment by 24ma13wg** [comment]
@dcworldwide maybe, yes. How would you write this?

**Comment by dcworldwide** [comment]
Is anyone successfully using MUI with searchkit? If yes, please share your solution.
