### ISSUE TITLE
SearchKit SearchBox Issue with Elastic Search 6.3

### ISSUE THREAD

**Issue by rajarameshvarma** [searchkit/searchkit#668]
Hi,

I am trying to use SearchKit with Elastic Search 6.3 and facing issues with some filter options. Here is the example of a query body generated by SearchBoX 

`{"query":{"query_string":{"query":"something","fields":["_all"]}},"size":20}`

As the [_all options is deprecated](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-all-field.html) in ES 6.0, Is there a chance to change this behavior or do we need create a mapping field?

Thanks

**Comment by florianbepunkt** [comment]
Also facing this issue. Will ES6 be supported by searchkit?
