### ISSUE TITLE
Reusable FilterItem component

### ISSUE THREAD

**Issue by ssetem** [searchkit/searchkit#68]
A reusable FilterItem component to be used with RefineminementFilter, Hierarchical, Nested etc

**Comment by GregoryPotdevin** [comment]
Should there be a single component with a few options (useCheckbox comes to mind) or 2 (FilterItem and CheckboxFilterItem) ?

**Comment by ssetem** [comment]
I think lets create 2 side by side, and spot the commonality and extract up
