### ISSUE TITLE
How do I set-up the initial search query?

### ISSUE THREAD

**Issue by dtrinh100** [searchkit/searchkit#683]
A user searches on the landing page, then it redirects them to a page with the results. How do I use the search term that was used on the landing page and put it into my SearchBox component on the results page and do a search query with the term?

**Comment by olf** [comment]
You can pass the q=[query terms from landing page] URL parameter to the SearchKit application, like this: http://demo.searchkit.co/?q=matrix

**Comment by dtrinh100** [comment]
I am using the React Router with the hash symbol in it and trying to do this causes some strange issues with the search like the term not populating. I have tried using window.location.href += "?q=${queryString}" upon user submitting the search from the landing page and I have tried using the Router's own history object as well. Is there a workaround for this issue?

**Comment by iiitmahesh** [comment]
@dtrinh100 any update???

**Comment by nikitapavets** [comment]
+1
