### ISSUE TITLE
Is there a way to change the selected sorting option via state?

### ISSUE THREAD

**Issue by donaldallen** [searchkit/searchkit#686]
If a user selects a specific category within a search, is it possible to also change the sort order from one option (like "Name (A-Z)") to another (like "Name (Z-A)"). Any pointers would be a huge help.

**Comment by ACPrice** [comment]
Also curious about this. Initial attempts to change sort order after `<RefinementListFilter >` has mounted have failed. @donaldallen Did you come up with a good solution?
