### ISSUE TITLE
React Warning with Searchbox

### ISSUE THREAD

**Issue by cmburcus** [searchkit/searchkit#703]
Hello,

Referencing closed issue [691](https://github.com/searchkit/searchkit/issues/691) which was closed with the resolution `this issue is resolved in "searchkit": "^2.3.1-alpha.9",`

I'm using `searchkit: ^2.3.2` and it seems the issue is still present.

![Screen Shot 2019-08-27 at 12 22 27 PM](https://user-images.githubusercontent.com/11837178/63789444-67607d00-c8c5-11e9-8307-ebdd1e19b575.png)

![Screen Shot 2019-08-27 at 12 22 43 PM](https://user-images.githubusercontent.com/11837178/63789452-69c2d700-c8c5-11e9-872c-983a39841432.png)

<img width="180" alt="Screen Shot 2019-08-27 at 12 24 12 PM" src="https://user-images.githubusercontent.com/11837178/63789544-98d94880-c8c5-11e9-80e1-526880dcdf99.png">

**Comment by trouba** [comment]
@cmburcus 
Doesn't seem like the 2.3.2 is an existing version https://www.npmjs.com/package/searchkit
