### ISSUE TITLE
Help implementing searchkit

### ISSUE THREAD

**Issue by williamhoos** [searchkit/searchkit#705]
If inappropriate to post, close this but would love if someone familiar with searchkit could help implement in our project. Contact us via the issue below. This is part of Hacktoberfest (https://github.com/search?q=label%3Ahacktoberfest+state%3Aopen+is%3Aissue+clinwiki&type=Issues)

https://github.com/clinwiki-org/clinwiki/issues/165

**Comment by joemcelroy** [comment]
Hi there, 

Im closing this issue but feel free to pin me on your github issue if theres anything in specific you need help on. Thanks
