### ISSUE TITLE
Tabs Menu Filter All tab problem

### ISSUE THREAD

**Issue by huseyingoztok** [searchkit/searchkit#706]
![tab menu](https://user-images.githubusercontent.com/43777036/68375182-6c5c6b00-0157-11ea-92bf-f789f9e4e3b2.PNG)

As you can see in the picture I am using the tab menu. I don't want the tab named All to appear when the page loads, and I want to show a tab by default. How can I do it. I will be grateful if you could help me.

**Comment by Fluorz** [comment]
You can't

**Comment by huseyingoztok** [comment]
I destroyed that tab with dom manipulation. Then I redirected to the page want to set when the page load. Thank you for your answer.

**Comment by iiitmahesh** [comment]
@huseyingoztok  I have same kind of requirement. Can you share the code, how exactly I can do?

**Comment by huseyingoztok** [comment]
searchkit.setQueryProcessor((props) => {
    const allTab = document.querySelector("[data-key='$all']");
    if (allTab) {
        allTab.parentNode.removeChild(allTab);
    }
    if (!(searchkit.query.index.selectedFilters.length > 0)) {
        window.location = "/yourdomain?Activities[0]=tabwanttofocuson";
    }
    return props;
});
