### ISSUE TITLE
Complex queries

### ISSUE THREAD

**Issue by jacksonp2008** [searchkit/searchkit#714]
Basic searchkit seems to be a simple keyword search out of the box.

I like the kibana syntax eg "apples AND oranges AND NOT grapes", a more complex search capability.

I tried changing the analyzer, but that didn't seem to do much. Also tired queryBuilder={"QueryString"} and the entire thing became unresponsive.

Any idea how to duplicate the kibana (lucene) style syntax with searchkit?

Here is my searchbox, default:

```
<SearchBox autofocus={true}

searchOnChange={true}

prefixQueryFields={prefixqueryfelds}

queryOptions={{analyzer:"standard"}}

/>
```
ps. I tried the "chat" from your website and no one ever responds.  Also searched everything I could find with no luck on getting this to work.

Appreciate any tips or pointers.

**Comment by pahan35** [comment]
@jacksonp2008 you may try to next style for your search `"apples" "oranges" +-grapes`

**Comment by forescout-spollock** [comment]
The above does not work.  Any idea how to create a complex search?  I see something in the querybuilder function but no idea how to use it.
