### ISSUE TITLE
Searchkit always followed by contributors ?

### ISSUE THREAD

**Issue by cb29** [searchkit/searchkit#718]
Hello,

is this react package followed by contributors? With ES 7.0 we have several compatibility problems. We don't see any new version.

And we see that ReactiveSearch seems to be the future of SearchKit.

Thanks for yours opinions on this subject.

**Comment by joemcelroy** [comment]
Hi there, its still being contributed to and no issues (that i know of!) with ES 7 as long as you use the alpha versions which other devs have been using (`searchkit@2.3.1-alpha.9`). If you still have issues, open it as an issue.

Thanks!

**Comment by joemcelroy** [comment]
fixed in v2.4.1
