### ISSUE TITLE
Code style inconsistency inside repo

### ISSUE THREAD

**Issue by pahan35** [searchkit/searchkit#729]
When I started my work on some fixes I noticed that current repo has some trailing whitespaces. For example, here I just decided to remove unused `let result` but together with this changed I did changes in trailing spaces.
![image](https://user-images.githubusercontent.com/13823215/71596993-37163d00-2b4a-11ea-8f76-c91cadbac1fc.png)

Also, it has some inconsistencies inside code like different space positions after `:` sign.
- space after `:` here https://github.com/searchkit/searchkit/blob/staging/packages/searchkit/src/__test__/core/react/SearchkitComponentSpec.tsx#L52
- no spaces here https://github.com/searchkit/searchkit/blob/staging/packages/searchkit/src/__test__/core/react/SearchkitComponentSpec.tsx#L113

You even have tabs inside the codebase
![image](https://user-images.githubusercontent.com/13823215/71597297-4053d980-2b4b-11ea-94e6-64d07ca254a0.png)

We can resolve such kind of problems by adding linter. There is one of the ways how to add it to TS project https://www.robertcooper.me/using-eslint-and-prettier-in-a-typescript-project

@joemcelroy are you interested in adding linter to the project. If yes, I'll try to prepare PR with it.

**Comment by joemcelroy** [comment]
absolutely! was working on this 😉 I use eslint prettier combo in my other TS projects so using that as a template for searchkit. Let me push up the change and if you can review, it will be much appreciated!

**Comment by pahan35** [comment]
I am glad to review the changes with linters. Also, further, it'll be much easier to add new changes to this repo.

Please ping me in some way when you do it

**Comment by joemcelroy** [comment]
@pahan35 PR opened.
