### ISSUE TITLE
Unable to connect to local Elasticsearch instance

### ISSUE THREAD

**Issue by lucidhack** [searchkit/searchkit#739]
I'm unable to make ***searchkit*** connect to my local Elasticsearch instance.
I have followed through many tutorials, but I am still stuck.  Hoping I've overlooked something simple.  Any help or advice on basic connection to a local instance would be greatly appreciated.  Thank you in advance.

This barebones app works for me, using the online demo data:
```bash
import React, { Component } from 'react'
import {SearchkitManager,SearchkitProvider,SearchBox,HitsStats,Layout} from 'searchkit'

const searchkit = new SearchkitManager("http://demo.searchkit.co/api/movies")

class App extends Component {
  render() {
    return (
      <SearchkitProvider searchkit={searchkit}>
        <Layout>
          <SearchBox prefixQueryFields={["title"]}/>
          <HitsStats translations={{"hitstats.results_found":"{hitCount} found"}}/>
        </Layout>
      </SearchkitProvider>
    );
  }
}
export default App;
```
The above working App.js code produces the following expected result (showing 4162 docs):
<img src="https://gitlab.com/lucidhack/knowl/raw/master/img/temp3.png">

When I modify the 'const searchkit = ' line to `const searchkit = new SearchkitManager("http://10.10.10.10:9200/fiction-books")` as shown below to use my local Elasticsearch instance,  I'm unable to retrieve data:
```bash
import React, { Component } from 'react'
import {SearchkitManager,SearchkitProvider,SearchBox,HitsStats,Layout} from 'searchkit'

const searchkit = new SearchkitManager("http://10.10.10.10:9200/fiction-books")

class App extends Component {
  render() {
    return (
      <SearchkitProvider searchkit={searchkit}>
        <Layout>
          <SearchBox prefixQueryFields={["title"]}/>
          <HitsStats translations={{"hitstats.results_found":"{hitCount} found"}}/>
        </Layout>
      </SearchkitProvider>
    );
  }
}
export default App;
```
The above non-working App.js code produces the following result (zero docs found):
<img src="https://gitlab.com/lucidhack/knowl/raw/master/img/temp4.png">

My Elasticsearch (docker) configuration is as follows:
```bash
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - http.cors.enabled=true
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=password
      - http.cors.allow-credentials=true
      - http.port=9200
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization,Access-Control-Allow-Headers,Accept
      - http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358,http://10.10.10.10:1358
      - xpack.security.authc.api_key.enabled=true
      - xpack.security.authc.anonymous.username=react
```
The following are a few of the other variations I have tried (which all produced the expected results when the URL portion is viewed with a web browser):
```bash
const searchkit = new SearchkitManager("http://elastic:password@10.10.10.10:9200/fiction-books/")
const searchkit = new SearchkitManager("http://10.10.10.10:9200/fiction-books/", {basicAuth:"elastic:password"})
const searchkit = new SearchkitManager("http://10.10.10.10:9200/fiction-books/", {basicAuth:"react:password"})
```

Elasticsearch user "elastic" has superuser role assigned.  Elasticsearch react is defined as an anonymous user.

When I navigate to http://10.10.10.10:9200/fiction-books in my web browser, to verify that the field `title` is present, I see that it is.  Title field snippet:
```bash
"title":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"titlehash":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}
```
Here is the full output of http://10.10.10.10:9200/fiction-books
```bash
{"fiction-books":{"aliases":{},"mappings":{"properties":{"@timestamp":{"type":"date"},"@version":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"aich":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"asin":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"authorfamily1":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"authorfamily2":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"authorfamily3":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"authorfamily4":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"authorhash":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"authorname1":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"authorname2":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"authorname3":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"authorname4":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"authorsurname1":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"authorsurname2":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"authorsurname3":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"authorsurname4":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"btih":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"commentary":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"cover":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"crc32":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"edition":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"edonkey":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"extension":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"filesize":{"type":"long"},"googlebookid":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"id":{"type":"long"},"identifier":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"language":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"md5":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"pages":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"path":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"pseudonim1":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"pseudonim2":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"pseudonim3":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"pseudonim4":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"publisher":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"role1":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"role2":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"role3":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"role4":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"russianauthorfamily":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"russianauthorname":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"russianauthorsurname":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"series1":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"series2":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"series3":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"series4":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"sha1":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"sha256":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"timeadded":{"type":"date"},"timelastmodified":{"type":"date"},"title":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"titlehash":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"tth":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"version":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"visible":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"year":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}}},"settings":{"index":{"creation_date":"1580427816760","number_of_shards":"1","number_of_replicas":"1","uuid":"QUe8dT7RQ8igTgVhcBQ8zg","version":{"created":"7050299"},"provided_name":"fiction-books"}}}}
```

**Comment by joemcelroy** [comment]
hey, whats the error within the browser?

**Comment by lucidhack** [comment]
joemcelroy,

Thank you for your reply.  Loading the page in a brower produces no error.  The second screenshot above is what displays before i try to search for anything.  Browser shows 0 (documents) found, when I expect to see a number higher than 0 (corresponding to the number of documents in my elasticsearch).

When i run yarn start, the process runs without error:
<img src="https://gitlab.com/lucidhack/knowl/raw/master/img/temp5.png">

Here is a sample document in my elasticsearch:
<img src="https://gitlab.com/lucidhack/knowl/raw/master/img/temp6.png">

When I search for "Wonderland" I would expect to see "1 found", but always receive 0, without error.
<img src="https://gitlab.com/lucidhack/knowl/raw/master/img/temp7.png">

Where should I look for additional error messages

**Comment by joemcelroy** [comment]
look at console XHR requests. you should see a call to the elasticsearch instance. Should have an error in the response.

**Comment by lucidhack** [comment]
Joseph,
Is there an easy way to do the XHR request for non-programmers?  I've been looking at XHR code snippets, and have not been able to get them to run.  Is there anything like an "XHR browser"?  If you can point me in the right direction, it would help a lot.  Thank you again for your assistance.

**Comment by joemcelroy** [comment]
Hey open chrome devtools (https://developers.google.com/web/tools/chrome-devtools) and look in particular the XHR tab, you should be able to see the request. Alternatively, you could look at the logs on your local ES instance.

**Comment by joemcelroy** [comment]
closing for now as I believe not an issue with searchkit. Il continue to help tho.

**Comment by lucidhack** [comment]
Joseph,
Thank you for pointing me towards the chrome-devtools, that's just what I needed!  The XHR tab did produce an error `POST http://10.10.10.10:3000/10.10.10.10:9200/fiction/_search 405 (Method Not Allowed)`

I double checked my elasticsearch environment in docker-compose, and believe I have the POST method set correctly as well as other required setting as outline in the <a href="http://docs.searchkit.co/stable/setup/elasticsearch.html">search-kit documentation</a>:

<img src="https://gitlab.com/lucidhack/knowl/raw/master/img/temp9.png">

Here's the main window showing the error:

<img src="https://gitlab.com/lucidhack/knowl/raw/master/img/temp10.png">

I think you were right, in that this isn't a search-kit issue.  Do you have any thoughts on how to resolve to POST error?  Thank you again for helping me along with this issue.  I'm really excited to get search-kit up and running.  :-)

**Comment by joemcelroy** [comment]
if you look at the url, it includes the current domain: 

http://10.10.10.10:3000/10.10.10.10:9200/fiction/_search

should be

http://10.10.10.10:9200/fiction/_search i believe. I think the url you are providing to searchkit doesn't have the http protocol therefore treating the endpoint as relative, adding the current domain to the url.

**Comment by lucidhack** [comment]
Progress! (I think)

I updated the URL in the call to search-kit, and now it's producing a URL in XHR as you describe it should be.  Also, when I navigate directly to Elasticsearch (below), it produces the expected results.

However, I'm presented with a new POST error 401.  I'm going to search through the elasticsearch forums to try and see if this is specifically elasticsearch.  i.e. perhaps my  http.cors.allow-methods line in my docker-compose.yml is malformed 
`http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE
` 
Still stuck, but moving along :-)

![401](https://user-images.githubusercontent.com/37647084/74361067-38b36180-4d94-11ea-81fb-d1a1fe48368d.png)
