### ISSUE TITLE
How to add custom components and use them with SearchBox component

### ISSUE THREAD

**Issue by hauph** [searchkit/searchkit#740]
Hello,

I successfully added *SearchBox* component to my app and it works very well. Then I want to create 2 selects that work with *SearchBox* (please refer to image below)
![image](https://user-images.githubusercontent.com/32501504/74718272-774d8e00-5264-11ea-9046-fe3af1368226.png)
One is **Sort By Date** (Today, Yesterday, Last 7 days, Older) and the other is **Sort By Type** (Image, Audio, Text)
I don't know how to achieve this since *searchkit* does not allow to create custom components to work in its own context.
Am I missing something here? Can anyone suggest me how to do this?
I would truly appreciate any help. Thank you!

**Comment by joemcelroy** [comment]
Great that it’s working well for you! So to me the type one is more a filter component (filtering between the types) with the combo of using the drop down renderer. Have a look at menufilter component.  The date one, you could look at the range filter one ( the options that it will display won’t match the ones you require ) or build a custom component that does the filtering.

You’ll then be able to apply css to display it as you desire.

 It’s a little tricky right now building a custom component but involves you extending the searchkit component class and the facet accessor  to achieve what you need
