### ISSUE TITLE
Enable React StrictMode

### ISSUE THREAD

**Issue by dcworldwide** [searchkit/searchkit#744]
The react team recommend that we should move to react strict mode in preparation for the upcoming concurrent rendering. What do you guys think? How much work will be involved?

https://reactjs.org/docs/strict-mode.html

**Comment by pahan35** [comment]
There is a usage of deprecated context.

> Warning: Legacy context API has been detected within a strict-mode tree.
The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.
Please update the following components: SearchBox, SearchkitProvider
Learn more about this warning here: https://fb.me/react-legacy-context

@joemcelroy are you going to migrate searchkit to a new Context API?
