### ISSUE TITLE
Advanced filter type UI for searchkit

### ISSUE THREAD

**Issue by risonsimon** [searchkit/searchkit#75]
Is it possible to create a UI similar to [react-redux-test demo](http://amitayh.github.io/react-redux-test/) where filters can be added based on predefined keywords. 

For example,
if the following 3 keywords are defined for searching,
1. Age 
2. Location
3. Price

The user will be able to add a new filter below the main search box. 

Also, it should support range input for fields like age, price (number field), (ability to show custom input types) when a new filter is added.

**Comment by GregoryPotdevin** [comment]
![image](https://cloud.githubusercontent.com/assets/1522455/12764972/9f2ac69e-c9fc-11e5-9160-b890ae3b4056.png)

**Comment by ssetem** [comment]
```javascript
{'query': {'bool': {'must': [{'multi_match': {'fields': ['answer'], 'query': u'more'}}, {'multi_match': {'fields': ['question_id'], 'query': 1}}]}}, 'from': 0, 'size': 10}
```
example query to be generated

**Comment by infacq** [comment]
how do I implement dynamic filter based on what the result has to offer
