### ISSUE TITLE
No response from elasticsearch

### ISSUE THREAD

**Issue by marciusl** [searchkit/searchkit#752]
Hello, 

I am using docker for elasticsearch. I can reach my elasticsearch cluster if I do not provide anything that they should filter by (but there is no data). But if I provide for example in search component any kind of field it return Network error (5sec passed) and it doesn't return any response of error (in tab section of Google Chrome).

This is quite urgent. Any help I could ask somewhere?

**Comment by joemcelroy** [comment]
is the error a CORS error? https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html#:~:text=Set%20to%20true%20to%20enable,allow%2Dorigin%20list.

**Comment by marciusl** [comment]
@joemcelroy No it isn't.

**Comment by joemcelroy** [comment]
What is the network error status code? I would suggest getting the network request body that searchkit calls elasticsearch and query that directly to elasticsearch using postman.

**Comment by marciusl** [comment]
@joemcelroy it doesn't show any status code. 

As you suggested I did tried to send from other cluster curl -X POST http://es01:9200/_search/ {"query":{"match_all":{}}} and it returned some data. So what might be a  problem?

**Comment by joemcelroy** [comment]
OK so the browser request just times out then? I suggest looking at why the browser cannot connect to your elasticsearch instance in that case.
