### ISSUE TITLE
RefinementListFilter prop listComponent breaking operator

### ISSUE THREAD

**Issue by broleomo** [searchkit/searchkit#756]
I'm trying to override my RefinementListFilter with a passed in listComponent, but when I do that it is breaking the operator that I need it to use "OR". It is always using an "AND" operator, even though I am passing in "OR". 

Here is the component I've built to pass into listComponent in my RefinementListFilter:
```
const MyList = (props) => {
  const myData = useData();
  return (
    <div className={styles.filters}>
      {myData.map((item) => (
        <>
          <p className={styles.filterHeader}>{item.label}</p>
          {item.checkboxes.map((checkbox) => (
            <CheckboxFilter
              id={checkbox.id}
              title={checkbox.label}
              label={checkbox.label}
              filter={TermQuery('my_field', checkbox.myField)}
            />
          ))}
        </>
      ))}
    </div>
  );
};
```
Here is how I am passing it in:
```
     <RefinementListFilter
        id="my-id"
        label="my-label"
        title="my-title"
        field="my_field"
        operator="OR"
        listComponent={MyList}
      />
```

Here you can see the header is being sent with a 'must' operator ('AND') instead of a 'should' operator ('OR'):
![image](https://user-images.githubusercontent.com/29212551/89439845-9e5b2780-d6ff-11ea-959d-8f9b45915860.png)

Here is a screenshot of the UI showing how the user should be able to select multiple filters and be able to select many and see results that match the selected filters. 
![image](https://user-images.githubusercontent.com/29212551/89440020-e5491d00-d6ff-11ea-940c-530790af325d.png)

## Expected Behavior
Be able to override the listComponent and use the 'OR' operator. 

cc: @graysonhicks @dpolant

**Comment by joemcelroy** [comment]
Thank you, @broleomo, what happens if you remove overriding the list component?

**Comment by graysonhicks** [comment]
Hi @joemcelroy I have been helping @broleomo with this on our team.  If we don't override the list component, it works fine.  But we need to override the list component due to our data structure.  The only way we have been able to get it working with the overridden list and the OR operator is by copy and pasting the AbstractItemList component and tweaking it.

This is not ideal because that relies on some internals that could easily introduce breaking changes.

**Comment by joemcelroy** [comment]
ah i think whats happening here is the aggregations that searchkit is building isn't from the RefinementList component which includes the OR operator but from the checkboxFilter which operates independently from RefinementList. Is that correct? 

What data comes from the hook?
