### ISSUE TITLE
High security vulnerability in Axios dependency

### ISSUE THREAD

**Issue by hkirsman** [searchkit/searchkit#763]
Our Whitesource is complaining about the Axios package but we can't upgrade it as it's locked to "^0.18.1" in Searchkit.

`Axios up to and including 0.18.0 allows attackers to cause a denial of service (application crash) by continuing to accepting content after maxContentLength is exceeded.`

To resolve it says we should upgrade to version 0.19.0. Maybe we could even go to latest 0.21.0? Could you update the dependency?

**Comment by hkirsman** [comment]
Can't be stale

**Comment by joemcelroy** [comment]
Hi there, will upgrade searchkit v2 dependencies and cut a release. In meantime take a look at searchkit v3 which doesn't use axios. Il write a migration doc to help with the process.

**Comment by alexef** [comment]
@joemcelroy any chance we can merge the fix for us Searchkit v2 users?

**Comment by joemcelroy** [comment]
@alexef yes will try get a good v2 release out soon.

**Comment by joemcelroy** [comment]
ok released this under v2.4.3. Have briefly tested this but great to hear if you have any issues on your apps!

**Comment by alexef** [comment]
thank you!

**Comment by alexef** [comment]
deployed, and app seems fine so far!
