### ISSUE TITLE
The date filter

### ISSUE THREAD

**Issue by xyy7260** [searchkit/searchkit#764]
searchkit-datefilter 和searchkit-daterangefilter 已经没有人维护了，请问有更好的日期过滤组件吗？ 目前使用他们直接报错

**Comment by joemcelroy** [comment]
HI there, Could you please create an issue in english? Thank you

**Comment by xyy7260** [comment]
@joemcelroy Searchkit-datefilter and SearchKit-Daterangefilter are no longer maintained. Is there a better date filtering component? Currently use them directly to report errors

**Comment by joemcelroy** [comment]
Not at the moment for v2. Im working on a big release for searchkit (v3) which will have date range filtering capabilities. Hopefully in next couple of weeks you should be able to use it!

**Comment by xyy7260** [comment]
@joemcelroy  That would be great, thank you

**Comment by joemcelroy** [comment]
@xyy7260 v3 has now been released. You can see it in action on the demo site (demo.searchkit.co) and the code in examples/next https://github.com/searchkit/searchkit/tree/next/examples/next

**Comment by xyy7260** [comment]
@joemcelroy  Thank you. I'll have a try at once

**Comment by xyy7260** [comment]
@joemcelroy   Thank you. This revision is quite different from the previous V2.

**Comment by xyy7260** [comment]
@joemcelroy  Thank you.   npm [https://www.npmjs.com/package/searchkit](url) I didn't see the latest version of V3

**Comment by joemcelroy** [comment]
hey @xyy7260 yes, searchkit npm module will remain on v2 and will be in maintenance mode. v3 is accessible by the other npm modules (@searchkit/apollo-resolvers, @searchkit/client, @searchkit/elastic-ui).

v3 is very different to v2 but in still delivers a really great search experience quickly. If you use next, you should be able to move from v2 to v3 easily. Il be putting up a migration doc for v2 -> v3 and in meantime take a look at our docs https://searchkit.co/docs/quick-start/api-setup

**Comment by xyy7260** [comment]
@joemcelroy Ok, thank you

**Comment by xyy7260** [comment]
@joemcelroy  Hello, some filtering components in V2 version cannot be used in V3 version, right.

**Comment by xyy7260** [comment]
@joemcelroy  I don't understand how the customise searchkit is used.  Should all queries be placed in variables?.

**Comment by joemcelroy** [comment]
hey @xyy7260, is this still related to dateFilter? Tell me what you are trying to customise anill see if i can improve the current documentation https://searchkit.co/docs/quick-start/customise-searchkit

**Comment by xyy7260** [comment]
@joemcelroy I'm sorry, there may be some problems with my translation. The V2 version was developed by my colleagues. I need to maintain this project recently. I plan to redo it with V3 version. I don't know whether the node side of V3 version needs to be changed or can be used directly. At present, there is a gap between V2 version sending query parameters and your current domain.

V2 post:  
![image](https://user-images.githubusercontent.com/23183393/99635973-bf147680-2a7d-11eb-8869-08f57c75d697.png)
V3 your 
![image](https://user-images.githubusercontent.com/23183393/99636066-e2d7bc80-2a7d-11eb-9267-f01ef0e6966a.png)
---
Custom components are great 😆😆

**Comment by joemcelroy** [comment]
so the request payload in the browser is now a GraphQL query which you will point to a graphQL that has searchkit resolvers configured for your search. See https://searchkit.co/docs/quick-start/api-setup. Il try write up a migration doc today to help you out fill in the gaps.

**Comment by xyy7260** [comment]
@joemcelroy   thank you

**Comment by joemcelroy** [comment]
Hope this helps @xyy7260 https://searchkit.co/docs/guides/v2-v3-migration. If not, you can reach directly to me on discord, discord link on the website.

**Comment by xyy7260** [comment]
@joemcelroy  Thank you for your reply. I understand. I have to see graphql and node to deal with it first.

**Comment by xyy7260** [comment]
@joemcelroy  [Prisma Example](https://www.searchkit.co/docs/examples/prisma-node-express)，Must PRISMA be used?

**Comment by xyy7260** [comment]
@joemcelroy [Prisma Example](https://www.searchkit.co/docs/examples/prisma-node-express) 
Try this demo and it appears





Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (2.12.0) to ./node_modules/@prisma/client in 62ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```

warn Prisma 2.12.0 has breaking changes.
You can update your code with npx @prisma/codemods update-2.12 ./
Read more at https://pris.ly/2.12
sh: ts-node: command not found
