### ISSUE TITLE
Prisma Example 

### ISSUE THREAD

**Issue by xyy7260** [searchkit/searchkit#786]
[According to PRISMA example demo, the following information appears on the console. Do you need to migrate?](https://www.searchkit.co/docs/examples/prisma-node-express)
[declarativeWrappingPlugin]: The nullable object prop used in the 'Mutation.createPost' field's 'title' argument has been
moved to a plugin, as improved chaining APIs and the list() / nonNull() helpers functions are preferred.

On Fields: 

t.string('someField', { nullable: false })   ->    t.nonNull.string('someField')

On args: 

stringArg({ required: true })    ->    nonNull(stringArg())

If you would like to incrementally migrate, or prefer the existing API, it is now supported via the declarativeWrappingPlugin. 
Add this to your plugins array in your makeSchema config:

makeSchema({
  plugins: [declarativeWrappingPlugin(), ...]
})

**Comment by joemcelroy** [comment]
it sounds like its a suggestion on updating to a new way of implementing the Post resolver. Il update the example to use this suggestion but shouldn't get in the way of using prisma.
