### ISSUE TITLE
query with wildcard

### ISSUE THREAD

**Issue by elhsoufiane** [searchkit/searchkit#788]
Hi,
does searchkit support query width wildcard?how can i perform search width 4 letters taped(ex: new*-> newyork/newdelhi)

**Comment by joemcelroy** [comment]
First figure out the elasticsearch query you want. For wildcard, you could use the following query https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wildcard-query.html

Then next build a query Class, similar to the current [MultiMatchQuery](https://github.com/searchkit/searchkit/blob/next/packages/searchkit-apollo-resolvers/src/query/MultiMatchQuery.ts) and adjust the getFilter method to return the elasticsearch query you want

```javascript

class CustomQuery extends MultiMatchQuery {

  getFilter(queryManager: QueryManager) {
    if (queryManager.hasQuery()) {
      return {
         "wildcard": {
            "field": {
               "value": queryManager.getQuery()+"*",
               "boost": 1.0,
               "rewrite": "constant_score"
            }
          }
      }
    }
    return {}
  }
}

export default MultiMatchQuery
```

**Comment by elhsoufiane** [comment]
I think ,i have to implement BaseQuery because with this implementation i have some errors:
TS2416: Property 'getFilter' in type 'CustomQuery' is not assignable to the same property in base type 'MultiMatchQuery'.   Type '(queryManager: any) => { "wildcard": { "field": { "value": string; "boost": number; "rewrite": string; }; }; } | { "wildcard"?: undefined; }' is not assignable to type '(queryManager: QueryManager) => { multi_match: { query: string; fields: string[]; }; } | { multi_match?: undefined; }'.     Type '{ "wildcard": { "field": { "value": string; "boost": number; "rewrite": string; }; }; } | { "wildcard"?: undefined; }' is not assignable to type '{ multi_match: { query: string; fields: string[]; }; } | { multi_match?: undefined; }'.       Type '{ "wildcard": { "field": { "value": string; "boost": number; "rewrite": string; }; }; }' is not assignable to type '{ multi_match: { query: string; fields: string[]; }; } | { multi_match?: undefined; }'.         Type '{ "wildcard": { "field": { "value": string; "boost": number; "rewrite": string; }; }; }' has no properties in common with type '{ multi_match?: undefined; }'.

**Comment by joemcelroy** [comment]
Hi @elhsoufiane 

You should be able to now add your own custom query via this https://searchkit.co/docs/reference/apollo-resolvers#customquery. Now released on rc15

**Comment by elhsoufiane** [comment]
Hi joemcelroy,
Yes,thank you.if now i want to combine the two queries i have to create my own custom query?if i want to query multimatch with a witldcard for example: i search for the word "James Comedy" but i want that the search will be performed for "Jam*" in the writers and the "Com*" in the Genres

**Comment by joemcelroy** [comment]
you should be able to use the CustomQuery filter and return both of the query terms for example:

```javascript
{
  "multi_match: {
          query: query,
          fields: ['title']
   },
  "wildcard": {
            "title": {
               "value": query+"*",
               "boost": 1.0,
               "rewrite": "constant_score"
            }
          }
}
```
