### ISSUE TITLE
total issue

### ISSUE THREAD

**Issue by elhsoufiane** [searchkit/searchkit#792]
Hi,
i think there is a bug when i try to get the total results but there is no data 
{
  "data": {
    "results": {
      "hits": {
        "page": {
          "total": null,
          "totalPages": null,
          "pageNumber": 0,
          "from": 0,
          "size": 10
        },
        "items": []
      }
    }
  },
  "errors": [
    {
      "message": "Float cannot represent non numeric value: { value: 0, relation: \"eq\" }",
      "locations": [
        {
          "line": 5,
          "column": 9
        }
      ],
      "path": [
        "results",
        "hits",
        "page",
        "total"
      ]
    }
  ]
}

**Comment by joemcelroy** [comment]
Hey @elhsoufiane thanks, which ES version are you using?

**Comment by elhsoufiane** [comment]
i'm using elasticsearch:7.3.0

**Comment by joemcelroy** [comment]
Thanks for the spot. should now be fixed in rc16
