### ISSUE TITLE
Old Documentation

### ISSUE THREAD

**Issue by OliverKK** [searchkit/searchkit#808]
Hello,
we are using version 2.4.1 of searchkit but there is no documentation available.
Could you please provide the documentation for the old versions of Searchkit also?

Greetings Oliver

**Comment by joemcelroy** [comment]
Hey Oliver, 

http://searchkit.github.io/searchkit/stable/

If you need to access it again, theres a link to searchkit v2 on the top of the docs site https://searchkit.co/docs and also on the overview page https://searchkit.co/docs#searchkit-classic

**Comment by axgeon** [comment]
Hello,
same issue here again, cant find v2 docs, i have reviewed both links joe and cant find neither something related to classic or v2.

i have a production app using searchkit v2 and need the docs to maintain it, if theres not available on web please provide a pdf or .md or similar.

thank you!

**Comment by joemcelroy** [comment]
Hi @axgeon, reinstated the docs for v2 aswell
