### ISSUE TITLE
how to access the results based on the query from the url

### ISSUE THREAD

**Issue by pranavp10** [searchkit/searchkit#809]
How to fetch the results based on the url similear below in version 3.0
https://xyz.com/search?q=react%20js

**Comment by joemcelroy** [comment]
Not easy to do yet, need to build in a way to support this but for time being

https://github.com/searchkit/searchkit/blob/next/packages/searchkit-client/src/searchkit.tsx#L152
this is where search is run by default when you land in the page. 

One proposal i've got is allow to pass via a prop a function to run to build the initial search state 

```
export function SearchkitProvider({ client, children, getInitialState }) {
  useEffect(() => {
    const state = getInitialState()
    client.setState(state)
    client.search()
  }, [])
  return <SearchkitContext.Provider value={client}>{children}</SearchkitContext.Provider>
}
```
```
<SearchkitProvider getInitialState={() => { 
const urlParams = new URLSearchParams(window.location.search);
const myParam = urlParams.get('q');
return {
  query: q
}
} />
```

as a searchkit supported way. For now if you dont want to PR a feature, you could hack it by recreating searchkitProvider and calling the client.setQuery(queryParam) before you trigger search

```
function CustomSearchkitProvider({ client, children }) {
  useEffect(() => {
    client.setQuery(queryParam)
    client.search()
  }, [])
  return <SearchkitContext.Provider value={client}>{children}</SearchkitContext.Provider>
}
```

**Comment by pranavp10** [comment]
i am still not getting the context can you make example for the above one

**Comment by joemcelroy** [comment]
Hey so tried this out, you will need RC20 for it to work too.
https://github.com/searchkit/searchkit/blob/next/examples/next/pages/index.jsx#L9
So you set the query here when you pass the reference of SearchkitClient instance to the provider. Here ive hardcoded the query "heat" as an example.
