### ISSUE TITLE
Tutorial - not working and missing details

### ISSUE THREAD

**Issue by compsci947** [searchkit/searchkit#816]
**The tutorial code doesn't launch after this step**

API Step: I visit localhost but don't find anything (I have elasticsearch running, should I have an app.js or connect.js?)

First install apollo-server-micro
yarn add apollo-server-micro
then create a graphql.js file in the pages/api folder

**The tutorial code for the latest searchkit version, has missing details.**

Add Searchkit Schema#
Install the NPM module for searchkit

yarn add @searchkit/apollo-resolvers

then add searchkit schema and resolvers to apollo-server       <-- Does this mean copying the provided code into a new file called apollo-server.js? If so, what directory should it be placed in?

**Comment by pranavp10** [comment]
Hear are few things i want to know to solve he issue :

1. Are you using the Next js framework 
2. what is your host in the pages/api/graphql.js pages
3. can you share the error log

**Comment by joemcelroy** [comment]
As discussed on discord, you need to first figure out how you want to index into your elasticsearch instance so you can use Searchkit. Figure out the fields you want to search by and the facets you want to index. Whilst this isn't really part of Searchkit, Ill try get a guide to help step through that process + some helpers to get that started.

Once you have that in place, take a look at the examples with might be more clearer in what you need to do and shows support for a wider range of implementations. https://github.com/searchkit/searchkit/tree/next/examples/next
