### ISSUE TITLE
support on elastic app search

### ISSUE THREAD

**Issue by jason-den** [searchkit/searchkit#824]
Hi guys. I'm new to elastic-search and `searchkit`. Just want to quickly check whether search kit supports "elastic app search". 
I have search around and cannot find any document relate to this. The interface `SearchkitConfig` doesn't accept `ENGINE_NAME`, but only `index`, so I assume `searchkit` doesn't support?

**Comment by joemcelroy** [comment]
I had a quick look on the documentation for Elasticsearch app search and yeh I believe its:
elasticsearch <-> app-search-engine <-> UI

app search uses elasticsearch under the hood and the engine transforms requests made by the client UI into elasticsearch queries. If you could find the host and index for elasticsearch that the engine uses, then you could configure searchkit to use it and will work.

Personally you could get started with elasticsearch quickly with searchkit and indexing guides (https://searchkit.co/docs/guides/elasticsearch-setup-indexing).

Hope this helps!
