### ISSUE TITLE
How to query all the data

### ISSUE THREAD

**Issue by xyy7260** [searchkit/searchkit#825]
In [express example](https://www.searchkit.co/docs/examples/express-js) demo, [typedefs](https://github.com/searchkit/searchkit/blob/next/examples/with-express/index.js#L22) defines types. The data stored in elasticsearch is nested with many hierarchies, and some data have those attributes, which is more troublesome to define types. Is there any way to get it all

**Comment by joemcelroy** [comment]
thats an interesting problem with no silver bullet answer. Heres a couple of suggestions:
- speeding up creating types via JSON -> graphQL types generator 
- JSON Object scalar type https://github.com/taion/graphql-type-json

**Comment by xyy7260** [comment]
@joemcelroy   OK
