### ISSUE TITLE
Pagination enhancement

### ISSUE THREAD

**Issue by GregoryPotdevin** [searchkit/searchkit#84]
A few ideas regarding pagination (for later) :
- adding support for meta tags (`<meta rel="next" href="...">`). Requires using react-helmet or a similar lib to inject metadata tags
- check out the suggestions in Pagination 101 : https://gist.github.com/mislav/622561
- flickr is considered as having a nice pagination
![image](https://cloud.githubusercontent.com/assets/1522455/12802485/8b23d752-cae3-11e5-9fc3-874708516e69.png)

(same ideas as the current 0.5 version, but allows to show 2 items for first/last pages)

**Comment by joemcelroy** [comment]
im closing this as we now have support for different list display components for pagination.
