### ISSUE TITLE
Feature: searchkit api should add a wild card for rangeFacet

### ISSUE THREAD

**Issue by pranavp10** [searchkit/searchkit#844]
the change required here is min / max should be optional, not required and if min / max opted out, searchkit api should add a wild card

**Comment by pranavp10** [comment]
@joemcelroy is this feature is added to the search kit? if so in which version or else are you planing to build this feature ?

**Comment by joemcelroy** [comment]
@pranavp10 yeh sorry haven't been able to make a start on this as been working on geosearch atm. Happy to accept PRs tho! It should be quite straightforward.

**Comment by pranavp10** [comment]
@joemcelroy  if it was any front end thing i would have done that but i need to do lots of research on this how it works as of now i am working on custom component docs

**Comment by joemcelroy** [comment]
this should of been released in rc30 FYI
