### ISSUE TITLE
Feature: Add ASCII folding token filter

### ISSUE THREAD

**Issue by castagne** [searchkit/searchkit#850]
In order to allow for searches that lack diacritics to match titles that have diacritics ([from ES docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-asciifolding-tokenfilter.html)).

**Comment by joemcelroy** [comment]
Hey yes! We could work on improving documentation + updating cli to support adding this configuration by default, like we do with the previous example indexer https://github.com/searchkit/searchkit-demo/blob/master/movie-index/indexer.coffee#L92

**Comment by castagne** [comment]
Thank you! Really appreciate all of your work on this, it's pretty great.
