### ISSUE TITLE
Control query type: must vs should

### ISSUE THREAD

**Issue by danieljuhl** [searchkit/searchkit#851]
I'm struggling trying to make a real custom query. The issue I'm facing is that the module wraps the query in `must`, leaving no way to append a `should` query part.

It would be preferred, if the CustomQuery was allowed to inject in the root of `query`. Another possible idea would be to have a query postprocessor, which is allowed to manipulate the query just before it is passed to Elasticsearch.

Any ideas or solutions I've simply not discovered yet?

**Comment by joemcelroy** [comment]
thanks @danieljuhl yeh not great that wraps it in must. https://github.com/searchkit/searchkit/blob/next/packages/searchkit-schema/src/core/SearchkitRequest.ts#L63. TBH i agree, would be much better if could spread the result into the root of query and extend the filter if result contains filter. Gladly will accept a PR for this if you're willing.

**Comment by danieljuhl** [comment]
@joemcelroy I'll give it a try.

**Comment by joemcelroy** [comment]
@danieljuhl great! Im also on discord if you need to reach out. See our website for discord link.
