### ISSUE TITLE
how to add credential in searchkitConfig

### ISSUE THREAD

**Issue by jason-den** [searchkit/searchkit#853]
Hi. I'm new to `searchkit`. 
It seems every example in doc uses `localhost` and it works well. I have trouble adding env variable (credential, like password) to the searchkitConfig so I can connect the `graphql.js` to my instance. (My ElasticSearch instance requires password and user name. )

**Comment by joemcelroy** [comment]
hey @jason-den, behind the scenes we use elasticsearch node SDK and host config param is the Client node param https://github.com/searchkit/searchkit/blob/next/packages/searchkit-schema/src/core/SearchkitRequest.ts#L55
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/basic-config.html

So you can do basic HTTP authentication via the url like so `https://username:password@localhost:9200` but yeh agree for more complex authentication, you need access to the client options. I will introduce a new optional config called connectionOptions which can be additional ES options like connecting through a proxy.

Could you tell me how you need to connect so I make sure its covered?

**Comment by jason-den** [comment]
Hi @joemcelroy. Thanks for answering. 
This `https://username:password@localhost:9200` looks good. 
I'm also looking the option of token-based auth https://www.elastic.co/guide/en/elasticsearch/reference/master/token-authentication-services.html 

BTW, It could be helpful to add `https://username:password@localhost:9200` as example into searchkt's doc.

**Comment by joemcelroy** [comment]
@jason-den yeh i agree and if you have time, happy to accept PRs to highlight this option :) https://searchkit.co/docs/reference/schema#searchkit-configuration under a heading for authentication
