### ISSUE TITLE
Any advice for a few errors with next.js example?

### ISSUE THREAD

**Issue by weisisheng** [searchkit/searchkit#861]
I swapped out the current graphql.js from the old one and get:

# error 1
 warn  - ./pages/_app.jsx
Anonymous arrow functions cause Fast Refresh to not preserve local component state.
Please add a name to your function, for example:

Before
export default () => <div />;

After
const Named = () => <div />;
export default Named;

I assigned the function a name and then error #2 pops up:

/components/index.js

Unhandled Runtime Error
TypeError: Cannot read property 'total' of null

<h2>{data?.results.summary.total} Results</h2>

When I swap out this line for a simpler one, I then get a 'map' related error, so I thought I would act the community first.

**Comment by weisisheng** [comment]
Will wait for next revision of code a la discord group.

**Comment by joemcelroy** [comment]
https://github.com/searchkit/searchkit/tree/next/examples/next-demo :)
