### ISSUE TITLE
Feature: RefinementSelectFacet can use nested ES objects to filter

### ISSUE THREAD

**Issue by GMuir17** [searchkit/searchkit#864]
As in V2, RefinementSelectFacet's have an optional prop `fieldOptions` which can take a value of nested and the path to a nested field.

Something like:
``` typescript
new RefinementSelectFacet({
        field: "metadata",
        identifier: "metadata",
        display: "ComboBoxFacet",
        label: "Meta",
        fieldOptions: {{ type: "nested", options: { path: "username"}}},
        multipleSelect: true,
      })
 ```

**Comment by tidd99** [comment]
I'm also having this problem - currently a bit of an oversight and would be very useful to get fixed ASAP

**Comment by joemcelroy** [comment]
sounds good! I can do this (might be a little while for the PR) or happy to code review a PR?
