### ISSUE TITLE
searchkit-schema: expose transport to es client to enable request signing to aws managed elasticsearch

### ISSUE THREAD

**Issue by dmccaffery** [searchkit/searchkit#865]
The SearchKitConfig should include support for configuring an instance of a transport round tripper that can be injected into the es client:

https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/advanced-config.html#_transport

The round tripper would be used here:

https://github.com/searchkit/searchkit/blob/7e75a6aeb16808123ff8e4a0383f27817140b5bf/packages/searchkit-schema/src/core/SearchkitRequest.ts#L68

The primary use case we have is to support a custom transport that performs request signing required by AWS Managed ElasticSearch. Other use cases I can think of is custom metrics collection as well as other forms of custom authentication.

I am happy to implement this and submit a PR -- wanted to get the thoughts of the community on a few things:

1. Does the community want this?
2. Should the transport be a singleton instance on the SearchKitConfig or a delegate used to create an instance?
    - I'm in favour of a singleton, personally -- I can't think of reasons that the tripper would need to retain state that is ephemeral based on the request

**Comment by leogcba** [comment]
Hi folks! I also need to connect to an AWS Managed ElasticSearch instance. IMO, this will be a very common scenario. I can also create a PR with the approach suggested by @dmccaffery

**Comment by dmccaffery** [comment]
I meant to do this but got side tracked on other things. I think the maintainers want to support the ability to pass in an entire es client instance that is pre-configured instead of augmenting the config options and creating an instance internally. Given the fork for OpenSearch, this is likely the only solution going forward as I'm sure the two will diverge over time. Hopefully the underlying API will remain useable for some time to come.

**Comment by leogcba** [comment]
Mmmm... I see your point. What i did was to allow to send `ClientOptions` as an alternative to the node URL... this was enough for me. I created this PR with that implementation: https://github.com/searchkit/searchkit/pull/969
Any feedback is more than appreciated.

Tonight I'll try to extend it to also allow the client, as you suggest.

**Comment by joemcelroy** [comment]
thanks! happy to review any PRs :)

**Comment by moltar** [comment]
Another option is to proxy all requests via Lambda, which signs them and passes them on to OS.

**Comment by moltar** [comment]
Not stale.

[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)

**Comment by joemcelroy** [comment]
Im closing this ticket as documented on how to connect to Elasticsearch / Opensearch with V4 using a custom transporter https://www.searchkit.co/docs/guides/setup-elasticsearch#custom-transport
