### ISSUE TITLE
Intelligent SelectedFilters

### ISSUE THREAD

**Issue by GregoryPotdevin** [searchkit/searchkit#87]
The current SelectedFilters uses too much space by default. 
When using RefinementListFilter with OR, you often have multiple selected values for the same field and each one adds a new button in the SelectedFilters component. 
![image](https://cloud.githubusercontent.com/assets/1522455/12821717/dd55390e-cb64-11e5-8a60-f8099f9cdbc3.png)
These could be grouped to save space and help readability.
Also not clear if these are AND or OR filters.

**Comment by joemcelroy** [comment]
Issue is design for removing a particular filter when combined. Haven't yet seen a good pattern for this yet

**Comment by GregoryPotdevin** [comment]
Hmm. Actually I think I had something like that in a previous site of mine ^^
![image](https://cloud.githubusercontent.com/assets/1522455/12829507/c6a4ec2e-cb8a-11e5-9ab5-d222e4163a88.png)
(I had my mouse over "Italy" so it was crossed out). 

The idea was to group filters by field. To be more explicit, each entry should be a little button and have a cross like the current design. I find that much cleaner for multiple values, but not sure if it's satisfying enough for single values.

You could even click on the field name and it removed all those filters at once but I'm not sure that'll be easy to understand for the end user.

**Comment by GregoryPotdevin** [comment]
#### `GroupedSelectedFilters` test :
![image](https://cloud.githubusercontent.com/assets/1522455/12964072/67ece650-d04e-11e5-9fd2-16ad38a6a110.png)

Features grouped selected filters, cross to remove all entries for a given field, and click on a filter to remove a filter's value (has line-through on hover)
Much more compact than the current version if you have multiples values (and the entries didn't get split)
![image](https://cloud.githubusercontent.com/assets/1522455/12964127/aa37b224-d04e-11e5-8157-556a60ba310c.png)

Current code : [GroupedSelectedFilters.tsx](https://github.com/searchkit/searchkit-demo/blob/playground/src%2Fapp%2Fsrc%2Fplayground%2FGroupedSelectedFilters%2FGroupedSelectedFilters.tsx)
