### ISSUE TITLE
Feature - subfacets or dependent facets

### ISSUE THREAD

**Issue by ProficientBell** [searchkit/searchkit#878]
We have an object structure like
```
 {
    "filename": "string",
    "numPages": 0,
    "tags": [
      {
        "key": "string",
        "value": "string"
      }
    ]
}
```
and would like to be able to have a facet on tag keys as well as tag values once a key is chosen

I've currently cobbled something together with a custom facet that accepts a key as a query and builds the value facet based on that key but it's clunky and requires the facets to be managed individually.  Being able to use sub aggregations to manage this would be great but another option would be create dependent facets that only trigger when the proper filter is passed would work as well

**Comment by joemcelroy** [comment]
thanks @ProficientBell, yes was also planning on adding a feature to facets to provide conditions on when they should be "enabled" and is available on all facets. Very rough example of this approach:

```javascript
facets: [
    new RefinementSelectFacet({
      field: 'type',
      identifier: 'type',
      label: 'Type',
      multipleSelect: true
    }),
    new RangeFacet({
      field: 'metascore',
      identifier: 'metascore',
      label: 'Metascore',
      range: {
        min: 0,
        max: 100,
        interval: 5
      },
      visible: [ // facet should be visible for any of the following conditions
         QueryContains("movie"), 
         FacetSelected("type", "movie"), 
         FacetSelected("Rating"),
         MyCustomVisibilityRule
      ] 
    }),

    const MyCustomVisibilityRule = (queryManager) {
       return queryManager.query === "test" && queryManager.filters.contains((filter) => filter.value === "bla" )
    }
```

Would that sound something useful?

I agree with the other issue where you want to be able to customise the values type. I think should be simple enough to do if we provide an interface for the values object and you are able to implement it for the custom value array types. Would that work?

**Comment by joemcelroy** [comment]
just to mention this has now been released. Read more information about the feature here https://searchkit.co/docs/customisations/conditional-facets
