### ISSUE TITLE
Highlighting matches

### ISSUE THREAD

**Issue by beepsoft** [searchkit/searchkit#879]
I was looking for some guidance on how to get query result highlighting via searchkit.

I found in this [README](
https://github.com/searchkit/searchkit/blob/7e75a6aeb16808123ff8e4a0383f27817140b5bf/packages/searchkit-schema/README.md) a mention of highlighting and some related code here:

https://github.com/searchkit/searchkit/blob/7e75a6aeb16808123ff8e4a0383f27817140b5bf/packages/searchkit-schema/src/core/SearchkitRequest.ts#L20

but otherwise it seems that highlighting is not supported. Am I right about this? Are there plans for adding it?

In my `postProcessRequest` function I could add an elastic highlighting request, but the result is not exposed via the GraphQL API.

**Comment by beepsoft** [comment]
I think I am close to a solution and it would only require adding a single line to HitsResolver.ts:

https://github.com/searchkit/searchkit/blob/7e75a6aeb16808123ff8e4a0383f27817140b5bf/packages/searchkit-schema/src/resolvers/HitsResolver.ts#L43-L47


```js
        return {
          items: hits.hits.map((hit) => ({
            id: hit._id,
            fields: hit._source,
            type: parent.searchkit.hitType,
            // This line need to be added:
            highlight: hit.highlight
          })),
```

This would expose the `highlight` field from the Elastic result to the resolvers. (Actually all "raw" elastic result fields could be exposed this way custom resolvers would have a chance to generate any kind of output for their clients.) 

If `highlight` is exposed like this, the rest can be done using the standard Searchkit API-s:

In my SearchkitSchemaConfig I added this to the elastic query, so that it returns a list of highlights:

```js
  postProcessRequest: (body: any) => {
    const newBody = { ...body };
    newBody.highlight = {
      fields: {
        '*': {},
      },
      require_field_match: false,
    };
    return newBody;
  },
```

In the ApolloServer typedefs I added:

```graphql
      type ResultHit implements SKHit {
        id: ID!
        fields: HitFields
        highlight: String
      }
```

finally, in the Apollo resolvers config:

```js
  resolvers: withSearchkitResolvers({
    ResultHit: {
      highlight: (hit: any) => JSON.stringify(hit.highlight),
    },
  }),
```

For now, it just returns the highlight as an encoded JSON string, but in theory it could be translated to any other graphql compatible structure.

May I create a PR for exposing `highlight` in HitsResolver.ts?

**Comment by joemcelroy** [comment]
hey @beepsoft thanks for looking into this. Your analysis is pretty spot on and very happy to accept a PR. Could you make this configurable, instead of doing it via postProcessRequest? 

`
hits: {    
   fields: ['type','title','year','rated','released','genres','directors','writers','actors','countries','plot','poster','id'],
   highlightedFields: [ 'title', 'genres'] 
},
`
Then as you demonstrated, the developer can add their own resolver + type for highlight and return it to any shape they want.

**Comment by beepsoft** [comment]
@joemcelroy, sure, I give it a try tomorrow!

**Comment by beepsoft** [comment]
@joemcelroy do you plan to release a new version with the highlight feature included?

**Comment by joemcelroy** [comment]
@beepsoft yep - hopefully today or tomorrow, im working on a few other changes. Need to address documentation and will be releasing soon 😄

**Comment by joemcelroy** [comment]
@beepsoft now on rc31 :)

**Comment by joemcelroy** [comment]
thanks for highlighting! Yeh it was due to another feature that was added in this release (url search state sync). Just updated with rc32 now with qs as a dependency. Long term shouldn't need QS if you're not using the routing HOC :-)
