### ISSUE TITLE
How to Sign Request to AWS Elasticsearch

### ISSUE THREAD

**Issue by kyledecot** [searchkit/searchkit#889]
I'm following the [Lambda Example](https://searchkit.co/docs/examples/aws-lambda) but running into an issue when attempting to connect to a AWS hosted Elasticsearch instance–I need to [sign the request](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html#es-request-signing-node) however I am unsure how to do this w/ searchkit. 

Is this something that is possible?

**Comment by joemcelroy** [comment]
Hey @kyledecot - i haven't recently used AWS elasticsearch but I think you should be able to create a domain for the AWS ES instance and connect via connection string rather than signing the request. 

https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-gsg-create-domain.html
