### ISSUE TITLE
Build custom queries

### ISSUE THREAD

**Issue by evancauwenberg** [searchkit/searchkit#9]
Hi there

First of all thnx for this awesome component!

I still have a few questions that i can't figure out :(
How can i build own custom queries in my React components? For ex.  (minified query)

```javascript
{
  "query": {
    "filtered": {
      "query": {
        "match": {
          "language": "nl-BE"
        }
      },
      "filter": {
        "and": [
          {
            "geo_distance": {
              "distance": "25km",
              ...
            }
          }
        ]
      }
    }
  },
  "sort": [
    {
      "_geo_distance": {
      }
    }
  ]
}
``` 

I'm currently looking at the "ImmutableQuery" object that i then assign the the "SearchkitManager" but without any results.

Thnx in advance!

**Comment by ssetem** [comment]
thanks for the interest in Searchkit, 

we are just refactoring this area of the code here
https://github.com/searchkit/searchkit/tree/develop/src/core/query

Perhaps you could join our gitter chat room so we can try and help better
https://gitter.im/searchkit/searchkit

Thanks

**Comment by evancauwenberg** [comment]
Thnx for the fast reply Perfect!

**Comment by ssetem** [comment]
http://docs.searchkit.co/stable/docs/core/SearchkitManager.html

http://docs.searchkit.co/stable/docs/core/ImmutableQuery.html

**Comment by evancauwenberg** [comment]
Super, thnx man!

Is it possible to run queries without setting them as defaultQuery?

**Comment by ssetem** [comment]
currently there are 2 modes, defaultQuery + components, both of which use Accessors to build the query.
Have you got an example of where you need to use a query?

**Comment by evancauwenberg** [comment]
I need to build a detailview based on the results of the overview (like in the example)

So correct me if i'm wrong but the best practice should be te create a custom component?

**Comment by ssetem** [comment]
I think the detail page + results page will have 2 seperate instances of SearchkitManager, and the defaultQuery for the detail instance will include the detail id etc, lets talk on gitter I think if you need further help

**Comment by joemcelroy** [comment]
closing this issue as now resolved over gitter

**Comment by bradennapier** [comment]
can we document this?. I need this and the solution was done in the chat so not really sure how to do it.
