### ISSUE TITLE
Keep filters when query changes

### ISSUE THREAD

**Issue by beepsoft** [searchkit/searchkit#902]
Currently it seems that when I call `setQuery()` the filters get cleared:

https://github.com/searchkit/searchkit/blob/401a16a4fdbbef19c643b6620fd6adfb5b64d712/packages/searchkit-client/src/searchkit.tsx#L86-L93

I tried to work it around by calling `api.setSearchState()` directly, but this doesn't seem to work, query is not executed at all:

```ts
    api.setSearchState((searchState: SearchState) => {
      return {
        ...searchState,
        theQueryString,
        // filters: [],
        page: { from: 0, size: searchState.page.size },
      };
    });
```

Is it possible somehow to keep the filters when the query string changes?

**Comment by joemcelroy** [comment]
Yep! And a few people have noticed this aswell. Happy to accept a PR where setQuery has additional arguments to preserveFilters and perservePagination with both having a default value of false. 

setting the searchState explicitly should of worked aswell as a workaround, i suspect you may of been a typo there 

```ts
    api.setSearchState((searchState: SearchState) => {
      return {
        ...searchState,
        query: theQueryString, // change
        page: { from: 0, size: searchState.page.size },
      };
    });
```

**Comment by beepsoft** [comment]
`theQueryString` is my variable with the new query string, so it should be OK but it is not. :-)

I will take a look at how it can be fixed.

**Comment by joemcelroy** [comment]
```ts
      return {
        ...searchState,
        theQueryString,
        // filters: [],
        page: { from: 0, size: searchState.page.size },
      };
```

would return an object where will have a key `theQueryString` where you want the key to be query. Without specifying the key explicitly, JS will use the variable name as the key. Hope that makes sense.

BTW we have a discord https://discord.gg/CRuWmSQZQx if you did want to reach me!

**Comment by beepsoft** [comment]
> would return an object where will have a key `theQueryString` where you actually want the key to be query. Without specifying the key explicitly, JS will use the variable name as the key. Hope that makes sense.

OMG, of course, I wanted to have:

```ts
    return {
        ...searchState,
        query: theQueryString,
        // filters: [],
        page: { from: 0, size: searchState.page.size },
      };
```

And with this it does work.
