### ISSUE TITLE
Ability to specify queryOptions in api requests.

### ISSUE THREAD

**Issue by stefan1968** [searchkit/searchkit#926]
We need to be able to send specific fields and options to the customQuery handler, allowing us to create specific queries that allow us to search by one field, combined fields, must, must_not etc.

Example query:-
```
{
    results(query: "my-search-entry", queryOptions: { fields: ["email", "secondary_email"]} {
        hits {
            id {
                field {
                    title
                }
            }
        }
    }
}
```

Example api:-
```
query: new CustomQuery({ 
    queryFn: (query, queryOptions, qm) => {
        const fields = queryOptions.fields
      return {
        bool: {
          must: [{
            wildcard: {
              field: {
                value: query + '*',
                boost: 1.0,
                rewrite: 'constant_score'
              }
            }
          }]
        }
      }
    }
  })
```

**Comment by joemcelroy** [comment]
thanks :) Sounds good. will try build the query options feature soon.

**Comment by joemcelroy** [comment]
so completed the first step to this by updating the API to accept queryOption fields. Documented here: https://searchkit.co/docs/customisations/customisations-query-boosting-relevance#query-options. This should allow you to get started. Right now the changes haven't made it to searchkit-client but shouldn't take too long with using React state and adding a new "queryOptions" graphql variable.
