### ISSUE TITLE
HighlightFields options

### ISSUE THREAD

**Issue by GregoryPotdevin** [searchkit/searchkit#94]
The current implementation of field highlight works great by default and is easy to use (just pass an array of field names).
However, there's no way to pass specific highlight field options, like

```
{
    "query" : {...},
    "highlight" : {
        "fields" : {
            "content" : {"fragment_size" : 150, "number_of_fragments" : 3}
        }
    }
}
```

One solution could be to allow either an array of strings (and convert that automatically to ES's format) or objects (and pass them without change). Or just keep highlightFields as is and add a `highlightOptions` override for ES experts.

**Comment by ssetem** [comment]
I like the highlightOptions idea, which an be a pass through to the query unmodified

**Comment by GregoryPotdevin** [comment]
It's probably best to have ES "specific" props that stay untouched, and "happy path" props that have different names to avoid confusion.

**Comment by udisun** [comment]
I would also appreciate that.
+1

**Comment by heylookalive** [comment]
Same here!
