### ISSUE TITLE
How to change facets size?

### ISSUE THREAD

**Issue by lutaev** [searchkit/searchkit#943]
Hi.

Looks like facet entries default size is equal to 5. For example, in your demo, if I select "Drama" from genres, then select "game" from types, I'll find that "Sci-fi" appears in genres while "Comedy" - vice versa. So, count of facet entries is always 5. Is there a way to increase it? Preferably, to get all of possible entries for all assets.

Thanks.

**Comment by joemcelroy** [comment]
hi @lutaev there is with `size` property :) https://searchkit.co/docs/reference/schema#refinementselectfacet

you will need to come up with a "magic number" for size as ES requires it.

```  
facets: [
    new RefinementSelectFacet({ field: 'type.raw', identifier: 'type', label: 'Type', size: 2000 })
  ]```

**Comment by lutaev** [comment]
> hi @lutaev there is with `size` property :) https://searchkit.co/docs/reference/schema#refinementselectfacet
> 
> you will need to come up with a "magic number" for size as ES requires it.
> 
> ```
> facets: [
>     new RefinementSelectFacet({ field: 'type.raw', identifier: 'type', label: 'Type', size: 2000 })
>   ]```
> ```

Thank you very much
