### ISSUE TITLE
Hierarchical Menu Filter

### ISSUE THREAD

**Issue by jan-runkel-zeitgleich** [searchkit/searchkit#945]
searchkit is awesome. Thanks very much!!

One Question:
Is there any plan to implement the Hierachical Menu Filter in the new v3 searchkit ?

**Comment by joemcelroy** [comment]
hey @jan-runkel-zeitgleich 

Glad you like searchkit :). Yes would love to. Would these requirements work?

configuration
```javascript

   new HierarchicalFacet({
      identifier: "categories",
      fields: [
         "categories_lvl1",
         "categories_lvl2",
         "categories_lvl3"
     ],
     label: "Categories"
   })

```

- When no filters are applied, will display lvl1 facet categories only
- When lvl1 filter applied, will return lvl1 facets AND lvl2 facets with lvl2 facets applied with lvl1 filter
- Same logic as above upto the length of fields
- Removing a filter from lvlN will remove all filter levels that are greater than N
- If lvl is leaf field, you can apply multiple filters. If not, can only select one filter

**Comment by jan-runkel-zeitgleich** [comment]
That sounds good. 
That would be the same as in version 2, right?
https://ssetem.gitbooks.io/searchkit/content/docs/components/navigation/hierarchical-menu.html

**Comment by joemcelroy** [comment]
yep similar behaviour :)

**Comment by joemcelroy** [comment]
Released in canary 41 https://searchkit.co/docs/build-your-own-components/hierarchical-facet
