### ISSUE TITLE
Highlighting Fields

### ISSUE THREAD

**Issue by HSUCHING** [searchkit/searchkit#948]
How to use Highlighting Fields? I have read doc (url:https://searchkit.co/docs/guides/highlighting-fields ),and i still cannot get right result. Need I modify some files (searchkit/client) ?

**Comment by joemcelroy** [comment]
hey @HSUCHING check the API response in your browser console. Does the highlighted fields return back in the response?

**Comment by HSUCHING** [comment]
@joemcelroy I have checked it ,but cannot find "highlighted" property in the response.

**Comment by joemcelroy** [comment]
OK the key then is you need to declare the field in types schema

```
    type ResultHit implements SKHit {
      id: ID!
      fields: HitFields
      highlight: String // add field
    }
```

then next add the resolver to serve the field for the ResultHit type

```
  resolvers: withSearchkitResolvers({
    ResultHit: {
      highlight: (hit: any) => JSON.stringify(hit.highlight) // add resolver
    }
  })
```

and then you need to update the graphql query on the client to ask it for the highlight field

```
query {
  results {
    hits {
      items {
        ... on ResultHit {
          id
          highlight // add field
          fields {
            title
          }
        }
      }
    }
  }
}
```

hope that makes sense. if not you can find me on discord (https://discord.gg/CRuWmSQZQx)
