### ISSUE TITLE
Multiple base filters

### ISSUE THREAD

**Issue by lutaev** [searchkit/searchkit#949]
Hi.
Thanks again for your work. I'm going to set up base filters, so, could you please help me?
I'm trying to use logical OR in base filters, but couldn't find how to do it. I tried something like this:

```javascript
const allowedIds = [4997, 4998, 4999];

const getBaseFilters = (parent: any, parameters: any, ctx: any) => {
  return allowedIds.map(id => ({
    term: { post_id: id }
  }))
};
```
but it returns an empty list because filtering uses `must` occurrence. How to switch it to `should`?

Thanks.

**Comment by joemcelroy** [comment]
hey @lutaev,

so you should be able to return a bool which contains a number of terms in a should array

```javascript
const allowedIds = [4997, 4998, 4999];

const getBaseFilters = (parent: any, parameters: any, ctx: any) => {
   return  [
                {
                    "bool": {
                        "should": allowedIds.map(id => ({
                           term: { post_id: id }
                       }))
                    }
                }
            ]
};
```

**Comment by lutaev** [comment]
@joemcelroy Thanks, it is really helpful.
