### ISSUE TITLE
Problem with setQueryProcessor

### ISSUE THREAD

**Issue by vabatista** [searchkit/searchkit#950]
Hi,
I'm not an expert with JS, but I'm having a bad time trying to call a webservice into the searchkitManager.setQueryProcessor. I'm using searchkit 2.4.4. Here is my code:
```
  async function expandQuery (plainQueryObject) {
    const query = encodeURIComponent(plainQueryObject.query.simple_query_string.query)
    console.log('query de entrada', query)

    const baseUrl = process.env.REACT_APP_BACKEND_URL + '/api/aqe'
    return await axios.get(`${baseUrl}/${query}`).then(data => data).catch(plainQueryObject)
  }

  searchkit.setQueryProcessor((plainQueryObject) => {
    setExpandedQuery('')

    if (typeof plainQueryObject.query !== 'undefined') {
      const queryString = plainQueryObject.query.simple_query_string.query

      if (queryString.includes(' ')) {
		  plainQueryObject.query.simple_query_string.query = `"${queryString}"~10 ${queryString}`
	  }

      expandQuery(plainQueryObject).then(newQuery => {
        plainQueryObject.query.simple_query_string.query = newQuery.data
        setExpandedQuery(newQuery.data)
        console.log('expanded before', plainQueryObject)

        return plainQueryObject
      })

	  console.log('expanded after', plainQueryObject)
	  return plainQueryObject
    } else {
      return plainQueryObject
    }
  })
```
The problem is that expanded query after returns first and it's fired againt Elastic. I also tried to put all the code into a async function, but it makes all the code crash resulting into no query been fired at all.

How can I make this happen? I need the user query to be expanded by this webservice and I think making a sync call is a bad idea.

**Comment by joemcelroy** [comment]
yeh difficult and no easy way. Two options I can see:
- searchkit behind the hood on v2 uses axios so you could use axios interceptors https://github.com/axios/axios#interceptors  to manipulate the body before its sent to elasticsearch
- find a way where you could get the user query expansion from the webservice before searchkit is mounted. obviously doesn't work if the user query expansion is different per request
- put in a middlelayer between client and elasticsearch which will do the query manipulation, like an API that takes in the ES query, the API middle layer expands the query filters  and continues passing it to elasticsearch. 

You could go down the route of monkey patching the queryProcessor but can be a long road :)

**Comment by vabatista** [comment]
I solved this issue using the last suggestion. I created a router into the backend and config SearchkitManager to point to that URL. The only detail I must take care was to change query syntax from simple_query_string to query_string, because my expanded query is in the form of 

`(original_token OR  (similar_token1^0.507 OR similar_token2^0.667 OR similar_token3^0.337) )`

Here is the backend code:

```
const elasticRouter = require('express').Router()
const logger = require('../logger')

const { Client } = require('@elastic/elasticsearch')
const client = new Client({
  node: process.env.ELASTIC_SEARCH_URL,
  ssl: {
    ca: process.env.elasticsearch_certificate,
    rejectUnauthorized: false
  }
})

elasticRouter.post('/_search', (request, response) => {
  async function run () {
    const result = await client.search({
      index: process.env.ELASTIC_SEARCH_INDEX,
      body: await expandQuery(request.body)
      // body: request.body
    })
    return result
  }
  try {
    run().then(result => response.json(result.body))
  } catch {
    logger.error('Error')
  }
})

async function expandQuery (originalRequest) {
  if (originalRequest.hasOwnProperty('query')) {
    const fields = JSON.parse(JSON.stringify(originalRequest.query.simple_query_string.fields))
    const query = encodeURIComponent(originalRequest.query.simple_query_string.query)
    const newQuery = await fetch(process.env.URL_QUERY_AQE + query).then(resp => resp.text())
    const newQueryObj = { query_string: { fields: fields, query: newQuery } }
    originalRequest.query = newQueryObj
    return originalRequest
  } else {
    return originalRequest
  }
}

module.exports = elasticRouter
```
