### ISSUE TITLE
Grandstack integration

### ISSUE THREAD

**Issue by llermaly** [searchkit/searchkit#995]
Hello, awesome library congrats <3.  I would like to use it in my project.

Is there a guide or best practices on how to integrate SK GraphQL with [Grandstack](https://grandstack.io/docs/getting-started-neo4j-graphql)? This one includes Neo4j and I want to create a Neo4j + ES search UI .

config file: https://github.com/grand-stack/grand-stack-starter/blob/master/api/src/index.js

Thanks

**Comment by joemcelroy** [comment]
Thanks for kind words! Yep should be no issue to integrate! see docs https://searchkit.co/docs/quick-start/api-setup and about having multiple schemas example here https://github.com/searchkit/searchkit/blob/next/examples/with-prisma/src/server.ts#L59

**Comment by llermaly** [comment]
Worked, thank you! 

Server ended up looking like this

```js
const server = new ApolloServer({
  context: {
    ...SKContext,
    driver,
    driverConfig: { database: process.env.NEO4J_DATABASE || 'neo4j' },
  },
  schema: stitchSchemas({
    subschemas: [
      { schema: neoSchema.schema },
      { schema: SearchkitExecutableSchema },
    ],
  }),
  introspection: true,
  playground: true,
})
```

The only difference is I had to import stitchSchemas from `@graphql-tools/stitch`
