### ISSUE TITLE
Cannot find module 'lodash' on Netlify function

### ISSUE THREAD

**Issue by llermaly** [searchkit/searchkit#997]
Hello,

I'm trying to deploy as a Netlify function and I'm facing this error: 

![image](https://user-images.githubusercontent.com/8575569/133165376-ed12ef3c-ef63-4d76-90c7-a14355e69651.png)

I tried installing lodash separately in my app without success. Any advice?

Thanks

**Comment by llermaly** [comment]
I solved it manually adding `"lodash": "^4.17.21"` to the build/node_modules/@searchkit/schema/package.json` . This means you should add it in the next release , right?

**Comment by joemcelroy** [comment]
thanks! Il add that to dependencies for schema :) You can also add lodash to your app dependencies for now.

**Comment by llermaly** [comment]
Thanks :) 

I tried installing lodash manually both in the main app as including a different package.json/package.lock inside the functions folder without success. Did I miss something?

**Comment by joemcelroy** [comment]
fixed the issue now. thanks for spotting. released under 3.0.0-canary.43. LMK if you have any problems :)
